### ISSUE TITLE
Ampache Support

### ISSUE THREAD

**Issue by Clementine-Issue-Importer** [clementine-player/Clementine#1059]
_From [Sherlock19](https://code.google.com/u/117883745557709626307/) on December 11, 2010 03:31:26_

adding ampache support to clementine will make it the worlds best player!

_Original issue: http://code.google.com/p/clementine-player/issues/detail?id=1059_

**Comment by Lykos153** [comment]
Ampache may be accessible through Subsonic API, but Owncloud isn't. So I request to reopen this issue since only Ampache support will make Clementine work with OC.

**Comment by Chocobozzz** [comment]
IMHO it would be more simple that Owncloud Music supports Subsonic API (https://github.com/owncloud/music/issues/329). And I think we would open a new issue ("support Ampache plugin of Owncloud Music" for example).
