### ISSUE TITLE
optional support for lyrics embedded in id3 tags

### ISSUE THREAD

**Issue by Clementine-Issue-Importer** [clementine-player/Clementine#1110]
_From [machat.v](https://code.google.com/u/110463128275502116150/) on December 16, 2010 02:19:07_

I have some mp3's with lyrics stored right in their id3 tags, so it would be great if I could see them in Song info tab. Could you add this option please?
Thanks for your great work...

_Original issue: http://code.google.com/p/clementine-player/issues/detail?id=1110_

**Comment by jraygauthier** [comment]
Should be pretty easy to implement using taglib:

<http://users.musicbrainz.org/~luks/taglib/api/classTagLib_1_1ID3v2_1_1Frame.html#259ca6b3acb155c023a30d541444fec6>

Could it be a possibility to add this library as a dependency of clementine?

**Comment by jraygauthier** [comment]
Nice. I just noticed that taglib is already a dependency of clementine.

**Comment by Chocobozzz** [comment]
See this PR https://github.com/clementine-player/Clementine/pull/4784/

**Comment by amuttsch** [comment]
Closed via  commit 258ae281d841e9ac891954b74a447d701334b747

**Comment by tmst** [comment]
Hmm. Lyrics are no longer automatically getting populated in the UI from network sources. I think this happened in the last few weeks. Perhaps a regression introduced by this enhancement?

v13.1 on openSuse Linux
