### ISSUE TITLE
change the language of 'Artist information' tab

### ISSUE THREAD

**Issue by Clementine-Issue-Importer** [clementine-player/Clementine#1112]
_From [keirangtp](https://code.google.com/u/117310112843043412265/) on December 16, 2010 09:20:41_

What steps will reproduce the problem? 1. Play a song.
2. Select the 'Artist information' tab. What is the expected output? What do you see instead? Some may want to see the biographies of artists in their native language. Right now it's always English.

_Original issue: http://code.google.com/p/clementine-player/issues/detail?id=1112_

**Comment by jbyvosges** [comment]
Nothing new since 2010 !
If Clementine is reserved to Anglophones alone, I'll leave you ...

**Comment by Yanpas** [comment]
+1

**Comment by Philippe2812** [comment]
Hi ! First I would like to thank the developers for their wonderful work !
Then I would like to add my point of view to this discussion : I understand the Echonest problem, but my question is : why use Echonest ? I know a very little in development, but it doesn't seem so hard to go on any website, copy the content and paste it into Clementine. So what about it ?

**Comment by fitojb** [comment]
If you aren’t a developer, you have no idea on how easy or difficult are things.

**Comment by Philippe2812** [comment]
I didn't mean no offense. I'm well aware of my ignorance. But as an user, I can see that most audio players, even the simpler, can parse lyrics sites or wikis and copy the content in the application. So I was figuring it could be the same for Wikipedia, which is a wiki too.

**Comment by Chocobozzz** [comment]
As @ArnaudBienner said, Clementine uses [Echonest API](http://developer.echonest.com/docs/v4/artist.html) to provide such information. Unfortunately , since his comment (2012) nothing changed. 

So if you really want this feature you should ask for Echonest to implement it :)
