### ISSUE TITLE
'files' tab: going back with 'backspace' doesn't work on windows

### ISSUE THREAD

**Issue by Clementine-Issue-Importer** [clementine-player/Clementine#1121]
_From [keirangtp](https://code.google.com/u/117310112843043412265/) on December 17, 2010 01:31:55_

"it works when I focus on the buttons but not on the actual list view, the list must steal the keypresses before the go up"

_Original issue: http://code.google.com/p/clementine-player/issues/detail?id=1121_

**Comment by ArnaudBienner** [comment]
Works for me.
