### ISSUE TITLE
the forward and backward keys support

### ISSUE THREAD

**Issue by Clementine-Issue-Importer** [clementine-player/Clementine#1129]
_From [kmusoy](https://code.google.com/u/104377330607044402928/) on December 18, 2010 06:52:34_

Please describe the feature you're requesting in as much detail as possible. my mouse has two keys to go backward and forward. but clementine don't support them.

_Original issue: http://code.google.com/p/clementine-player/issues/detail?id=1129_

**Comment by Chocobozzz** [comment]
Closing this very old issue. Feel free to reopen.
