### ISSUE TITLE
there should be an option to embed your ratings into a song file

### ISSUE THREAD

**Issue by Clementine-Issue-Importer** [clementine-player/Clementine#1175]
_From [keirangtp](https://code.google.com/u/117310112843043412265/) on December 25, 2010 13:40:29_

We're loading them - why can't we support the other way around too?

_Original issue: http://code.google.com/p/clementine-player/issues/detail?id=1175_

**Comment by svnpenn** [comment]
https://github.com/clementine-player/Clementine/issues/5145
