### ISSUE TITLE
Multiple shortcuts for every action

### ISSUE THREAD

**Issue by Clementine-Issue-Importer** [clementine-player/Clementine#1308]
_From [Ivo.Karadzhov](https://code.google.com/u/102398589405771012720/) on January 16, 2011 18:16:01_

I'd really like the media shortcuts, but for an example it will be good when I'm inside the player to pause/play also with an alternative shortcut like space. So when I'm outside the player I'm play/pausing with the media shortcut, and when I'm in I do it with the space bar. This will be a nice feature I guess.

_Original issue: http://code.google.com/p/clementine-player/issues/detail?id=1308_

**Comment by Gibbz** [comment]
Currently I only see support for a single shortcut per action. It it possible to support multiple like foobar?

I like to have the multimedia buttons for next, play and pause. But i also like to have the next button bound to ctrl+LeftArrow for example. As its usually more convenient to use the alternative, but often use both...

A feature request i guess :)
