### ISSUE TITLE
add option to use decibells for volume level

### ISSUE THREAD

**Issue by Clementine-Issue-Importer** [clementine-player/Clementine#132]
_From [andrew.gaydenko](https://code.google.com/u/andrew.gaydenko/) on March 29, 2010 01:14:53_

With aim to avoid long description, please, just look at this issue: https://bugs.kde.org/show_bug.cgi?id=195556

_Original issue: http://code.google.com/p/clementine-player/issues/detail?id=132_

**Comment by gaydenko** [comment]
Can we, please, reopen the issue? It is still the main barrier to every-day Clementine usage. And, well, we can still show percentage to user but make 1% equal 0.5db.
