### ISSUE TITLE
Error connecting MTP device

### ISSUE THREAD

**Issue by Clementine-Issue-Importer** [clementine-player/Clementine#1339]
_From [bristela](https://code.google.com/u/113157128466109396108/) on January 21, 2011 22:51:00_

What steps will reproduce the problem? 1. Connect Zen Mozaic (which is recognised by Clementine)
2. Double click to open (as suggested)
3. Get error of "Error connecting MTP device What is the expected output? What do you see instead? Expect Clementine to scan device but get error then says 0 songs found. What version of the product are you using? On what operating system? Clementine 0.6 on Mac OS X Snow Leopard (also same problem with 0.5) Please provide any additional information below.

_Original issue: http://code.google.com/p/clementine-player/issues/detail?id=1339_

**Comment by Chocobozzz** [comment]
Closing this old issue. Feel free to ask for reopening it.
