### ISSUE TITLE
libnotify shows "<Invalid markup, cannot display message>"

### ISSUE THREAD

**Issue by Clementine-Issue-Importer** [clementine-player/Clementine#1356]
_From [socketubs](https://code.google.com/u/107041385361714385229/) on January 24, 2011 13:20:24_

What steps will reproduce the problem? 1. Using desktop notify
2. Listen a music with "13 & God" artist, i think the "&" is most important

And when i listen the describe music artist, libnotify send :
"<Invalid markup, cannot display message>" on screen.
But with other music with normal artist name, no problem. What version of the product are you using? On what operating system? I use Linux, Archlinux i686, Awesome wm with libnotify and Clementine 6.0.

_Original issue: http://code.google.com/p/clementine-player/issues/detail?id=1356_

**Comment by Chocobozzz** [comment]
Closing this old issue. Feel free to ask for reopening it.
