### ISSUE TITLE
Loading multiple songs from file browser causes multiple instances of Clementine to load!

### ISSUE THREAD

**Issue by Clementine-Issue-Importer** [clementine-player/Clementine#1361]
_From [anomnomnomaly](https://code.google.com/u/102551446466775473653/) on January 25, 2011 18:36:33_

What steps will reproduce the problem? 1. Open file browser
2. Navigate to a directory with multiple music files, for example an entire album.
3. Highlight all the music files.
4. Right click --> Open in Clementine

What is the expected output? 
One instance of Clementine loads with all of the files in the playlist, in alphabetical order by filename, and the first song starts playing.

What do you see instead?
An explosion of 15 (or however many files were highlighted) instances of Clementine opening, each one playing a different song simultaneously in a nightmarish cacophony. What version of the product are you using? On what operating system? Clementine 0.6 in Linux Mint 9 (Isadora), using GNOME's Nautilus file browser. Please provide any additional information below. Amarok does this as expected.

_Original issue: http://code.google.com/p/clementine-player/issues/detail?id=1361_

**Comment by SylannBin** [comment]
I'm still having this issue with version 1.3.1 on ubuntu 17.10.
Can't remember but probably installed by default or with "Ubuntu Software".
Also not really related, there is another software named "clementine" instead of "Clementine" referenced. Kind of odd.
