### ISSUE TITLE
lyricsplugin.com is not working anymore

### ISSUE THREAD

**Issue by Clementine-Issue-Importer** [clementine-player/Clementine#1432]
_From [ivanovnegro](https://code.google.com/u/117832764531417599614/) on February 08, 2011 19:18:04_

What steps will reproduce the problem? 1. If you add in the settings about titel info the lyric engines, one of them is lyricsplugin.com, this one will no longer work on Clementine. If you enable this engine and go to the titel info tab it will give you this message:  'Upgrade to Lyrics Plugin version 0.4'. 

2. When you click on it you will be transported to the internet site: http://www.lyricsplugin.com/ . Seems this engine is now exculively for Winamp, WMP and iTunes software.

3. It does not seem to be a problem with Clementine. What is the expected output? What do you see instead? Expected output was to be able to see the lyrics also from this engine. What version of the product are you using? On what operating system? r2775 on Maverick. Please provide any additional information below. Its not a big deal, I think this engine is no longer available for Clementine, Im not sure. I disabled it.
But Keiran wanted me to report it.
I attached also a screenshot.

**Attachment:** [Bildschirmfoto.png](http://code.google.com/p/clementine-player/issues/detail?id=1432)

_Original issue: http://code.google.com/p/clementine-player/issues/detail?id=1432_

**Comment by Chocobozzz** [comment]
I'm not sure we need this anymore.
