### ISSUE TITLE
Save track position between sessions

### ISSUE THREAD

**Issue by Clementine-Issue-Importer** [clementine-player/Clementine#1454]
_From [andrew.gaydenko](https://code.google.com/u/andrew.gaydenko/) on February 11, 2011 15:45:52_

Continuing the discussion in issue #410 . Suggestion:

At case the player was closed at paused or plaing back state, at next session start the player must be at paused state on the same track position it was closed.

As option, if last session was closed at playing state - start playing from the same track position. But such behavior must not be default one ("unexpected plaing" case must be avoided as fefault way at any case).

_Original issue: http://code.google.com/p/clementine-player/issues/detail?id=1454_

**Comment by kmulvey** [comment]
+1

**Comment by kakynologyst** [comment]
+1, extremely useful for playing audiobooks

**Comment by Chocobozzz** [comment]
It is already implemented (tools -> preferences -> behavior -> resume playback on start).

Try with the latest build if you notice this bug: https://github.com/clementine-player/Clementine/pull/4880

**Comment by kakynologyst** [comment]
Thanks but the option is muted (can't click) on my mac.

www.kakyn.com

**Comment by Chocobozzz** [comment]
Yes, the options are disabled on Darwin systems.

@hatstand Is it still needed ?

**Comment by kotofos** [comment]
Still needed for me.

**Comment by andresmoschini** [comment]
It still does not work on Mac

![imagen](https://user-images.githubusercontent.com/1157864/49012473-49a89080-f158-11e8-934a-e18629d5be40.png)

Is there a workaround? Can I edit a file to enable it?

**Comment by jonaski** [comment]
You can't be using the latest code, I fixed this in commit c264725

**Comment by jonaski** [comment]
I tested the qt 5 branch on Mojave, resume on startup is possible. I moved the option out of the "When Clementine starts group" in the mentioned commit so it should appear just below the startup settings.

**Comment by smalltimer** [comment]
Hi, resuming does not seem properly to work in v1.3.1. The player starts from the beginning of the song/piece on restart. Also, is it possible to not start playing, but just remember the position in the song? I have been looking through the options but can't seem to find any way to do this. Any help/tips? Thanks!
