### ISSUE TITLE
new artist in library breaks alphabetical sorting

### ISSUE THREAD

**Issue by Clementine-Issue-Importer** [clementine-player/Clementine#1470]
_From [multiregion](https://code.google.com/u/116969448555975523093/) on February 15, 2011 22:41:52_

What steps will reproduce the problem? 1. Add tracks from artist who is currently not in library to playlist
2. Move or copy tracks to library
3. Newly added artist shows up as last (or first) entry for letter What is the expected output? What do you see instead? No alphabetical sorting, instead new artist gets added as last entry for the beginning letter. Manually resorting or restarting is neccessary. What version of the product are you using? On what operating system? clementine 0.6 r2402 / Ubuntu 10.10

Hint: This is not a duplicate of issue 1117 . This is not about the playlist sorting.

**Attachment:** [clementine-sorting2.png](http://code.google.com/p/clementine-player/issues/detail?id=1470)

_Original issue: http://code.google.com/p/clementine-player/issues/detail?id=1470_

**Comment by Chocobozzz** [comment]
Closing this old one. Feel free to reopen.
