### ISSUE TITLE
Guess track tags from filename

### ISSUE THREAD

**Issue by Clementine-Issue-Importer** [clementine-player/Clementine#1489]
_From [quezak](https://code.google.com/u/quezak/) on February 20, 2011 16:13:23_

In Amarok 1.4, when editing track information, there was a nice button called "guess tags from filename" (or sth like that, I always used Polish version). It tried to fill the tags comparing file path/name with _editable_ schemes, for example with schemes

&#37;artist/[&#37;year] &#37;album/&#37;track - &#37;title
&#37;artist - &#37;album - &#37;track - &#37;title

it would properly fill tags for files:
[...]/Mastodon/[2009] Crack The Skye/01 - Oblivion.mp3
[...]/misc/White Stripes - Elephant - 01 - Seven Nation Army.mp3

This was a really nice feature when organising new music, so i thought it might be added to Clementine too :)

_Original issue: http://code.google.com/p/clementine-player/issues/detail?id=1489_

**Comment by qwabra** [comment]
let's reopen this - on edit, get tag info from file name
