### ISSUE TITLE
Can't stop play after current track (using keyboard shorcut)  if the list playing isn't the one currently selected.

### ISSUE THREAD

**Issue by Clementine-Issue-Importer** [clementine-player/Clementine#1505]
_From [ailurosity](https://code.google.com/u/104521021539627113246/) on February 24, 2011 22:59:09_

What steps will reproduce the problem? 1.Start playlist playing.
2.Switch to another playlist tab & minimise/hide Clementine.
3.Enter keyboard shortcut to stop at end of current track. What is the expected output? What do you see instead? Expect playback to stop after current track, but it carries on playing. What version of the product are you using? On what operating system? 0.6 r2818 OSX 10.6.6 Please provide any additional information below.

_Original issue: http://code.google.com/p/clementine-player/issues/detail?id=1505_

**Comment by paperbagcorner** [comment]
This was bug was fixed over a year ago in commit 4872766f8024562571758edef41c2e384c057f13
