### ISSUE TITLE
Tracks with Cyrillic tags can not be played

### ISSUE THREAD

**Issue by Clementine-Issue-Importer** [clementine-player/Clementine#151]
_From [rnd.mr.ded](https://code.google.com/u/107983831462254793684/) on April 03, 2010 08:56:02_

What steps will reproduce the problem? 1.open track with Cyrillic tags
2.click "play" What is the expected output? What do you see instead? track can not play
and incomprehensible files are creating in ~/ directory What version of the product are you using? On what operating system? clementine-player ver. 0.2 
operating system: ArchLinux

**Attachment:** [2010-03-29--1269879865_1280x800_scrot.png](http://code.google.com/p/clementine-player/issues/detail?id=151)

_Original issue: http://code.google.com/p/clementine-player/issues/detail?id=151_

**Comment by username459045** [comment]
Hello. Clementine doesn't display some of cyrillic tags(tags is ok i checked it) and doesn't play one flac album, which is normally playing in MPC. Clementine displays his tags like ????? How can i fix it? Thanks.
![2024-01-15_204255](https://github.com/clementine-player/Clementine/assets/155245319/f86cad95-8bd7-403d-a796-53e4c88f4937)

![2024-01-15_203907](https://github.com/clementine-player/Clementine/assets/155245319/3aa09240-027f-4be7-a00a-2fa3396e3f3f)
