### ISSUE TITLE
Extra/Rain pressed icon is not displayed correctly on WinXP

### ISSUE THREAD

**Issue by Clementine-Issue-Importer** [clementine-player/Clementine#1600]
_From [luigibrosse](https://code.google.com/u/109728806925585294448/) on March 22, 2011 14:06:22_

What steps will reproduce the problem? 1. Activate Rain
2. Reopen Extra menu What is the expected output? What do you see instead? 1. I expect to see a "nice" icon of rain telling me that the option is activated.
2. I see an unfinished square around the icon (see attachment), which is not nice at all :o) What version of the product are you using? On what operating system? v0.7RC on WinXP64

**Attachment:** [rain.jpg](http://code.google.com/p/clementine-player/issues/detail?id=1600)

_Original issue: http://code.google.com/p/clementine-player/issues/detail?id=1600_

**Comment by Chocobozzz** [comment]
The attachment is not accessible. Please ask for reopen this issue if you encounter the same problem.
