### ISSUE TITLE
editing album/track info makes it disappear from the library view

### ISSUE THREAD

**Issue by Clementine-Issue-Importer** [clementine-player/Clementine#1622]
_From [goetzchrist](https://code.google.com/u/101757420644949299224/) on March 25, 2011 23:43:13_

When changing some information from an album or track (tags or not tags) the whole album (or track) disappears from the library view if it was previously searched in the library view. Only when changing the library's search criteria, the album/track will reaper in the list. What version of the product are you using? On what operating system? r3035 Kubuntu 10.10

_Original issue: http://code.google.com/p/clementine-player/issues/detail?id=1622_

**Comment by Chocobozzz** [comment]
Closing this outdated issue. Please tell us if you notice this issue with the latest release.
