### ISSUE TITLE
Album Artist Tag not supported in ogg, m4a or flac

### ISSUE THREAD

**Issue by Clementine-Issue-Importer** [clementine-player/Clementine#1624]
_From [julien.rouillard](https://code.google.com/u/114806850757542565108/) on March 27, 2011 01:03:38_

What steps will reproduce the problem? 1. Add .ogg file with Album artist tag to player
2. tag not displayed
3. add .mp3 file with album artist tag, tag displayed What is the expected output? What do you see instead? I expected to see the tag for album artist What version of the product are you using? On what operating system? I used 0.6 and tried also on 0.7 RC1 both on MS Windows XP Please provide any additional information below. It is quite useful to have this tag, I have a lot of classical music (especially piano) and I use this tag for the musician.

I can provide test files if requested.

Thank you.

Julien

_Original issue: http://code.google.com/p/clementine-player/issues/detail?id=1624_

**Comment by cameron-martin** [comment]
I'm commenting to open this issue, since it is still a problem in version 1.2.3.

**Comment by Chocobozzz** [comment]
Please try with the latest build http://builds.clementine-player.org/

**Comment by cameron-martin** [comment]
I installed the latest build, version `1.2.3-1202-g127ee5f`, and this is still a problem.

**Comment by acurl** [comment]
oh sorry, I didn't read the last comment
