### ISSUE TITLE
Clementine doesn't scrobble a song after pausing and unpausing it

### ISSUE THREAD

**Issue by Clementine-Issue-Importer** [clementine-player/Clementine#1645]
_From [ravicious](https://code.google.com/u/112357005075857931911/) on March 28, 2011 17:32:24_

Start playing a song, pause it at the beginning and unpause after a few minutes. Clementine won't scrobble this track, you can't explain that. Also Clementine ocasionally won't scrobble the track that was played before the paused song AND mark the paused song as scrobbled, that's weird.

Could you check out how it's done in Rhythmbox or Banshee? Scrobbling works perfectly in these players.

Clementine 0.7 rc1, Ubuntu 10.10 32-bit

_Original issue: http://code.google.com/p/clementine-player/issues/detail?id=1645_

**Comment by TheUbuntuGuy** [comment]
This issue was fixed long ago...
