### ISSUE TITLE
Clementine stops playing after track.

### ISSUE THREAD

**Issue by Clementine-Issue-Importer** [clementine-player/Clementine#1679]
_From [Nomad71st](https://code.google.com/u/114100015701596881529/) on March 31, 2011 19:51:11_

What steps will reproduce the problem? 1. Add some lossless audio (ape + cue, or flac + cue)
2. listen to the song, when the song ends, clementine willn't jump to the next one What is the expected output? What do you see instead? Expected result: Next song.
Actual result: Clementine stops playing. What version of the product are you using? On what operating system? Clementine 0.7.1
Os: Fedora 14

_Original issue: http://code.google.com/p/clementine-player/issues/detail?id=1679_

**Comment by Pupskuchen** [comment]
I also have this issue.

I have a playlist with files of different types (MP3, FLAC (both splitted files and single-file albums using a cue), ...), when playing it (usually in shuffle mode, haven't tryed anything else) it sometimes just stops the playback either at the end of the last or in the beginning of the next track.
cross fade and replay gain are turned off.

When playing single-file albums using a cue, the next track of the flac file is also played for a few seconds before it either stops or plays the next track.

Clementine 1.2.3-1071-g1098028 (and some previous versions), Mac OS X Yosemite 10.10.3

**Comment by cheoppy** [comment]
I experience this issue when I'm playing FLAC files (no cue and no mp3 or other file types are involved), and Clementine stop after changing albums, hanging at 0:01 seconds of the first song of the next album.

Running clementine from the terminal and looking at the debug messages did not reveal anything suspicious. 

Clementine 1.2.3 on Ubuntu 12.04.

**Comment by jsirex** [comment]
Same issue. Debian jessie
Package: clementine                      
State: installed
Automatically installed: no
Version: 1.2.3+dfsg-2+b1
Linux sirex-pc 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt20-1+deb8u4 (2016-02-29) x86_64 GNU/Linux  
Kde 4, GStreamer

**Comment by abika** [comment]
Guess this was already fixed during the transition to gstreamer-1.0 or as a side effect by other fixes. If somebody can provide a configuration (fading, buffer size, {length/type}-from/to_track, ...) where the track transition always fails i could confirm this.

It happened to me too in recent years but I was never able to reproduce it reliable. And fixing a bug (probably some race condition in gstreamers usage) that occurs one out of 100 times is very tricky.

**Comment by JulianVolodia** [comment]
Hmm... is not buffering issue? Maybe it displays that "it is playing" but not doing it? Maybe sth blocking some threads (I do not know big part of that project, i only guess). What are you think @abika ?

I try to make ramfs with slower transfer rate... I will check if that block playing music after changing album... You think it could happen this way?

**Comment by abika** [comment]
Well, the bug should be somewhere in the gst pipeline during TransitionToNext or the callbacks, or something like that. If its still there...

> I try to make ramfs with slower transfer rate... I will check if that block playing music after changing album... You think it could happen this way?

Good idea. But I tried this using cgroup with blkio without success.

**Comment by szbnwer** [comment]
it did the same for me, crossfade helped here too, but then it cut off the size of given at the gstreamer buffer, from the end of every tracks (now its 0ms and no issues left)

problem appeared for an album (mp3 lame, if i know well there are other lame stuffs here, and all my tracks are in a big folder without anything else) and a few other tracks (i dont know which are those, if needed i can search for them, its all related to these files, but no idea how)
playing stopped after these tracks, not when they are about to start
i think if no any better solution (its an old issue...) then no crossfade could be implemented as crossfade with 0ms and maybe defaulted as well...

i hope i could bring anything usable, i like clementine, many thcx for your work!

**Comment by lobo-tuerto** [comment]
Seeing this problem in Ubuntu 16.04.

It randomly stops after playing a couple of songs (it varies from 1 to 5~ I guess).

It always stops at 0:04 of the next song (I think it has to do with the crossfade).

**Comment by lobo-tuerto** [comment]
@JulianVolodia sure, what would you like to know?

Here is the version of Clementine I'm using: 1.2.3
Ubuntu is the 64bit version.

**Comment by JulianVolodia** [comment]
@lobo-tuerto everything you could provide about when it happen or the best if you blame a part of code with debugger.

If it is 'randomly' really - try to find which steps (running apps, some specific behaviour and so...) make it happen...

**Comment by gazhay** [comment]
I've always had this problem with one particular track and assumed it was the track at fault, but today it is happening with everything.

**Comment by FranzSkuffka** [comment]
Same here - it just does not play through playlists. Stops at the end of each many songs.

**Comment by boospy** [comment]
Same problem here on KDE Neon with 1.3.1. If jumping from mp3 to flac or from flac to mp3 oder to mp4 clementine stop playing... but not really, it hangs.

**Comment by scotte** [comment]
I've been seeing the same symptoms - it seems to happen for both MP3 queues and icecast streams (I don't think I've seen it with soma.fm streams, for some reason), but it's intermittent. It's hard to say if it's all the same exact problem or not, but the symptoms match. The player controls show Clementine is still playing, but nothing is until I manually restart it (select next track, hit stop/play, etc).

**Comment by theronaldreis** [comment]
The solution (in fact, a workaround) for me was the comment of the Clementine-Issue-Importer (commented on 9 Dec 2013), that is: 

Turn on "Cross fade when changing tracks automatically" in Preferences menu. In my case, turn on "Transição suave quando mudar de faixa automaticamente" (Portuguese language, Brazil country).

Thanks and cheers!!

**Comment by scotte** [comment]
Unfortunately, the workaround of turning on cross fade does not work for me.

**Comment by theronaldreis** [comment]
Holping helping some mates, I'm posting the prints of my Clementine Preferences screens (now in English). My computer system (Ubuntu base: 18.04):

Operational System: KDE neon 5.15
Version of KDE Plasma: 5.15.2
Version of KDE Frameworks: 5.55.0
Version of Qt: 5.12.0
Version of kernel: 4.15.0-46-generic
Type of operational system: 64 bits
Processors: 2 × Intel® Core™2 Duo CPU T6600 @ 2.20GHz
Memory: 3,8 GiB of RAM

Clementine Preferences screens:

![01 - Clementine - Preferences - Playback - part 1](https://user-images.githubusercontent.com/7315034/54054660-8c531d80-41c9-11e9-8a30-cea0ebd9387f.jpeg)
![02 - Clementine - Preferences - Playback - part 2](https://user-images.githubusercontent.com/7315034/54054661-8c531d80-41c9-11e9-9b72-86d5c996044d.jpeg)
![03 - Clementine - Preferences - Behavior - part 1](https://user-images.githubusercontent.com/7315034/54054662-8c531d80-41c9-11e9-9cd3-9410c65b0f97.jpeg)
![04 - Clementine - Preferences - Behavior - part 2](https://user-images.githubusercontent.com/7315034/54054663-8c531d80-41c9-11e9-8eac-849c72532b86.jpeg)
![05 - Clementine - Preferences - Music Library](https://user-images.githubusercontent.com/7315034/54054665-8cebb400-41c9-11e9-9c67-fccdcca3ad60.jpeg)
![06 - Clementine - Preferences - Network Proxy](https://user-images.githubusercontent.com/7315034/54054666-8cebb400-41c9-11e9-9b12-e5c0ec6ed7ce.jpeg)
![07 - Clementine - Preferences - Transcoding - part 1](https://user-images.githubusercontent.com/7315034/54054667-8d844a80-41c9-11e9-9e39-0cd414ca1d49.jpeg)
![08 - Clementine - Preferences - Transcoding - part 2](https://user-images.githubusercontent.com/7315034/54054668-8d844a80-41c9-11e9-8ea4-bb0140b509de.jpeg)
![09 - Clementine - Preferences - Transcoding - part 3](https://user-images.githubusercontent.com/7315034/54054669-8e1ce100-41c9-11e9-80f4-55f1e0037845.jpeg)
![10 - Clementine - Preferences - Transcoding - part 4](https://user-images.githubusercontent.com/7315034/54054671-8e1ce100-41c9-11e9-91b4-59601456e0f1.jpeg)
![11 - Clementine - Preferences - Transcoding - part 5](https://user-images.githubusercontent.com/7315034/54054672-8eb57780-41c9-11e9-8568-f46ba9146c45.jpeg)
![12 - Clementine - Preferences - Transcoding - part 6](https://user-images.githubusercontent.com/7315034/54054676-8f4e0e00-41c9-11e9-951f-f79c92f34b3c.jpeg)
![13 - Clementine - Preferences - Transcoding - part 7](https://user-images.githubusercontent.com/7315034/54054677-8f4e0e00-41c9-11e9-9a05-40c2b4ea0d8b.jpeg)
![14 - Clementine - Preferences - Network Remote](https://user-images.githubusercontent.com/7315034/54054683-8fe6a480-41c9-11e9-9bab-2497df6d520a.jpeg)
![15 - Clementine - Preferences - Wiimotedev](https://user-images.githubusercontent.com/7315034/54054685-907f3b00-41c9-11e9-84d9-dc26d4c7efde.jpeg)

**Comment by boospy** [comment]
> The solution (in fact, a workaround) for me (my system is KDE Neon) was the comment of the Clementine-Issue-Importer (commented on 9 Dec 2013), that is:
> 
> Turn on "Cross fade when changing tracks automatically" in Preferences menu. In my case, turn on "Transição suave quando mudar de faixa automaticamente" (Portuguese language, Brazil country).
> 
> Thanks and cheers!!

This helped me. Thanks...

**Comment by scotte** [comment]
For me it seems to be the opposite now - I turned **off** `Cross-fade when changing tracks automatically` and now Clementine has stopped freezing between tracks.
