### ISSUE TITLE
graphic glitches when mouse is over the track slider bar on some themes (like Oxygen)

### ISSUE THREAD

**Issue by Clementine-Issue-Importer** [clementine-player/Clementine#1715]
_From [h.ibrahim.gungor](https://code.google.com/u/106553568437094269971/) on April 09, 2011 11:30:08_

What steps will reproduce the problem? 1.Add a new song via Playlist->Add file, whether there is already a playlist or not.
2.Open any song, whether the song is the one you just added or any song in a playlist
3.Observe that when you mouse over the seek bar, the little shiny dialog is not behaving normally as always do. It's blinking and seems awkward. What is the expected output? What do you see instead? It should behave just like before the new song is not added to playlist What version of the product are you using? On what operating system? 0.7.1, Pardus GNU/Linux. Qt 4.7.1 Please provide any additional information below. If you can't reproduce the issue, i can upload a video showing the defect.

_Original issue: http://code.google.com/p/clementine-player/issues/detail?id=1715_

**Comment by notargets** [comment]
I have the same problem with KDE Plasma 5.3.1 and Clementine 1.2.3. This has not been the case with KDE 4.14 though. I think this issue could be reopened.
