### ISSUE TITLE
scrobbling queue lost when offline and restarting the application

### ISSUE THREAD

**Issue by Clementine-Issue-Importer** [clementine-player/Clementine#174]
_From [kadaimx](https://code.google.com/u/kadaimx/) on April 06, 2010 08:21:09_

What steps will reproduce the problem? 1. Load Clementine and disconnect yourself from the network (we want to
generate a queue of pending submissions)
1. Play then some files (2 or 3) and make sure they were attempted to be
   sent to last.fm service.
2. Shutdown Clementine, connect yourself to the network. Once connected,
   start again the software.
3. Look then your last.fm account for the played tracks. They will not be
   there, meaning that they got lost on shutdown. What is the expected output? What do you see instead? Expected Clementine to -save- on a queue (similar to Amarok 1.4) the
   pending tracks to be sent to last.fm service. What version of the product are you using? On what operating system? Revision 585 on Kubuntu 9.10 Please provide any additional information below. While this is not a critical issue, it can be considered important for any
   of the users that like to have stats of all his/her played tracks.

Now, I'm not sure who handles then the queue, but apparently Clementine had
to do that, no?

In such case, there will be the need to create a file with the information
pending to be sent just to do not loss it.

Additional to it, as fine-tunning, the user could be then informed about if
a track was successfully submitted to last.fm or not on the status bar of
the main window (for example, saying "Track <name> successfully sent to
<service name>" or either "Scrobble of <track> failed. <number> tracks on
queue")

_Original issue: http://code.google.com/p/clementine-player/issues/detail?id=174_

**Comment by dowcet** [comment]
Clementine is only scrobbling when I am online. Nothing I listen to while offline is scrobbled, even if Clementine has not been restarted. Is there anything in the above I should try?
