### ISSUE TITLE
allow to hide left info area (next to sidebar) and show play list over whole window width

### ISSUE THREAD

**Issue by Clementine-Issue-Importer** [clementine-player/Clementine#1804]
_From [lukas.middendorf](https://code.google.com/u/101322788893012434774/) on April 25, 2011 13:18:08_

Most of the time I'm not interested in the content of the information area next to the sidebar (like the Library browser or the Song info). Instead I like to have more (horizontal) space for the playlist.
I could just drag the border between playlist and information area and hide the later and the sidebar altogether, but it is quite some hassle to get it back (from time to time I want to use it) and the short info about the current track (title, artist, album) is also gone then.

In Amarok 1.4 you could just click on the tab of the currently active Browser and then it was hidden and could be shown again with a click on the tab (or a different tab could be chosen). The browser tabs (which corresponds to the sidebar in clementine) were visible all the time. I would like to also see that behavior in clementine.

_Original issue: http://code.google.com/p/clementine-player/issues/detail?id=1804_

**Comment by vascomartins** [comment]
Hi to all,
Is this issue resolved yet!? 
I would like to be able to hide the side bar as well, is strange that I can't drag the separator all the way to the left!

Please make this possible
Thank you for all the effort and great app
Vasco
