### ISSUE TITLE
Invalid repeat/shuffle icons on Windows and Mac v.0.7.1

### ISSUE THREAD

**Issue by Clementine-Issue-Importer** [clementine-player/Clementine#1808]
_From [spider.player](https://code.google.com/u/106235439612429628664/) on April 25, 2011 20:35:30_

Compare:
-- Linux (as expected) http://images.clementine-player.org/screenshots/clementine-0.7-1.png -- Windows (WTF?) http://images.clementine-player.org/screenshots/clementine-0.7-3.png -- Mac OS X (WTF?) http://images.clementine-player.org/screenshots/clementine-0.7-4.png

_Original issue: http://code.google.com/p/clementine-player/issues/detail?id=1808_

**Comment by JulianVolodia** [comment]
#245 follow up
