### ISSUE TITLE
Crash on startup; Windows 7; Clementine 0.7.1 & debug version

### ISSUE THREAD

**Issue by Clementine-Issue-Importer** [clementine-player/Clementine#1851]
_From [degerrit](https://code.google.com/u/113496297446016630356/) on May 05, 2011 23:11:46_

Crash immediately on startup; Windows 7
No window is visible at all, it just disappears. In the task manager no clementine processes remain running.

Clementine worked fine earlier this week (fresh install; just configured and used it once!)

Additional info:

Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\degerrit>"C:\Program Files\Clementine\clementine.exe"
22:56:03.297 INFO  Player:493                       Registered URL handler for "lastfm"
22:56:03.297 DEBUG RadioModel:81                    Adding radio service: "Last.fm"
22:56:03.298 DEBUG SpotifyService:62                Spotify system blob path: "C:/Program Files/Clementine/clementine-spotifyblob.exe"

22:56:03.298 DEBUG SpotifyService:63                Spotify local blob path: "C:/Users/degerrit/.config/Clementine/spotifyblob/version1
-32bit/blob"
22:56:03.298 INFO  Player:493                       Registered URL handler for "spotify"
22:56:03.298 INFO  PlaylistManager:413              Registered special playlist type "spotify-search"
22:56:03.299 DEBUG RadioModel:81                    Adding radio service: "Spotify"
22:56:03.299 INFO  Player:493                       Registered URL handler for "somafm"
22:56:03.299 DEBUG RadioModel:81                    Adding radio service: "SomaFM"
22:56:03.311 INFO  Player:493                       Registered URL handler for "magnatune"
22:56:03.311 DEBUG RadioModel:81                    Adding radio service: "Magnatune"
22:56:03.321 DEBUG RadioModel:81                    Adding radio service: "Jamendo"
22:56:03.327 DEBUG RadioModel:81                    Adding radio service: "Icecast"
22:56:03.327 DEBUG RadioModel:81                    Adding radio service: "SavedRadio"
22:56:03.329 WARN  IconLoader:54                    Couldn't load icon "clementine-panel"
22:56:03.329 WARN  IconLoader:54                    Couldn't load icon "clementine-panel-grey"
22:56:03.334 DEBUG QxtGlobalShortcutBackend:32      registering
22:56:03.359 DEBUG ScriptManager:83                 Script search paths: ("C:/Users/degerrit/.config/Clementine/scripts", "/usr/local/s
hare/clementine/scripts", "/usr/share/clementine/scripts", "/usr/local/share/clementine/scripts", "C:/Program Files/Clementine/scripts"
)
22:56:03.360 DEBUG MainWindow:205                   Starting
22:56:03.381 WARN  IconLoader:54                    Couldn't load icon "find"
22:56:03.382 DEBUG WmdmLister:58                    Starting
22:56:03.425 DEBUG MainWindow:249                   Initialising player
22:56:03.428 DEBUG MainWindow:255                   Creating models
22:56:03.460 DEBUG MainWindow:277                   Creating UI
22:56:03.462 DEBUG WmdmLister:65                    Obtaining CP container
22:56:03.464 DEBUG Windows7ThumbBar:46              Setting actions
22:56:03.467 DEBUG Windows7ThumbBar:55              Done
22:56:03.481 DEBUG MainWindow:590                   Creating sparkle updater
22:56:03.484 DEBUG MainWindow:641                   Creating equalizer
22:56:03.480 DEBUG WmdmLister:69                    Obtaining CP
22:56:03.485 DEBUG MainWindow:656                   Creating now playing widget
22:56:03.490 DEBUG WmdmLister:73                    Registering for notifications
22:56:03.503 DEBUG MainWindow:668                   Registering script action locations
22:56:03.563 DEBUG MainWindow:700                   Loading settings
22:56:03.582 DEBUG MainWindow:740                   Initialising library
22:56:03.587 DEBUG MainWindow:753                   Initialising scripting
22:56:03.588 DEBUG ScriptManager:96                 Initialising
22:56:03.589 DEBUG ScriptManager:141                Adding directory watch: "C:/Users/degerrit/.config/Clementine/scripts"
22:56:03.591 DEBUG MainWindow:766                   Started
22:56:03.761 DEBUG WmdmLister:80                    Fetching device list
22:56:03.762 DEBUG WmdmLister:96                    Querying device
22:56:03.763 DEBUG WmdmLister:155                   Reading device info
22:56:03.774 DEBUG WmdmLister:172                   Read device strings: "E63 - Phone memory" "Nokia" "\\?\root#wpd#0006#{f33fdc04-d1ac
-4e8e-9a30-19bbd4b108ae}$0"

C:\Users\degerrit>

_Original issue: http://code.google.com/p/clementine-player/issues/detail?id=1851_

**Comment by Chocobozzz** [comment]
Closing this old issue. Feel free to reopen.
