### ISSUE TITLE
global shortcuts for love / ban last.fm actions

### ISSUE THREAD

**Issue by Clementine-Issue-Importer** [clementine-player/Clementine#1885]
_From [f.flottum](https://code.google.com/u/101430033791486202242/) on May 14, 2011 21:37:15_

Adding the option to have a shortcut for loving a track on last.fm

_Original issue: http://code.google.com/p/clementine-player/issues/detail?id=1885_

**Comment by edvinasme** [comment]
+1 as it is the only feature that I REALLY miss from Clementine so far.
