### ISSUE TITLE
Your GStreamer installation is missing a plug-in

### ISSUE THREAD

**Issue by Clementine-Issue-Importer** [clementine-player/Clementine#1893]
_From [sebastien.lourenco](https://code.google.com/u/117884917900009643530/) on May 17, 2011 22:06:58_

What steps will reproduce the problem? 1.can't read some streams 2. 3. What is the expected output? What do you see instead? I don't know how to fix it.., it can't read some streams.. What version of the product are you using? On what operating system? Clementine 0.7.1 on windows 7 Please provide any additional information below.

**Attachment:** [Sans titre.jpg](http://code.google.com/p/clementine-player/issues/detail?id=1893)

_Original issue: http://code.google.com/p/clementine-player/issues/detail?id=1893_

**Comment by kapitaali** [comment]
Also 1.3.1, on Debian 9.
