### ISSUE TITLE
Crashes when adding music to library from the preferences. (Adding a folder)

### ISSUE THREAD

**Issue by Clementine-Issue-Importer** [clementine-player/Clementine#1927]
_From [hermania](https://code.google.com/u/106361712905658658478/) on May 26, 2011 21:12:20_

What steps will reproduce the problem? 1.Adding music from preferences. (Adding folders) What is the expected output? What do you see instead? Expect to see music added to Library.  Instead, Clementine crashes. What version of the product are you using? On what operating system? Clementine 0.7. Mac OSX 10.6.7 Please provide any additional information below. Error report was too long so I put it into a text file and attached it.

**Attachment:** [Clementine Error Report.rtf](http://code.google.com/p/clementine-player/issues/detail?id=1927)

_Original issue: http://code.google.com/p/clementine-player/issues/detail?id=1927_

**Comment by Chocobozzz** [comment]
Closing this outdated issue. Please tell us if you notice this issue with the latest release.
