### ISSUE TITLE
ID3 Tag Editing by Pressing F2 Button in Playlist

### ISSUE THREAD

**Issue by Clementine-Issue-Importer** [clementine-player/Clementine#194]
_From [turkay.eren](https://code.google.com/u/104967927358743630188/) on April 11, 2010 13:25:40_

Amarok on KDE3 supported tag editing by pressing F2 button on playlist. 
However, I cannot find this feature in Clementine.

It would be more easy to use this feature instead of repeatedly right-
clicking the song, and pressing "Edit Track Information".

The features that are expected:
1- When F2 is pressed, the first column in the playlist should turn into 
editbox, and all the text in it should be selected at first.
2- When TAB is pressed, it should go to the next column.
2- When Enter is pressed, it should save ID3 tag.

_Original issue: http://code.google.com/p/clementine-player/issues/detail?id=194_

**Comment by NeverLoved** [comment]
I think this thing should be editable at least! 
I Use F-keys for player control (f2 next, f3 pause, f4 stop, f5 prev), and when i'm hitting F2 - clementine switches to next song (according to global hotkeys setting), but dont move focus on current position - just stays at current position with edit on "name" tag.
My point is, can I configure clementine internal hotkeys?
