### ISSUE TITLE
METADATA_BLOCK_PICTURE tag in OGG support

### ISSUE THREAD

**Issue by Clementine-Issue-Importer** [clementine-player/Clementine#2016]
_From [codered12](https://code.google.com/u/111278372810347666010/) on June 24, 2011 18:52:26_

Hello

I posted this on the mailing list, but didn't get any reply. Anyway here's the issue.

I recently tried out clementine to test album art in my ogg vorbis
files.It seems that clementine doesn't support the official
specification of METADATA_BLOCK_PICTURE for cover art, and instead
supports COVERART. Is there a particular reason not to support the
official specification?

Please take a look here: http://wiki.xiph.org/VorbisComment#Cover_art I would request that for maximum compatibility, the devs please support
the METADATA_BLOCK_PICTURE comment as well as COVERART comment.

Thanks

_Original issue: http://code.google.com/p/clementine-player/issues/detail?id=2016_

**Comment by notfoss** [comment]
@hatstand 

I just tried it with clementine 1.2.3~trusty from the PPA, but it still isn't working. None of my ogg files with METADATA_BLOCK_PICTURE are showing the album art. Let me know if you need more information.
