### ISSUE TITLE
Sort by album that respects track number

### ISSUE THREAD

**Issue by Clementine-Issue-Importer** [clementine-player/Clementine#2075]
_From [palfguy](https://code.google.com/u/109248715178465400305/) on July 12, 2011 22:31:59_

Long time iTunes user, switched to Ubuntu and welcomed Clementine into my life.  One thing that irks me a lot, is if I sort by album it sorts the song by album but doesn't sort the albums into the correct track number order.  This seems like a logical feature to have.

_Original issue: http://code.google.com/p/clementine-player/issues/detail?id=2075_

**Comment by dowcet** [comment]
A closely related issue that remains open: https://github.com/clementine-player/clementine/issues/1154
