### ISSUE TITLE
Clementine is practically unusable with non-local network drives

### ISSUE THREAD

**Issue by Clementine-Issue-Importer** [clementine-player/Clementine#2126]
_From [dizone](https://code.google.com/u/108195363667358142598/) on August 04, 2011 02:06:35_

What steps will reproduce the problem? 1. Setup a large (>80G) Media library over non local network drive
2. Play music What is the expected output? What do you see instead? Should be playing the song (after potentially one or two seconds of pre-buffering) with no hiccups. Playback should be gap less between songs. Exiting the application shouldn't take 5 minutes.

Instead:
- there are lots of hiccups while playing any song (I've tried different albums, different bitrates, this is an all MP3 collection); it makes using the application unbearable (the hiccups also seem random)
- between songs it takes a 2-3 seconds break
- exiting the application takes about 5 minutes (in this time the application icon is present on the Dock) What version of the product are you using? On what operating system? 0.7.1, OS X 10.6.x Please provide any additional information below. If I disable library update monitoring then the exit issue is resolved (Clementine exits immediately). But the hiccups and non gap less playback problems persist. I tried increasing the gstreamer buffer size (from 1second to 5) and it did not help, it actually seems to increase the gap between songs. The network drive I'm playing from can provide data with a fairly constant rate of about 300kbytes/s (that is about 10 times more than a 256kbit MP3 stream) so there should be no reason for Clementine to work with the drive. If I copy an album on the local disk and play it from there with Clementine it works as expected.

Any other OS X media player I tried seems to perform better with the same network drive:
- iTunes is pretty slow at every startup (probably trying to scan everything) but has no playback hiccups nor gaps between songs
- Songbird <= 1.8.x worked perfectly (if not for the constant last.fm problems); Songbird >= 1.9.x started having gaps between consecutive songs
- Cog (old, obsolete, simple media player) has no issues (but also doesn't have library management)

I like the features Clementine provides and overall how fast it reacts to actions (as opposed to iTunes) but because of the problems described it's practically unusable with non local network drives.

_Original issue: http://code.google.com/p/clementine-player/issues/detail?id=2126_

**Comment by cemelmaci** [comment]
please see here https://github.com/clementine-player/Clementine/issues/4563

I posted this as a reply to #3653 on the original issue tracker but apparently it was eaten by the migration to github. Since I just ran into this frustrating bug again I thought I'd post my fix on this issue:For anyone else pulling their hair out over this this issue: turns out that a recent kernel change re: cifs could be to blame.If you check the mount.cifs man page, there is a option "cache=loose". This was the default before kernel 3.7. Afterwards it changed to "cache=strict".Switching back to cache=loose fixed the issue for me.
--
