### ISSUE TITLE
Export music to conventional folder and file structure

### ISSUE THREAD

**Issue by Clementine-Issue-Importer** [clementine-player/Clementine#2134]
_From [garethnickson](https://code.google.com/u/garethnickson@gmail.com/) on August 05, 2011 00:30:40_

My current process is as follows :-
1. Open Banshee and ensure that playlist has all metadata fields matching for relevant files, and remove the disc 1 of 2 metadata to ensure that end result files multi-disc album in to 1 folder.
2. Do full library re-scan in Clementine.
3. Create playlist.
4. Create folder to export music files to. /home/user/music_export/
5. Clementine > Tools > Preferences > Music Library > Add New Folder > (select folder from previous step.
6. Select all tracks in playlist.
7. Right click > Organise files > Set destination to new folder from step 4.
8. Change 2nd option 'After copying...' to keep the original files.
9. Click OK.
10. Carry out whatever task I wish to complete next with exported data.
11. Delete folder from local drive using a file manager (not Clementine), so as not to have duplicates in library.
12. Reverse step 5, if you like to keep things tidy.

After processing (step 9) I have a folder that can be relocated or burned to DVD for playback elsewhere (dvd player, car, mobile phone memory card, etc).

Exporting to a new folder would be so much easier.

NB. I have not managed to find a burning software that can import a playlist and burn to data disc, rather than audio cd. Hence this convoluted process.

_Original issue: http://code.google.com/p/clementine-player/issues/detail?id=2134_

**Comment by richlv** [comment]
this is exactly what i wanted to do - copying the files, based on a playlist, to an arbitrary directory. the hackish workaround above works (and thanks to the now-anonymous-author for that), but a bit more convenient way would be better.

could we please reopen this issue, so that i don't have to create a duplicate ? :)

**Comment by fcastilloec** [comment]
I also need this feature. I have a big music library and I sync a subset of it into a folder where other devices can sync to. I don't want to sync my whole library, and having a subset sync to a local folder allows me to use rsync, bittorrent sync or any other protocol that automatically pushes changes (and only the changes) to my devices.

**Comment by avimar** [comment]
Thanks, I was able to use these steps to create a second scanned folder, and then duplicate my playlist to that second folder to sync between devices (using syncthing).
