### ISSUE TITLE
sometimes clementine does not update tags (when they were edited with external tagging software for example)

### ISSUE THREAD

**Issue by Clementine-Issue-Importer** [clementine-player/Clementine#221]
_From [trickykid1982](https://code.google.com/u/trickykid1982@gmail.com/) on April 16, 2010 01:07:24_

What steps will reproduce the problem? 1.Editing metadata in .flac files, either using Clementine or external tag
editor/player. What is the expected output? What do you see instead? Tags do not update in library despite being written to file. What version of the product are you using? On what operating system? OS X 0.3 beta 2 Please provide any additional information below.

_Original issue: http://code.google.com/p/clementine-player/issues/detail?id=221_

**Comment by jerobarraco** [comment]
i'm still having the issue, i'm trying to solve the problem but when i debug it it doesn't seem to show the behavior.

**Comment by kevincox** [comment]
I'm using 1.2.3 on Arch Linux and tag editing now appears to be working most of the time.  There are some rare cases where it doesn't apply but I haven't been able to track down when that it (I suspect it has something to do with filtering a playlist then editing a track but am not sure).

**Comment by tommycarstensen** [comment]
Same issue with 1.2.2 on Mac.

**Comment by zoltan-sule** [comment]
I was happy when I found the Clementine, because I think this is a good alternative and what is more this is the best music player for kind of linux users like me.
But this caching (I just suppose it) problem gives me big troubles. This way I can't manage my albums. I have to spend a lot of time to remove the musics from the list, rename them and add them to the same list one after the other (remembering all of them) all the time if I change the BPM, the comment with bpm-tool or with puddletag.
I imagine a simple button: switch of the pre-caching. Or a button that clean the caches, but don't remove the lists and the ratings. I don't mind if the loading of it isn't so fast, because the process above takes hours.

I am in Ubuntu 14.04 + Clementine 1.2

**Comment by Hepo** [comment]
I'm running Linux Mint 17.1 and Clementine 1.2.3 from PPA. Still encountering this bug; updating the tags, rescanning the library, removing/re-adding the library does not fix the issue. The artist is constantly put underneath its Genre as "Various Artists".

**Comment by rodrigodiez** [comment]
Is there any special feature around the 'various' keywork in a tag? As far as I remember, most of the times that I have experimented issues with tagging they were while trying to update a 'various' ish tag

**Comment by spock** [comment]
This issue looks like what I am looking for...

My setup:
- around 70 GB of music, 20.5k files (including .mood);
- the 'music' directory is synced between 2 PCs (home and work), both running Debian testing, Clementine 1.2.3+dfsg-3;
- ratings and play/skip counts are saved to files on both PCs;
- the idea is to maintain "the same" library across multiple devices, preserving ratings/play/skip counts.

The problem:
- after 'music' directory sync finishes, I start Clementine and `Do a full library rescan`, but Clementine does not see updated play/skip counts and ratings - the old values (from the database, I guess) are still shown;
- in the context of this issue, this seems equivalent to "external tag editing";
- it might be the case that upon playing a file Clementine will write "play count = 1" even if the file already had a higher play count in it, but had nothing in the database; I haven't tested this good enough to be sure, though.

The workaround (as already mentioned in some comments above):
- open Tools -> Preferences -> Library, delete 'music' directory, then immediately re-add it, and let Clementine re-scan everything (the process is surprisingly quick!);
- note: if the Preferences dialog is closed before adding 'music' back after removing it, currently open playlists will lose their content.

I'll gladly provide more info or do more testing, I just need to know what kind of testing is required :)

**Comment by kdesmet** [comment]
The problem is the time. If you change the tag with an external program (like EasyTag) the upper dir time does not change. Sometimes Clementine refuses to change tags (no warning or anything), so an external program is sometimes needed. Perform following command and then do a library update. It recursively resets the date for files and dirs.

find "Bb King & Eric Clapton" -exec touch {} \;

Now Clementine will rescan and update the tags in directory "Bb King & Eric Clapton". That's my linux solution, don't know for mac and windows! 
A full rescan every time for a little change with a very large library is just insane.

**Comment by tchoulihan** [comment]
I have this issue with clementine 1.2.3 in ubuntu. After changing the name of a track, it gets stuck on "Updating library...", and I have to restart clementine to get it to work again.

**Comment by jerobarraco** [comment]
i have an ssd, so i have mounted it with -o relatime. 
maybe thats part of the problem.
i also have my files synced over internet, so i will never update the time unless extremely necessary.

**Comment by RandomReaper** [comment]
I have clementine 1.2.3 in ubuntu 14.04.3 LTS, and it bugs updating the database...

@jerobarraco Using `-o relatime` should not be a problem. I use `-o noatime` on all my linux boxes, never seen any problem related to this.

**Comment by ahdok** [comment]
There's an awful lot of discussion and issues here, but my version of this problem is pretty simple. It is impossible for me to edit or update any tag information in Clementine at all, I can open different menus to edit tags, but the moment I save a tag, it immediately reverts to the wrong tag, and nothing is changed. This behaviour isn't intermittent, it happens no matter what I try. I'm using the current release  (1.2.3) on windows 10.

It's sad for me, because a long time using iTunes has left me with a hugely corrupt set of broken or wrong tags. The musicbrainz tagger in Clemtine is almost always right, but I can't fix or change anything with Clementine, so it's very difficult for me to want to make the switch.

**Comment by narunlifescience** [comment]
Clementine recently updated to taglib 1.10.0 (#5129). could you check if the issue persists with the developer builds ? http://builds.clementine-player.org/

**Comment by cristianmtr** [comment]
For me this worked:

I had this album with these files:
```
» ls -l                                          /cygdrive/d/music/Atheist/Elements
total 98316
-rw-r--r-- 1 cristian None 13375704 Jan  9 17:57 Air.mp3
-rw-r--r-- 1 cristian None 10065479 Jan  9 17:56 Animal.mp3
-rw-r--r-- 1 cristian None  3415773 Jan  9 17:54 Displacement.mp3
-rw-r--r-- 1 cristian None  9348677 Jan  9 17:54 Earth.mp3
-rw-r--r-- 1 cristian None 13916983 Jan  9 17:54 Elements.mp3
-rw-r--r-- 1 cristian None 11103055 Jan  9 17:53 Fire.mp3
-rw-r--r-- 1 cristian None  1773197 Jan  9 17:54 Fractal_Point.mp3
-rw-r--r-- 1 cristian None  8111545 Jan  9 17:57 Green.mp3
-rw-r--r-- 1 cristian None 10947377 Jan  9 17:54 Mineral.mp3
-rw-r--r-- 1 cristian None  4752193 Jan  9 17:47 Samba_Briza.mp3
-rw-r--r-- 1 cristian None  3100220 Jan  9 17:54 See_You_Again.mp3
-rw-r--r-- 1 cristian None 10747794 Jan  9 17:54 Water.mp3
```

But originally they had track number - track title in the filename. And that's how they showed up in Clementine. Of course, I had to get the correct tags (without the track number in the title). 

What I did to get Clementine to save the tags:

- Make sure you turn **off** auto sync of library;
- Add album to playlist
- Right click all songs - Automatically get tags...
- Accept defaults
- **DO NOT** play any of the songs yet
- Right click all songs selection again - organise files
- Make sure track no is not set in the format line
  - I had the following:
   ```
%artist/%album{ (Disc %disc)}/%title.%extension
```
- Save
- Tools - Sync dir updates

**Comment by JulianVolodia** [comment]
So, when not play song or auto sync was disabled is it caused bug still?

**Comment by matvidaln** [comment]
Hi,
I have the same issue in Version 1.2.3. running in linux mint 17.3. 
Today, serendipitously, I found a different solution to the problem:

1- Modify the tag of the files using clementine. 
2- In order to get them saved by clementine, I temporarly moved the directory with the modified songs to a different location and pressed "updated changed library files". 
3- Move back the directory with the songs to the original location and press again "updated changed library files". 

Hope is useful!

**Comment by UndeadKernel** [comment]
The bug is still there in Clementine 1.3.1
After modifying the tags of some MP3 files, Clementine would refuse to show the updated tags.
As stated by the previous comment, by renaming the folder with the edited songs and updating the library, the tags were picked up correctly.

**Comment by lursel** [comment]
I too have this problem (Clementine 1.3.1), both on Linux Mint 18 and Windows 10. Even playing another song after renaming a track (without restarting) reverts changes.

**Comment by ssrublev** [comment]
In my Fedora Linux Clementine's Tag fetcher doesn't work at all (can't find any song). MusicBrainz Picard and its libraries are installed and work.

**Comment by nkosi23** [comment]
> I too have this problem (Clementine 1.3.1), both on Linux Mint 18 and Windows 10. Even playing another song after renaming a track (without restarting) reverts changes.

Same problem on Windows 10, changes reverted as soon as either : 
- The song is played, then another another song is played
- Clementine is restarted

Very annoying problem, massively affecting usability, why hasn't it been fixed for so long ? From a macro perspective I find suspicious that libtag would have such a blatant bug, my speculation is that stuff are being done in-memory and a persistence method is not called when it should be, could be as simple as that.
.
Thanks for the work anyway, hopefully someone has the bandwidth to look into it.

**Comment by fcastilloec** [comment]
I'd like to add that the only way to fix this is by doing a full library rescan, simply updating changed library folders doesn't do anything. Any chance this can get fix in the next release?

**Comment by thenewnano** [comment]
I have some issues when editing tags does not stick on OSX. Will remove Clementine and install it again now and download my library again, if the problems is still there I guess I have to stick with my second Ubuntu machine for DJ-ing, my old one died on me and I was thinking to use my MacBook .

**Comment by thenewnano** [comment]
well I don't know if I should create a new issue... So sad I can't move over to my MacBook , and this issue has been there for years :( 

Changes are made to file but not to databse, full library scan is extremely slow in Mac and absolutely not an option, creating new playlists doesn't help, tags are not changed in the UI or library View regardless. Same version of Clementine in Ubuntu works just fine. 

clementine-1.3.1-537-g3c8a558
osx 10.14.3 Beta (18D32a)
Music Library with over 40000 files

**Comment by JulianVolodia** [comment]
So, looking for changes in files with changed checksums or even faster - last modification time will be cool?

**Comment by JulianVolodia** [comment]
Hello
Could you reply about issues here, and clean up a bit @thenewnano @brokenwu @fcastilloec @nkosi23  @ssrublev  @lursel @UndeadKernel @matvidaln @cristianmtr @ahdok @narunlifescience  ? 

Before doing below check if issue is quite recent, and maybe it was already fixed.

Great to have:
- summary *what to do* here when someone get this item to work with,
- fulfill issue again, even changing subject to have it clear with corespondence with current state of issue, leaving it in *great condition* in backlog for future work when someone have time.

Will appreciate if some important (like workarounds, recomendation for fixes, pre-investigation info) will be left with mark with ~shattering~ with `~this~` for fast reference, but best is to leave issue *most compressed as you could*.

Thanks in advance.

**Comment by ssrublev** [comment]
In my current (latest) Fedora Linux Clementine's "Complete tags automatically" function every time causes Clementine to crash. ABRT bug report about this to Fedora Bugzila (I made 2 or 3) automatically receives invisible status and never get any answer.

**Comment by JulianVolodia** [comment]
@ssrublev neat. Good to know. Have some debug log output which you could provide, more for compare than resolve so not necessarly.

**Comment by ssrublev** [comment]
Console output:
<pre>
(clementine:21119): GStreamer-CRITICAL **: 17:29:22.915: gst_mini_object_unlock: assertion 'state >= SHARE_ONE' failed

(clementine:21119): GStreamer-CRITICAL **: 17:29:22.915: gst_mini_object_unref: assertion 'GST_MINI_OBJECT_REFCOUNT_VALUE (mini_object) > 0' failed
Segmentation fault (core dumped)
</pre>

ABRT output: 
<pre>
SHELL=/bin/bash
IMSETTINGS_INTEGRATE_DESKTOP=yes
SESSION_MANAGER=local/unix:@/tmp/.ICE-unix/980,unix/unix:/tmp/.ICE-unix/980
WINDOWID=71303174
COLORTERM=truecolor
XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session0
HISTCONTROL=ignoredups
HISTSIZE=1000
HOSTNAME=ssr-dexp-fedora
SSH_AUTH_SOCK=/run/user/1000/keyring/ssh
XMODIFIERS=@im=none
DESKTOP_SESSION=mate
SSH_AGENT_PID=1166
XDG_SEAT=seat0
MATE_DESKTOP_SESSION_ID=this-is-deprecated
PWD=/home/ssr
LOGNAME=ssr
XDG_SESSION_DESKTOP=mate
XDG_SESSION_TYPE=x11
XAUTHORITY=/run/lightdm/ssr/xauthority
XDG_GREETER_DATA_DIR=/var/lib/lightdm-data/ssr
HOME=/home/ssr
LANG=en_US.UTF-8
LS_COLORS=rs=0:di=38;5;33:ln=38;5;51:mh=00:pi=40;38;5;11:so=38;5;13:do=38;5;5:bd=48;5;232;38;5;11:cd=48;5;232;38;5;3:or=48;5;232;38;5;9:mi=01;37;41:su=48;5;196;38;5;15:sg=48;5;11;38;5;16:ca=48;5;196;38;5;226:tw=48;5;10;38;5;16:ow=48;5;10;38;5;21:st=48;5;21;38;5;15:ex=38;5;40:*.tar=38;5;9:*.tgz=38;5;9:*.arc=38;5;9:*.arj=38;5;9:*.taz=38;5;9:*.lha=38;5;9:*.lz4=38;5;9:*.lzh=38;5;9:*.lzma=38;5;9:*.tlz=38;5;9:*.txz=38;5;9:*.tzo=38;5;9:*.t7z=38;5;9:*.zip=38;5;9:*.z=38;5;9:*.dz=38;5;9:*.gz=38;5;9:*.lrz=38;5;9:*.lz=38;5;9:*.lzo=38;5;9:*.xz=38;5;9:*.zst=38;5;9:*.tzst=38;5;9:*.bz2=38;5;9:*.bz=38;5;9:*.tbz=38;5;9:*.tbz2=38;5;9:*.tz=38;5;9:*.deb=38;5;9:*.rpm=38;5;9:*.jar=38;5;9:*.war=38;5;9:*.ear=38;5;9:*.sar=38;5;9:*.rar=38;5;9:*.alz=38;5;9:*.ace=38;5;9:*.zoo=38;5;9:*.cpio=38;5;9:*.7z=38;5;9:*.rz=38;5;9:*.cab=38;5;9:*.wim=38;5;9:*.swm=38;5;9:*.dwm=38;5;9:*.esd=38;5;9:*.jpg=38;5;13:*.jpeg=38;5;13:*.mjpg=38;5;13:*.mjpeg=38;5;13:*.gif=38;5;13:*.bmp=38;5;13:*.pbm=38;5;13:*.pgm=38;5;13:*.ppm=38;5;13:*.tga=38;5;13:*.xbm=38;5;13:*.xpm=38;5;13:*.tif=38;5;13:*.tiff=38;5;13:*.png=38;5;13:*.svg=38;5;13:*.svgz=38;5;13:*.mng=38;5;13:*.pcx=38;5;13:*.mov=38;5;13:*.mpg=38;5;13:*.mpeg=38;5;13:*.m2v=38;5;13:*.mkv=38;5;13:*.webm=38;5;13:*.ogm=38;5;13:*.mp4=38;5;13:*.m4v=38;5;13:*.mp4v=38;5;13:*.vob=38;5;13:*.qt=38;5;13:*.nuv=38;5;13:*.wmv=38;5;13:*.asf=38;5;13:*.rm=38;5;13:*.rmvb=38;5;13:*.flc=38;5;13:*.avi=38;5;13:*.fli=38;5;13:*.flv=38;5;13:*.gl=38;5;13:*.dl=38;5;13:*.xcf=38;5;13:*.xwd=38;5;13:*.yuv=38;5;13:*.cgm=38;5;13:*.emf=38;5;13:*.ogv=38;5;13:*.ogx=38;5;13:*.aac=38;5;45:*.au=38;5;45:*.flac=38;5;45:*.m4a=38;5;45:*.mid=38;5;45:*.midi=38;5;45:*.mka=38;5;45:*.mp3=38;5;45:*.mpc=38;5;45:*.ogg=38;5;45:*.ra=38;5;45:*.wav=38;5;45:*.oga=38;5;45:*.opus=38;5;45:*.spx=38;5;45:*.xspf=38;5;45:
XDG_CURRENT_DESKTOP=MATE
VTE_VERSION=5803
XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
IMSETTINGS_MODULE=none
XDG_SESSION_CLASS=user
TERM=xterm-256color
GTK_OVERLAY_SCROLLING=0
LESSOPEN=||/usr/bin/lesspipe.sh %s
USER=ssr
DISPLAY=:0
SHLVL=1
QT_IM_MODULE=xim
XDG_VTNR=1
XDG_SESSION_ID=1
XDG_RUNTIME_DIR=/run/user/1000
LC_TIME=ru_RU.UTF-8
QT_AUTO_SCREEN_SCALE_FACTOR=0
PATH=/home/ssr/.local/bin:/home/ssr/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin
GDMSESSION=mate
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
MAIL=/var/spool/mail/ssr
QT_SCALE_FACTOR=1
_=/usr/bin/clementine
</pre>

Easily reproducible, I can provide other ABRT data if needed

**Comment by JulianVolodia** [comment]
@ssrublev must be reproduced on my side, sorry for long wait.

**Comment by ssrublev** [comment]
I have just discovered and installed latest 1.4 on Fedora 32 and I see this crash no more! Will try later in Ubuntu! If this is fixed that's amazing!!! I guess we have to thank @hatstand

**Comment by ssrublev** [comment]
I confirm, 1.4 rcs have this problem no more in Ubuntu 20.04

**Comment by JulianVolodia** [comment]
Dear @hatstand
That looks like this could be closed.

**Comment by nkosi23** [comment]
This should not be closed, @ssrublev has kind of hijacked this thread with his crash report. This issue wasn't about a crash but about the fact that Clementine does not update tags. No one has reported that this problem has been fixed, there is no reason to close this.

**Comment by JulianVolodia** [comment]
Hmmm, so that is my fault then @nkosi and @fcastilloec 

So, full case description please. I will try to do what you see and get over with that. Please, be detailed not about logs but steps. Best make sceen recording with narrow thing.

I want to see clean Clementine 1.4.
Then, you showing tags in Clementine.
Next, your external tag modifier and saving this changes.
At the end - showcase in clementine that it not worked.

One video without cutting. Then I will reproduce and debug that fully.

Thanks.

**Comment by fcastilloec** [comment]
@JulianVolodia 
Here's the video you requested, the only thing to note is that I recently updated to Ubuntu 20.04 and I'm using Clementine from the official repos, so the version is v1.4.0-rc1 and you guys don't have a focal `.deb` in your latest release.

[Peek 2020-06-29 16-35.webm.zip](https://github.com/clementine-player/Clementine/files/4848536/Peek.2020-06-29.16-35.webm.zip)

**Comment by JulianVolodia** [comment]
Thanks. BTW. GitHub shows edit history. no need to adding Edit mark

**Comment by ssrublev** [comment]
> you guys don't have a focal `.deb` in your latest release.

I see `clementine_1.4.0rc1-283-g0fcb1df20.focal_amd64.deb` in assets, all releases have this .deb which I used to install

**Comment by JulianVolodia** [comment]
> > you guys don't have a focal .deb in your latest release.

> I see clementine_1.4.0rc1-283-g0fcb1df20.focal_amd64.deb in assets, all releases have this .deb which I used to install

Hi @ssrublev , I don't have any doubts against it, just mention that we both work on same thing.

@fcastilloec @ssrublev will you be able to test out the patch I send you by compiling on your machines?
Have you any programming experience?

Best regards.

**Comment by ssrublev** [comment]
> @fcastilloec @ssrublev will you be able to test out the patch I send you by compiling on your machines?
> Have you any programming experience?

I have very little programming experience but have adminning. If you tell me what to do, I think I can try to test. I can test in Fedora, Ubuntu, Windows 7, Windows 10 and sometimes also Windows 8.

**Comment by mlig212** [comment]
Hey
Same problem on Windows 10, 5 dec 21... No fix?

**Comment by ssrublev** [comment]
> Hey Same problem on Windows 10, 5 dec 21... No fix?

Do not install 1.3.1, instal latest 1.4 pre-release from Github https://github.com/clementine-player/Clementine/releases

**Comment by bannisdale** [comment]
> > Hey Same problem on Windows 10, 5 dec 21... No fix?
> 
> Do not install 1.3.1, instal latest 1.4 pre-release from Github https://github.com/clementine-player/Clementine/releases

Just installed Version 1.4.0rc1-814-g2b340da79 but have the same issue on Windows 10.

Playlist with 20 tracks, edited a title and a year for two separate tracks. A few minutes later, both changes aren't visible in the playlist but are reflected in the file tags.

**Comment by pie3636** [comment]
@hatstand Please refer to the last 9 comments. This issue is not fixed yet and should not have been closed.
