### ISSUE TITLE
Pandora Integration

### ISSUE THREAD

**Issue by Clementine-Issue-Importer** [clementine-player/Clementine#2211]
_From [Auth...@gmail.com](https://code.google.com/u/117800788601712233693/) on September 03, 2011 20:52:38_

Clementine supports integration with several online streaming services. The one I use is Pandora; can we get Pandora integration with Clementine?

_Original issue: http://code.google.com/p/clementine-player/issues/detail?id=2211_

**Comment by curtisgibby** [comment]
:+1:

**Comment by chris13524** [comment]
Any update on this? I made my own application for playing Pandora using this API documentation: https://6xq.net/pandora-apidoc/json/

**Comment by hatstand** [comment]
Without an official API, it's unlikely.

**Comment by chris13524** [comment]
Why do you have to use an official API? This is the API that Pandora uses, it's just not documented by Pandora.

**Comment by chris13524** [comment]
It is the "official" API.

**Comment by Ferroin** [comment]
If there's not an officially acknowledged publicly documented API, that puts anyone who uses whatever API they may expose in a tenuous legal position, which is not a good place for an open source project to be in.

Unless they give explicit permission for third party applications to use this API, then Clementine can't do so in most legal jurisdictions.

**Comment by ColinHarrington** [comment]
:+1: for Pandora Integration.

**Comment by HaoZeke** [comment]
Well... Pithos and pianobar manage to use Pandora...

**Comment by Uberarchangel** [comment]
So Pandora offers APIs

https://developer.pandora.com/docs/key-concepts/apis/

Odds of this happening still low?
