### ISSUE TITLE
Clementine changes id3v2 tags to id3v1 tags when editing tags.

### ISSUE THREAD

**Issue by Clementine-Issue-Importer** [clementine-player/Clementine#2282]
_From [the.bina...@gmail.com](https://code.google.com/u/111139589827521053810/) on October 08, 2011 09:11:45_

What steps will reproduce the problem? 1. Add mp3 with id3v2 tags to the playlist
2. Edit fields/tags via the playlist 3. What is the expected output? What do you see instead? ==Before changing==
psyber@Bitslip:~/Downloads/mp3$ file 01-The_Concubines_Of_Debauchery-Emil_Bulls-Oceanic-2011.flac.mp3 
01-The_Concubines_Of_Debauchery-Emil_Bulls-Oceanic-2011.flac.mp3: Audio file with ID3 version 2.3.0, contains: MPEG ADTS, layer III, v1, 320 kbps, 44.1 kHz, JntStereo

psyber@Bitslip:~/Downloads/mp3$ id3v2 -l 01-The_Concubines_Of_Debauchery-Emil_Bulls-Oceanic-2011.flac.mp3 
id3v2 tag info for 01-The_Concubines_Of_Debauchery-Emil_Bulls-Oceanic-2011.flac.mp3:
TSSE (Software/Hardware and settings used for encoding): LAME 32bits version 3.98.2 ( http://www.mp3dev.org/ )
TLEN (Length): 79440
TIT2 (Title/songname/content description): The Concubines Of Debauchery

TRCK (Track number/Position in set): 01

TPE1 (Lead performer(s)/Soloist(s)): Emil Bulls

TALB (Album/Movie/Show title): Oceanic

TYER (Year): 2011

TCON (Content type): Electronic
 (255)
== After Changing ==
psyber@Bitslip:~/Downloads/mp3$ file 01-The_Concubines_Of_Debauchery-Emil_Bulls-Oceanic-2011.flac.mp3 
01-The_Concubines_Of_Debauchery-Emil_Bulls-Oceanic-2011.flac.mp3: Audio file with ID3 version 2.4.0, contains: MPEG ADTS, layer III, v1, 320 kbps, 44.1 kHz, JntStereo

psyber@Bitslip:~/Downloads/mp3$ id3v2 -l 01-The_Concubines_Of_Debauchery-Emil_Bulls-Oceanic-2011.flac.mp3 
id3v1 tag info for 01-The_Concubines_Of_Debauchery-Emil_Bulls-Oceanic-2011.flac.mp3:
Title  : The Concubines Of Debauchery    Artist: Emil Bulls  
Album  : Oceanic                         Year: 2011, Genre: Unknown (255)
Comment:                                 Track: 1 What version of the product are you using? On what operating system? Clementine version: 0.7.1
OS: Linux Bitslip 2.6.32-30-generic #59trisquel1-Ubuntu SMP Sat Apr 2 19:23:44 UTC 2011 i686 GNU/Linux Please provide any additional information below. Attached is the window I use for "Mass editing" the files that changes the tags to id3v1.

**Attachment:** [Screenshot-Edit track information.png](http://code.google.com/p/clementine-player/issues/detail?id=2282)

_Original issue: http://code.google.com/p/clementine-player/issues/detail?id=2282_

**Comment by caph1993** [comment]
Is this issue solved? I am experiencing this issue, and when I transfer songs to my android device, the tags appear empty (because the app does not expect ID3v1 and ID3v2 simultaneously).

I am on linux, Clementine version 1.4rc1
