### ISSUE TITLE
Restarting after using "Stop after track" doesn't work right

### ISSUE THREAD

**Issue by Clementine-Issue-Importer** [clementine-player/Clementine#2351]
_From [Maximili...@googlemail.com](https://code.google.com/u/116188357758332011422/) on October 29, 2011 12:00:16_

When using the option "stop after a selected track" (which i like a lot) or "stop after the track playing", the restart doesn't work right. When restarting, the last played track is replayed. That shouldn't happen, as it is quite annoying skipping the track to get the right one.

After it stopped the last played track remains marked. Maybe this marking just has to jump to the next track.

I'm using Clementine 0.7.1 on Windows 7 32-bit.

Thanks for this nice player.

_Original issue: http://code.google.com/p/clementine-player/issues/detail?id=2351_

**Comment by paperbagcorner** [comment]
This issue has been fixed a long time ago. From what I can see, it was fixed in commit 53e175e5034cc4c024fc88bbcf06181426270c49.
