### ISSUE TITLE
Cannot copy from ipod to device(Ubuntu)

### ISSUE THREAD

**Issue by Clementine-Issue-Importer** [clementine-player/Clementine#2455]
_From [deck...@gmail.com](https://code.google.com/u/105511743628800930020/) on December 03, 2011 09:52:57_

What steps will reproduce the problem? 1.Connect iPod
2. Browse iPod library
3. Right-click and select copy to Lib What is the expected output? What do you see instead? Option to copy songs from iPod to Clemetine lib What version of the product are you using? On what operating system? clementine 1.10 rc 1. ipod classic 120GB, v2.0 Please provide any additional information below. I try this with Ubuntu 11.10

_Original issue: http://code.google.com/p/clementine-player/issues/detail?id=2455_

**Comment by FrankVanDamme** [comment]
Googled this problem and came straight to this issue...
