### ISSUE TITLE
Clementine RC1 Crashes "Clementine Has Stopped Working..." When Adding Folder To Library

### ISSUE THREAD

**Issue by Clementine-Issue-Importer** [clementine-player/Clementine#2458]
_From [Apex109](https://code.google.com/u/Apex109/) on December 03, 2011 23:05:52_

What steps will reproduce the problem? 1. Start Clementine
2. Select "Add Music" in the side pane
3. Add folder (from D: partition) What is the expected output? What do you see instead? Clementine is expected to scan the folder and add the music to the library, however Clementine immediately crashes upon beginning the scan with the Windows "this program has stopped working" dialog. What version of the product are you using? On what operating system? Clementine RC1, Windows 7 7600 x64 Please provide any additional information below. Clementine crashes upon subsequent startup until the config directory is cleared, removing the folder from the library.

** Adding the "My Music" folder from the C partition with some test MP3 files seems to still work properly. **

**Attachment:** [Capture.PNG](http://code.google.com/p/clementine-player/issues/detail?id=2458)

_Original issue: http://code.google.com/p/clementine-player/issues/detail?id=2458_

**Comment by Chocobozzz** [comment]
Closing this outdated issue. Please tell us if you notice this issue with the latest release.
