### ISSUE TITLE
Loading large library crashes my system

### ISSUE THREAD

**Issue by Clementine-Issue-Importer** [clementine-player/Clementine#2495]
_From [Porteou...@gmail.com](https://code.google.com/u/109259477069839007705/) on December 20, 2011 04:05:11_

What steps will reproduce the problem? 1. Set the Library folder to be my entire music library (about 450GB)
2. Clementine will seem to load the library OK after a while, but then I get the error
LibrayBackend: Unable to open database file. Unable to fetch row.
This dialog cannot be dismissed, and I can't switch out of Clementine. Can't force quit. I actually need to unplug my computer.

It worked fine when I only used part of my library.

What version of the product are you using? 
I have tried this with 0.7.1 and also 0.7.3-521-g4f11b50

I have a mid-2011 Core7 iMac with 8GB ram running MacOS 10.7.2

In general, would you prefer people to use the 0.7.1 version when reporting bugs? Or should I download recent builds often?

Is there a recommended max size for the library?

_Original issue: http://code.google.com/p/clementine-player/issues/detail?id=2495_

**Comment by Chocobozzz** [comment]
I think we can close this old issue since we have no news.
