### ISSUE TITLE
Spotify option crashes clementine 1.0.0 on Windows 7 64-bit

### ISSUE THREAD

**Issue by Clementine-Issue-Importer** [clementine-player/Clementine#2554]
_From [lilian...@gmail.com](https://code.google.com/u/109139625304353531138/) on January 03, 2012 17:15:36_

What steps will reproduce the problem? 1. Open Clementine 1.0.0
2. Go to(from the bar on the left): Internet -> Spotify(click on Spotify)
3. Observe a crash What version of the product are you using? On what operating system? The stable Clementine 1.0.0 on Windows 7 64-bit(I'll test it on Kubuntu 11.10 64-bit)

_Original issue: http://code.google.com/p/clementine-player/issues/detail?id=2554_

**Comment by Chocobozzz** [comment]
Please try with the latest build and reopen if you have the same issue.
