### ISSUE TITLE
Default Shortcuts Media keys are not working reliably

### ISSUE THREAD

**Issue by Clementine-Issue-Importer** [clementine-player/Clementine#2650]
_From [jedi...@gmail.com](https://code.google.com/u/116041503715672760647/) on January 23, 2012 06:41:53_

What steps will reproduce the problem? 1.Quit Clementine
2.Launch Clementine
3.Try to use Media keys (Play, Next, Previous, Stop) What is the expected output? What do you see instead? Clementine should react to Media keys pressed What version of the product are you using? On what operating system? Clementine 1.0 32bits Deb for Debian on Linux Mint debian edition (LMDE). Please provide any additional information below. I can work around by going to preferences and deselecting/reselcting the Media keys : 
In preferences / clicking on none and immediately after clicking on default again then Applying the changes will make the Media keys work recognised by Clementine but the workaround has to be repeated each time i relaunch clementine...).

_Original issue: http://code.google.com/p/clementine-player/issues/detail?id=2650_

**Comment by Chocobozzz** [comment]
Normally fixed.
