### ISSUE TITLE
Media keys doesn't work

### ISSUE THREAD

**Issue by Clementine-Issue-Importer** [clementine-player/Clementine#2679]
_From [Alan.Kut...@gmail.com](https://code.google.com/u/106423212661058507924/) on January 30, 2012 23:24:35_

What steps will reproduce the problem? 1.Run clementine
2.Push global media shortcut
3.It doesn't work What is the expected output? What do you see instead? Global shortcuts should work. What version of the product are you using? On what operating system? Clementine 1.0.1
Fedora 16
Gnome 3.2 Please provide any additional information below. Clementine writes warns:
23:20:11.179 WARN  unknown                          QxtGlobalShortcut failed to register: "Media Next"  
23:20:11.179 WARN  unknown                          QxtGlobalShortcut failed to register: "Media Play"  
23:20:11.180 WARN  unknown                          QxtGlobalShortcut failed to register: "Media Previous"  
23:20:11.180 WARN  unknown                          QxtGlobalShortcut failed to register: "Media Stop"

_Original issue: http://code.google.com/p/clementine-player/issues/detail?id=2679_

**Comment by 1358** [comment]
In KDE media keys starts working in clementine if they are globally unbound (system settings -> global shortcuts -> khotkeys -> none)

**Comment by Chocobozzz** [comment]
As @1358 the system shortcut prepends Clementine shortcut so you have to unset them manually.  Please reopen if you it still doesn't work.
