### ISSUE TITLE
Make your player 20&#37; cooler with Rainbow Dash

### ISSUE THREAD

**Issue by Clementine-Issue-Importer** [clementine-player/Clementine#2685]
_From [faust....@gmail.com](https://code.google.com/u/114894426186294597406/) on February 01, 2012 17:06:09_

You guys do really great player and not forget about funny things.

Could you add rainbow dash analyzer? like nyancat but with rainbow dash?

_Original issue: http://code.google.com/p/clementine-player/issues/detail?id=2685_

**Comment by paperbagcorner** [comment]
This feature has been implemented in revision 663b7430d8f9b2dca088a150ecaf112cd5ff9543 (pull request #4367) so I believe this issue can be closed.

Also, I think the priority of this issue should be higher.

**Comment by g4borg** [comment]
even this is the bestest feature ever, I find it sad, the colors are not exactly upside down to the nyan cat one, to meet the coloring of the trail to Dashs' tail.
