### ISSUE TITLE
Grooveshark stream URL displayed in case of HTTP connection issues

### ISSUE THREAD

**Issue by Clementine-Issue-Importer** [clementine-player/Clementine#2698]
_From [a...@official.fm](https://code.google.com/u/104964562763990631100/) on February 06, 2012 22:52:02_

What steps will reproduce the problem? 1. Play a Grooveshark track (requires a Grooveshark Anywhere subscription)
2. Provoke an HTTP timeout (for example, make a computer hibernate/sleep for a few, long enough for the TCP connection to die)
3. Clementine displays this error message http://i.imgur.com/AlGWT.png including the stream URL

I believe this error should never be shown to the user. Grooveshark attempts to make a GET with a 'Bytes' field in the HTTP header, but the Grooveshark servers don't support that. There's probably a Grooveshark request to make to obtain a stream URL that start with a certain position (or however Clementine handles seeking Grooveshark streams right now), that should be done instead - but at the very least, not displaying a dialog and moving on to the next track would still be an acceptable fix imho.

I tested this on Grooveshark 1.0 on Windows 7.

_Original issue: http://code.google.com/p/clementine-player/issues/detail?id=2698_

**Comment by Chocobozzz** [comment]
Closing this as Grooveshark is dead...
