### ISSUE TITLE
Play Count/Last played feature not working

### ISSUE THREAD

**Issue by Clementine-Issue-Importer** [clementine-player/Clementine#2763]
_From [timkirtl...@gmail.com](https://code.google.com/u/117765233466965437124/) on February 28, 2012 08:38:15_

What steps will reproduce the problem? 1. Playing songs from "Files" tab 2. 3. What is the expected output? What do you see instead? Last played says "never" even right after playing the track.
Play count never updates either but i think they are one in the same problem.
Just noticed Ratings doesn't work at all on songs that are being played from the "Files" tab What version of the product are you using? On what operating system? v1.01
Mac OS X 10.7.3 Please provide any additional information below.

_Original issue: http://code.google.com/p/clementine-player/issues/detail?id=2763_

**Comment by victorparmar** [comment]
A simple solution is to add the relevant folder to the library. I also play music from the files view but statistics are tracked if the actual files are in the Library
