### ISSUE TITLE
No other option but to transcode to same folder on OSX

### ISSUE THREAD

**Issue by Clementine-Issue-Importer** [clementine-player/Clementine#2776]
_From [maxboey2...@gmail.com](https://code.google.com/u/113941770476806193408/) on March 02, 2012 16:19:12_

If the Transcode tool is used on OSX, I'm not given any other option except to transcode to the same folder, this causes another issue where encoding to the same file format (such as mp3) will create a trackname.mp3.0

I expect the option to transcode to another folder so the files do not get renamed.

I have seen this on both 1.0.1 and 1.0.1-215-ga7332d1

_Original issue: http://code.google.com/p/clementine-player/issues/detail?id=2776_

**Comment by alleyoopster** [comment]
I am also running 1.2.3-7 and have the same problem. Can anyone say if this has been fixed in git or the qt5-git?

thanks

**Comment by narunlifescience** [comment]
This issue seems to be fixed. You have to use developer builds (http://builds.clementine-player.org/) to get this feature.
