### ISSUE TITLE
problems with gstreamer's buffer

### ISSUE THREAD

**Issue by Clementine-Issue-Importer** [clementine-player/Clementine#278]
_From [yellow_onion@orcon.net.nz](https://code.google.com/u/100939741841532727985/) on May 04, 2010 02:57:34_

What steps will reproduce the problem? 1. Play Audio file
2. start browsing the internet or the computer or anything slightly CPU 
intensive What is the expected output? What do you see instead? I expecting smooth sound, but I get stutter What version of the product are you using? On what operating system? 0.3 rc 1 , Windows 7 x64 Please provide any additional information below. perhaps you need to enable the high res timer and/or make the buffer larger

_Original issue: http://code.google.com/p/clementine-player/issues/detail?id=278_

**Comment by algazarra** [comment]
Hi, I'm having this issue with lubuntu 15.04 playing from remote drive over samba. Clementine 1.2.3
