### ISSUE TITLE
Add support for ReplayGain normalization

### ISSUE THREAD

**Issue by Clementine-Issue-Importer** [clementine-player/Clementine#28]
_From [okeeblow](https://code.google.com/u/109221911734702223861/) on February 25, 2010 22:32:08_

A native implementation for reading ReplayGain tags is preferable to an
Amarok 1.4-style script because it eliminates the lag between a track
playing and the volume adjusting.

_Original issue: http://code.google.com/p/clementine-player/issues/detail?id=28_

**Comment by Chocobozzz** [comment]
I close this since the read of the ReplayGain metadata was implemented.

**Comment by feinstaub** [comment]
@Chocobozzz as I understand _reading_ ReplayGain metadata is implemented. What about _calculating_ them? I have something in mind like having a smart view that shows all non-ReplayGained files -> select all -> right click -> (Re)calculate ReplayGain.

**Comment by Chocobozzz** [comment]
I think a new issue for writing replay gain tags would be more readable :)
