### ISSUE TITLE
gstreamer refuses connection

### ISSUE THREAD

**Issue by Clementine-Issue-Importer** [clementine-player/Clementine#2820]
_From [aliguy...@gmail.com](https://code.google.com/u/103251097843368780326/) on March 23, 2012 17:30:26_

What steps will reproduce the problem? 1.Openning up Clementine 1.0.1-328 (or latest git revision) on arch linux with the latest upstream gstreamer plugins
2.Playing any audio file

Clementine ouputs: 
[CODE]
20:24:43.911 ERROR GstEnginePipeline:517            1 "pulsesink.c(570): gst_pulseringbuffer_open_device (): /GstPulseSink:autoaudiosink-1-actual-sink-pulse" 
20:24:43.911 ERROR GstEnginePipeline:517            1 "gstautoaudiosink.c(369): gst_auto_audio_sink_detect (): /GstPipeline:pipeline/GstBin:audiobin/GstAutoAudioSink:autoaudiosink-1:
Failed to find a supported audio sink" 
20:24:43.961 WARN  GstEngine:594                    Gstreamer error: "Failed to connect: Connection refused" 
20:24:43.963 WARN  unknown                          QTimeLine::start: already running 
20:25:17.574 DEBUG DeviceKitLister:39               virtual DeviceKitLister::~DeviceKitLister() 
20:25:17.575 DEBUG WorkerPool<HandlerType>:180      Closing worker socket 
20:25:17.576 DEBUG WorkerPool<HandlerType>:180      Closing worker socket 
[\CODE]

I didn't use a file with non-ascii characters and I'm using the latest revisions.

_Original issue: http://code.google.com/p/clementine-player/issues/detail?id=2820_

**Comment by tomachinz** [comment]
How should I attempt to install or verify if i have another sink such as 'alsa'?
I'm on manjaro / arch. 

```Accepted IPv6 client on socket 34, port 41341
Local : fe80::44c9:3496:1d1c:0034%2
Remote: fe80::0e4d:e9ff:feb6:72cd%2
connection request from hotel (iMac14,1) with deviceID = 0C:4D:E9:B6:72:CD

Client identified as User-Agent: AirPlay/200.34.4
ct=2 spf=352 usingScreen=0 isMedia=0  audioFormat=0x40000
start audio connection, format ALAC 44100/16/2
raop_rtp starting audio
GStreamer error (audio): autoaudiosink1-actual-sink-pulse The stream is in the wrong format.
Connection closed on socket 34
```
This is uxplay - a airshare / airplay server.
