### ISSUE TITLE
Possibility to have more than one library

### ISSUE THREAD

**Issue by Clementine-Issue-Importer** [clementine-player/Clementine#2851]
_From [mat.hub...@gmail.com](https://code.google.com/u/106864533208232668481/) on April 04, 2012 19:23:36_

I think it would be great to be able to create more than one library, each of them pointing to different folders.

For instance, if more than one user is using the computer, each can search his own music libraries, or all of them together...

_Original issue: http://code.google.com/p/clementine-player/issues/detail?id=2851_

**Comment by tng99** [comment]
if not possible, please write a comment so other will not ask the same thing again.

**Comment by tng99** [comment]
i try winamp, songbird, mediamonkey didnt help.
mediamonkey uses "collections" just like winamp's "smart view", where you setup the criteria manually
http://www.mediamonkey.com/forum/viewtopic.php?t=62982

I have 2 folders "d:\western music"  and "d:\eastern music" (with unicode) , just wish I can create 2 separate libraries and choose which one is activated. I think Itunes has that option, not sure.

**Comment by tng99** [comment]
got an email from "Jonas Kvinge", he wrote NO
