### ISSUE TITLE
Unmaximized size not remembered when Clementine is hidden

### ISSUE THREAD

**Issue by Clementine-Issue-Importer** [clementine-player/Clementine#286]
_From [rickard.narstrom](https://code.google.com/u/100737552440092145248/) on May 06, 2010 07:15:28_

What steps will reproduce the problem? 1. Open Clementine's main window
2. Make sure the window is not maximized
3. Resize the window to make sure it dose not cover the entire screen
4. Maximize the window
5. Unmaximize the window
6. Maximize the window again
7. Hide the window by clicking the tray icon
8. Show the window by clicking the tray icon
9. Unmaximize the window What is the expected output? What do you see instead? The Window should be restored to the same size it had after 3 when 
unmaximized. What version of the product are you using? On what operating system? The Window is restored to the correct size after 5, but not after 9. Please provide any additional information below. OS: Ubuntu 10.04 LTS "Lucid Lynx"
WM: metacity 1:2.30.1-0ubuntu1
Clementine 0.2.99

_Original issue: http://code.google.com/p/clementine-player/issues/detail?id=286_

**Comment by narunlifescience** [comment]
It looks like a qt bug as i stumbled over it using amarok and other qt apps as well..
