### ISSUE TITLE
All album in one flac isn't played

### ISSUE THREAD

**Issue by Clementine-Issue-Importer** [clementine-player/Clementine#2884]
_From [armaty...@gmail.com](https://code.google.com/u/117692321962641050001/) on April 19, 2012 00:29:25_

What steps will reproduce the problem? 1.Start clementine via console.
2.Manually add one-album flac. file.
3.Be amazed by flood output in console as follows:
ERROR GstEnginePipeline:506            167 "gstfilesrc.c(1055): gst_file_src_start (): /GstPipeline:pipeline/GstURIDecodeBin:uridecodebin-2822/GstFileSrc:source:
No such file "/media/Muzyka/Lacrimosa/lossless/1994-Schakal/Lacrimosa - Schakal.wav"" What is the expected output? What do you see instead? Actually be able to listen to the music from flac file :D What version of the product are you using? On what operating system? clementine 1.0
debian squeeze
all gstreamers plugins on board.
flac file is fine any other soft does not complain. Please provide any additional information below. After splitting the one-flac-album into one-flac-track clementine stops complaining. ^^

_Original issue: http://code.google.com/p/clementine-player/issues/detail?id=2884_

**Comment by Chocobozzz** [comment]
Closing this old issue.
