### ISSUE TITLE
Next|Prev playlist keyboard shortcuts

### ISSUE THREAD

**Issue by Clementine-Issue-Importer** [clementine-player/Clementine#2932]
_From [tomas.pr...@gmail.com](https://code.google.com/u/103404869143991179936/) on May 10, 2012 13:51:42_

Hi,
I'd like to know whether it's polssible to add keyboard shortcuts options for looping over playlists. I would love to have such multimedia key on keyboard.

Thanks for awesome player btw ;)

_Original issue: http://code.google.com/p/clementine-player/issues/detail?id=2932_

**Comment by Chocobozzz** [comment]
Implemented as @ArnaudBienner said, like for web browsers (*Ctrl+Tab* / *Ctrl+Shift+Tab*).
