### ISSUE TITLE
Grooveshark: Adding multiple songs to a Grooveshark playlist via right click menu

### ISSUE THREAD

**Issue by Clementine-Issue-Importer** [clementine-player/Clementine#2934]
_From [ema...@gmail.com](https://code.google.com/u/112522840008970788636/) on May 11, 2012 16:27:55_

I guess the summary says it all; the ability to add multiple songs at once to a Grooveshark playlist - via the right click menu.

_Original issue: http://code.google.com/p/clementine-player/issues/detail?id=2934_

**Comment by Chocobozzz** [comment]
Closing this since Grooveshark is dead...
