### ISSUE TITLE
locking stop mode

### ISSUE THREAD

**Issue by Clementine-Issue-Importer** [clementine-player/Clementine#2957]
_From [uwemiy...@gmail.com](https://code.google.com/u/108737196443798073309/) on May 25, 2012 20:34:58_

i would like to lock the stop mode, i.e. i want stop-after-this-track be permanent and not that i always have to press the shortcut.

the best i would like is : 1. Stop is Stop!

and an addition stopmode cycle (like repeat mode): 1. Continue 2. Stop-after-track 3. Intro Play (xx seconds).

if the next track starts it will be Intro or Stop-after or Continue automatically.

maybe issue 1828 correlates.

Thanks

_Original issue: http://code.google.com/p/clementine-player/issues/detail?id=2957_

**Comment by TheUbuntuGuy** [comment]
These were addressed in #4866 and #4905
