### ISSUE TITLE
transform umlaut/accent characters to usual ones during search

### ISSUE THREAD

**Issue by Clementine-Issue-Importer** [clementine-player/Clementine#2995]
_From [shaforos...@gmail.com](https://code.google.com/u/101991949134887114949/) on June 12, 2012 13:48:49_

What steps will reproduce the problem? 1. Enter 'Senor' in the playlist or collection search line
2. Files with Señor in the tags are not shown What is the expected output? What do you see instead? Files with Señor in the tags _are_ shown (as foobar2000 does on windows)

Please store in the RAM and/or in collection simplified versions of tag fields that contain the following symbols with accents:
é replace with e
ó replace with o
á replace with a
ñ replace with n
í replace with i
ú replace with u

so that files with accents in their tags could be found more easily.

this behaviour have at least windows explorer, foobar2000 and itunes

_Original issue: http://code.google.com/p/clementine-player/issues/detail?id=2995_

**Comment by gordon-morehouse** [comment]
#4736 duplicates this issue, but has more information and is more active. This one should be closed.
