### ISSUE TITLE
Prevent emptying of library if network drive is not accessible

### ISSUE THREAD

**Issue by Clementine-Issue-Importer** [clementine-player/Clementine#3032]
_From [alan.n.d...@gmail.com](https://code.google.com/u/100753764958954465694/) on July 02, 2012 14:45:55_

What steps will reproduce the problem? 1. Store your music on a samba share
2. Add the samba directory to Clementine's library
3. Wait for the library to update
4. Shutdown Clementine
5. Disconnect the PC running Clementine from the network, or shutdown the PC hosting the samba share.
6. Restart Clementine

The library now automatically updates, and will delete everything out of it, which means that next time the share is accessible it has to re-add everything which can take a long time.

It should instead just display some sort of warning saying that the network share is inaccessible.  Maybe a dialog box asking what it should do (Delete or leave items in the library)?

This doesn't necessarily only affect network shares.  Libraries stored on external hard disks would also be affected.  Maybe it should display the warning whenever the top level folder of the library is inaccessible, regardless of whether that is a network share, external or local hard disk.

Version 1.0.1-523-gc57f588
Windows 7 x64

_Original issue: http://code.google.com/p/clementine-player/issues/detail?id=3032_

**Comment by githubjsorg** [comment]
Why is this closed? This is still an issue in the latest available version 1.3.1.
