### ISSUE TITLE
Light/Dark Theme support

### ISSUE THREAD

**Issue by Clementine-Issue-Importer** [clementine-player/Clementine#3060]
_From [dr.dut...@gmail.com](https://code.google.com/u/112076464574111389775/) on July 17, 2012 10:29:36_

Simple request, maybe an option to change between the current theme (light) and a dark theme?
White text on a black background etc. Or even the option to customise the colors of difference parts of the GUI ourselves?

Foobar's (Windows only) very simple color change options could be used as an example.
Thankyou.

_Original issue: http://code.google.com/p/clementine-player/issues/detail?id=3060_

**Comment by N00BM4573R** [comment]
The top left menu bar (Music, Playlist, Tools, Extras, Help) remains black and is not visible when using a user defined black or dark background. The text on the buttons inside the tabs of the Settings window are light grey or white, and thus are not visible when the appearance has been changed to dark background and bright text.
![image](https://user-images.githubusercontent.com/59672584/169906325-b7ded698-de29-45bb-aa0f-c85c50448d18.png)
![image](https://user-images.githubusercontent.com/59672584/169906489-ac5aa899-7826-4887-83ca-a092e821c4da.png)

Version 1.4 rc2 on Mint 19.3 Cinnamon (4.4.8).
