### ISSUE TITLE
MPD support

### ISSUE THREAD

**Issue by Clementine-Issue-Importer** [clementine-player/Clementine#3087]
_From [rodrigou...@gmail.com](https://code.google.com/u/116688425651481565236/) on August 01, 2012 06:40:12_

It will be great to add MPD(Music Player Daemon) client support for multiple MPD servers to this player.

_Original issue: http://code.google.com/p/clementine-player/issues/detail?id=3086_

**Comment by Kry07** [comment]
nice - great work :D clementine is my favourit player and he helped me sooo much with sorting my birg music library - thanks
