### ISSUE TITLE
Clementine fails to play 24bit/96khz flac files

### ISSUE THREAD

**Issue by Clementine-Issue-Importer** [clementine-player/Clementine#3091]
_From [dodonvic...@gmail.com](https://code.google.com/u/100091879091303936121/) on August 02, 2012 12:37:51_

What steps will reproduce the problem? 1. Try to open a 24bit/96kHz flac file What is the expected output? What do you see instead? I expect clementine to play the file, instead it gives the error:
"Could not get/set settings from/on resource." What version of the product are you using? On what operating system? Clementine v1.0.1
OS: Archlinux x86_64
gstreamer 0.10.36
flac 1.2.1 Please provide any additional information below. Clementine plays normally 24bit/44.1kHz and 16bit/44.1kHz. Other players like deadbeef or vlc play normally 24bit/96kHz flac files.

_Original issue: http://code.google.com/p/clementine-player/issues/detail?id=3090_

**Comment by idl0r** [comment]
It still doesn't play anything as >16bit.
http://www.2l.no/hires/
http://www.lindberg.no/hires/test/2L-145/2L-45_stereo_01_FLAC_176k_24b.flac
% file 2L-45_stereo_01_FLAC_176k_24b.flac
2L-45_stereo_01_FLAC_176k_24b.flac: FLAC audio bitstream data, 24 bit, stereo, 176.4 kHz, 54206544 samples

Playing with mplayer works just fine. It even seems to upsample 16bit stuff.

Also, my settings are on "Choose automatically" and it still doesn't work. It also doesn't work when I select anything else in that list.

**Comment by idl0r** [comment]
Please re-open.
