### ISSUE TITLE
can't jump to current played track

### ISSUE THREAD

**Issue by Clementine-Issue-Importer** [clementine-player/Clementine#316]
_From [mischa.lang](https://code.google.com/u/114404122133506544121/) on May 15, 2010 16:44:51_

I would like the option "jump to current played track".
If you have a large playlist an random track selection, it is very annoying
to find the current track by scrolling the whole list. In Rhythmbox the
shortcut is strg+j I think.
I would like such option in a future release.

_Original issue: http://code.google.com/p/clementine-player/issues/detail?id=316_

**Comment by phobos282** [comment]
"Isn't that enough?"

No. It would be highly desirable to have a spot (say a goto track in the album art area?) that we could click or double click to jump to track. I know that Songbird/Nightingale could do it fine. I'm trying to convert from that to this program. I found the feature HIGHLY useful for meta-data editing, or if I want to delete a song, to find it easily. I have a large library, and this feature is highly useful for the maintenance and care. Could this please be added?

(Sorry for necro)

**Comment by madprops** [comment]
Would be nice to have a button for this.

**Comment by Arnavion** [comment]
<kbd>Ctrl</kbd>-<kbd>J</kbd>
