### ISSUE TITLE
Album Artist cannot be edited in flac in windows

### ISSUE THREAD

**Issue by Clementine-Issue-Importer** [clementine-player/Clementine#3194]
_From [Zade...@gmail.com](https://code.google.com/u/113851922626882860131/) on October 02, 2012 23:50:28_

What steps will reproduce the problem? 1.Select edit track information on a flac file
2.Change the album artist
3.Save What is the expected output? What do you see instead? Expected: the album artist to be changed
Instead: no changes What version of the product are you using? On what operating system? Problem appears in Windows 7 and Windows 8, Clementine Version 1.0.1-670-gbb710ed Please provide any additional information below.

_Original issue: http://code.google.com/p/clementine-player/issues/detail?id=3193_

**Comment by Holzhaus** [comment]
Also confirmed in Clementine 1.2.3 on ArchLinux.
