### ISSUE TITLE
Show playlist statistics under it

### ISSUE THREAD

**Issue by Clementine-Issue-Importer** [clementine-player/Clementine#3199]
_From [igorsant...@gmail.com](https://code.google.com/u/105128625192055066486/) on October 05, 2012 04:20:20_

I found the number of songs under the playlist to be a little bit misleading (reinforcing: it's my opinion only).
I would expect information under the playlist are to be related to:
A) what's being currently played, as the progress bar, fav/hate buttons, etc
B) playlist controls (play, pause, stop, etc)
C) playlist settings and general data, like repeat and shuffle buttons, and... playlist numbers.

Instead, the number of songs and total duration is not from the playlist, but from my library. To see information about the current playlist I have to ctrl+a first.

I think it would be reasonable to show, instead of only library statistics, general playlist statistics when nothing is selected, like: "250 selected of 1600 - [1 day 4:00:00]".

_Original issue: http://code.google.com/p/clementine-player/issues/detail?id=3198_

**Comment by TheUbuntuGuy** [comment]
This was fixed a while ago.

**Comment by Chocobozzz** [comment]
Thanks Mark
