### ISSUE TITLE
Clementine always opens on wrong display

### ISSUE THREAD

**Issue by Clementine-Issue-Importer** [clementine-player/Clementine#3212]
_From [christia...@gmail.com](https://code.google.com/u/110354568552284963623/) on October 12, 2012 09:22:13_

Hi,

i got two displays on my computer. The left one is my primary display. I usually have my music player on the right one, so I drag Clementine to it. But every time I close and open it, it reappears on the left display. It's annoying to drag it to the right one every time.

I use Win7 Prof x64, with all admin rights.

_Original issue: http://code.google.com/p/clementine-player/issues/detail?id=3211_

**Comment by narunlifescience** [comment]
I think fixed in #5124

**Comment by Chocobozzz** [comment]
Thanks @narunlifescience
