### ISSUE TITLE
Cover Manager do not work; also choosing cover manually

### ISSUE THREAD

**Issue by Clementine-Issue-Importer** [clementine-player/Clementine#324]
_From [furkaneralp](https://code.google.com/u/113232037032201603721/) on May 18, 2010 06:55:34_

As i said in the title, when i open the cover manager and click fetch
missing covers, it isn't downloading the covers. Also when i right-click on
an album and select fetch automatically, nothing happens again.

Choosing manual cover is not working too. I select a cover from disk but
there's the grey cd icon again. What can be the problem?

I'm using Clementine 0.3 on Windows 7.
Thank you.

_Original issue: http://code.google.com/p/clementine-player/issues/detail?id=324_

**Comment by koshkamau** [comment]
I really don't know what have you fixed. I've had problems with album art in Clementine somewhere in 2014 and therefore stopped using this player. Now I installed version 1.3.1 on Kubuntu 18.04 and on the third album it refuses to show album art. 
Image file 468x468px "folder.jpg" lies inside album folder but Clementine does not show it. Moreover, it does not show this file even if I select it manually. Even if I choose "search for album covers" and Cover Manager finds similar cover on Last.fm - Clementine does not show it anywhere. I see only some rectangular image - kind of CD box or something.
