### ISSUE TITLE
accidentally editing tracks

### ISSUE THREAD

**Issue by Clementine-Issue-Importer** [clementine-player/Clementine#3252]
_From [christia...@gmail.com](https://code.google.com/u/110354568552284963623/) on November 01, 2012 13:53:22_

Hi,

I know a lot of users wanted to edit the tracks ID3-tags in clementine, but I do this with other applications.

And sometimes I accidentally edit a track and it's annoying to retype i.e. the artist name.

Can't it be possible to activate/deactivate the edit function in the options?

Thanks

_Original issue: http://code.google.com/p/clementine-player/issues/detail?id=3251_

**Comment by TheUbuntuGuy** [comment]
This was fixed in #4417
