### ISSUE TITLE
OS X 10.8 Macbook Play/Pause, Forward/Back Buttons wont work with Clementine

### ISSUE THREAD

**Issue by Clementine-Issue-Importer** [clementine-player/Clementine#3262]
_From [stephen....@gmail.com](https://code.google.com/u/113797569511336801692/) on November 05, 2012 16:34:18_

What steps will reproduce the problem? 1. Open Clementine on OS X 10.8 (Could effect 10.7 and below)
2. Play a song
3. Try to pause song or skip to the next/previous on the playlist using the Mac assigned buttons on a Macbook/Mac Keyboard. What is the expected output? What do you see instead? To be able to play/pause forward/back a song or playlist using the integrated buttons provided. What version of the product are you using? On what operating system? Macbook Late 2009 Model
OS X 10.8 Mountain Lion Please provide any additional information below. Nothing else to add.

TY

_Original issue: http://code.google.com/p/clementine-player/issues/detail?id=3261_

**Comment by Guilz** [comment]
It could indeed be very useful to be able to use those keys to control Clementine.

**Comment by niftylettuce** [comment]
I have this issue with a bluetooth headset.  Play/next/back buttons work in iTunes but do not work in Clementine.  I've used this to try to patch it, but didn't work <https://github.com/thebitguru/play-button-itunes-patch>

**Comment by niftylettuce** [comment]
Related: https://github.com/jguice/mac-bt-headset-fix

**Comment by niftylettuce** [comment]
Looks like Clementine Player on Mac OS X doesn't have a Scripting Definition, so I can't modify that `mac-bt-headset-fix` repo for this.

**Comment by niftylettuce** [comment]
Related: https://github.com/nevyn/SPMediaKeyTap

**Comment by niftylettuce** [comment]
FOUND A FIX!!!!

https://github.com/JamesFator/BTHSControl

**Comment by ArnaudBienner** [comment]
I remember fixing this issue recently.
Will be in the next release.

**Comment by dland** [comment]
I confirm this is fixed in build clementine-1.2.3-1396-gd9150ec.dmg

Thanks Arnaud, great work :)
