### ISSUE TITLE
udisks2 support

### ISSUE THREAD

**Issue by Clementine-Issue-Importer** [clementine-player/Clementine#3264]
_From [Nickollai](https://code.google.com/u/Nickollai/) on November 05, 2012 20:26:43_

https://bugs.gentoo.org/show_bug.cgi?id=439644 Current clementine docs do not tell anything about supported udisks versions. Both wiki and git repo. Please add and verify udisks2 support and document it at https://code.google.com/p/clementine-player/wiki/PortableDevices .

_Original issue: http://code.google.com/p/clementine-player/issues/detail?id=3263_

**Comment by jontis** [comment]
Is this still an issue? Just asking because Clementine does not see inserted USB devices and my systems uses udisks2.

**Comment by Ferroin** [comment]
Yes, this is still an issue, and it's a rather annoying one for people like myself who have both versions of udisks installed just to make it work (I only have 4 programs that need udisks on my system, and Clementine is the only one that needs udisks1).
