### ISSUE TITLE
Bandcamp support

### ISSUE THREAD

**Issue by Clementine-Issue-Importer** [clementine-player/Clementine#3269]
_From [facocher...@gmail.com](https://code.google.com/u/106040886564734535075/) on November 07, 2012 11:55:27_

Do you plan to add Bandcamp support ?

_Original issue: http://code.google.com/p/clementine-player/issues/detail?id=3268_

**Comment by linxon** [comment]
https://bandcamp.com/developer

>Labels and merchandise fulfillment partners can interact with their accounts via the Bandcamp API. To register for API use, [contact us](https://bandcamp.com/contact?subj=API%20Access), and include in your email a brief description of how you intend to use API access. 

>Calls to all Bandcamp APIs use [OAuth 2.0](https://tools.ietf.org/html/rfc6749) for authentication. Once a client has been created for you, you'll find your client ID and client secret by going to the API Access tab of your Settings page.

May be you need send message and take the API key?
Or this is not solution?

**Comment by rlimaeco** [comment]
Hey there, if the API is a big problem , how this works : https://github.com/iheanyi/bandcamp-dl

Soundcloud is not giving out any keys too, but the plugin still there useless, i think bandcamp and clementine will just fit very well.
