### ISSUE TITLE
Eight 'clementine-tagreader' Processes Spawned

### ISSUE THREAD

**Issue by Clementine-Issue-Importer** [clementine-player/Clementine#3345]
_From [vascofal...@gmail.com](https://code.google.com/u/113220132968091109120/) on December 08, 2012 18:52:48_

What steps will reproduce the problem? 1. Start Clementine
2. Open GNOME System Monitor
3. There will be eight (for a quad core CPU with hyperthreading, anyway) processes named 'clementine-tagreader', each using 1 MB of memory and no CPU. What is the expected output? What do you see instead? Processes seem to be unnecessary, at least so many of them. Why is there one per core? What version of the product are you using? On what operating system? Version 1.1.1-201-g7d4f576 from the daily ppa on Ubuntu 12.10

_Original issue: http://code.google.com/p/clementine-player/issues/detail?id=3344_

**Comment by netmaxt3r** [comment]
this is insane I have got 16 of them CPU 5960x  
![image](https://cloud.githubusercontent.com/assets/1734518/7106613/0ed18778-e158-11e4-83e3-4340c0d2279c.png)

**Comment by webzorg** [comment]
I got 12 :s this is not right...

**Comment by andreyv** [comment]
On my four processor system these processes together use about 70 MB of RAM, nearly as much as Clementine itself. Seeing a long process list in `top` isn't nice either.

Why not start these processes on demand when they are needed?
