### ISSUE TITLE
Player does not prevent sleep mode

### ISSUE THREAD

**Issue by Clementine-Issue-Importer** [clementine-player/Clementine#3353]
_From [datakin...@gmail.com](https://code.google.com/u/113671249145947589402/) on December 12, 2012 13:34:34_

The player does not override the systems power saving mode, letting the computer go to sleep even while a song is playing.

Using Clementine v. 1.1 on MacOSX 10.8.2 (Mountain Lion)

_Original issue: http://code.google.com/p/clementine-player/issues/detail?id=3352_

**Comment by dronkit** [comment]
Guys please don't put this in wontfix! In Windows we have no such thing as a prevent sleep hot corner!

**Comment by Chocobozzz** [comment]
@dronkit See https://github.com/clementine-player/Clementine/pull/5150?
