### ISSUE TITLE
Spotify metadata not loaded when loading playlist

### ISSUE THREAD

**Issue by Clementine-Issue-Importer** [clementine-player/Clementine#3358]
_From [pvi...@gmail.com](https://code.google.com/u/118176110351984044711/) on December 14, 2012 14:12:24_

1. Create a playlist and add songs from Spotify to it.
2. Save the playlist into PLS format.
3. Load the saved PLS playlist.

However, in the loaded playlist, only the track name appears.
The artist and album fields are empty. Also when the file
is played, no metadata appears.

I'd have expected that the artist and album names are loaded
when the playlist is loaded, or at least when the song is played
the next time.

I'm using Clementine 1.1.1 on Ubuntu 12.10, libspotify

_Original issue: http://code.google.com/p/clementine-player/issues/detail?id=3357_

**Comment by ArnaudBienner** [comment]
It's working for me.
As no one else reported the problem, and as this issue is quite old, I think we close it. Let us know if it reappears.
