### ISSUE TITLE
qualifiers for library serach

### ISSUE THREAD

**Issue by Clementine-Issue-Importer** [clementine-player/Clementine#338]
_From [andrew.gaydenko](https://code.google.com/u/andrew.gaydenko/) on May 23, 2010 10:44:56_

It would be handy (and will correspond to playlist filtering) to add
qualifiers for library serach. I mean using of contexts as

genre:text
artist:text
date:text ot year:text
album:text
title:text

And, BTW, it will close rfe for using years in library search.

_Original issue: http://code.google.com/p/clementine-player/issues/detail?id=338_

**Comment by imperator-** [comment]
+1

**Comment by daviddavo** [comment]
Seriously, we need the year:1997 filter. And It would be nice to use regex, so I could find songs from a decade or 1955-1965

**Comment by jsams** [comment]
This seems partially implemented. What is missing, for me, are 'year' (or date, this seems to be a popular one), 'format', and 'added' qualifiers. In amarok, I can do "date:>=1990 date:<2000" to get 90's music. I can do "added:<3d" to get music added in the last 3 days, where h/d/w/m seem to be accepted qualifiers. And I can do "format:flac" to view only my flac encodes.

Amarok has a number of other qualifiers: comment, filename, tracknumber, discnumber, bpm, length, bitrate, samplerate, filesize, firstplayed, lastplayed, playcount, modified. It also has score, rating, and label filters, though those are more specific to how Amarok handles the library. These are all read from tag/file stat data. e.g. bpm is only available on tracks that have a bpm tag and is not detected by scanning the file.
