### ISSUE TITLE
ProjectM visualizations missing

### ISSUE THREAD

**Issue by Clementine-Issue-Importer** [clementine-player/Clementine#3433]
_From [jrkong....@gmail.com](https://code.google.com/u/107440880376847007308/) on January 16, 2013 19:45:14_

What steps will reproduce the problem? 1.Open visualizations
2.projectM default visualization doesn't change What is the expected output? What do you see instead? The default ProjectM visualization seems to be the only one there as I don't see the list of visualizations I usually have What version of the product are you using? On what operating system? Clementine 1.1 on Mac OSX 10.8.2 Please provide any additional information below.

_Original issue: http://code.google.com/p/clementine-player/issues/detail?id=3433_

**Comment by logological** [comment]
On recent versions of openSUSE (and maybe 12.3 too, for all I know) you need to install the [projectM-data](https://software.opensuse.org/package/projectM-data) package in order to get visualizations besides the default one.
