### ISSUE TITLE
Clementine eats 100&#37; CPU when a drive is unmounted while scanning it

### ISSUE THREAD

**Issue by Clementine-Issue-Importer** [clementine-player/Clementine#352]
_From [mail@icesheep.de](https://code.google.com/u/108326814684193951398/) on May 28, 2010 10:41:30_

What steps will reproduce the problem? 1. Have your collection stored on a network drive
2. Start to scan it with Clementine
3. Close Clementine while scanning
4. Disconnent your network cable
5. Start clementine again What is the expected output? What do you see instead? I expect Clementine to pause scanning until the network drive is available
again. Instead Clementine eats 100&#37; of my CPU. What version of the product are you using? On what operating system? Clememtine 0.3.2 on Mac OS X 10.6.3 Please provide any additional information below. Screenshot attached.

**Attachment:** [Bildschirmfoto 2010-05-28 um 10.06.10.png](http://code.google.com/p/clementine-player/issues/detail?id=352)

_Original issue: http://code.google.com/p/clementine-player/issues/detail?id=352_

**Comment by Chocobozzz** [comment]
Closing this old issue. Feel free to ask for reopening it.
