### ISSUE TITLE
Support for Deezer

### ISSUE THREAD

**Issue by Clementine-Issue-Importer** [clementine-player/Clementine#3531]
_From [Mickael....@gmail.com](https://code.google.com/u/105139642061627731809/) on March 02, 2013 18:56:05_

Deezer recently opened an API for streaming, and is planning to be available to the USA as well as a whole lot of other new countries soon, is there any plan to support them ?

_Original issue: http://code.google.com/p/clementine-player/issues/detail?id=3531_

**Comment by lbssousa** [comment]
Deezer has released a "Native SDK" in April 2016:

http://developers.deezer.com/sdk/native

Maybe it has what you want for integrating the service with Clementine.

**Comment by hatstand** [comment]
Looks like it writes directly to pulseaudio which is pretty crap.
