### ISSUE TITLE
TuneIn.com Support

### ISSUE THREAD

**Issue by Clementine-Issue-Importer** [clementine-player/Clementine#3536]
_From [dhvm...@gmail.com](https://code.google.com/u/115048482582905226997/) on March 06, 2013 04:00:08_

Please add support for at least the following features regarding TuneIn.com:
1. Ability to save login information in Clementine and auto-login, as Grooveshark does.
2. Ability to browse/select/play from saved favorite stations.

I will certainly contribute beta testing time if this feature is added. Thanks to the Clementine community for making such an awesome tool.

_Original issue: http://code.google.com/p/clementine-player/issues/detail?id=3536_

**Comment by sim642** [comment]
Mopidy has a TuneIn plugin available, which doesn't seem to be very complicated: https://github.com/kingosticks/mopidy-tunein

**Comment by umpirsky** [comment]
What I would like to have, and I already done this for Rhytmbox ([Rhytmbox Tunein Import](https://github.com/umpirsky/rhytmbox-tunein-import)) is a way to import my favorite stations from Tunein.

**Comment by Radioenlignefrance** [comment]
мне больше нравится слушать радио на radioenlignefrance.com

**Comment by NHellFire** [comment]
There is a public API, the documentation just seems to have been lost with website changes. archive.org has an old copy: https://web.archive.org/web/20110823171916/http://inside.radiotime.com:80/developers/api/opml

No registration is required (just per-IP usage limits may apply).

https://opml.radiotime.com/
It provides XML intended to be structured as a menu. There's also a search API at /Search.ashx?query=$query
