### ISSUE TITLE
"Keep running in the backgroud" option

### ISSUE THREAD

**Issue by Clementine-Issue-Importer** [clementine-player/Clementine#3557]
_From [pozdnyak...@gmail.com](https://code.google.com/u/101991960373334881291/) on March 16, 2013 13:03:39_

Please, make "Keep running in the backgroud when the window is closed" independent from "Show tray icon" option. It's will be nice to have Clementine's controls in sound indicator without tray icon on Ubuntu with Unity.

_Original issue: http://code.google.com/p/clementine-player/issues/detail?id=3557_

**Comment by MrMino** [comment]
"The effort required to implement it and the potential confusion this can cause are simply not worth it."

One: the effort required is to simply detach state of one checkbox from the other
Two: second workspace means additional mess for people who work on gnome3
Three:  if you are afraid that people will use it in 'confused' manner, then just add a warning to it. 
Four: there aren't that many people who use the tray icon anyway
Five: on gnome it is SUPPER annoying, especially if you are using topicons extension

And to be honest, I'm actually trying to tweak the code right now.

**Comment by MrMino** [comment]
Oh, guess what? The actual effort to accomplish this was erasing two lines from `Clementine / src / ui / behavioursettingspage.h`, namingly `267` and `268`:

      ui_->b_keep_running_->setEnabled(on);
      ui_->b_keep_running_->setChecked(on);

Too much effort my ass.

**Comment by mmccoy37** [comment]
@MrMino can you add a separate UI checkbox for this option and make a pull request? That is how I had changes I wanted get added. If you code it and it looks fine they will add it, especially if it is low lines of code that they can look at in < 5 mins. :)

**Comment by MrMino** [comment]
@mmccoy37 I doubt I will have time to do it, since I'm not a C++ developer and I don't have much experience with QT either. Also, I already switched to cmus, since I'm going lightweight, so...

Sorry, but I can't.
