### ISSUE TITLE
Sorting playlist by files directory

### ISSUE THREAD

**Issue by Clementine-Issue-Importer** [clementine-player/Clementine#357]
_From [vnu007dl](https://code.google.com/u/110410825174756988125/) on May 29, 2010 15:41:55_

In playlist we can set up some columns, for example: filename, length, size 
sample rate etc, but I still miss "path column", or "directory"
I have my music in few diferent directories, and and dlike to sort playlist 
by those directories, how to do this?
PS. Sorry for my english, I belive, you undestand my request :)

_Original issue: http://code.google.com/p/clementine-player/issues/detail?id=357_

**Comment by mehr-licht** [comment]
I messed around with sorting - don't know how.
Now I want it to be back as it was - sorted by folder, subfolder, etc (the subfolder has band name and album title) and filename (song order and title).

I tried sorting by "File name" and "File name (without path)" but none works!! When I have repeated albums their songs do not appear in their own separated folder but grouped together...
A "sort by path" would be ideal.
