### ISSUE TITLE
'Could not demultiplex stream' when trying to play WMA files

### ISSUE THREAD

**Issue by Clementine-Issue-Importer** [clementine-player/Clementine#3593]
_From [Comenius...@gmail.com](https://code.google.com/u/112478286136507647404/) on April 04, 2013 17:28:19_

What steps will reproduce the problem? 1. Add any .wma file to your playlist
2. Play it back
3. After about 1-2 minutes in the playback will abort with this error message:

Could not demultiplex stream. What version of the product are you using? On what operating system? I am running Clementine Version 1.1.1-456-ga798347 on Ubuntu 12.04.2 LTS Please provide any additional information below. $ uname -r
3.8.2-030802-generic

~$ lsb_release -a
LSB Version:    core-2.0-amd64:core-2.0-noarch:core-3.0-amd64:core-3.0-noarch:core-3.1-amd64:core-3.1-noarch:core-3.2-amd64:core-3.2-noarch:core-4.0-amd64:core-4.0-noarch
Distributor ID: Ubuntu
Description:    Ubuntu 12.04.2 LTS
Release:    12.04
Codename:   precise

_Original issue: http://code.google.com/p/clementine-player/issues/detail?id=3593_

**Comment by jfaurbo** [comment]
Can someone explain how I implement this fix? I'm a little useless with scripts and code.
