### ISSUE TITLE
Bandcamp.com integration

### ISSUE THREAD

**Issue by Clementine-Issue-Importer** [clementine-player/Clementine#3609]
_From [russomar...@gmail.com](https://code.google.com/u/117739868123106490891/) on April 12, 2013 15:38:07_

It would be really great to add bandcamp.com as a music source in global search, like you did for Soundcloud. Do you think it is possible?

_Original issue: http://code.google.com/p/clementine-player/issues/detail?id=3609_

**Comment by soupault** [comment]
I believe that the issue can be re-opened. Following the link above, I've found that the Bandcamp API is now available (implementation is quite complicated though, imo).

**Comment by hatstand** [comment]
Nope, they removed the actually useful APIs completely.

**Comment by soupault** [comment]
Oh, sorry, silly me. That is indeed just for labels and merch.

**Comment by S0llarCode** [comment]
+1 https://bandcamp.com/developer#key_request
