### ISSUE TITLE
[Crash] Segmentation when scanning library with files which have invalid encoding

### ISSUE THREAD

**Issue by Clementine-Issue-Importer** [clementine-player/Clementine#3616]
_From [gabriel....@gmail.com](https://code.google.com/u/100772282298395792960/) on April 14, 2013 21:29:58_

What steps will reproduce the problem? 1. Configure a path for the library.
2. Crash. Segmentation Fault.
3. Reestart and keep crashing. What is the expected output? What do you see instead? This is the output:
TagLib: Could not open file /mnt/data/pipo/music/Dimmu Borgir/[1994] For All Tid/08. Raabjrn Speiler Draugheimens.ogg
Segmentation fault (core dumped) What version of the product are you using? On what operating system? Ubuntu 12.10 on amd64 architecture.
Clementine version 1.0.1 Please provide any additional information below. This is the backtrace.
#0  0x00007ffff1f30a41 in ftell () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007ffff770fb5d in TagLib::File::find(TagLib::ByteVector const&, long, TagLib::ByteVector const&) () from /usr/lib/x86_64-linux-gnu/libtag.so.1
#2  0x00007ffff76f9ba9 in TagLib::Ogg::File::nextPage() () from /usr/lib/x86_64-linux-gnu/libtag.so.1
#3  0x00007ffff76fa5d0 in TagLib::Ogg::File::packet(unsigned int) () from /usr/lib/x86_64-linux-gnu/libtag.so.1
#4  0x00007ffff7700541 in TagLib::Vorbis::File::read(bool, TagLib::AudioProperties::ReadStyle) () from /usr/lib/x86_64-linux-gnu/libtag.so.1
#5  0x00007ffff7700779 in TagLib::Vorbis::File::File(char const*, bool, TagLib::AudioProperties::ReadStyle) () from /usr/lib/x86_64-linux-gnu/libtag.so.1
#6  0x00007ffff7734e04 in TagLib::FileRef::create(char const*, bool, TagLib::AudioProperties::ReadStyle) () from /usr/lib/x86_64-linux-gnu/libtag.so.1
#7  0x00007ffff7735c1f in TagLib::FileRef::FileRef(char const*, bool, TagLib::AudioProperties::ReadStyle) () from /usr/lib/x86_64-linux-gnu/libtag.so.1
#8  0x00000000006725cb in TagLibFileRefFactory::GetFileRef(QString const&) ()
#9  0x0000000000673dd9 in Song::InitFromFile(QString const&, int) ()
#10 0x000000000086591e in LibraryWatcher::ScanNewFile(QString const&, QString const&, QString const&, QSet<QString>*) ()
#11 0x0000000000864346 in LibraryWatcher::ScanSubdirectory(QString const&, Subdirectory const&, LibraryWatcher::ScanTransaction*, bool) ()
#12 0x00000000008648a8 in LibraryWatcher::ScanSubdirectory(QString const&, Subdirectory const&, LibraryWatcher::ScanTransaction*, bool) ()
#13 0x00000000008648a8 in LibraryWatcher::ScanSubdirectory(QString const&, Subdirectory const&, LibraryWatcher::ScanTransaction*, bool) ()
#14 0x00000000008635ba in LibraryWatcher::AddDirectory(Directory const&, QList<Subdirectory> const&) ()
#15 0x00000000009115e2 in ?? ()
#16 0x00007ffff714743e in QObject::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#17 0x00007ffff61dbe9c in QApplicationPrivate::notify_helper(QObject_, QEvent_) () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#18 0x00007ffff61e030a in QApplication::notify(QObject_, QEvent_) () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#19 0x00007ffff713256e in QCoreApplication::notifyInternal(QObject_, QEvent_) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#20 0x00007ffff71363f1 in QCoreApplicationPrivate::sendPostedEvents(QObject_, int, QThreadData_) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#21 0x00007ffff7160a63 in ?? () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#22 0x00007ffff3673ab5 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#23 0x00007ffff3673de8 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#24 0x00007ffff3673ea4 in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#25 0x00007ffff7160c16 in QEventDispatcherGlib::processEvents(QFlagsQEventLoop::ProcessEventsFlag) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#26 0x00007ffff71312bf in QEventLoop::processEvents(QFlagsQEventLoop::ProcessEventsFlag) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#27 0x00007ffff7131548 in QEventLoop::exec(QFlagsQEventLoop::ProcessEventsFlag) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#28 0x00007ffff7032b10 in QThread::exec() () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#29 0x0000000000858fd3 in BackgroundThreadImplementation<LibraryWatcher, LibraryWatcher>::run() ()
#30 0x00007ffff7035aec in ?? () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#31 0x00007ffff51bee9a in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#32 0x00007ffff1fb4cbd in clone () from /lib/x86_64-linux-gnu/libc.so.6
#33 0x0000000000000000 in ?? ()

_Original issue: http://code.google.com/p/clementine-player/issues/detail?id=3616_

**Comment by Tazmain** [comment]
This issue has still not been resolved in version 1.3.1 it still crashes like clock work for me at 75% scanning my library
