### ISSUE TITLE
no podcasts listed for gpodder on Windows

### ISSUE THREAD

**Issue by Clementine-Issue-Importer** [clementine-player/Clementine#3618]
_From [bigras.b...@gmail.com](https://code.google.com/u/101402796964288694599/) on April 15, 2013 15:09:49_

What steps will reproduce the problem? 1. Login with gpodder credentials in Clementine's options
2. Click on "Podcasts" from the "Internet" tab. What is the expected output? What do you see instead? I expect to see all the podcasts I'm subscribed to but the list is empty.

Doing the "update all podcasts" doesn't seem to do anything. What version of the product are you using? On what operating system? Clementine 1.1.1 on Windows 7 64-bits

_Original issue: http://code.google.com/p/clementine-player/issues/detail?id=3618_

**Comment by Chocobozzz** [comment]
Feel free to reopen if you encounter this issue again.
