### ISSUE TITLE
WMA files crashing Clementine

### ISSUE THREAD

**Issue by Clementine-Issue-Importer** [clementine-player/Clementine#3682]
_From [benzp...@gmail.com](https://code.google.com/u/104065972560665348609/) on May 15, 2013 18:52:54_

What steps will reproduce the problem? 1. Drag a WMA into Clementine
2. Clementine crashes What version of the product are you using? On what operating system? 1.1.1-507 on Win7 x64 (also tried on 1.1.1-464) Please provide any additional information below. After this Clementine won't launch successfully until the WMA in the playlist is moved/renamed/deleted so that Clementine can't find it. Tested with WMAs from different sources, same occurrence.

_Original issue: http://code.google.com/p/clementine-player/issues/detail?id=3682_

**Comment by chtfn** [comment]
I'm having this issue on Ubuntu 14.04 with the build 1.2.3-964-gc96502e
Has this crept back for other people too?
