### ISSUE TITLE
Playlist loses organized tracks

### ISSUE THREAD

**Issue by Clementine-Issue-Importer** [clementine-player/Clementine#3693]
_From [alphadel...@gmail.com](https://code.google.com/u/107136459110240960141/) on May 18, 2013 03:08:50_

What steps will reproduce the problem? 1.  Make a playlist.
2.  Add a track from the library to it.
3.  Modify the tags and "organize" the track, causing its file path to be changed.
4.  Try to open the track's information. What is the expected output? What do you see instead? The track's data should be displayed, but it's empty and grayed out. What version of the product are you using? On what operating system? 1.1.1-508-gcea4180~quantal Please provide any additional information below. This is similar to but not the same as issue 1241 .

When Clementine organizes a track, it should search open playlists for instances of that file and modify the instances to point to the new path.

This is especially frustrating, because since Clementine lacks tags, I have been organizing tracks by attribute (e.g. relaxing, upbeat, etc) into playlists.  If, after adding a track to a playlist, I update its tags and then reorganize it based on the updated tags, it will no longer be on the playlist, but I won't even know (other than remembering this bug), because the old track data is still in the playlist.  

The end result is that it's nearly impossible to organize one's library with Clementine based on musical attributes, only by track metadata.

_Original issue: http://code.google.com/p/clementine-player/issues/detail?id=3693_

**Comment by mithereal** [comment]
methinks this is because when you organize tracks, a duplicate is made in the database, and clementine only picks up the newest created one, i noticed after i organized my playcounts went to 0 after inspecting clementine.db i saw this, maybe clementine needs to concat based on track name vs id r something.
