### ISSUE TITLE
Library updates "*** glibc detected *** /home/joel/Projects/clementine-player/bin/clementine-tagreader: corrupted double-linked list: 0x000000000145cfd0 ***"

### ISSUE THREAD

**Issue by Clementine-Issue-Importer** [clementine-player/Clementine#3773]
_From [cincoden...@gmail.com](https://code.google.com/u/105505315440794373505/) on July 07, 2013 17:41:45_

What steps will reproduce the problem? 1. Start Clementine with some new music to scan (mp3s in my case), or initiate a re-scan
2. View debug info
3. To see more, run a killall clementine-tagreader, which will kill and respawn the stalled reader processes and allow them to crash again. What is the expected output? What do you see instead? I expect my new music will be scanned and added What version of the product are you using? On what operating system? I've used 1.1, up to the latest git version, with the same results Please provide any additional information below. This hopefully is an issue that has something to do with my system, but I don't know how to go about pinning it down.  I'll try a bisect, if I can find a good reproducible test case, as I haven't had much luck with gdb, largely because I don't know how to deal well with threads there.

I did note that #3374 is similar to this, but was merged into a bug that seems possibly unrelated.

_Original issue: http://code.google.com/p/clementine-player/issues/detail?id=3773_

**Comment by Chocobozzz** [comment]
Ubuntu one was removed from Clementine so the issue should be gone. Feel free to reopen if it's not the case.
