### ISSUE TITLE
Flac files not shown in the library

### ISSUE THREAD

**Issue by Clementine-Issue-Importer** [clementine-player/Clementine#3787]
_From [mikko.v....@gmail.com](https://code.google.com/u/104058766343511769423/) on July 22, 2013 20:17:51_
1. Add a directory with FLAC files to the Clementine library
2. Do a library rescan

Expected output is to see the FLAC files in the music library. However, the FLAC files are not shown, although other files (.ogg, .mp3) are shown.

FLAC files can be opened with Music -> Open File and added to the playlist. Only the library view does not show them.

Clementine version 1.1.1, operating system Windows 7.

_Original issue: http://code.google.com/p/clementine-player/issues/detail?id=3787_

**Comment by vnickolov** [comment]
I have the exact same problem as @kevle 

I am running 
openSUSE Leap 42.2 64-bit
Gnome 3.20.2
gstreamer-plugins-good-lang-1.8.3-3.1.noarch
gstreamer-plugins-good-1.8.3-3.1.x86_64

Any ideas?

**Comment by DrGrandmaster** [comment]
same, ubuntu 19.04
