### ISSUE TITLE
No music from Grooveshark working

### ISSUE THREAD

**Issue by Clementine-Issue-Importer** [clementine-player/Clementine#3815]
_From [a...@skoomaband.com](https://code.google.com/u/102055023014634172653/) on August 15, 2013 18:06:32_

Logged into Grooveshark via Clementine immediately after install, loaded my playlists into the current playlist and included local music. When attempting to play the music, it may pause for a second then move on, or, it will just move on immediately. No error messages or anything.

Using Clementine 1.1.1 on Win7 professional x64.

_Original issue: http://code.google.com/p/clementine-player/issues/detail?id=3815_

**Comment by Chocobozzz** [comment]
Closing this since Grooveshark is dead...
