### ISSUE TITLE
Adjustable Playback Speed / Silence Skip

### ISSUE THREAD

**Issue by Clementine-Issue-Importer** [clementine-player/Clementine#3867]
_From [daniel.g...@gmail.com](https://code.google.com/u/114452276484952976318/) on September 26, 2013 05:12:16_

Being able to adjust playback speed can slow down fast parts so that you can hear what is happening or speeding up the playback of an audiobook or podcast can save you time. Another trick to increasing playback speed without distorting the audio would be to auto-skip silence blocks.

_Original issue: http://code.google.com/p/clementine-player/issues/detail?id=3867_

**Comment by chrisdane** [comment]
Hi

So is is possible to increase the playback speed with clementine? Using version `1.4 rc1` I cannot find a button for this...

Thanks!
Chris
