### ISSUE TITLE
No usb mass storage with Clementine 1.2

### ISSUE THREAD

**Issue by Clementine-Issue-Importer** [clementine-player/Clementine#3891]
_From [rollop...@gmail.com](https://code.google.com/u/106235308957034195550/) on October 12, 2013 20:19:33_

What steps will reproduce the problem? 1. Attach a usb mass storage
2. Try to detect/connect it What is the expected output? What do you see instead? The device isn't detected, and if is already listed (due a 1.1 version detection) it wan't open What version of the product are you using? On what operating system? The bug appear with Clementine 1.2 on Windows 7 @64bit, no problem with Clemente 1.1

_Original issue: http://code.google.com/p/clementine-player/issues/detail?id=3891_

**Comment by mbnoimi** [comment]
Sorry for extracting this from the death :)

Both Windows (8.1 x64) and Linux (Mint 17 x64) recognize my mobile phone as Mass storage so I'm unable to attach it to Clementine :(

Is there any trick or tool I can use it for sync my favorites in Clementine to my mobile phone?
