### ISSUE TITLE
Ability to disable tag editing in playlist

### ISSUE THREAD

**Issue by Clementine-Issue-Importer** [clementine-player/Clementine#392]
_From [Nickollai](https://code.google.com/u/Nickollai/) on June 10, 2010 21:00:17_

Click by selected song in playlist starts tag editing. For me it is unwanted behaviour because it causes random and wrong tag editing when I do not want to edit tags.

_Original issue: http://code.google.com/p/clementine-player/issues/detail?id=392_

**Comment by dowcet** [comment]
I just discovered that this was actually addressed! Tools > Preferences > Behavior > uncheck "Enable song metadata..." option.
