### ISSUE TITLE
Analyzers broken on lossless files with large sample size

### ISSUE THREAD

**Issue by Clementine-Issue-Importer** [clementine-player/Clementine#3939]
_From [kazmis...@gmail.com](https://code.google.com/u/111282920849391762172/) on November 02, 2013 12:57:04_

What steps will reproduce the problem? 1. Play lossless audio files (flac, alac, wave) What is the expected output? What do you see instead? Analyzer operating smoothly as configured
It lags Bug #3675 is still not fixed and my suggested workaround only works for lossy audio files post-1.1.1 What version of the product are you using? On what operating system? Windows 7 x64 Home Premium and Xubuntu 12.04, 12.10 and 13.04
every Version newer than 1.1.1 (even newer builds (ie 646) i took from ppas)

_Original issue: http://code.google.com/p/clementine-player/issues/detail?id=3939_

**Comment by TheUbuntuGuy** [comment]
This was fixed. If there is still a framerate problem, please open a new issue.
