### ISSUE TITLE
Clementine does not update Artist tag

### ISSUE THREAD

**Issue by Clementine-Issue-Importer** [clementine-player/Clementine#3955]
_From [w...@spings.net](https://code.google.com/u/115623320734956550423/) on November 09, 2013 17:45:17_

What steps will reproduce the problem? 1.Edit Artist tag, via either the "Edit track information" or "Edit 'Artist' tag" context menu
2.No change appears, feel free to do a full library rescan 3. What is the expected output? What do you see instead? I expect the Artist field to update. Running the external program mediainfo also returns that the Artist fields has not changed. Either method is able to modify other fields (track name, album title, album artist). What version of the product are you using? On what operating system? Clementine 1.2, Qt 4.8.2, Debian Wheezy Please provide any additional information below.

_Original issue: http://code.google.com/p/clementine-player/issues/detail?id=3955_

**Comment by tchoulihan** [comment]
This is probably a copy of : 
https://github.com/clementine-player/Clementine/issues/221

**Comment by JulianVolodia** [comment]
@SonicPotions, you think it is regression? Try to find specific version where it cannot work? Maybe a copy of #221 as mentioned? I think we should close ( @hatstand ? ) unless somebody tell us it is different than #221.
