### ISSUE TITLE
Per-playlist repeat/shuffle

### ISSUE THREAD

**Issue by Clementine-Issue-Importer** [clementine-player/Clementine#3989]
_From [knuck...@gmail.com](https://code.google.com/u/102797600864531592627/) on November 25, 2013 20:46:49_

It would be very nice if the repeat/shuffle setting could be per-playlist and not global.

Sometimes I just have a large amount of songs and set it on random, but then I want to listen to some album, and open a new playlist, and only after 1 or 2 songs do I notice that I'm still on random.

I think this setting makes more sense on a per-playlist base, than being global.
But I'm guessing some people would disagree, so I request that at least this be made an option.

Thank you and rock on! :)

_Original issue: http://code.google.com/p/clementine-player/issues/detail?id=3989_

**Comment by gordon-morehouse** [comment]
#5673 duplicates this, but that feature request has a bit more detail than this one.

**Comment by ivoanjo** [comment]
Thanks for looking into this 👍
