### ISSUE TITLE
Mac OSX - Media Keyboard Shortcut problem

### ISSUE THREAD

**Issue by Clementine-Issue-Importer** [clementine-player/Clementine#4002]
_From [emiliano...@gmail.com](https://code.google.com/u/110736339009104196064/) on December 03, 2013 14:48:35_

What steps will reproduce the problem? 1. Try to use media button (play/pause, previous and next) What is the expected output? What do you see instead? Expected : 
- Change Song, play/pause song
  Actual : 
- Nothing. Any button is ignored. What version of the product are you using? On what operating system? Clementine : 1.2.0 - 1.2.1
  O.S. : Mac OSX Mavericks Please provide any additional information below. I try to change shortcut key and remap them with the same key but Clementine ignore my input.

_Original issue: http://code.google.com/p/clementine-player/issues/detail?id=4002_

**Comment by Ardakilic** [comment]
Thanks, this fixed for me, also works globally on Yosemite with latest version.
