### ISSUE TITLE
Cover album images do not save to the MP3 file

### ISSUE THREAD

**Issue by roadapathy** [clementine-player/Clementine#4043]
I've never had this problem before but the version from the Ubuntu 13.10 repositories doesn't save cover art to the MP3 file and neither does the latest .deb version. It seems to have amnesia. I will again install from the latest deb after removing all config files. If that fixes the problem, I will delete this new issue. 

Thank you and I love Clementine Player! It has been the best ever ever ever.

Joel

**Comment by 89z** [comment]
https://github.com/clementine-player/Clementine/issues/1176

https://github.com/clementine-player/Clementine/issues/4043
https://github.com/clementine-player/Clementine/issues/4106
https://github.com/clementine-player/Clementine/issues/5195
https://github.com/strawberrymusicplayer/strawberry/issues/286
