### ISSUE TITLE
Clementine not moving to the next song correctly

### ISSUE THREAD

**Issue by ghost** [clementine-player/Clementine#4044]
Hi,

I have a playlist containing songs from .cue and .tta files, but Clementine doesn't move onto the next song properly after playing some songs.

After the song is played, Clementine will play a few seconds of the next song from the same tta file before playing the next song that it is supposed to play.

This is a major bug for me.

**Comment by WGH-** [comment]
Why was this closed? I'm having the same issue, except it's not "few seconds" for me: Clementine just continues to play the next track instead of the next playlist entry.
