### ISSUE TITLE
Clementine plays songs multiple times by accident

### ISSUE THREAD

**Issue by sfuhrm** [clementine-player/Clementine#4047]
Clementine plays certain mp3-songs in a playlist _multiple_ times, but single play is chosen. The current song display (UI) continues to the next song in the playlist, but still the old song is played twice. 

Songs are from the collection/local disk.
Platform is Debian Linux Wheezy.
Version is 1.2.1.
Problem occurs on multiple installations with Debian Wheezy.

**Comment by Burrito-Bazooka** [comment]
Why was this closed immediately? I'm now also having this issue.

[What did you see?](https://xkcd.com/979/)

**Comment by Burrito-Bazooka** [comment]
Duplicate of what? [What did you see?](https://xkcd.com/979/)
