### ISSUE TITLE
Playlist font size does not change

### ISSUE THREAD

**Issue by clementine-user** [clementine-player/Clementine#4063]
Clementine Player version: 1.2.1
OS: OS X versions 10.7.5 and 10.8.5

Problem: Font size does not change in playlist when Preferences > User Interface > Song Information > Appearance is set to any size. Quitting and restarting app after preference change does not resolve issue. Deleting preferences or playlist and re-applying font size does not resolve issue.

**Comment by Gluups** [comment]
Hello,
I think I found something that will interest you :
https://www.wintools.info/index.php/system-font-size-changer
The fonts that are selected there are **completely** ignored by Windows 10, but Clementine respects them. I could change the font size of the tooltips, and of the dropdown menus. I even changed the font size in the list, for that I do not remember whether I changed the icon or palette title font. I think it was icon, strangely.
