### ISSUE TITLE
Artist in mp3 metadata (track information) do not saved

### ISSUE THREAD

**Issue by Lehych** [clementine-player/Clementine#4098]
Version 1.2.1  (x64)
OS: Ubuntu 13.04 (x64)

I have some files with Cyrilic symbols in mp3 meta that is displayd incorrectly. (I have no idea about encoding of files and how this files were created). I've desided to organise MetaData but dealt with a problem.

I can't change `Artist` tag if `Performer`  tag is filed with wrong-encoded cyrilyc simbols. This leads to another problem: `Complete tags automaticly` function replace all tags except `Artist` until I remove everything from `Performer` tag.

Sample mp3 file I can sand directly to developer email if needed (since I'm not shure it's correct to leave here someones music files).

Maby related to #4097

**Comment by simonwiles** [comment]
this issue brought me here too (Clementine 1.2 on Mint 17.1); if I clear the "Performer" tag I can change the "Artist", but then the "Performer" tag is set to the same value (as "Artist").  Likewise, if I clear the "Artist" tag, I can put what I like in "Performer", but, again, both "Artist" and "Performer" will be set to the same value.  Seems like the two input fields are point (incorrectly) at the same ID3 tag, with the "Artist" field taking precedence where both have values.

**Comment by Chocobozzz** [comment]
Can you test with the latest build ? http://builds.clementine-player.org/

**Comment by simonwiles** [comment]
@Chocobozzz -- yes, thanks, works correctly in 1.2.3-1060-gccf5bff.  Cheers!

**Comment by Chocobozzz** [comment]
So I think we can close this issue.
