### ISSUE TITLE
Embedded Artwork for supported file types

### ISSUE THREAD

**Issue by octoquad** [clementine-player/Clementine#4106]
Currently Clementine doesn't support writing artwork directly to the music file. This becomes a problem when you use Clementine on multiple machines or even a different music application, like Traktor Pro 2 by Native Instruments (DJing application). 

At the moment my setup involves three computers that basically sync music to and from each other either using rsync scripts or a windows application. As a DJ, I would love to see this feature implemented as it can save me a lot of time trying to use the djing application on one monitor and having to switch between a web browser and the application. At my main computer I have two monitors that make updating song information a breeze.

Could this feature be implemented as an experimental feature, something that can be activated or deactivated in preferences until it becomes stable? I won't even mind testing out the new code in separate branch and compiling Clementine from source and providing feedback on any problems (my C foo is weak :( ).

Thanks

**Comment by 89z** [comment]
https://github.com/clementine-player/Clementine/issues/1176
https://github.com/clementine-player/Clementine/issues/4043

https://github.com/clementine-player/Clementine/issues/4106
https://github.com/clementine-player/Clementine/issues/5195
https://github.com/strawberrymusicplayer/strawberry/issues/286
