### ISSUE TITLE
memory leaks when parsing non-utf8 tags

### ISSUE THREAD

**Issue by Lavande** [clementine-player/Clementine#4115]
I have three flac files which contains non-utf8 tags.
When I open clementine, it starts consuming about 80M memory, but then this suddenly goes up to nearly 100% of my total memory.
While this happens, the terminal shows:
17:14:37.824 ERROR logging:55                       gst_tag_parse_extended_comment: assertion 'g_utf8_validate (ext_comment, -1, NULL)' failed 
17:14:37.825 ERROR logging:55                       gst_tag_parse_extended_comment: assertion 'g_utf8_validate (ext_comment, -1, NULL)' failed 
So I moved two of these files out of the library directory and left one there to test.
Then I started clementine again, the same happened.
However, if I clear all the tags of the flac file and run clementine, everything's fine.

**Comment by JulianVolodia** [comment]
Dig diggy that issue...

Hi Pals! I have a joy with my lovely ASANs and getting over with some mem leaks.

@Lavande , are you still there and could you try to reproduce for this?

If there will be no response I will look for that but for now I will wait, if somebody could test it again (un)successfully ;->

Best regards and see You soon. :)

**Comment by Lavande** [comment]
Hi @JulianVolodia Memory doesn't leak any more with the same file now on clementine 1.3.1

**Comment by JulianVolodia** [comment]
@Lavande nice to hear that. I understand that if you don't see the bug now and could check that 1.2.3 had it and now it's gone, the issue could be closed. Am I right?

**Comment by Lavande** [comment]
@JulianVolodia Yes of course this should be closed since it's only in a ancient version which is gone now. Thanks for reminding me of this.

**Comment by JulianVolodia** [comment]
Great! :)
