### ISSUE TITLE
Playback sometimes paused when track ends

### ISSUE THREAD

**Issue by nuklea** [clementine-player/Clementine#4189]
Playback paused at 00:01 on next track. After some time playback resumed.

I use clementine from git.

``` bash
$ LC_ALL=C yaourt -Qi clementine-git | grep Version
Version        : 1.2.1.305.gacfc7e6-1

$ uname -a
Linux footbaby 3.12.9-2-ARCH #1 SMP PREEMPT Fri Jan 31 10:22:54 CET 2014 x86_64 GNU/Linux
```

**Comment by fortysixandtwo** [comment]
I can confirm what pernatiy reported:
Transition between songs with 44,1 andd 48kHz sample rate causes player to be stuck at 00:01.
Using Clementine 1.2.3 on Win7 64bit (but I think I have the same issue in Linux aswell).

**Comment by Ferroin** [comment]
I'd been doing some experimentation myself, and had come across the same thing, with the caveat that it happened for any case of transitioning between sample rates (I tested with a mix of 22.05k, 44.1k, 48k, and 96k sample rates).

**Comment by Ferroin** [comment]
Also, it happens more consistenly for me with larger sample sizes (eg, more often for 24-bit than 16-bit), and more frequently with FLAC than MP3 or Vorbis.

**Comment by zluca** [comment]
Clementine 1.3.1. Bug is still here.
