### ISSUE TITLE
using network shares for music storage

### ISSUE THREAD

**Issue by andyclay** [clementine-player/Clementine#4213]
I cant see any way to select music thats on a network share from clementine. The network share is listed in my ubuntu "files" dash. How do you get network shares to show up in clementine?

**Comment by Karry** [comment]
Mounting network share is not usable solution. System is completely unusable on network with high latency or even packet drops.  Such simple thing like `df` may freeze for seconds. It would be really nice to support Clementine collections via KIO and be prepared for asynchronous file operations...
