### ISSUE TITLE
problems when loading tracks from file list 

### ISSUE THREAD

**Issue by tomsgithub** [clementine-player/Clementine#4221]
(using German version, sorry for bad translation, hope you know what I mean)
1.
select file list
try to add some files to tracklist
some files could be added some not:
with many files it stops with 'Loading tracks xx%'
one file: 'Loading tracks 0%'
try it another time
 'Loading tracks 0%, Loading tracks 0%'
 another time
 'Loading tracks 0%, Loading tracks 0%, Loading tracks 0%'
...
2. 
it doesn't works to add files twice

1.1.1 works fine

v. 1.2 with actual openSuse 31.1

Thanks a lot

**Comment by pamanes** [comment]
I can confirm the issue, same thing with certain WAV files at the moment, Version 1.2.3 on kubuntu
