### ISSUE TITLE
Add VST support

### ISSUE THREAD

**Issue by dbogdanov** [clementine-player/Clementine#4229]
Hello, is it technically possible to add VST support and is it ever planned? 
Foobar provides similar functionality.

**Comment by jterrain** [comment]
@davidsansome @MathieuDuponchelle now there is:

https://github.com/centricular/gstreamer-vst3

Possible integration?

**Comment by MathieuDuponchelle** [comment]
heh, that's quite the throwback, I don't remember if there were specific reasons for not upstreaming this, @sdroege ?

**Comment by sdroege** [comment]
I think because it only supports a very small subset of VST3. If it's useful for others in this shape, sure why not :)
