### ISSUE TITLE
Linux: Clementine should seek all icons from current theme

### ISSUE THREAD

**Issue by franksouza183** [clementine-player/Clementine#4268]
Clementine should seek all icons from current theme on Linux. The app seems to seek some correctly, but others are hardcoded, like "love" "star_off" (tabs) providers, "tiny-start" / "tiny-pause" (used with the tray icon and tabs), "currenttrack_pause "," currenttrack_play "," Nocover "," spotify "etc.. It's horrible to see a program using mixed icons.

**Comment by elmat0** [comment]
Wow @uzvermode that looks really nice! Is it much work for you to propose a pull request and merge your changes back to master?

**Comment by narunlifescience** [comment]
if you need homogeneity for icons, you can use your own icon set. this is really simple (see #5051).this works on windows, linux & mac systems

**Comment by Ferroin** [comment]
The point is that Clementine should be trying to look nice without the user having to do anything.  It's a perfectly reasonable expectation that an application will use a uniform icon set by default without any user intervention.

**Comment by narunlifescience** [comment]
Hmm..  I think clementine looks pretty decent. It is pretty hard to replace the entire clementine default icons(I  tried to replaced some of them)with new ones which satisfy  light and dark themes. for example the icon set of @uzvermode looks nice on light themes but may not provide enough contrast on a dark theme..

**Comment by Ferroin** [comment]
Usually, it looks perfectly fine, but sometimes you end up with stuff like in the screenshot that @MightyPork posted.  Notice how the internet icon is disproportionately big compared to the others, and how the drop shadow is noticeably different from on the other icons.

**Comment by narunlifescience** [comment]
@Ferroin that seems to be a qt4 bug (see  #2298). This should be fixed in qt5 builds..

**Comment by thecountoftuscany** [comment]
@MightyPork I am facing the same problem as yours for some reason. How did you fix it?

**Comment by MightyPork** [comment]
I got a better internet provider, so it stopped happening so often.
Unfortunately I have nothing else to suggest, short of trying to fix it
yourself (it was very messy last time I looked at the code)

**Comment by thecountoftuscany** [comment]
@MightyPork  Internet provider? I am talking about the ugly icons (probably Oxygen/KDE4?). How to make Clementine use the default breeze or breeze-dark icons?

**Comment by MightyPork** [comment]
sorry thought it was the other issue, with streams stopping. This I think just vanished by itself with some unrelated update.
