### ISSUE TITLE
Linux: Horrible performance under stress

### ISSUE THREAD

**Issue by Jimi-James** [clementine-player/Clementine#4306]
Whenever my hard drive is working hard--and it can be anything, from USB transfers to internal partition transfers to booting my Windows Virtualbox--Clementine just completely gives up on life. The GUI is the first to go. Having access to the GUI while anything more taxing than Firefox runs is just not something that happens. After that, the music will follow--it might freeze for 5-10 minutes straight (and STAY frozen if I end the process and relaunch Clementine), and when it's finally done freezing, it might resume from where it left off, or it might get stuck in the middle of a song, reporting that it's 10 minutes into a 5-minute song and stuck that way until I stop and restart the song. Raising Clementine's CPU or hard drive priorirty doesn't fix this. I've notice that whenever it's going through one of its fits, KDE's process manager will say it's in disk sleep.

I have a quad-core 3GHz CPU and 8GB of RAM, and I only give 2 cores and 2GB to the Windows virtual machine I mentioned, so I can't imagine why this is happening.

**Comment by ArnaudBienner** [comment]
Commit 946c0381d1e73a1ef3aa0e3e6166706f31376432 probably fixed this issue.
If you can give it a try, let us know if this actually fixes your problem (and wait for the next official release to be in Arch repo, as we don't provide developers build for Arch Linux in http://builds.clementine-player.org/)

**Comment by Chocobozzz** [comment]
clementine-git from AUR provide the latest Clementine build on ArchLinux (https://aur.archlinux.org/packages/cl/clementine-git/PKGBUILD)

**Comment by Jimi-James** [comment]
Actually, it's already been a while since I had the issue. On top of that, just now, I tried backing up my computer while playing music (something that would reliably reproduce it a few months ago), running the latest AUR git version (which is a bit newer than that commit), and nothing happened. I think we can assume it's fixed, unless it pops up again.

**Comment by ArnaudBienner** [comment]
OK, thanks for letting us know :)
