### ISSUE TITLE
1.2.3 (Windows) Freezes up

### ISSUE THREAD

**Issue by GiantGerman** [clementine-player/Clementine#4320]
Since the 1.2.3 update, when i change songs manually or automatically, after a random amount of time or songs switched, clementine stop responding. At times it will completely close out, or it will take a few manual song changes to make it respond. Otherwise it will take upwards of 10 minutes for it to respond on its own.

Not sure what happened there but its not cool. The previous version had the issue of if i paused and played so many times, clementine would simply crash. That was annoying but simple to deal with. The newest version is just not acceptable. 

If you need performance data, or crash data, i could supply it but i don't know where to look for it.

**Comment by curtisgibby** [comment]
:+1: I've had this happen consistently for months.  Looking forward to a release that fixes it.  In the mean time, I'm reverting to 1.2.2.
