### ISSUE TITLE
Some keyboard shortcuts not working in Ubuntu 14.04

### ISSUE THREAD

**Issue by shawnabdushakur** [clementine-player/Clementine#4323]
In Ubuntu 14.04, using the PPA, the keyboard shortcuts for Play/Pause and Audio Mute don't work. Audio up and down do work. These all work in VLC.

**Comment by grattojf** [comment]
FYI bug still present on Kubuntu 14.04.1 and Clementine 1.2 (all relevant packages / dependencies up to date). I managed to work around by assigning play/pause, previous and next to META + UP_ARROW, META + LEFT_ARROW and META + RIGHT ARROW respectively. META being your left Windows key, for those wondering.

This works. I'm using this as I type this comment.

**Comment by mortlind** [comment]
I confirm that I have the same behaviour on Debian testing+unstable with KDE 4.14.2 and Qt 4.8.6. Clementine is v. 1.2.3.

I can set the multimedia keys as shortcuts through Clementine preferences, and there are no global shortcuts conflicting. No response in Clementine when trying to use the set shortcuts.

Using Alt+FN* works, as reported by MightyPork.

**Comment by Playermet** [comment]
Also. Numpad keys not working in Windows.

**Comment by 1358** [comment]
Ubuntu 15.04, KDE 4.14.6, Clementine 1.2.3, QT 4.8.6
media keys doesn't work. they can be assigned within clementine but they do nothing.
Amaroks global bindings are removed.

Clementine outputs some warnings, too:
11:11:47.443 WARN  unknown                          QxtGlobalShortcut failed to unregister: "Media Next"  
11:11:47.443 WARN  unknown                          QxtGlobalShortcut failed to unregister: "Media Play"  
11:11:47.443 WARN  unknown                          QxtGlobalShortcut failed to unregister: "Media Previous"  

Workaround is assigning custom clobal shortcuts for the media keys and assign them to clementine -t -s -r -f, however they are really global and always start clementine, if it is not running already.

**Comment by theHaeryOne** [comment]
I'm also having the same issue using Xubuntu 15.04 and Clementine 1.2.3
The multimedia keys (Fn + Arrows on an ASUS N550) work in VLC, but not in Clementine. I have tried clearing the bindings and remapping; Clementine recognizes the key when mapping, but doesn't do anything when they are pressed.

**Comment by Chocobozzz** [comment]
Please try the latest build of Clementine and unmap *Fn + Arrows* in XFCE keyboard preferences.

**Comment by theHaeryOne** [comment]
I'm afraid I've actually moved over to using MATE after an instability in Xubuntu forced me to reinstall. The keys all work out of the box on Mate and thus can't test for you.

Sorry,

**Comment by lolole13** [comment]
Using ubuntu Mate 15.04 and Clementine 1.2.3 but the trouble is always the same. 
Before running VLC, all my multimedia keys on my keyboard work perfectly. 
After running and closing VLC, it seams that the sound applet keep focus on it, preventing the good use of these multimedia keys. 

Hope it was usefull.

**Comment by dVaffection** [comment]
Confirm for Kubuntu 15.04 and Clementine 1.2.3. Multimedia keys don't work, in console I see the following output:
```bash
18:37:22.508 WARN  unknown                          QxtGlobalShortcut failed to unregister: "Media Next"  
18:37:22.508 WARN  unknown                          QxtGlobalShortcut failed to unregister: "Media Play"  
18:37:22.509 WARN  unknown                          QxtGlobalShortcut failed to unregister: "Media Previous"  
18:37:25.894 WARN  unknown                          QxtGlobalShortcut failed to unregister: "Media Next"  
18:37:25.895 WARN  unknown                          QxtGlobalShortcut failed to unregister: "Media Play"  
18:37:25.895 WARN  unknown                          QxtGlobalShortcut failed to unregister: "Media Previous"
```

**Comment by isms** [comment]
Confirm for Ubuntu 15.10 (kernel 4.2.0-18) with i3 windows manager and Clementine 1.2.3.

I have:
* Unset Gnome media key shortcuts via `unity-control-center`.
* Unclicked "Use Gnome's shortcut keys" within Clementine > Preferences > Configure Shortcuts

Here is the window:
![image](https://cloud.githubusercontent.com/assets/1284973/11574089/94dfa27c-99d7-11e5-9ba4-26ebf6e14c4c.png)

Whenever I click one of the settings with a "Media _____" shortcut set, these warnings are logged in the console:

```
16:03:52.604 WARN  unknown                          QxtGlobalShortcut failed to unregister: "Media Next"  
16:03:52.605 WARN  unknown                          QxtGlobalShortcut failed to unregister: "Media Play"  
16:03:52.605 WARN  unknown                          QxtGlobalShortcut failed to unregister: "Media Previous"
```

**Comment by fredg02** [comment]
Didn't work for me with Clementine 1.2 on Kubuntu 14.04.5 LTS. After updating to Clementine 1.3.1 it finally works (don't know if any version in between already had a fix for it).

**Comment by 1358** [comment]
Works with 1.3.1 here too (Kubuntu 16.10)
