### ISSUE TITLE
feature request: Integration with Yandex Music

### ISSUE THREAD

**Issue by rubinchyk** [clementine-player/Clementine#4439]
Good day! We would like to see our favorite player integration with Yandex Music.

**Comment by anyx** [comment]
+1

**Comment by zeloras** [comment]
+1

**Comment by Malezha** [comment]
+1

**Comment by selumin** [comment]
As far as i know, Yandex music service doesn't have an official API.
Also, it is not legal because of their terms of use (article 2.3 at page https://yandex.ru/legal/music_termsofuse . Sorry, i didn't found translated version of this page).

**Comment by MurzNN** [comment]
Seems that API already available: 
https://www.searchengines.ru/yandeks-api-dlya-audio.html
Яндекс открыл доступ к API для воспроизведения аудио

**Comment by R242** [comment]
There is the browser API only. This library not even supported by node.js.

**Comment by MurzNN** [comment]
From description on https://github.com/yandex/audio-js
You can include this libraray as npm-package:
var YandexAudio = require('YandexAudio');

**Comment by byaka** [comment]
Is anyone want to implement this? :)

**Comment by MurzNN** [comment]
I have found https://gitlab.com/ColinDuquesnoy/MellowPlayer that works well with Yandex Music!

**Comment by acherkashin** [comment]
Пилю интеграцию яндекс музыки в виде экстеншина для VsCode. 
Просто оставлю ссылки здесь. Любая помощь/фидбэк приветствуются.

[Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=acherkashin.yandex-music-extension)
[Репозиторий](https://github.com/acherkashin/yandex-music-extension)

![image](https://user-images.githubusercontent.com/9947582/88843096-3da48a00-d1e9-11ea-8943-6bf3e342916f.png)
