### ISSUE TITLE
"Date created" field in Linux is wrong.

### ISSUE THREAD

**Issue by abhnvkmr** [clementine-player/Clementine#4454]
The date created field corresponds to _ctime_ file attribute which is change-time, not creation-time. _ctime_ timestamps track when the inode/metadata of the file was changed. Old linux filesystems did not track crtime i.e. creation time . It's a relatively new addition to newer ext filesystems.

_crtime_ cannot be used, as the only way to access it as-of-now is
*# debugfs "stat <inode>" /dev/sdXn

So I think, "Date created" field is highly misleading, as it always changes whenever a file is modified because _ctime_ will always remain newer or same as _mtime_ (modified time).

On NTFS volumes in Linux, Clementine maps "Date created" to "Entry modified" timestamp, which is nowhere reflected in the Windows operating system.
## Testing methodology

Operating System: Kubuntu 14.04 and Arch Linux
Kernel: 3.15.6
Filesystem: ext4
### Steps to reproduce:
1. Select a track and open its track information
2. Change a field and save
3. Open info again
4. Now Both "Date created" and "Date modified" share the same value in Clementine
5. Change any attribute via file manager (this would change just the ctime)
   Now "Date created shows time when the file was modified by File Manager"
   ### Verification
   _ls -il --time=ctime file.name_ maps to "Date created"
   while _sudo debugfs *stat *_inode**" /dev/sda5 is the original creation time which can only be obtained as root.

If I modify a file on a NTFS volume, same thing happens. _Date created_ shows the entry modified timestamp. But when I boot into Windows, the "Date created" of that file is different (older and original) from Clementine shows in Linux.
### Resolution

Don't show _Date created_ on Linux systems. Getting the real "Date created" i.e. _crtime_ is impossible as a non-root user.

**Comment by uqs** [comment]
This needs to be reopened, it looks like Clementine trying to be clever with ctime (which is NOT and has NEVER been "creation" time) is leading to it failing to do anything on an NFS mount here, as reported in issue #5187

**Comment by liofeu** [comment]
Same issue on Mac OSX, Clementione Version 1.3.1

Both field "Date creation" and "Date modification" displays the "Date modification".

It is a new issue on Max OSX, it was not the case before. 

It is very annoying for those using the playing list "recently added to the library".
