### ISSUE TITLE
Cannot access subsonic server

### ISSUE THREAD

**Issue by avbudin** [clementine-player/Clementine#4476]
Login validates, then upon trying to access the server Clementine displays "Fetching Subsonic Library" and does nothing. Tested by installing a fresh subsonic server with only 10 songs on the same machine as Clementine but the issue remained.

**Comment by andor44** [comment]
This is still happening for me. I've tried 1.2.3 stable on both Linux and Windows (also the git version on Linux) and I can authenticate but I get stuck on "Fetching Subsonic library". Also worth noting that Clementine *does* appear in Subsonic's player list, but the type shows up as (Unknown) and there is no "last seen" date.

**Comment by Chocobozzz** [comment]
@andor44 This looks like your subsonic server is empty and this is the reason why "Fetching Subsonic library" doesn't stop. I submitted a PR to fix this bug.

Didn't you forget to "Scan media folders now" in the Subsonic interface ?

I just tested with Subsonic 5.1 and the latest build of Clementine and it's work fine.

**Comment by andor44** [comment]
Yes, this was the case! Pardon me, I'm quite new to Subsonic and my understanding was that there was no need to scan the library, since everything appeared in the lefthand menu. Scanned my library and Clementine can now successfully fetch it too. Thanks for the tip.

**Comment by mueslo** [comment]
I have the same problem, on 1.2.3-5 on Arch Linux. My subsonic library isn't empty though.

**Comment by Chocobozzz** [comment]
Please try with clementine-git

**Comment by mueslo** [comment]
Works like a charm :)

**Comment by davidgfnet** [comment]
Yep it should be solved. It is not solved on the qt5 branch, I guess it's behind several commits from master.
The issue is that clementine doesn't send user/pass in any query it performs except for the initial "ping" query (to validate the login). What commit did fix that?
Cheers!

**Comment by zardini123** [comment]
I am having the same issue with the most recent build of clementine to date (Version 1.3.1-611-gda04471) on macOS Mojave, using Airsonic as my subsonic server.  My server is not empty, has been scanned, and is confirmed working with other applications.  Any thoughts?

**Comment by sersorrel** [comment]
I'm also having this issue with Clementine 1.3.1+git276-g3485bbe43+dfsg-1.1build1 (from Ubuntu 18.04) and a Supysonic server, which works fine with other applications.

**Comment by paperbagcorner** [comment]
@sersorrel That version is over three years old. You should try a recent build from https://github.com/clementine-player/Clementine/releases

**Comment by dbogdanov** [comment]
I am getting the "Fetching Subsonic library" issue too. 

Clementine 1.4 rc2, installed with APT on Ubuntu 20.10.
