### ISSUE TITLE
[Possible bug] MP3 file with bad ID3v2 (but valid ID3v1) not loaded into library

### ISSUE THREAD

**Issue by jochemliem** [clementine-player/Clementine#4500]
Dear developers,

I've noticed that part of my music is not loaded into Clementine's music library. I think the cause is that the file has invalid ID3v2 (but valid ID3v1 data), according to MP3TAG. Perhaps such files should still be added to the library and the information should be extracted from the ID3v1 data? I've added a link to one of the offending files. 

Steps to reproduce:
1. Place the linked file in an empty directory.
http://staff.science.uva.nl/~jliem/temp/Yoko%20Shimomura%20-%20Dearly%20Beloved.mp3
2. Set the clementine music library to this empty directory

Actual result:
The music library remains empty

Desired result:
The file is added to the library

Specifications:
Windows 7 Ultimate (SP1, 64 bit)
1.2.3-703-g13cda62 (and also in the latest stable)

**Comment by nacenteno** [comment]
Based on what jochemliem found I made a copy of a song file, updated the tags and was able to see the file.

I saw another case when the file had Tag2 but no Tag1 data.

Now that I look closer I see I have several files like these that are not visible.

What do you suggest?

**Comment by Chocobozzz** [comment]
@jochemliem sent me the files and in fact this is taglib which crashes when it try to read tags of the files. The crash seems to have been fixed since the last release of TagLib https://github.com/taglib/taglib/issues/416 (I tested and TagLib 1.9.1 crashed whereas the git version was able to read the tags).

**Comment by Chocobozzz** [comment]
I close this since it's a "taglib issue" (fixed in the git version).
