### ISSUE TITLE
Portable Version

### ISSUE THREAD

**Issue by jlanzarotta** [clementine-player/Clementine#4509]
Whatever happened to the portable version of Clementine?  A while back there was a portable version 1.2p, now I cannot find an updated version.  Has this feature been abandoned?

**Comment by Wyatts** [comment]
It seems this is at least merged into master, though testing against HEAD is a bit problematic unless you can already build for windows.  Is it within scope of "Make a portable version" to have up-to-date portable builds on http://builds.clementine-player.org/win32/?  I noticed there are a few "Clementine-PortableSetup" executables, but the most recent one is from 2014-10-29, nearly four months ago.

**Comment by jlanzarotta** [comment]
An updated portable version would be awesome as I prefer a portable version to having to install it...

**Comment by jlanzarotta** [comment]
Any word on if the portable version will be kept up to date with the rest of the product?  It would be nice if a portable version was built each time a new windows version was generated...

**Comment by hatstand** [comment]
I built a new version, let me know if it works and I'll enable automatic builds.

http://builds.clementine-player.org/win32/release/Clementine-PortableSetup-1.2.3-1127-g5256a11.exe

**Comment by jlanzarotta** [comment]
Thanks, I will give it a try and let you know in a few minutes.

**Comment by jlanzarotta** [comment]
Looks good!  Thanks.

**Comment by hatstand** [comment]
Automatic builds are enabled now

**Comment by jlanzarotta** [comment]
Many thanks!

**Comment by Wyatts** [comment]
Oh, excellent!  Thank you very much.  With that, I think this can probably be closed, now.  Or were you going to wait for a release milestone first?

**Comment by jlanzarotta** [comment]
Any idea why a new portable version has not been built for quite a while now?

**Comment by Chocobozzz** [comment]
See https://github.com/clementine-player/Clementine/issues/5021

**Comment by jlanzarotta** [comment]
Any ideas on why the portable version is no longer being built?  Thanks...

**Comment by davidsansome** [comment]
My fault - this got forgotten when I was refactoring the buildbot configs.  I've added it back in https://github.com/clementine-player/Buildbot/commit/02abc8b4d75362c83da1a95887bb841efe63d1e7

**Comment by jlanzarotta** [comment]
No problem...  Much appreciated for the fix.

**Comment by jlanzarotta** [comment]
Okay, I was able to find the latest buildbot version, http://buildbot.clementine-player.org/builders/Windows%20Portable/builds/16; however, not one in http://builds.clementine-player.org/win32/portable/

**Comment by davidsansome** [comment]
Oops they were being put in the wrong directory.  Fixed with https://github.com/clementine-player/Buildbot/commit/3d778aeda26c1f027a31c885e2163ff4b1f95185

**Comment by vatterspun** [comment]
I've been enjoying portable Clementine and watching this topic closely so I was curious with the 1.3.0**rc2** file posted to the /win32/portable folder mentioned above.  "RC" usually means "Release Candidate" so I was wondering if that means you're approaching an official portable release?  Or is that just in line with the standard 1.3.0 release cycle?

Thanks!

**Comment by amuttsch** [comment]
I triggered a build, should be there in a few minutes. 

On March 2, 2016 9:51:46 PM GMT+01:00, vatterspun <notifications@github.com> wrote:
>I've been enjoying portable Clementine and watching this topic closely
>so I was curious with the 1.3.0**rc2** file posted to the
>/win32/portable folder mentioned above.  "RC" usually means "Release
>Candidate" so I was wondering if that means you're approaching an
>official portable release?  Or is that just in line with the standard
>1.3.0 release cycle?
>
>Thanks!
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/clementine-player/Clementine/issues/4509#issuecomment-191424665

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.
