### ISSUE TITLE
load playlists

### ISSUE THREAD

**Issue by marius6298** [clementine-player/Clementine#4519]
When loading an existing playlist, it comes up with the error message:The Playlist '....' was empty or could not be loaded.
This happens with playlists are accidentally removed by pressing the X in the playlist tab, and any other playlist. I have tried to copy and paste the tracks into a loaded playlist XML file but that doesn't seem to work either, and should not be necessary. So now the only way to recover a playlist is to recreate it from mp3 files.
My system is a desktop with Ubuntu 14.10 and Clementine 1.2.

**Comment by geg-mopo3** [comment]
I have the same issue. I use Clementine 1.2.

I exported an XSPF playlist in Amarok, but couldn't load it in Clementine. But it loads well in Amarok and is valid according to http://validator.xspf.org/

Hm, I can't attach the file. Getting the error:
"We don’t support that file type. with a PNG, GIF, JPG, DOCX, PPTX, XLSX, TXT, PDF, or ZIP. "
