### ISSUE TITLE
Interface laggy: v1.2.3 and v1.2.2 on Mavericks

### ISSUE THREAD

**Issue by alexrjohnston** [clementine-player/Clementine#4523]
Hi guys im new to Clementine, really impressed! unfortunately the GUI is really sticky and slow on my 2011 macbook pro. scrolling playlists and the vu bar are very choppy. Ive had a decent search all over the internet and while ive found people with the same issue i have found no solution.

have a missed something or is this still a current issue?

best
Al

**Comment by ArnaudBienner** [comment]
I confirm the issue

**Comment by ArnaudBienner** [comment]
Trying the old buil from http://builds.clementine-player.org/mac/
for me the problem appears between build 200 (commit c4bf176) and 209 (commit 886f489).
Commits in between:
48f15c9fc7359ec581fcd36441a45cd1d31cd3c0
bacef04405310f18a9927def7dcd6fc445a28727
ab5ccf69da293fdfcd32c0ff11e4a6f38e2589e1
23724b667fcaf530d9af77f6f1cf70f1c7ba28b2
63f13b19f2bcf4eb5a121d52b331e6a0181a90db
747e0f510f1fc1d2cc8ed448626e526f61d7da3b
04dcfeb9d22d89ae24b5f60cdaa2c20e11f956d6
526a9d99604d2a2e90e7c1f7a26505648af1fce6

Looking at the dependencies, there was no change around this time (no Qt version upgrade or anything that would have been a good candidate to explain the regression):
https://github.com/clementine-player/Dependencies/commits/master?page=3

**Comment by ArnaudBienner** [comment]
Seems that commit ab5ccf69da293fdfcd32c0ff11e4a6f38e2589e1 is to blame: the Utilities::SetThreadIOPriority in LibraryWatcher.
Maybe it worked at that time, but something in OS X internal changes its behavior.
I will have a deeper look.

**Comment by ArnaudBienner** [comment]
The problem is that before this commit, the set_thread_io thing was set during run, by the thread itself.
Now, SetIOPriority is done in LibraryWatcher constructor, by the main thread.
So it probably also impacts Linux, even the bad effect of this aren't so obvious.

I guess we should create new Thread class that inherits QThread, but with just an additional set_thread_io method, and use this class for our library watcher_thread_

**Comment by tmikaeld** [comment]
I just want to say THANK YOU for fixing this.
