### ISSUE TITLE
Clementine and internet streams

### ISSUE THREAD

**Issue by Clementine-Issue-Importer** [clementine-player/Clementine#453]
_From [smarquesPT](https://code.google.com/u/102722975706781462481/) on June 30, 2010 12:05:42_

What steps will reproduce the problem? 1. Add internet stream in Clementine
2. Open stream with clementine What is the expected output? What do you see instead? It`s supposed to listen the stream. Instead clementine crash. What version of the product are you using? On what operating system? I´m using clementine 0.4 r1387 on Vista. Please provide any additional information below. The default streams soma; magnatune and last.fm work fine.

The radio streams added are in mms; http; mmsh protocols

Those streams work fine in mplayer.

Here are some examples:

http://195.245.168.21/antena3
mms://195.23.102.196/cidadecbr96
mmsh://stream2.mega.fm/MEGAFM?MSWMExt=.asf

All of them are Portuguese radios

_Original issue: http://code.google.com/p/clementine-player/issues/detail?id=453_

**Comment by iamthom** [comment]
SOLVED Ubuntu 14.04

Using Clementine 1.2, and can't play aac files. Solved it by installing all gstreamer plugin:
`sudo apt-get install gstreamer0.10-plugins-bad`

Restart the clementine if you open it.
