### ISSUE TITLE
Some tracks have no length

### ISSUE THREAD

**Issue by liftarn** [clementine-player/Clementine#4530]
Some of my music files get listed as having no length. No 0:00 but just blank.

**Comment by liftarn** [comment]
Tested with 1450 and the issue is still there.

**Comment by Chocobozzz** [comment]
I can't reproduce with the latest build on Windows with the file you uploaded. Can you send me (by email or whatever) another file?

**Comment by liftarn** [comment]
OK, I get no length info on 
https://www.dropbox.com/s/pbfvbvo7vsy1jay/13%20Hunter%20Down.mp3?dl=0
and
https://www.dropbox.com/s/8984lxg48gtmow3/18%20Combine%20Harvester.mp3?dl=0
using 1457.

**Comment by TsudaKageyu** [comment]
Hi guys,

I confirmed that it's a bug of TagLib. Some MPEG frames of the given files are broken, and TagLib v1.10 can't handle them properly. I fixed it about a week ago, but I will check if TagLib works with the files again.

**Comment by Chocobozzz** [comment]
Great, thanks @TsudaKageyu to keep us informed :)

**Comment by TsudaKageyu** [comment]
The current snapshot of TagLib can read the files, but returns wrong lengths. I will continue working on this issue. Thanks for your report, @liftarn!

**Comment by liftarn** [comment]
And this too https://www.dropbox.com/s/97aclp9r50n3wvg/08%20Sleep%20Away.mp3?dl=0

**Comment by TsudaKageyu** [comment]
Hi guys, I created a pull request https://github.com/taglib/taglib/pull/705 to fix this bug.
I confirmed that all files provided by @liftarn is parsed properly with that patch.

**Comment by Chocobozzz** [comment]
Awesome thanks @TsudaKageyu, so we'll wait the next release :)

Closing this since it is a TagLib issue.

**Comment by liftarn** [comment]
Could you please also check https://www.dropbox.com/s/8v8n5u6ql8dytol/01%20Libation%20Unto%20Ambrose%20Bierce.mp3?dl=0 
I have tried it with 1.2.3-1480-gab000b1 and it gives no length.

**Comment by narunlifescience** [comment]
you may have to wait until the next release of Taglib https://github.com/taglib/taglib to get this fixed as this issue seems to be related with Taglib rather than clementine.

**Comment by TsudaKageyu** [comment]
It's the same bug as I described and fixed above. Some of the MPEG audio frames of ```01 Libation Unto Ambrose Bierce.mp3``` are broken, and TagLib v1.10 cannot handle them properly.

**Comment by liftarn** [comment]
Tested with 1.3.1 and some tracks still get no lenght.

**Comment by Chocobozzz** [comment]
@liftarn What is your OS?

**Comment by liftarn** [comment]
@Chocobozzz Windows 7 Pro, SP1, 64bit

**Comment by Chocobozzz** [comment]
@ArnaudBienner Could you update [Clementine dependencies for Windows/Mac](https://github.com/clementine-player/Dependencies) to TagLib v1.11?

**Comment by ArnaudBienner** [comment]
@Chocobozzz done. I've updated the 3rd party lib as well.
Windows dependencies build failed, but I'm not sure why... seems like gsttaglib doesn't like the new version. I will have a deeper look.

**Comment by Chocobozzz** [comment]
@ArnaudBienner: Great, thanks a lot.

**Comment by ArnaudBienner** [comment]
@hatstand @davidsansome  any idea why the win dep build is failing?

**Comment by ArnaudBienner** [comment]
Hmmm OK, will give that a try
