### ISSUE TITLE
Seeking with mouse wheel broken

### ISSUE THREAD

**Issue by xonfour** [clementine-player/Clementine#4568]
When I try to seek a track using the mouse wheel while pointer is on the track slider / moodbar the song is always rewinded by a few ms. If I do that to often in a row (~ 5-10 times) the track starts from the beginning.

I saw
  Amarok::Slider::wheelEvent(QWheelEvent* e)
in
  widgets/sliderwidget.cpp
It says vertical scroll events "Will be handled by the parent widget" but where exactly is that?

I'm using Version 1.2.3-782-g78804b1

**Comment by Mythos** [comment]
I can confirm that it's still broken. In the stable version 1.2.3 it works, but here on Version 1.2.3-1396-gd9150ec it's still broken.
