### ISSUE TITLE
App doesn't show network drives in files tab under windows

### ISSUE THREAD

**Issue by Clementine-Issue-Importer** [clementine-player/Clementine#457]
_From [ilkevich](https://code.google.com/u/111249325032583163558/) on June 30, 2010 15:22:20_

1. Run app at Win7
2. Go to Files tab
3. Try to find/use network drives

I see only local drives instead. Probably this is qt issue.

Version used: ClementineSetup- r1387 -rel.exe

_Original issue: http://code.google.com/p/clementine-player/issues/detail?id=457_

**Comment by ArnaudBienner** [comment]
Works for me on Windows 8.1.
If you still have the issue on a recent Windows version, please let me know and I will reopen the issue.
