### ISSUE TITLE
Moodbar not working on development builds

### ISSUE THREAD

**Issue by Dominiquini** [clementine-player/Clementine#4575]
In the last development builds the moodbar is not working. Here is one screenshot:
http://imgur.com/EKR8AC0
I'm using version 1.2.3-787-gaa3671b.
But the problem also happens in previous versions...
Seeking with mouse wheel also broken (#4568)
I'm testing in Ubuntu 12.04 and using development ppa (ppa:me-davidsansome/clementine-dev), but the builds on http://builds.clementine-player.org/ubuntu-precise/ also have these problems.
The stable build "1.2.3" are OK!!!

Thank you.

**Comment by Dominiquini** [comment]
In version 1.2.3-954-g2cc560f this problem still persists.
Is there any information you can send to help to identify this bug?

Thank you.

**Comment by KottV** [comment]
Confirm. Seek/moodbar broken.

**Comment by TheUbuntuGuy** [comment]
Is this still an issue in the current dev builds? I feel like this was fixed in one of the many moodbar changes that happened since then.

**Comment by ArnaudBienner** [comment]
Duplicate of #4770
