### ISSUE TITLE
Implement a 'Preview' feature

### ISSUE THREAD

**Issue by Clementine-Issue-Importer** [clementine-player/Clementine#459]
_From [gil.desmarais](https://code.google.com/u/110725766267065912969/) on June 30, 2010 15:38:53_

It would be nice to have a preview feature to prelisten a certain time at a certain (relative) position in a file.

The idea comes from my favoured windows audio player, foobar 2000, where the foo_preview plugin ( http://skipyrich.com/wiki/Foobar2000:Preview ) adds this feature to the player.

The position where the file should start playing should be customizable and relative to track length  (e.g. 25&#37;, 32&#37;). The playtime should also be relative to track length, but should alternatively be absolute (e.g. 10 seconds).

The function could be located at the Extras menu where it can simply be turned on and off.

_Original issue: http://code.google.com/p/clementine-player/issues/detail?id=459_

**Comment by TheUbuntuGuy** [comment]
This was partially implemented in #4903.

**Comment by Chocobozzz** [comment]
So I think we can close the issue.
