### ISSUE TITLE
Feature request: Execute external command on Play and Stop

### ISSUE THREAD

**Issue by LukeOwncloud** [clementine-player/Clementine#4684]
It would be nice if clementine could execute external commands when playing starts and stops. This way Clementine could switch on the audio speakers whenever they are needed.

**Comment by SaSteDD** [comment]
This can already be achieved using Clementine's DBus interface.
https://code.google.com/p/clementine-player/wiki/MPRIS

**Comment by LukeOwncloud** [comment]
Thank you very much! That's it. Here is how you can filter for the PlaybackStatus:

    dbus-monitor "type='signal',sender='org.mpris.clementine',interface='org.freedesktop.DBus.Properties'" | grep PlaybackStatus -A1
