### ISSUE TITLE
Add dependency on gstreamer0.10-plugins-bad

### ISSUE THREAD

**Issue by pavelvat** [clementine-player/Clementine#4687]
1.Install Debian/Ubuntu.
2.Install Clementine.
3.Run Clementine, play Internet->JAZZRADIO.COM->Smooth Jazz.

Appear window with text:
Your GStreamer installation is missing a plug-in 

It's solved by installing the package gstreamer0.10-plugins-bad (not trivial action for ordinary Ubuntu user).
Please add dependency on gstreamer0.10-plugins-bad in the deb package Clementine.

**Comment by Holzhaus** [comment]
This is not something the clementine devs can fix. You should tell the debian/ubuntu packagers.

**Comment by friederbluemle** [comment]
I am getting **Your GStreamer installation is missing a plug-in** as well when I try to stream any internet station. Running Ubuntu 14.04 LTS. Installing gstreamer0.10-plugins-bad does not help in my case. Any other ideas?

**Comment by friederbluemle** [comment]
This was the solution in my case:

    sudo apt-get install gstreamer1.0-libav

**Comment by Chocobozzz** [comment]
Yes, Clementine uses gstreamer1.0 now.

**Comment by friederbluemle** [comment]
Thanks @Chocobozzz
