### ISSUE TITLE
import rating form RythmBox / keep data in plain files

### ISSUE THREAD

**Issue by shalnoff** [clementine-player/Clementine#4695]
It would be wery nice to have this feature. I found your player ocasionally anf find it really the best. But my collection was in RythmBox for ages. It would be not a ptoblem if the data was in plainfiles. Just a short skript would help. However, I see that you use DB :( So I need to go in the same way as users of proprietary software use to went.... ask you*. 

So simple and open varian of soluiotn: 
Please use plain files (and filesystem as a database)

Complex and less transparent solution: 
Please add the Rating import feature

thank you. 

* And it's out of beautiful POSIX stadards.

**Comment by ArnaudBienner** [comment]
Not sure I understood you, but rating support have been improved recently: more ratings are importing when indexing files, and you can now save back ratings in files (in addition of storing them in our DB).
The reason why it's not activated by default is that we don't want to modify files unless users explicitly activated an option to do so.
I don't remember if it is in  1.2.3, but you can try one of the (unstable) developer build if you want to try: http://builds.clementine-player.org/

**Comment by shalnoff** [comment]
great. thank you, I'll try.

**Comment by shalnoff** [comment]
and by keeping the rating in plain files I didn't mean music files (mp3 or any other), but plain text files that anybody can process with (e.g.) sed, awk or any other app with standard POSIX tools and features, or just edit manually.

**Comment by ArnaudBienner** [comment]
I don't think there is standard defined to store ratings this way, in plain files, while there are standard defined to store rating in file metadata.
So I'm not sure this is something we would like to implement.

**Comment by Ferroin** [comment]
Why not just do a simple list of key-value pairs like SoX does when processing files in verbose mode?
For example:
FMPS_PLAYCOUNT=5
FMPS_RATING=1
FMPS_RATING_AMAROK_SCORE=0.9

To be honest though, there are a lot of easy to use command-line tools that provide a very easy to use interface to extract and edit tags from audio files.

**Comment by ArnaudBienner** [comment]
Closing this as AFAICT there is no standard to handle ratings this way. If we do something like this, we would be the only software to do so. And we already provide standard, interoperable ways to store ratings.
