### ISSUE TITLE
Linux: One of the sidebar icons is larger than others

### ISSUE THREAD

**Issue by diath** [clementine-player/Clementine#4701]
I've noticed that the "Internet" icon seems to be way larger than the other icons in the sidebar.

See this screenshot to get an idea of what I mean:
https://i.imgur.com/zNVGjjX.png

I noticed that this happens only on Linux, I checked it on Windows and the icon was properly scaled to the size of other icons. I'm not sure about Macs, I couldn't check it.

This happens with version 1.2.3 and as far as I recall it's been there before so it's not this version specific issue.

**Comment by davidsansome** [comment]
See #1057, #2803, #4074, #4324...
