### ISSUE TITLE
Clementine’s list of languages displays Spanish as Spanish (Spain)

### ISSUE THREAD

**Issue by fitojb** [clementine-player/Clementine#4703]
Given that only one Spanish translation is maintained (by me) and no other Spanish translation file is present (we’ve removed an obsolete and full-of-errors `es_AR` translation long ago), I find it odd that Clementine still parses my `es` translation as `es_ES`. And I’m not even from Spain.
![captura de pantalla de 2015-01-08 21 41 26](https://cloud.githubusercontent.com/assets/554953/5675249/20810aca-977f-11e4-8ec5-3e4b749ad560.png)

**Comment by fitojb** [comment]
Does anybody know from where is that string “español de España” taken? Is it from Qt?

**Comment by hatstand** [comment]
It's from Qt

**Comment by fitojb** [comment]
Then, I guess this is an upstream issue…
