### ISSUE TITLE
Cmd-Q doesn't quit Clementine on Mac OS X

### ISSUE THREAD

**Issue by Guilz** [clementine-player/Clementine#4708]
When Clementine is open, the "Clementine" menu offers a "Quit" option with keybord shortcut Cmd-Q (as any decent application running on Mac OS X).
But typing the shortcut puts focus in Clementine's search bar instead of quitting the application as expected.

Fixing this would nicely enhance integration with the OS. :-)

**Comment by nigels-com** [comment]
Works for me with Clementine 1.2.2 on OS X 10.9.5.
Anything special about your setup?

**Comment by Guilz** [comment]
No special setup that I'm aware of. I use Mac OS X 10.10.1 but this presumed bug also happened under 10.9.x if I recall well (and also under 10.10).
I just tried to reinstall Clementine (although keeping config files in place) and it still happens.

**Comment by gerdgoebel** [comment]
I just tried Cmd-Q on my MBP 10.9.5 with Clementine 1.2.3-964 and it closed without a problem.

**Comment by ArnaudBienner** [comment]
If I'm right, this bug will happen only for people using non QWERTY keyboard (at least that was the case for me).
I fixed this.

**Comment by Guilz** [comment]
I'm using an AZERTY keyboard indeed, it simply didn't appear to me as a "special setup".
Thank you for this fix. :-)
