### ISSUE TITLE
Cannot stop playing when playlist repeat is on an all tracks are missing.

### ISSUE THREAD

**Issue by mtomeczek** [clementine-player/Clementine#4713]
When playlist contains only invalid tracks, and repeat mode is "Repeat playlist" then it is impossible to stop playing. Only way to stop it is to close Clementine process or add one track to playlist.
With all tracks invalid UI don't activate STOP button.

To duplicate:
1. copy tracks to new folder
2. add tracks from folder to new playlist
3. rename|delete folder with tracks
4. change replay mode to "Playlist"
5. start playing.

Version: Clementine 1.2+dfsg-2build1 Mint 17.1 x64

Best regards - Michal T.

![zrzut ekranu z 2015-01-16 11 56 10](https://cloud.githubusercontent.com/assets/7336221/5775174/f06ee494-9d76-11e4-8c08-2a602129e04e.png)

**Comment by Ferroin** [comment]
I can confirm that this the case on both  x86_64 Linux, and 64-bit Windows 8.1.

**Comment by ArnaudBienner** [comment]
I thought someone fixed this some time ago... which version are you using?
Maybe you can try one of the developer builds which include latest modifications? (they are unstable) builds.clementine-player.org/

**Comment by Ferroin** [comment]
I just looked, I actually have an old version on both the systems I tested it on, which might explain why I had it happen.

**Comment by mtomeczek** [comment]
Applies to outdated version of Clementine, but  I've no chance to check it with recent version.
