### ISSUE TITLE
Can't rate song in Ubuntu 14.04

### ISSUE THREAD

**Issue by tthanh** [clementine-player/Clementine#4717]
I'm using clementine in ubuntu 14.04. I can't rate the song by edit track information. I set permission 755, 775 and 777 for track but always no change after save information.

**Comment by ArnaudBienner** [comment]
What do you mean "no change after save information"? The new rating isn't visible in the edit dialog? Or you don't see the rating when opening the file with another software?
If it is the latter: rating aren't saved to file by default, but kept in a separate database file used by Clementine (there is a preference to change this).

**Comment by tthanh** [comment]
New rating didn't visible in edit dialog. I show rate column in clementine but same as in dialog, no rate at all.

**Comment by tthanh** [comment]
![screenshot from 2015-01-20 08 45 41](https://cloud.githubusercontent.com/assets/8962973/5813050/55afc73a-a0a9-11e4-9669-8cfe71c9abd8.png)

**Comment by ArnaudBienner** [comment]
You can only rate songs that are part of your library.
From what I can see, your library is empty currently.
