### ISSUE TITLE
internet/vk

### ISSUE THREAD

**Issue by stsouko** [clementine-player/Clementine#4718]
caching functions create broken files with size ~160 bytes.
i dunno how to create pull req. 

this code is fix for existing broken files in cache.

bool VkMusicCache::InCache(const QUrl& url) {
  if (QFile::exists(CachedFilename(url))){
    QFile file;
    file.setFileName(CachedFilename(url)); 
    if (file.size() > 1000){
      return true;
    }
    file.remove();
    return false;
  }
  return false;
}

**Comment by ivan-leontiev** [comment]
Can you provide more information about this issue. What steps will reproduce this?

**Comment by stsouko** [comment]
i just add track and listen.
and then i try to repeat this track, in some times raise gstreamer exception .
in cache track file has size 160 bytes.
then i delete it, player recaching track.

p.s.
i listen track completely.

**Comment by ivan-leontiev** [comment]
I can't reproduce this. I've checked it with Clementine 1.2.3-964-gc96502e on Archlinux x86_64 and on windows 8.1 x86. Also I've looked through my vkcache for the last two months and there are no file of strange size.

**Comment by stsouko** [comment]
I was build clementine in november. I don't remember a day.
but. I don't see in project history any fixes of internet/vk. and I don't know why problem arise only in my pc.
I use ubuntu 14.04.
