### ISSUE TITLE
Server doesn't support seeking issue

### ISSUE THREAD

**Issue by maxrd2** [clementine-player/Clementine#4730]
This happens when playing audio from stream that doesn't support seeking.
If you pause playback for several minutes and the hit play, clementine plays buffered audio, throws error 'Server doesn't support seeking' and skips to next track.
Can you change it so that in this case it restarts playing same track instead of skipping to next one?
If you prefer can look into it myself and submit patch.

**Comment by gaga9999** [comment]
This also happens at **network outages** or **network changes**. Clementine just skips to the next item in the playlist. For webradios it would be nice to have a repeat-counter and/or duration, as i.e. I have some network hickups from time to time. or is there already a way to do so? thx!

**Comment by gordon-morehouse** [comment]
#5116 duplicates this, but that issue is more popular and may have more information than this one.
