### ISSUE TITLE
Extremely high memory consumption by Clementine Player when Clementine Remote is on

### ISSUE THREAD

**Issue by DmitryNikonov** [clementine-player/Clementine#4737]
Hello.
I noticed that sometimes Clementine Player (running on my laptop) consumes a lot (up to 3GiB or even more, seems like leak) of memory when I'm using Clementine Remote app on my Android phone.

Running Clementine on ArchLinux (1.2.3, the latest version from official repo) with stock 3.18.2 kernel and the latest version of Clementine remote (10.1) on Android 5.0.1.

Will provide any additional information if needed.

**Comment by rdsqc22** [comment]
I have the same issue, it's definitely a leak, it just expands to fill all available memory. It got to 15gb usage a couple times before I noticed.

**Comment by Chocobozzz** [comment]
Can you try with the git version to confirm the bug is still present ?

**Comment by DmitryNikonov** [comment]
Sure.
I will check it as soon as possible.

**Comment by DmitryNikonov** [comment]
Well, I tried the git build for a while but couldn't reproduce it so far.

**Comment by Asfaloth** [comment]
Closed with commit aba0517b4cae5f2cd7aa8ac7ea0607167333f833
