### ISSUE TITLE
Make mood files hidden in NTFS

### ISSUE THREAD

**Issue by Yanpas** [clementine-player/Clementine#4741]
Win explorer shows files starting with dot by default. Add to mood files attribute Hidden. System command: ATTRIB +H

**Comment by santigl** [comment]
How about adding these lines to function `MoodbarLoader::RequestFinished` (defined in **src/moodbar/moodbarloader.cpp**) after the write to `mood_filename`?

```C++
#ifdef Q_OS_WIN32
        if (!SetFileAttributes((LPCTSTR)mood_filename.utf16(),
                               FILE_ATTRIBUTE_HIDDEN)) {
          qLog(Warning) << "Error changing hidden attribute for file"
                        << mood_filename;
        }
#endif
```
I can't test it on Windows, but if someone confirms it works I can send the patch.

**Comment by Chocobozzz** [comment]
@santigl You can make a pull request :)

**Comment by Yanpas** [comment]
I can test it on windows

**Comment by narunlifescience** [comment]
@hatstand I think this issue should be closed..
