### ISSUE TITLE
Spotify-blob crashes

### ISSUE THREAD

**Issue by Diftraku** [clementine-player/Clementine#4745]
When starting Clementine, the clementine-spotifyblob.exe crashes after a few seconds. This occurs again when trying to play a song from Spotify.

Giving a quick look, the blob crashes while it is populating playlists on startup.

Gist of crash errors and verbose log taken with the debug release of Clementine: https://gist.github.com/Diftraku/adada3d96b698146b760

Tested with latest stable (1.2) and latest (at the time) nightly build (1.2.3-999-gfca6214), both release and debug versions.
OS: Win8.1 Pro x64 (Version 6.3, build 9600)

**Comment by Asfaloth** [comment]
Please try the newest version. I fixed a Spotify releated bug.

**Comment by Diftraku** [comment]
I removed two extremely large playlists (upwards of 2k songs), this may be an issue with the way SpotifyBlob enumerates the playlists, especially the larger ones. Streaming now works as the playlists are successfully enumerated.

**Comment by Asfaloth** [comment]
Okay, then I close this one.
