### ISSUE TITLE
"Artist" tag cannot be modified if other tags are set

### ISSUE THREAD

**Issue by rfgiusti** [clementine-player/Clementine#4747]
If the "Performer" or "Album Artist" tags are manually defined, further attempts to modify the "Artist" tag are inneffective. Still, the interface behave as if the tag had been modified: the tag field is displayed in bold and no error messages are shown when the user clicks the save button.

Steps to reproduce:

- add music file to playlist
- edit track information
- set a value for "Album Artist"
- save
- edit track information
- set a value for "Artist"
- save

Expected result: the "Artist" tag is modified
Obtained result: the "Aritst" tag remains a copy of the "Performer" tag

**Comment by Chocobozzz** [comment]
Which version of Clementine do you use ?

**Comment by rfgiusti** [comment]
1.2.3

From Debian repos: clementine-1.2.3+dfsg-2+b1

**Comment by Chocobozzz** [comment]
Can you try to reproduce with the latest build ? http://builds.clementine-player.org/

**Comment by rfgiusti** [comment]
Now I can modify the "Artist" tag, but the "Performer" tag is always blank.

Comprehensively:

**clementine-1.2.3+dfsg-2+b1**

- When you first enter the "Artist" tag in a file that has no tags, it seems to modify both the "Artist" and the "Performer" tag
- Further editions to the file ignore the "Artist" tag

**latest build (clementine_1.2.3-1019-g18f8a74~jessie_amd64.deb)**

- Accept changes to the "Artist" tag
- Does not show value for "Performer"
- Modifying the "Performer" tag and saving causes no effect
