### ISSUE TITLE
[podcast] Unable to parse date: Mon, 14 July 2008 20:00:00 +0200

### ISSUE THREAD

**Issue by cgiess** [clementine-player/Clementine#4760]
The date in some rss feeds can not be parsed.  An example is http://archiv.ulm.ccc.de/feeds/cs_mp3.xml

Reason: the month name in `<pubDate>` is not abbreviated to 3 letters as described in RFC 822 but fully written.

The follwoing fix will accept bot, an abbreviated an fully written month name:
```
diff --git a/src/core/utilities.cpp b/src/core/utilities.cpp
index 78e24e8..377d65d 100644
--- a/src/core/utilities.cpp
+++ b/src/core/utilities.cpp
@@ -580,7 +580,7 @@ QDateTime ParseRFC822DateTime(const QString& text) {
   if (ret.isValid()) return ret;
   // Because http://feeds.feedburner.com/reasonabledoubts/Msxh?format=xml
   QRegExp re2(
-      "(\\d{1,2}) ([a-zA-Z]{3}) (\\d{4}) "
+      "(\\d{1,2}) ([a-zA-Z]{3})[^ ]* (\\d{4}) "
       "(\\d{1,2}):(\\d{1,2}):(\\d{1,2})");
 
   QMap<QString, int> monthmap;
```

**Comment by sobkas** [comment]
I have had enough with staring at this cancer that QRegExp is, time to cut it out

**Comment by cgiess** [comment]
Thank you for addressing this issue.
However, I am a little bit disappointed about your judgement of the code. IMHO the code was really easy to understand and the use of regular expressions appropriate for that purpose.
Learning regular expressions instead of making the intend of the code unclear would have been bette :( (Just 2 cents of an old man who has seen a lot of bad code in the last decades and was really happy when he looked at Clementine).

**Comment by sobkas** [comment]
I have nothing against regexp but I have everything against QRegExp, I would really like to use  QRegularExpression but until clementine moves to qt5 it's not an option

but if I will be able to produce single regexp to cover all cases in test I will consider going back to QRegExp

**Comment by sobkas** [comment]
Found one, will be moving back to regexp

**Comment by sobkas** [comment]
@cgiess thanks for an advice, I hope code now looks a bit better
