### ISSUE TITLE
Hide sidebar tabs

### ISSUE THREAD

**Issue by olmokramer** [clementine-player/Clementine#4767]
I basically only use the "Library" tab, so I would like to hide the tabbar in the sidebar altogether. Is this possible?

**Comment by ArnaudBienner** [comment]
You can move the side bar sections to the top: right click on the side bar and select one of the option (probably "Icon on top" would be great for you). This will save you lot of space (I guess this is what you are looking for).

**Comment by olmokramer** [comment]
No, I already have them at the top. It's that I keep accidentally scrolling the tabs when I want to scroll through my library, which switches the tabs

**Comment by ArnaudBienner** [comment]
OK then.
It seems there is already a feature request opened about this: #1559

**Comment by olmokramer** [comment]
Ah my bad. Didn't search good enough. Thanks!
