### ISSUE TITLE
mp3 playback on a fresh ubuntu install ends most ungracefully

### ISSUE THREAD

**Issue by Clementine-Issue-Importer** [clementine-player/Clementine#477]
_From [himynameiszacHandiamapirate](https://code.google.com/u/116275170679458301339/) on July 03, 2010 18:57:58_

What steps will reproduce the problem? 1. install ubuntu fresh
2. install clementine (I did through source, using only the packages suggested in the wiki)
3. add an mp3 to your playlist and double click it What is the expected output? What do you see instead? Well, in a perfect world, it would just PLAY. In an ubuntu world, it would ideally tell me nicely that I need more plugins to play this file back, and offer to search for those plugins. I was able to get totem (shudder) to display such messages, and plugins were promptly installed (see pictures below). In clementine, however, the program just segfaults. Terminal output is thus (might have some lines that aren't related):
virtual void GnomeGlobalShortcutBackend::DoUnregister() 
virtual bool GnomeGlobalShortcutBackend::DoRegister() 
"gstdecodebin2.c(2944): gst_decode_bin_expose (): /GstPipeline:pipeline/GstURIDecodeBin:uridecodebin/GstDecodeBin2:decodebin20:
no suitable plugins found" 
Gstreamer error: "Your GStreamer installation is missing a plug-in." 
QTimeLine::start: already running
Segmentation fault

Would it be possible to implement something graceful? We don't necessarily have to go out of our way and install the plugins ourselves, but it should at least not crash, and ideally also pop up a helpful dialog. What version of the product are you using? On what operating system? r1410 on ubuntu lucid (yep, all upgraded)

**Attachment:** [Screenshot-Search for suitable plugin.png Screenshot-Install Multimedia Plugins.png Screenshot-Untitled Window.png](http://code.google.com/p/clementine-player/issues/detail?id=477)

_Original issue: http://code.google.com/p/clementine-player/issues/detail?id=477_

**Comment by Chocobozzz** [comment]
Closing this old issue. Feel free to ask for reopening it.
