### ISSUE TITLE
Can't play stream with domain name in url

### ISSUE THREAD

**Issue by fenuks** [clementine-player/Clementine#4775]
I noticed that Clementine (version 1.2.3 and build from git) can't play stream if it's url have domain name instead direct IP address.
For example, Radio Paradise have stream at http://stream-dc1.radioparadise.com/rp_96m.ogg and Clementine won't play this, but if I change url to http://174.36.251.136/rp_96m.ogg then stream is played. Also it is worth to note that, Clementine handle playlists even if stream urls have domain names.

**Comment by sobkas** [comment]
Can you write something about your os? I can't reproduce your problem on linux debian 64bit.
Also running clementine --verbose and posting it here should give me some info. Thanks.

**Comment by fenuks** [comment]
Sorry, my bad I forgot to write about disto. I use Arch x86_64, running `clementine --verbose` has no additional effect (no error messages in terminal, only usual libpng profile warnings). Clementine shows gui warning: `Error loading http://stream-dc1.radioparadise.com/rp_96m.ogg`.

**Comment by Chocobozzz** [comment]
I can play your URL on ArchLinux with the latest build. Maybe it is a problem with your DNS ?

**Comment by fenuks** [comment]
I suspected my DNS, but since the same streams imported from playlist were successfully played I thought it was rather Clementine bug. After your comment I changed my DNS server and it works. Thank you and sorry for false alarm.
