### ISSUE TITLE
Make application icon 128x128

### ISSUE THREAD

**Issue by ndzou** [clementine-player/Clementine#4777]
I noticed the default application icon (under data/icon.png) is 64x64.  Even though higher resolution ones can be produced from the SVG.  This creates a slightly inconsistent look under KDE using the kwin large icon alt-tab switcher since most other system apps use 128x128, the screenshot below illustrate this inconsistency:

![clementine-icon](https://cloud.githubusercontent.com/assets/3036958/6630536/9bbdf266-c8df-11e4-9b57-05fab2fcd130.png)

Recommendation: replace data/icon.png with a 128x128 version.

I've produced one from the SVG and attached it below, it has not been pngcrunch'd.

![clementine_128](https://cloud.githubusercontent.com/assets/3036958/6630622/a325f232-c8e0-11e4-8f5b-53b991cb7fc7.png)

More notes about icons, the installed icon name /usr/share/icons/hicolor/64x64/apps/application-x-clementine.png does not follow Freedesktop.org specifications:

http://standards.freedesktop.org/icon-naming-spec/latest/ar01s03.html

It should simply be clementine.png, same for the svg version under /usr/share/icons/hicolor/scalable/apps.

**Comment by Chocobozzz** [comment]
Thanks :)
