### ISSUE TITLE
Random palying

### ISSUE THREAD

**Issue by Lubchak** [clementine-player/Clementine#4793]
I think Clementine need random playing function without shuffling.

**Comment by ArnaudBienner** [comment]
I don't get what you mean: in Clementine, you can already shuffle songs while playing, or shuffle a playlist so songs will be reordered randomly. How is "random playing" something different?

**Comment by Lubchak** [comment]
For example, I have list with few artist albums.
Artist_A
    1.a
    2.b
    3.c
Artist_B
    1.a
    2.b
    3.c

And i want that playlist doesn't shuffle, but tracks play: Artist_A.a -> Artist_B.c -> ....

**Comment by selumin** [comment]
There is a button on the left side from track's progress bar with such function. 
![image](https://cloud.githubusercontent.com/assets/1284882/6998534/029c3724-dbee-11e4-853c-894dd065acd2.png)

**Comment by Lubchak** [comment]
Thanks. Works. Sorry for the trouble.
