### ISSUE TITLE
Feature: sync rating with musicbrainz's rating API

### ISSUE THREAD

**Issue by p2kmgcl** [clementine-player/Clementine#4815]
I've looking for a way of storing my ratings online (just for the case my library get's broken) and I saw that musicbrainz does have API methods for sending music ratings:

```
wget --user=<editor name> --password=<password> --post-data=id=8f6bd1e4-fbe1-4f50-aa9b-94c450ec0f11\&entity=artist\&rating=3
```

It's done by simple `GET` and `POST` requests, so I guess if clementine could sync this ratings with songs that already have a mbid.

**Comment by ArnaudBienner** [comment]
Could you please provide more details on this works? I guess you need to have an account somehow to be sure those tags are "your tags". I think they should have a documentation about this?

**Comment by p2kmgcl** [comment]
Sorry for taking so long to reply, but I'm quite busy now. Here you have the documentation I found in musizbrainz. I promise I'll bring a more detailed example as soon as I can (maybe in two weeks).

https://musicbrainz.org/doc/Development/XML_Web_Service/Version_2#ratings
https://wiki.musicbrainz.org/Development/JSON_Web_Service

The JSON web service is much less documented, but I think it has the same behaviour. Thank you for being interested in my idea.
