### ISSUE TITLE
Error trying to install Clementine on Raspberry pi

### ISSUE THREAD

**Issue by JairLeBentz** [clementine-player/Clementine#4820]
Hi 
Iam trying to install Clementine on Raspberry pi 2 with raspbian.
I have done all like you said but when I go to 
 cmake ..
I get that at the end: 
The following components WILL NOT be built:
   Crash reporting (disabled in CMake config)
   Sparkle integration (missing Mac OS X, Sparkle)
   Spotify support: non-GPL binary helper (missing libspotify)

CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
ECHONEST_INCLUDE_DIRS
   used as include directory in directory /home/pi/Clementine/src
   used as include directory in directory /home/pi/Clementine/src
ECHONEST_LIBRARIES
    linked by target "clementine_lib" in directory /home/pi/Clementine/src

-- Configuring incomplete, errors occurred!

And when I try: make -j2
I get that:
make: *** No targets specified and no makefile found.  Stop.
How can I go forward?
thanks a lot!
Jairo

**Comment by Chocobozzz** [comment]
You need to install libechonest-dev.

**Comment by JairLeBentz** [comment]
Thank you! it really works. Clementine is now compiled but I can't open it.
Intruction said I must star clementine with:  ./clementine
But I become this:
bash: ./clementine: No such file or directory

**Comment by Chocobozzz** [comment]
It should be in the bin/ directory. If it isn't, this surely means the compilation failed.

**Comment by JairLeBentz** [comment]
I fount it.
Thanks!!

**Comment by thegreyshadow** [comment]
I honestly think echonet should not be a hard dependency. Could you make it a compile-time option please?
