### ISSUE TITLE
Can't install on Xubuntu 15.04 because of missing libprotobuf8

### ISSUE THREAD

**Issue by marcelpaulo** [clementine-player/Clementine#4827]
I've just upgrade Xubuntu on my laptop to 15.04, and can't install clementine from:

```
deb http://ppa.launchpad.net/me-davidsansome/clementine-dev/ubuntu utopic main
```

because it depends on `libprotobuf8`, which is not available in the repositories:

```
paulo@monk:~$ sudo apt-get install clementine
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 clementine : Depends: libprotobuf8 but it is not installable
E: Unable to correct problems, you have held broken packages.
```

I get the impression that `libprotobuf8` has been replaced by `libprotobuf9` in Vivid 15.04:

```
paulo@monk:~$ apt-cache -n search libprotobuf
libprotobuf-dev - protocol buffers C++ library (development files)
libprotobuf-lite9 - protocol buffers C++ library (lite version)
libprotobuf9 - protocol buffers C++ library
libprotobuf-c-dev - Protocol Buffers C static library and headers (protobuf-c)
libprotobuf-c1 - Protocol Buffers C shared library (protobuf-c)
libprotobuf-c1-dbg - Protocol Buffers C shared library debug symbols (protobuf-c)
libprotobuf-java - Java bindings for protocol buffers
```

**Comment by marcelpaulo** [comment]
As a workaround:

1. Created `/etc/apt/sources.list.d/utopic.list` with all utopic repositories
2. Refreshed the apt cache
3. Installed clementine

This way, apt-get pulls `libprotobuf8` from utopic.

**Comment by polsVoice** [comment]
Is there a way to do this that does *not* involve having to pull in all the Utopic repositories? Could I just recompile Clementine with libprotobuf.so.9.0.1 instead of libprotobuf.so.8?

**Comment by marcelpaulo** [comment]
I should have mentioned: after I installed Clementine, I commented out all Utopic deb sources, so that no other packages might perchance be pulled from Utopic.

**Comment by polsVoice** [comment]
It just seems like there should be a better way than downgrading.

**Comment by hatstand** [comment]
Vivid PPA exists now

**Comment by marcelpaulo** [comment]
This is great news, @hatstand, thank you so much. I'll update my install instructions.
