### ISSUE TITLE
Lololyrics support?

### ISSUE THREAD

**Issue by Tatsh** [clementine-player/Clementine#4843]
I have no issue starting work on this and creating a PR but I wanted to know if there is any interest from users. Lololyrics is particularly good because it has a lot of UK hardcore song lyrics (typically referred to as *happy hardcore*).

API is relatively simple: http://api.lololyrics.com/

**Comment by Chocobozzz** [comment]
There is lololyrics support in the unstable builds (see https://github.com/clementine-player/Clementine/pull/4475)

**Comment by Tatsh** [comment]
Okay, closing
