### ISSUE TITLE
Errors compiling in Ubuntu Studio 15.4

### ISSUE THREAD

**Issue by Vrak** [clementine-player/Clementine#4848]
vrak@crystal:~/Clementine-1.2.3/bin$ cmake -DCMAKE_BUILD_TYPE=Debug ../
-- Found Qt4: /usr/bin/qmake (found suitable version "4.8.6", minimum required is "4.5.0") 
-- Found Qt4: /usr/bin/qmake (found version "4.8.6") 
-- Boost version: 1.55.0
-- checking for module 'indicate-qt'
--   package 'indicate-qt' not found
-- checking for module 'libmygpo-qt>=1.0.7'
--   package 'libmygpo-qt>=1.0.7' not found
-- checking for module 'qca2'
--   package 'qca2' not found
-- checking for module 'libspotify>=12.1.45'
--   package 'libspotify>=12.1.45' not found
CMake Error at CMakeLists.txt:260 (message):
  Either QCA must be available or the non-GPL Spotify code must be compiled
  in

-- Configuring incomplete, errors occurred!
See also "/home/vrak/Clementine-1.2.3/bin/CMakeFiles/CMakeOutput.log".
See also "/home/vrak/Clementine-1.2.3/bin/CMakeFiles/CMakeError.log".

**Comment by sobkas** [comment]
You need to install libqca2-dev(debian) or qca-devel(fedora) depending on the distribution you use.
