### ISSUE TITLE
Error with "make" (Ubuntu Studio 15.4)

### ISSUE THREAD

**Issue by Vrak** [clementine-player/Clementine#4849]
vrak@crystal:~/Clementine-1.2.3/bin$ make
[  2%] Built target Renderer
[  3%] Built target MilkdropPresetFactory
[  4%] Built target projectM
[  4%] Built target sqlite
[  4%] Built target qsqlite
[  4%] Built target qtsingleapplication
[  5%] Built target qtiocompressor
[  6%] Built target qxt
[  6%] Built target sha2
[ 11%] Built target mygpo-qt
[ 11%] Built target Qocoa
[ 12%] Built target gstmoodbar
[ 13%] Built target libclementine-common
[ 14%] Built target libclementine-tagreader
[ 14%] Built target libclementine-remote
[ 14%] Built target clementine-spotifyblob-messages
[ 14%] Generating qrc_translations.cxx
Scanning dependencies of target clementine_lib
[ 14%] Building CXX object src/CMakeFiles/clementine_lib.dir/devices/devicekitlister.cpp.o
In file included from /home/vrak/Clementine-1.2.3/src/devices/devicekitlister.cpp:24:0:
/home/vrak/Clementine-1.2.3/bin/src/dbus/udisksdevice.h:792:22: error: ‘namespace org::freedesktop::UDisks { }’ redeclared as different kind of symbol
     namespace UDisks {
                      ^
In file included from /home/vrak/Clementine-1.2.3/src/devices/devicekitlister.cpp:23:0:
/home/vrak/Clementine-1.2.3/bin/src/dbus/udisks.h:235:45: note: previous declaration ‘typedef class OrgFreedesktopUDisksInterface org::freedesktop::UDisks’
     typedef ::OrgFreedesktopUDisksInterface UDisks;
                                             ^
cc1plus: error: unrecognized command line option "-Wno-unknown-warning-option" [-Werror]
cc1plus: error: unrecognized command line option "-Wno-unused-private-field" [-Werror]
cc1plus: all warnings being treated as errors
src/CMakeFiles/clementine_lib.dir/build.make:11934: recipe for target 'src/CMakeFiles/clementine_lib.dir/devices/devicekitlister.cpp.o' failed
make[2]: *** [src/CMakeFiles/clementine_lib.dir/devices/devicekitlister.cpp.o] Error 1
CMakeFiles/Makefile2:775: recipe for target 'src/CMakeFiles/clementine_lib.dir/all' failed
make[1]: *** [src/CMakeFiles/clementine_lib.dir/all] Error 2
Makefile:117: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Chocobozzz** [comment]
Do you try to build the make version ?
