### ISSUE TITLE
[Feature Request] Export and Import Smart Playlists

### ISSUE THREAD

**Issue by jfenske89** [clementine-player/Clementine#4852]
# Summary

Requesting the ability to export and import smart playlist definitions across all devices using Clementine. This feature should function between the Linux and Windows version of the application.
# Details

For users that have Clementine on multiple devices, it would be very useful to be able to export smart playlists, and import them on another device. Right now, the smart playlists need to be created and updated by hand. It can be time consuming if users have complex rules in the smart playlist.

**Comment by james3mc** [comment]
Oh yes please. Love Clemy but hate having to recreate my complex smart playlists.

**Comment by akovia** [comment]
I think this would be a nice feature for simplicity, but you can copy all the songs from a smart playlist to a new playlist and export/save that instead.

**Comment by james3mc** [comment]
Yes but you'd then have a 'playlist' not a 'smart playlist'. What we want is a method of exporting or copying to another device, the smart playlist rules.
