### ISSUE TITLE
Clementine not playing from Ampache + Subsonic API

### ISSUE THREAD

**Issue by bhcopeland** [clementine-player/Clementine#4854]
bug https://github.com/clementine-player/Clementine/issues/1059 was closed due to using the Subsonic API

I have setup the API, I can connect and fetch my media, but when I try and play tracks it just skips them. 

I have tried the ampache subsonic API on other subsonic apps (Dsub on mobile) and it works fine.

[15/May/2015:14:27:57 +0100] "GET /ampache/rest/stream.view?v=1.8.0&c=Clementine&u=bhcopeland&p=xxxxxxx&id=24512 HTTP/1.1" 200 5 "-" "Clementine 1.2.3" "-"

**Comment by Chocobozzz** [comment]
Please try with the latest build http://buildbot.clementine-player.org/

**Comment by bhcopeland** [comment]
Thanks.

Installed it from yaourt (https://aur.archlinux.org/packages/clementine-git/) and it is now working.
