### ISSUE TITLE
search just searches for prefixes

### ISSUE THREAD

**Issue by cornicis** [clementine-player/Clementine#4855]
Searching in library view doesn't allow arbitrary subwords to be sought.

This makes up paradoxes like returning nothing for "hell bastard" but getting the correct result for "hellbastard".
Nevertheless, it works well when the subword is prefixed by a space character.

**Comment by hatstand** [comment]
You can actually use the full FTS3 syntax described here: https://sqlite.org/fts3.html#section_3

**Comment by cornicis** [comment]
You're right, it is possible to search for arbitrary subwords with this syntax, nevertheless my given scenario should return results in both cases.

But I'm aware of this being some kind of nitpicking and don't mind the issue being dropped due to low priority.
