### ISSUE TITLE
Add support for Google Play Music

### ISSUE THREAD

**Issue by igorsantos07** [clementine-player/Clementine#4871]
As we are now able to upload thousands of music files into Google Play Music cloud, would be cool to be able to play those from Clementine, leveraging all it's indexing / additional info abilities :)

Google Drive sync does not touch Play files, unfortunately. Not sure if they're even related, actually.

**Comment by ArnaudBienner** [comment]
Duplicate of #2204

**Comment by igorsantos07** [comment]
Sorry! I haven't seen that; I was searching the issues for "Google Play" or "Play Music" lol
