### ISSUE TITLE
Artist tag in play queue reads from Performer tag

### ISSUE THREAD

**Issue by danner** [clementine-player/Clementine#4876]
To reproduce:
1. Add a track to the play queue. 
2. Right click track, Edit Track Information.
3. Change the Artist to "Fred", and the Performer to "Billy"
4. Save the track info
5. Review Artist tag in play queue.

It looks like editing the performer tag saves to both the artist and performer tag, writing to the artist tag does nothing, and artist and performer headers display the performer tag.

**Comment by Chocobozzz** [comment]
Did you try with the latest build of Clementine ?

**Comment by danner** [comment]
nope, I was on Version 1.2.2, it works fine on Version 1.2.3-1163-g3f536d2

Derp. I'll close this and run closer to edge from now on.
