### ISSUE TITLE
Add Nightly builds for Fedora 22

### ISSUE THREAD

**Issue by yafp** [clementine-player/Clementine#4892]
There are no nightly builds available on http://builds.clementine-player.org/ for Fedora 22

Right now:
* Fedora 23 = Future release
* Fedora 22 = current
* Fedora 21 = Older version, still supported
* Fedora 20 = Older version, still supported (end of life is near 2015-06-23)

**Comment by hatstand** [comment]
http://builds.clementine-player.org/fedora-22/

**Comment by yafp** [comment]
Big thanks to the team - i'll report back if i notice something.
