### ISSUE TITLE
Library update stuck

### ISSUE THREAD

**Issue by Letheed** [clementine-player/Clementine#4895]
After being up for some time, Clementine displays "Updating library 0%" forever.

* I can still play music although covers aren't loaded anymore (neither for the playing track nor the albums in the library).
* I haven't noticed anything wrong with the CPU usage or the memory footprint, nor does sysmonitor say anything wrong about clementine or the tag reader's state.
* The process won't die, I have to kill it. (It stops playing, the GUI goes away, it displays a notification, and the icon tray disappears, but the process and the tagreaders are still there).

I'm using the latest version from ppa:me-davidsansome/clementine-dev.
Log: http://pastebin.com/YJ8TVUNT

**Comment by Letheed** [comment]
Closing since the issue is gone. I'm not sure what solved it, since I had had that problem for weeks before. Could be an unrelated clementine commit. I also added the kubuntu backports ppa to my sources recently; could be that.

**Comment by jerobarraco** [comment]
I still have this problem. And i has it since a long time now.

**Comment by Letheed** [comment]
@jerobarraco Well the issue has not happened to me again since, so I'm not sure if this should be reopened. You should specify exactly what's happening, the version of Clementine you're using, your distribution, the steps you've taken to try and solve it, etc. Make sure you're using the latest version in case it's been solved. You could try deleting the lib folders in Clementine config, removing the databases in .config/Clementine (keeping only the .conf file) in case it's been corrupted and adding your music folder again. Something solved it for me I'm just not sure what :)

**Comment by jerobarraco** [comment]
is actually bug #3064 https://github.com/clementine-player/Clementine/issues/3064

**Comment by calltheninja** [comment]
I found a fix for this after googling for a while and not finding this suggestion. My suspicion was that Clementine was choking on some file it couldn't access or do something important with. I tried disabling "update library" etc. This is on Ubuntu 14.04 x64 with Clementine 1.3.1. Here's the fix that worked for me:

1. Fix permissions on all local music files
I just did the command below to make sure any user/program on the system could access the files:
sudo chmod -R 777 /directory/to/music

2. Fix weird filenames, UTF-8 characters, etc
Install the package "detox" from the Ubuntu repos or download it from the link below:
https://sourceforge.net/projects/detox/files/detox/
Run the command:
detox -r /path/to/music
You can add a -n to see what it would change (dry run).

3. Restart clementine
Kill clementine completely and open it again.

This got it working for me, hopefully it works for you!

**Comment by alysson-azevedo** [comment]
Often also see the library updating getting stuck, even when i don't change anything in my music files. 
But just now i was fixing some id3tags of my music files and went to update my library on clementine and it was stucked again. I restarted the clementine and run the full scan. it run correctly and everything.

So, if the problem was permissions, it would stuck again after restarting the clementine.
Does clementine uses inotify to track changes in files? What if it is exceeding the max_user_watches?

**Comment by mxdpeep** [comment]
I have detoxed all my MP3s, still the bug is present (Ubuntu 14.04)

**Comment by jerobarraco** [comment]
this issue is closed, 
this is actually bug #3064 , i suggest you report that there.
