### ISSUE TITLE
connection to   data.clementine-player.org:80? 

### ISSUE THREAD

**Issue by gerroon** [clementine-player/Clementine#4898]
Hi

I am not sure why Clementine tries to connect to the website mentioned above during startup. Mostlikely case is to check for a new version but the thing is that I am on Debian and I see no where to disable auto check.  I am not sure if this is packagers fault or not.

I also do not have any online service enabled.

In any case it would be nice if this connection is disclosed.

11:54:39.124 DEBUG InternetModel:126                Adding internet service: "Radio GFM" 
11:54:39.125 INFO  Player:579                       Registered URL handler for "rockradio" 
11:54:39.125 DEBUG InternetModel:126                Adding internet service: "RockRadio" 
11:54:39.128 DEBUG InternetModel:126                Adding internet service: "SavedRadio" 
11:54:39.128 INFO  Player:579                       Registered URL handler for "sky" 
11:54:39.128 DEBUG InternetModel:126                Adding internet service: "SKY.fm" 
11:54:39.129 INFO  Player:579                       Registered URL handler for "somafm" 
11:54:39.129 DEBUG InternetModel:126                Adding internet service: "SomaFM" 
11:54:39.130 DEBUG InternetModel:126                Adding internet service: "SoundCloud" 
11:54:39.131 DEBUG SpotifyService:79                Spotify system blob path: "/usr/bin/clementine-spotifyblob" 
11:54:39.131 DEBUG SpotifyService:80                Spotify local blob path: "/home/xxx/.config/Clementine/spotifyblob/version14-64bit/blob" 
11:54:39.131 DEBUG InternetModel:126                Adding internet service: "Spotify" 
11:54:39.131 INFO  Player:579                       Registered URL handler for "subsonic" 
11:54:39.154 DEBUG InternetModel:126                Adding internet service: "Subsonic" 
11:54:39.155 INFO  Player:579                       Registered URL handler for "box" 
11:54:39.155 DEBUG InternetModel:126                Adding internet service: "Box" 
11:54:39.156 INFO  Player:579                       Registered URL handler for "dropbox" 
11:54:39.156 DEBUG InternetModel:126                Adding internet service: "Dropbox" 
11:54:39.156 INFO  Player:579                       Registered URL handler for "googledrive" 
11:54:39.156 DEBUG InternetModel:126                Adding internet service: "Google Drive" 
11:54:39.157 INFO  Player:579                       Registered URL handler for "seafile" 
11:54:39.157 DEBUG InternetModel:126                Adding internet service: "Seafile" 
11:54:39.158 INFO  Player:579                       Registered URL handler for "skydrive" 
11:54:39.158 DEBUG InternetModel:126                Adding internet service: "OneDrive" 
11:54:39.159 INFO  Player:579                       Registered URL handler for "vk" 
11:54:39.159 DEBUG InternetModel:126                Adding internet service: "Vk.com" 
11:54:39.161 DEBUG CddaLister:98                    No CD devices found 
11:54:39.161 DEBUG CoverProviders:32                Registered cover provider "last.fm" 
11:54:39.162 DEBUG NetworkProxyFactory:29           Detected system proxy URLs: ("", "", "", "") 
11:54:39.162 DEBUG CoverProviders:32                Registered cover provider "Amazon" 
11:54:39.162 DEBUG CoverProviders:32                Registered cover provider "Discogs" 
11:54:39.162 DEBUG CoverProviders:32                Registered cover provider "MusicBrainz" 
11:54:39.167 WARN  IconLoader:50                    Couldn't load icon "clementine-panel" 
11:54:39.169 WARN  IconLoader:50                    Couldn't load icon "clementine-panel-grey" 
11:54:39.187 WARN  OSD:89                           Error connecting to notifications service. 
11:54:39.188 DEBUG QxtGlobalShortcutBackend:30      registering 
11:54:39.189 WARN  unknown                          QxtGlobalShortcut failed to register: "Media Next"  
11:54:39.189 WARN  unknown                          QxtGlobalShortcut failed to register: "Media Play"  
11:54:39.189 WARN  unknown                          QxtGlobalShortcut failed to register: "Media Previous"  
11:54:39.189 WARN  unknown                          QxtGlobalShortcut failed to register: "Media Stop"  
Strict chain  ...   data.clementine-player.org:80 11:54:39.256 DEBUG MainWindow:201                   Starting 
11:54:39.263 WARN  IconLoader:50                    Couldn't load icon "find" 
11:54:39.265 WARN  IconLoader:50                    Couldn't load icon "find" 
11:54:39.325 DEBUG MainWindow:266                   Initialising player 
11:54:39.334 DEBUG MainWindow:272                   Creating models

**Comment by hatstand** [comment]
It's used for geolocation for the songkick nearby events.

**Comment by gerroon** [comment]
That is fine, but what about the privacy implications? For example I do not use songkick, never heard of it before.

Anyway if this is a geolocation, it should be disclosed. Even browsers have to ask for a geolocation permission.

**Comment by hatstand** [comment]
It's based off your IP address and is only city level - it's pretty meaningless privacy-wise as there are approximately 167 unique requests in Clementine.

**Comment by gerroon** [comment]
Well, meaninglessness can be a relative perspective given that the data connection is done on port 80, it still can be, plus we do not know what is been sent in the pipe. I probably tcpdump this.

Anyway I do not want to bug you guys about this more, I was trying to bring a point of view that is important some people but not maybe all. 

thanks

**Comment by hatstand** [comment]
Even if it were HTTPS, it'd still contain your IP address which is enough data to make the same geolocation anyway.

**Comment by gerroon** [comment]
Sure but but at list the data cannot be accessed by 3rd parties. Assume you are at a cafe  and running Clementine while using their network. And lets presume that the connection is monitored for various reasons. Or the worse you are connected to a poisoned wifi connection (which you probably would not know about it) . Well they do not give a damn the geolocation at that point because they provide the ip themselves but they might have vested interest in skimming through peoples connection data for various reasons. And if Clementine is sending some other info beyond the ip location, they might have interest in them. Pure speculation obviously. If all you sent is the name/code of the city then this speculation is going to be meaningless most likely.
  
So we have 2 issues, one is the actual undisclosed connection related to some 3rd party service and the second is the lack of protection of that data and the content of the data. 

Again I do not want to drag you into this more ;) I am sure you implemented these features with well designed intentions, however as a user it is my job to report the possible side effects from the user perspective.
