### ISSUE TITLE
Tray icon mouse scrolls

### ISSUE THREAD

**Issue by Yanpas** [clementine-player/Clementine#4918]
Banshee has cool feature with their tray icon. If you scroll up over tray icon - banshee plays next track, if scroll down - previous track. I would like to see it in Clementine. Maybe OS X won't support it

**Comment by rodrigorega** [comment]
I would love to have this too. But I think that scroll down must be next track, not previous (Maybe this should be configurable).

Audacious Media Player has this feature too.
