### ISSUE TITLE
[Feature Request] Please add support for minimalistic left-side panel

### ISSUE THREAD

**Issue by Tutanharak** [clementine-player/Clementine#4926]
Hello. Could you please add support for one more style of left-side panel: something like panel using QT-theme colors instead of special background image, while still displaying different sources this way: "http://i.imgur.com/xhLsgre.png"? That would be both functional (unlike all the other options, which sometimes look too small and text is being shortened) and minimalistic. Thank you.

**Comment by ArnaudBienner** [comment]
If I understood what you meant, this is already possible: just right click on the left panel and you can choose another way to display it.

**Comment by Tutanharak** [comment]
Not exactly what I meant. What I would like to have is just the same panel, as on the screenshot (same format of buttons, same text, etc) but without this blue-colored background image. Instead, a background should be solid-color, using default color of qt theme.
Is it possible?
