### ISSUE TITLE
QT5 Branch - Fedora Environment - libechonest

### ISSUE THREAD

**Issue by Silarn** [clementine-player/Clementine#4941]
While trying to build the qt5 branch on my Fedora 22 installation, I discovered a minor incompatibility with the way Fedora is packaging the libechonest-qt5-devel libraries and the way the Clementine qt5 branch currently handles the include directory.

Essentially, Fedora is using the same /usr/include/echonest/ directory to handle both devel packages - both libechonest-devel and libechonest-qt5-devel. Because the qt5 branch searches specifically for an echonest5 directory, the check for ECHONEST5_INCLUDE_DIRS fails, and subsequently several instances of #include <echonest5/somefile.h> also fail.

This is easily fixed locally by updating these references to say echonest instead of echonest5, but a robust build system probably needs to detect Fedora and change the include path. Either that, or a ticket needs to be made in Fedora to change the devel package to use the echonest5 directory.

I'm not sure which solution would be the most correct in this case, if echonest5 is standard with other distros.

**Comment by Chocobozzz** [comment]
Thanks for reporting this. :)
