### ISSUE TITLE
file delete of current playing track fails

### ISSUE THREAD

**Issue by thewriteway** [clementine-player/Clementine#4946]
Hi 

I can't seem to delete the current playing file?

![clementime_error](https://cloud.githubusercontent.com/assets/13290180/8634322/cdb6a35a-27ec-11e5-8b2a-43d4799fb39f.PNG)

possible fix - if it auto moved to the next item in the playlist and then deleted the now unlocked track selected? :)

Many thanks

**Comment by hatstand** [comment]
This is a symptom of Windows being terrible. You get this experience in all apps as you can't delete files that are being used anywhere else in any way.
