### ISSUE TITLE
No longer decoding .m4a files in Clementine 1.2.3 (Ubuntu 15.04)

### ISSUE THREAD

**Issue by neltnerb** [clementine-player/Clementine#4947]
I cannot get Clementine to play .m4a files which previously worked in Ubuntu 15.04 with Clementine 1.2.3 installed. The complaint is that gstreamer is missing the plugin, but installing the -bad plugins no longer fixes the issue.

**Comment by Chocobozzz** [comment]
Don't forget to use 0.10 version with Clementine 1.2.3 and 1.* version of GStreamer with the latest builds of Clementine. Moreover you can try to install gstreamer ffmpeg/libav.

**Comment by algazarra** [comment]
+1

**Comment by davinellulinvega** [comment]
Hello,
I have the same problem on ubuntu 15.10, with the version 1.2.3 of clementine.
The application crashes with a lovely message:
<pre><code>
*** stack smashing detected ***: clementine terminated
Aborted (core dumped)
</code></pre>
I have all the gstreamer 0.10 plugins installed (good, bad and ugly), as well as the ffmpeg  and  gstreamer-libav.

Is there any other information that you might need to tackle this problem?

Sincerely.

**Comment by Chocobozzz** [comment]
Can you try with the latest builds ? buildbot.clementine-player.org

**Comment by davinellulinvega** [comment]
however, when will this build be available in the official repository? (only asking for information purposes no complaining here).

**Comment by fitojb** [comment]
Yeah, when? As a translator there’s been two years of no releases, and that means that my work of that period hasn’t been made available to users.

**Comment by Chocobozzz** [comment]
Closing this after @davinellulinvega said the issue doesn't seem to be in the latest build.

**Comment by DimanNe** [comment]
I am still experiencing this problem. Clementine says "Your GStreamer installation is missing a plug-in.", while attempting to playback m4a file. I am using Ubuntu 15.10. Vlc DOES play it as well as Amarok. But I want to listen to music in Clementine.
Which packages/plugins should be installed in order to play m4a?

**Comment by DimanNe** [comment]
I built 1.3 from git and it seems it works well now.

**Comment by RedSoxFan04** [comment]
In Debian 8.6, I’m still having problems with playing M4A/ALAC files in Clementine. It keeps telling me I’m missing a plugin. I did some research, installed a bunch of plugins, and it still won’t play my ALAC files.

**Comment by AlexandreBonneau** [comment]
In Debian Stretch (stable), you still experience this bug in clementine `1.3.1+git276-g3485bbe43+dfsg-1`.

`m4a` files are now unplayable :'(

**Comment by RedSoxFan04** [comment]
It's been a while. I've been using Banshee lately and I re-encoded all of my CDs in FLAC.
