### ISSUE TITLE
There is no way to close clementine process under windows

### ISSUE THREAD

**Issue by mikelmi** [clementine-player/Clementine#4960]
I cannot kill clementine process. After close clementine player, the still running in background and I cannot stop it neither from task manager nor from cmd. And resources (cpu and memory) are used up to 100%

**Comment by Chocobozzz** [comment]
Did you try with the latest builds ?

**Comment by mikelmi** [comment]
I removed previous version, removed all settings and installed new version (1.2.3)
And it works fine now)

**Comment by mikelmi** [comment]
*UPD*
Same problem has appeared when I added new folder to the Music library
