### ISSUE TITLE
Opus-files with R128-relative (-23db LUFS) playback gain must be played 5db louder to get to ReplayGain reference level of -18db LUFS

### ISSUE THREAD

**Issue by madig** [clementine-player/Clementine#4963]
I noticed while playing around with opusenc and foobar2000's ReplayGain-scanner that the Opus file format has a R128_TRACK_GAIN tag and a build-in "Playback gain" header. It looks like the playback gain is relative to the R128 reference listening level of -23db LUFS, while the typical ReplayGain level is -18db LUFS. The result is that Opus files with these gains are 5db quieter than other ReplayGain-ed tracks. Please preamp such Opus files +5db like Foobar2000 does.

**Comment by hatstand** [comment]
You should probably file this bug against gstreamer instead
