### ISSUE TITLE
Di.fm stations stuck as "playing" when try them to play without internet connection

### ISSUE THREAD

**Issue by ivan-leontiev** [clementine-player/Clementine#4969]
This issue occurs in latest dev builds and also in 1.2.3

The cause of this issue is that in DigitallyImportedUrlHandler::LoadPlaylistFinished()
when it failed to get playlist it just ignore and returns. We should emit 
AsyncLoadComplete(LoadResult(url)) instead.

Thanks for reading.

**Comment by Chocobozzz** [comment]
Hi @ivan-leontiev 

Why don't you open a PR ? :)
