### ISSUE TITLE
Progress goes over 100% when parsing Jamendo catalogue

### ISSUE THREAD

**Issue by MightyPork** [clementine-player/Clementine#4971]
![screenshot_2015-07-31_14-10-25](https://cloud.githubusercontent.com/assets/2041118/9007063/208e29c6-378e-11e5-89f6-adec98326148.png)
![screenshot_2015-07-31_14-10-37](https://cloud.githubusercontent.com/assets/2041118/9007064/208ea43c-378e-11e5-8e3f-aec8f91c1b89.png)

Not a big issue, just kinda funny—reminiscent of Windows xD

**Comment by Chocobozzz** [comment]
With the dev builds ?

**Comment by MightyPork** [comment]
the latest stable release. Will try with the git build if I manage to run it...

**Comment by Chocobozzz** [comment]
http://builds.clementine-player.org/

**Comment by MightyPork** [comment]
I'm on Arch... no tgz?

**Comment by Chocobozzz** [comment]
There is an AUR package (clementine-git).

**Comment by MightyPork** [comment]
yes that builds it from source

**Comment by MightyPork** [comment]
Okay took 30 minutes to build but works - and the bug is fixed there.
