### ISSUE TITLE
Soundcloud will not list more than 10 songs from a single artist

### ISSUE THREAD

**Issue by Croberson12** [clementine-player/Clementine#4976]
Basically searching in Soundcloud for an artist will not list all the songs of the artist (only ten). 
![thanksobama](https://cloud.githubusercontent.com/assets/8097115/9053113/35ca6798-3a25-11e5-9d0c-02f2c953d5ca.png)

**Comment by Chocobozzz** [comment]
This is a desired behaviour with the simple search (https://github.com/clementine-player/Clementine/blob/master/src/internet/soundcloud/soundcloudservice.cpp#L64).

**Comment by Croberson12** [comment]
I suppose this is what I get for not looking through the code more thoroughly. Thanks!
