### ISSUE TITLE
Crash on playing Spotify tracks (OS X)

### ISSUE THREAD

**Issue by xiongchiamiov** [clementine-player/Clementine#4979]
Using the builds from http://builds.clementine-player.org , playing a track from Spotify immediate crashes clementine on `clementine-1.2.3-1280-g10860b7.dmg` ([crash log](https://gist.github.com/xiongchiamiov/7ae0d68a82a159f23e70)).  `clementine-1.2.3-1260-ge0c5f29.dmg` works as expected.

I haven't narrowed down which build specifically introduces the issue, if it's only certain tracks or everything, or anything like that because I'm at work and should probably be working. :)  But I can do that later if it'd be helpful.

**Comment by ArnaudBienner** [comment]
Yes sure: if you can identify a particular build (thus a particular revision) that introduced a regression, that would be very helpful! :)

**Comment by xiongchiamiov** [comment]
Checked the latest revision and everything's fine - whether through something being fixed in Clementine or something being fixed on my end, I don't know.  But either way, it's working. :)

**Comment by ArnaudBienner** [comment]
OK thanks for letting us know :)
