### ISSUE TITLE
Error while linking main binary, Debian stretch, libxcb

### ISSUE THREAD

**Issue by SaSteDD** [clementine-player/Clementine#4982]
When trying to complie the QT5 branch on Debian I get the following error when linking the main executable:

     Linking CXX executable ../clementine
     /usr/lib/gcc/i586-linux-gnu/4.9/../../../i386-linux-gnu/libGL.so: undefined reference to    `xcb_poll_for_special_event'
     //usr/lib/i386-linux-gnu/libxcb-dri3.so.0: undefined reference to `xcb_get_reply_fds'
     //usr/lib/i386-linux-gnu/libxcb-dri3.so.0: undefined reference to `xcb_send_fd'
     /usr/lib/gcc/i586-linux-gnu/4.9/../../../i386-linux-gnu/libGL.so: undefined reference to  `xcb_wait_for_special_event'
     /usr/lib/gcc/i586-linux-gnu/4.9/../../../i386-linux-gnu/libGL.so: undefined reference to      `xcb_unregister_for_special_event'
     /usr/lib/gcc/i586-linux-gnu/4.9/../../../i386-linux-gnu/libGL.so: undefined reference to      `xcb_register_for_special_xge'
     collect2: error: ld returned 1 exit status
     src/CMakeFiles/clementine.dir/build.make:129: recipe for target 'clementine' failed
     make[2]: *** [clementine] Error 1
     CMakeFiles/Makefile2:982: recipe for target 'src/CMakeFiles/clementine.dir/all' failed
     make[1]: *** [src/CMakeFiles/clementine.dir/all] Error 2
     Makefile:116: recipe for target 'all' failed
     make: *** [all] Error 2

Googling this did not help at all. Is there anyone who succeeded to compile the Qt5 branch in Debian stretch? Does anyone know what could cause this?

**Comment by Chocobozzz** [comment]
Doesn't seem a Clementine issue.

Have you try to look at some bug reports on Ubuntu ? https://bugs.launchpad.net/ubuntu/+source/libxcb/+bug/1265642

**Comment by SaSteDD** [comment]
I just had time too look into this again. As you said this is most likely not a Clementine issue. 
It also happens on the main branch and it also with commits from months ago that used to compile on my machine. 

I was able to install the .deb-file provided under http://builds.clementine-player.org/debian-jessie/clementine_1.2.3-1280-g10860b7~jessie_i386.deb installed just fine, and Clementine appears to be working.

Guess I will just stick with that for now and try again later...
