### ISSUE TITLE
Clementine does not play downloaded podcast episodes properly

### ISSUE THREAD

**Issue by goggle** [clementine-player/Clementine#4985]
When I right click on a podcast episode and choose "Download this episode", the episode will be downloaded and saved in a specified directory. But after putting the episode to the playlist, e.g. by using "Append to current playlist", Clementine won't use the downloaded podcast file properly. I am not able to use the seekbar and sometimes, the playback stops in the middle of the episode.

As a workaround, I can choose the downloaded podcast file in the "Files" sidebar and add this file to the playlist. Then everything works as expected.

**Comment by goggle** [comment]
Ok, the problem seems to be solved in the current git version of Clementine, so i suggest, we can close this.

**Comment by dowcet** [comment]
I was having this problem on Ubuntu 14.04 which still includes an out-of-date version of Clementine. Upgrading as described here did the trick: https://www.clementine-player.org/downloads
