### ISSUE TITLE
Windows development builds are not updated

### ISSUE THREAD

**Issue by adem4ik** [clementine-player/Clementine#4987]
It seems like Windows builds are stuck in 6th of July (http://builds.clementine-player.org/win32/), while there is constant updates of Ubuntu builds (http://builds.clementine-player.org/ubuntu-trusty/)

**Comment by TheUbuntuGuy** [comment]
The situation is actually a little worse than that. Ubuntu, Fedora, and Mac are also not updating.
http://buildbot.clementine-player.org/grid has details. Windows stopped compiling due to changes to the dependencies.

**Comment by davidsansome** [comment]
Fixed these by switching to the new docker-based continuous build

**Comment by adem4ik** [comment]
thank you so much!
