### ISSUE TITLE
Debugging Clementine

### ISSUE THREAD

**Issue by Fabius89** [clementine-player/Clementine#4988]
How can I enable debugging and where are stored log files?

os: Manjaro Linux

Clementine version: 1.2.3-6

**Comment by Chocobozzz** [comment]
You have to compile Clementine without the Release CMake flag to have debug messages in the output.

**Comment by cmorty** [comment]
I couldn't find any documentation on this. Did I overlook it? I tried strawberry and suddenly clementine started logging to the console. Thus there must be a way to do this.
