### ISSUE TITLE
Make shuffling more random

### ISSUE THREAD

**Issue by Yanpas** [clementine-player/Clementine#4997]
For example I enabled shuffling, and have play list of songs `1,2,3,4,5`
For example If I start playing from song `4`, then click next it will bring me to song `2`, afte `2` will be played `5`.
But if I double click on song `4` again - the song that will be played after `4` will be `2` again! Shuffling is pre-defined, make it truly random, please.

**Comment by coconutlulz** [comment]
With 1.2.3-1306-gd97e9ae the shuffle order changes each time for me.

**Comment by hatstand** [comment]
Try using this patch https://github.com/clementine-player/Clementine/commit/9f6899ac82e9af47fcec05fa82a68343abfafaca

**Comment by Yanpas** [comment]
Version 1.3rc1, still same result. Was this patch applied?
