### ISSUE TITLE
Suggestion for Spotify Module

### ISSUE THREAD

**Issue by TheGuyDanish** [clementine-player/Clementine#5000]
At the time of writing, right-clicking a track in the Spotify module in the left side of the program will only give the context menu option to "Configure Spotify". Would it be an idea to give the ability to add a song to the end of a playlist, or after a current track, rather than just having to drag it to the bottom of a possibly colossal list of tracks. Something alike the context menu given when you handle files.

**Comment by ArnaudBienner** [comment]
Thanks for the suggestion :)
One tip for next time you open: make you title more descriptive ;) e.g. "Add playlist actions to Spotify songs"

**Comment by ArnaudBienner** [comment]
Also:
┏━━━┓╋╋╋╋╋╋╋╋╋╋╋╋╋┏┓╋╋╋┏┓╋╋╋┏┓
┃┏━┓┃╋╋╋╋╋╋╋╋╋╋╋╋┏┛┗┓╋╋┃┃╋╋┏┛┗┓
┃┃╋┗╋━━┳━┓┏━━┳━┳━┻┓┏╋┓┏┫┃┏━┻┓┏╋┳━━┳━┓
┃┃╋┏┫┏┓┃┏┓┫┏┓┃┏┫┏┓┃┃┃┃┃┃┃┃┏┓┃┃┣┫┏┓┃┏┓┓
┃┗━┛┃┗┛┃┃┃┃┗┛┃┃┃┏┓┃┗┫┗┛┃┗┫┏┓┃┗┫┃┗┛┃┃┃┃
┗━━━┻━━┻┛┗┻━┓┣┛┗┛┗┻━┻━━┻━┻┛┗┻━┻┻━━┻┛┗┛
╋╋╋╋╋╋╋╋╋╋┏━┛┃
╋╋╋╋╋╋╋╋╋╋┗━━┛

On opening the issue 5000! (but there is nothing to win, sorry :) )
