### ISSUE TITLE
Ubuntu 15.10 (Wily) build?

### ISSUE THREAD

**Issue by nazar-pc** [clementine-player/Clementine#5002]
Ubuntu 15.10 recently switched over to GCC 5 and many packages were recompiled under new names with `v5` suffix.
Since then Clementine build from Vivid ppa can't be installed because of unsatisfied dependencies.
Any chances to add Ubuntu 15.10 builds?

**Comment by nazar-pc** [comment]
Repacking with changed dependencies:
> libcrypto++9 > libcrypto++9v5
> libprotobuf9 > libprotobuf9v5

Results in error:
> clementine: symbol lookup error: clementine: undefined symbol: _ZN6google8protobuf8internal13empty_string_E

**Comment by nazar-pc** [comment]
Just compiled from source and it works nicely, so it is just a matter of build addition I guess.

**Comment by nazar-pc** [comment]
One more dependency update from yesterday:
> libtag1c2a > libtag1v5

**Comment by nazar-pc** [comment]
When will Wily be added to ppa?

**Comment by davidsansome** [comment]
The buildmaster should do this automatically now:
https://launchpad.net/~me-davidsansome/+archive/ubuntu/clementine-dev
http://buildbot.clementine-player.org/builders/Ubuntu%20dev%20PPA%20Wily

**Comment by nazar-pc** [comment]
Thank you!
