### ISSUE TITLE
Last.fm Authentication Failed

### ISSUE THREAD

**Issue by liftarn** [clementine-player/Clementine#5005]
When I set up Clementine I enter username and password for my Last.fm account (should perhaps be done by authenticating instead) I get the message "Authentication Failed - You do not have permission to access the service"
It may have something to do with the recent site redesign over at Last.fm

**Comment by jaseemabid** [comment]
Is there a plan to migrate clementine to use OAuth?

**Comment by liftarn** [comment]
Today it worked so it must have been a problem at Last.fm

**Comment by acurl** [comment]
I have the same problem. I created a last.fm account few days ago and there is always the "Authentification failed" error message when I try to connect in Clementine (Version 1.2.3-1280-g10860b7). Am I the only one ?

**Comment by liftarn** [comment]
@acurl, can you log in to the site? It may be that the user database they are running is an older version.

**Comment by acurl** [comment]
Yes, I can log in from this url https://secure.last.fm/login

**Comment by Chocobozzz** [comment]
It's the same with my account but Lastfm are migrating their data so retry later.

**Comment by dufferzafar** [comment]
I am having this issue too! Clementine just displays Authentication failed, while I can login from the website.

**Comment by ixaxaar** [comment]
+1 same issue on Version 1.3 rc1

```
16:05:49.799 DEBUG unknown                          "<?xml version="1.0" encoding="utf-8"?> 
16:05:49.799 DEBUG unknown                          <lfm status="failed"> 
16:05:49.799 DEBUG unknown                            <error code="4">Authentication Failed - You do not have permissions to access the service</error> 
16:05:49.799 DEBUG unknown                          </lfm> 
16:05:49.799 DEBUG unknown                          "  
16:05:49.803 WARN  unknown                          QSpiAccessible::accessibleEvent not handled:  "2"  obj:  QMessageBox(0x7fff217fba20) ""  
16:05:49.804 DEBUG unknown                          FIXME: handle dialog start.  
16:05:53.031 DEBUG unknown                          FIXME: handle dialog end. 
```

**Comment by obsidiannonparity** [comment]
I am still having this issue too. Banshee and other players are connecting fine to last.fm so it seems like we just need to change the auth method to the new method last.fm deployed last year.

**Comment by obsidiannonparity** [comment]
I see this has been going on awhile but last.fm has been having an api issue this past week too
http://status.last.fm/ so that may be I am unable to connect

**Comment by amuttsch** [comment]
Try the latest nightly build or 1.3rc2. I migrated Clementine to the new authentication method a few weeks ago. Scrobbing and login should work fine there.

**Comment by dufferzafar** [comment]
@amuttsch Where can I find 1.3rc2 package for Ubuntu Wily (15.10) ?

**Comment by narunlifescience** [comment]
go to https://builds.clementine-player.org/ubuntu-wily/
& scroll down to last two entries..

**Comment by ixaxaar** [comment]
@amuttsch  yep, 1.3rc2 does fix this :beers:

**Comment by brutalcrozt** [comment]
Pardon me, but i like to ask 1.3.2 to be released.
I am trying not to avoid creating an invalid issue.
