### ISSUE TITLE
Windows Build Instructions are Out Of Date

### ISSUE THREAD

**Issue by redyoshi49q** [clementine-player/Clementine#5010]
I attempted to follow the build instructions listed [here](https://github.com/clementine-player/Clementine/wiki/Compiling-from-Source-%28Windows%29), but encountered this error while attempting to make the Windows dependencies:

    cd gst-plugins-base-1.5.2 && autoreconf
    configure.ac:1: error: Autoconf version 2.69 or higher is required

After doing some research on the subject, I followed the instructions listed [here](http://askubuntu.com/a/632769/314186) to install both autoconf 2.69 and automake 1.14 (the versions available to the chroot without the PPA were 2.68 and 1.11.3, respectively).  With these two packages, the `make` command eventually created .dll files as expected.  If the environment that is generating releases hasn't been updated accordingly, this may also be a contributing factor to [why Windows builds aren't being generated anymore](https://github.com/clementine-player/Clementine/issues/4987).

Additionally, it seems that making the Windows executable fails at the *very* last part of it; below is a copy of the end of `make`'s log:

    [100%] Building CXX object src/CMakeFiles/clementine.dir/main.cpp.obj
    /home/ethan/dev/clementine/src/main.cpp:23:0: warning: "_WIN32_WINNT" redefined [enabled by default]
     #define _WIN32_WINNT 0x0600
     ^
    In file included from /mingw/i686-w64-mingw32/include/crtdefs.h:10:0,
                     from /mingw/i686-w64-mingw32/include/wchar.h:9,
                     from /mingw/i686-w64-mingw32/include/c++/4.9.0/cwchar:44,
                     from /mingw/i686-w64-mingw32/include/c++/4.9.0/bits/postypes.h:40,
                     from /mingw/i686-w64-mingw32/include/c++/4.9.0/iosfwd:40,
                     from /mingw/i686-w64-mingw32/include/c++/4.9.0/memory:72,
                     from /home/ethan/dev/clementine/src/main.cpp:18:
    /mingw/i686-w64-mingw32/include/_mingw.h:229:0: note: this is the location of the previous definition
     #define _WIN32_WINNT 0x502
     ^
    cc1plus: warning: unrecognized command line option "-Wno-unknown-warning-option" [enabled by default]
    cc1plus: warning: unrecognized command line option "-Wno-unused-private-field" [enabled by default]
    Linking CXX executable ../clementine.exe
    /target/lib/libsqlite3.a(sqlite3.o):sqlite3.c:(.text+0x16680): multiple definition of `sqlite3_backup_remaining'
    /target/lib/libgpod.dll.a(d000252.o):(.text+0x0): first defined here
    /target/lib/libsqlite3.a(sqlite3.o):sqlite3.c:(.text+0x16690): multiple definition of `sqlite3_backup_pagecount'
    /target/lib/libgpod.dll.a(d000251.o):(.text+0x0): first defined here
    /target/lib/libsqlite3.a(sqlite3.o):sqlite3.c:(.text+0x27b60): multiple definition of `sqlite3_backup_step'
    /target/lib/libgpod.dll.a(d000253.o):(.text+0x0): first defined here
    /target/lib/libsqlite3.a(sqlite3.o):sqlite3.c:(.text+0x2c590): multiple definition of `sqlite3_errmsg'
    /target/lib/libgpod.dll.a(d000316.o):(.text+0x0): first defined here
    /target/lib/libsqlite3.a(sqlite3.o):sqlite3.c:(.text+0x30fe0): multiple definition of `sqlite3_backup_init'
    /target/lib/libgpod.dll.a(d000250.o):(.text+0x0): first defined here
    /target/lib/libsqlite3.a(sqlite3.o):sqlite3.c:(.text+0x31160): multiple definition of `sqlite3_backup_finish'
    /target/lib/libgpod.dll.a(d000249.o):(.text+0x0): first defined here
    /target/lib/libsqlite3.a(sqlite3.o):sqlite3.c:(.text+0x31f60): multiple definition of `sqlite3_close'
    /target/lib/libgpod.dll.a(d000275.o):(.text+0x0): first defined here
    /target/lib/libsqlite3.a(sqlite3.o):sqlite3.c:(.text+0x68030): multiple definition of `sqlite3_open'
    /target/lib/libgpod.dll.a(d000349.o):(.text+0x0): first defined here
    /mingw/bin/../lib/gcc/i686-w64-mingw32/4.9.0/../../../../i686-w64-mingw32/bin/ld: /target/lib/libsqlite3.a(sqlite3.o): bad reloc address 0x0 in section `.data'
    collect2: error: ld returned 1 exit status
    make[2]: *** [clementine.exe] Error 1
    make[1]: *** [src/CMakeFiles/clementine.dir/all] Error 2
    make: *** [all] Error 2

Note that this is a version of the source that compiled for Linux, and that a clean compilation directory was used for this build.

**Comment by davidsansome** [comment]
Probably the dockerfile should be the canonical build "instructions" now:
https://github.com/clementine-player/Buildbot/blob/master/docker/slave-mingw/Dockerfile

Anyway this "works" (http://buildbot.clementine-player.org/builders/Windows%20Release) and I've fixed the permissions on the builds directory so it can upload releases (http://builds.clementine-player.org/win32/release/)

**Comment by vdheuvel** [comment]
Encountering the same error. How did you solve this on your machine, @davidsansome ? I extended clementine, and I want to cross compile a windows version. I'm not a contributor to this repository, so I can't push and use the build slave.
