### ISSUE TITLE
libsqlite3-0.dll seems to be missing in win32 dev builds

### ISSUE THREAD

**Issue by adem4ik** [clementine-player/Clementine#5011]
Just installed latest win32 dev build http://builds.clementine-player.org/win32/release/ClementineSetup-1.2.3-1304-g509b4cc.exe

got following error after running Clementine:
![image](https://cloud.githubusercontent.com/assets/4707112/9473572/2f867e1c-4b64-11e5-8f75-398cc78031d4.png)

"System Error: it is impossible to start the program, cause there is no libsqlite3-0.dll on this PC. Try to reinstall program."

**Comment by Agent24** [comment]
I just had the same problem too with build 1304. Was running an earlier Debug build though without the issue.

**Comment by Xeramon** [comment]
Same problem here. All newer downloads seems to be broken here: http://builds.clementine-player.org/win32/release/

**Comment by OS-X** [comment]
So anyone thought of a work around, will installing an early version Help ?

**Comment by Agent24** [comment]
I haven't. I reverted to the stable release after that. I did try using libsqlite3-0.dll from GIMP install that I found on my drive, but Clementine just threw a different error. Don't know if that was because that Clementine build has a problem, or the dll from GIMP was different somehow.

**Comment by davidsansome** [comment]
This should be fixed now
