### ISSUE TITLE
Libprotobuf8 not available on Debian Jessie

### ISSUE THREAD

**Issue by jeukel** [clementine-player/Clementine#5024]
Debian Jessie has only libprotobuf9 and Wheezy libprotobuf7.

**Comment by Chocobozzz** [comment]
Please specify your error.

**Comment by jeukel** [comment]
Can't install using the .deb built available on the site.

**Comment by davidsansome** [comment]
The latest Jessie build in http://builds.clementine-player.org/debian-jessie/ depend on libprotobuf9
