### ISSUE TITLE
Playback issues when adding rating to currently playing track with .m4a 

### ISSUE THREAD

**Issue by noreye** [clementine-player/Clementine#5026]
Hi all,

Im using Version 1.2.3-1305-g2cfafbd and when I try to change the rating of the currently playing track (.m4a format) I get a wall of white noise. The only solution is to stop playback and restart the track.

OSX 10.9.5
Focusrite Scarlett Solo soundcard

**Comment by narunlifescience** [comment]
cannot reproduce this issue on OSX 10.10.5 (macbook pro).

**Comment by noreye** [comment]
I cant reproduce it now. I wonder if it was a certain few files or if I changed some settings...will report back if I can reliably reproduce it.
