### ISSUE TITLE
Add a 'const' rating column

### ISSUE THREAD

**Issue by Tomaqa** [clementine-player/Clementine#5029]
Hi,
I'd like to suggest to add an option to show 'const' rating column in main window where it wouldn't be possible to modify any song rating.
This would prevent changing a song rating by unconscious mouse click.
Preferences->General->Behaviour: "Enable song metadata inline edition with click" does not affect rating column.

**Comment by narunlifescience** [comment]
Hmm... that would be a bit overkill to put that in preferences section. It would be better to keep that    
option in mouse left click menu on the ratings widget. Also the configuration needs to be saved so that clementine remembers the setting.
