### ISSUE TITLE
Clementine 1.2.2 does not update tags when editing data

### ISSUE THREAD

**Issue by sorin2120** [clementine-player/Clementine#5034]
Very similar to this issue, which was closed but never fixed: https://github.com/clementine-player/clementine/issues/3955

**Comment by tchoulihan** [comment]
This is probably a copy of : 
https://github.com/clementine-player/Clementine/issues/221

**Comment by Chocobozzz** [comment]
@sorin2120 Did you try with the latest build ? http://builds.clementine-player.org/

**Comment by JulianVolodia** [comment]
@Chocobozzz maybe closing is the best way in that case?

**Comment by Chocobozzz** [comment]
:+1:
