### ISSUE TITLE
Sorting playlist messes up queue

### ISSUE THREAD

**Issue by cornicis** [clementine-player/Clementine#5041]
Sorting the playlist by clicking on the column headers reassigns the queue items.

Reproduced by:
1. Add 10 tracks to new playlist.
2. Mark the first 3 tracks.
3. Add these tracks to queue.
4. Sort tracks by length.
5. Tracks get reassigned automatically.

Interestingly the item-highlighting reproduces this behavior. The pattern is not random, the same playlist actually reproduces the same result, but the result differs for other playlists.

Setup: Arch Linux 4.0.6, Clementine 1.2.3

**Comment by TheUbuntuGuy** [comment]
I am unable to reproduce this with the latest development build from http://builds.clementine-player.org/.
Can you update and verify that the issue still exists?

**Comment by cornicis** [comment]
Nice, bug not present at least in version 1.2.3-1360-g8f84a53.
