### ISSUE TITLE
[Feature Request] Prevent monitor from sleeping when HDMI audio is used

### ISSUE THREAD

**Issue by mdmksrbn** [clementine-player/Clementine#5049]
If HDMI audio is used and the monitor goes to sleep, the audio is suspended until the monitor is awakened by the user.
Would it be possible to prevent the monitor to go to sleep, but only while Clementine is playing tracks?
Thus playback would not be interrupted every 10 minutes or so, depending on OS settings.

I think the current behaviour is standard, so the feature should be optional.

**Comment by xenithorb** [comment]
Bump

I agree with this, it's kind of annoying to have to bump my wireless keyboard every once in a while when I don't want the tv (and therefore receiver) to go to sleep and stop playing audio. 

Temporary solution is to disable power management when I want to play music through clementine. I imagine this shouldn't be that hard considering that playing music via watching a HTML5 youtube video has the intended effect of keeping the system on.

**Comment by hatstand** [comment]
If someone feels like coding something like this, there's already some code for inhibiting the screensaver in src/ui/screensaver.cpp and it's used in src/visualisations/visualisationcontainer.cpp

Bonus: if you're not on windows you can kind of get the behaviour you want by turning on full screen visualisations.
