### ISSUE TITLE
Spotify Blob 15 won't work no more on last clementine build

### ISSUE THREAD

**Issue by Kwaadpepper** [clementine-player/Clementine#5058]
http://paste.ubuntu.com/12647646/
Using https://packages.debian.org/wheezy/libprotobuf7 (i'm on Kubuntu ~~15.04~~  15.10 so i have libprotobuf9 in depot)

Version ~~1.2.3-1354-gdaddbde~~ 1.2.3-1434-gf300946~wily

Installed from **ppa:me-davidsansome/clementine-dev**

**Solution:**
https://github.com/clementine-player/Clementine/issues/5058#issuecomment-160394904

**Comment by Kwaadpepper** [comment]
The issue is that, libprotobuf7 is no more available, and still if installed from deb package, it version might not match, and you would be able to log in spotify, but it won't read spotify API as protobuf won't be able to parse Spotify server answer.

So in a nutshell please, provide new build against libprotobuf9 which is by default available on 15.04 and 15.10.

To any one struggling on this stupid issue, you have to compile Clementine on hand, but before you have to install libspotify : 

    wget https://developer.spotify.com/download/libspotify/libspotify-12.1.51-Linux-x86_64-release.tar.gz
    dtrx libspotify-12.1.51-Linux-x86_64-release.tar.gz
    cd libspotify-12.1.51-Linux-x86_64-release
    sudo make install prefix=/usr/local
    sudo ldconfig

Then compile Clementine, it will have Spotify support without using the failing blob.

**Comment by starenka** [comment]
Same problem here, Debian testing, Clementine 1.2.3+git1354-gdaddbde+dfsg-1

**Comment by Kwaadpepper** [comment]
Hey, i have the solution here. You have to compile clementine your self, then with spotify dependency.
It will compile the blob with **libprotobuf9** instead of **libprotobuf7** like the blobs spotify automaticly downloads.

Then you will have to replace ```~/.config/Clementine/spotifyblob/version15-64bit/blob``` by ```Clementine/bin/clementine-spotifyblob``` of course from rename ```clementine-spotify``` into ```blob```.

To compile Clementine with libspotify, you will have to compile **libspotify** which does not have a .bed package take it here, https://developer.spotify.com/technologies/libspotify/

Also don't try to install libprotobuf7 to make it work, it won't. If you have troubles to compile refer yourself to the wiki page https://github.com/clementine-player/Clementine/wiki/Compiling-from-Source

**Comment by starenka** [comment]
Hi, thanks for help. You don't happen to have such blob uploaded somewhere? ;)

**Comment by Kwaadpepper** [comment]
Yes I do, but is should recommends you to compile it, but any way here is the link https://www.freethepepper.com/owncloud/index.php/s/sj2CdQynUyGtQF2
Copy spotifyblob in ```~.config/Clementine/```, there is only the 64 bit version since I have a 64 bit system.

**Comment by starenka** [comment]
Cheers! Unfortunately copying your file as `blob` didn't work, the login dialog keeps spinning and nothing happens. Funny thing that I don't get any error in console, though. I guess I will need to compile it myself...

**Comment by Kwaadpepper** [comment]
You have check that you have libprotobuf9 ? I have version 2.6.1-1 0. You are on a 64 bit system ?
And of course restarted clementine ? You may also clean preferences eventually.

**Comment by starenka** [comment]
yes a 64b debian testing....

root /tmp # aptitude show libprotobuf9v5
Package: libprotobuf9v5                  
New: yes
State: installed
Automatically installed: yes
Multi-Arch: same
Version: 2.6.1-1.3
Priority: optional
Section: libs
Maintainer: Robert Edmonds <edmonds@debian.org>
Architecture: amd64
Uncompressed Size: 1,253 k
Depends: libc6 (>= 2.14), libgcc1 (>= 1:4.1.1), libstdc++6 (>= 5.2), zlib1g (>= 1:1.1.4)
Conflicts: libprotobuf9, libprotobuf9:i386
Breaks: libprotobuf9v5:i386 (!= 2.6.1-1.3)
Replaces: libprotobuf9, libprotobuf9:i386, libprotobuf9v5:i386 (< 2.6.1-1.3)

**Comment by Kwaadpepper** [comment]
Yes you do have a more recent version of libprotobuf9, also as it may need other dependencies, it is normal that it won't work, i'm on Kubuntu 15.10, so only option for you seems to compile it.

**Comment by Kwaadpepper** [comment]
To anyone futur person reading this and wondering how to install libspotify:
 - Download and extract
  - **i386:** https://developer.spotify.com/download/libspotify/libspotify-12.1.51-Linux-i686-release.tar.gz
  - **amd64:** https://developer.spotify.com/download/libspotify/libspotify-12.1.51-Linux-x86_64-release.tar.gz
 - run this command in the extracted folder
```sudo make install prefix=/usr/local```

**Comment by starenka** [comment]
@Kwaadpepper Cheer mate, It works like you say. Here's my blob compile against more recent liprotobuf (debian testing, `libprotobuf9v5 2.6.1-1.3`) if somebody is to lazy to compile

http://junk.starenka.net/clementine-spotifyblob

**Comment by Chocobozzz** [comment]
Should be fixed with the latest dev builds (https://github.com/clementine-player/Clementine/commit/170c64cd8bef9df2ea88dd4f72eec641c250bcfd).

**Comment by liskin** [comment]
So when can we expect the updated blob to hit https://spotify.clementine-player.org/?

**Comment by hatstand** [comment]
Fixed

**Comment by starenka** [comment]
It's broken again in 1.3 rc1 :(

**Comment by liskin** [comment]
Well I downloaded the v16 blob a put it in /home/tomi/.config/Clementine/spotifyblob manually and I think it may work. Couldn't test it thoroughly as spotify won't accept my paypal.

**Comment by starenka** [comment]
I did the same thing, but clementine says it has no client and downloads
v15 blob (which does not work)

---
In Perl you shoot yourself in the foot, but nobody can understand how you
did it. Six months later, neither can you. | print 'aknerats'[::-1]

**Comment by liskin** [comment]
Did you put it in the v15 directory?

**Comment by starenka** [comment]
Aha, if you put the v16 downloaded blob into v15 directory, it kinda works
- well login, playlists... but not seach :(

---
In Perl you shoot yourself in the foot, but nobody can understand how you
did it. Six months later, neither can you. | print 'aknerats'[::-1]

**Comment by buckket** [comment]
Spotify apparently broke their search API. Having the same problem in Clementine as well as in another tool which uses libspotify.
