### ISSUE TITLE
Dropbox sign-out gets reversed as soon as one closes and then re-opens the preferences window

### ISSUE THREAD

**Issue by ACinnamonUserInUK** [clementine-player/Clementine#5063]
. . on both Windows (8.1.1 x64) and Linux (Mint 17.2 x64 Cinnamon). Oh dear! Clementine version: 1.2.3 (Windows); 1.2 (Linux).

**Comment by Chocobozzz** [comment]
Can you try with the latest build? http://builds.clementine-player.org/

**Comment by ivan-leontiev** [comment]
Can't reproduce with the latest build on Arch. This issue have already been fixed (commit 06e5b67).
