### ISSUE TITLE
Make the play/pause shortcut more global

### ISSUE THREAD

**Issue by Jojo144** [clementine-player/Clementine#5072]
When the focus is given to the left side panel (for instance, just after launching music by a double-click), the play/pause shortcut (the space bar) doesn't work...
It would be nice if this shortcut always work.

**Comment by narunlifescience** [comment]
Go to preferences -> configure shortcuts and change play/pause to use custom shortcut. then you can use that shortcut to control play/pause whenever clementine is running. space wont be a good option as that would make problems, try to use two key combinations like ctrl+p or something like that...

**Comment by kernc** [comment]
How is Space not a good option?! Ask _any_ media player what it thinks about pausing/resuming playback on Space!
