### ISSUE TITLE
Crash when touching the equalizer

### ISSUE THREAD

**Issue by mxa** [clementine-player/Clementine#5090]
Version 1.2.3-1388-g240605a on Linux Mint crashes as soon as you touch the equalizer.

**Comment by TheUbuntuGuy** [comment]
What version of gst-plugins-good are you using? Versions before gst-plugins-good-1.4.4 have a bug which can cause this. See #4541

**Comment by Chocobozzz** [comment]
Closing this issue since we have no news. Feel free to reopen.

**Comment by mxa** [comment]
the system offers gstreamer1.0-plugins-good and gstreamer0.10-plugins-good, both are installed. There is no newer version available.
