### ISSUE TITLE
Keyboard shortcut not working !

### ISSUE THREAD

**Issue by vincegre** [clementine-player/Clementine#5091]
Unable to get shortcuts assigned in Preferences of Clementine to work :( Assigned few for Next/previous and Play/Pause on functions buttons of my keyboard but none work !!

Clementine 1.2.3 on Ubuntu 64 bits.

**Comment by Chocobozzz** [comment]
Please try with latest builds (https://launchpad.net/~me-davidsansome/+archive/ubuntu/clementine-dev)

**Comment by vincegre** [comment]
oki added the dev ppa ! It stills doesn't work with shortcut in Clementine but if I tick Use Gnome shortcut and setup them in Unity it works fine ;)

Thanks for help
