### ISSUE TITLE
Clementine does not use track numbers in xspf playlists

### ISSUE THREAD

**Issue by jasmith79** [clementine-player/Clementine#5093]
Clementine does not seem to have any support for \<trackNum>\</trackNum> from the xspf specification. Does not recognize that attribute of a track when loading, does not create it when saving in xspf format. This situation is unfortunate for tracks that cannot be matched against a database.

**Comment by Chocobozzz** [comment]
That's what we call "efficacity" :p

**Comment by jasmith79** [comment]
Wow that was fast. Thanks!
