### ISSUE TITLE
Playing Music from SounClound doesn't work

### ISSUE THREAD

**Issue by thomasdelagoutine** [clementine-player/Clementine#5101]
Hi,

I can't play music from SounCloud .... When I put a music on my playlist from SoundCloud, it is impossible to play it and the Clementine change to the next title...
Does the function with SoundCloud is available ? 

Thank you

**Comment by ArnaudBienner** [comment]
It works for me using the latest development version.
Could you please try one of the latest build available here: builds.clementine-player.org/
and let us know if you still have the issue?

**Comment by thomasdelagoutine** [comment]
Clémentine étant français, je vais vous répondre en français !

J'ai installé la dernière version et les musiques en provenance de
SoundCloud sont lisibles.
Merci de votre aide !

2015-11-04 15:27 GMT+01:00 ArnaudBienner <notifications@github.com>:

> It works for me using the latest development version.
> Could you please try one of the latest build available here:
> builds.clementine-player.org/
> and let us know if you still have the issue?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/clementine-player/Clementine/issues/5101#issuecomment-153741516>
> .
>



-- 
*Thomas Jamme de Lagoutine*
*thomasdelagoutine@gmail.com <thomasdelagoutine@gmail.com>*
*+33668636375*
*13,chemin des fontaines*
*81290 Viviers-les-montagnes, FRANCE*

**Comment by ArnaudBienner** [comment]
Clementine est disponible dans plusieurs langues, dont le français, mais je suis l'un des seuls développeurs à être français. Du coup il préférable de poser les questions en anglais, pour augmenter la chance que quelqu'un puisse répondre ;-)
