### ISSUE TITLE
Track never plays

### ISSUE THREAD

**Issue by liftarn** [clementine-player/Clementine#5104]
I have this track and I never get it to play with 1.2.3. under MS Windows 7. It just says it's buffering.
https://www.dropbox.com/s/smayueo5uwksymp/04%20ROCK%27N%27ROLL%20HIGH%20SCHOOL.mp3?dl=0

**Comment by mafagafogigante** [comment]
Hey there, @liftarn. Could you please download and install the latest release from [here](http://builds.clementine-player.org/win32/release/) and attempt to reproduce the problem?

**Comment by liftarn** [comment]
Appears to work in 1450.
