### ISSUE TITLE
"Server doesn't support seeking" and radio stops

### ISSUE THREAD

**Issue by MightyPork** [clementine-player/Clementine#5116]
I'm getting interrupted radio streams with Clementine (built from master checked out yesterday) - previous version (from git built in july (?)) suffered from the same bug.

After a while, the stream stops, and instead of buffering and continuing, it shows an alert that "Server does not support seeking", and the play queue advances (to the end, as there's only 1 item). I can restart it manually.

The stream URL is `http://icecast5.play.cz/cro3-128.mp3`, if it helps with debugging - but I'm getting it with multiple streams. 

I tried adjusting the buffer duration etc in settings, but it didn't help.

**Comment by Kwaadpepper** [comment]
Same issue here using any radio, even if it do not happen often.

**Comment by Israphel** [comment]
Same issue, even with "Repeat Playlist" enabled.

**Comment by jeffmcneill** [comment]
Getting this every time my OSX wakes up from sleep. I'm playing a playlist which is a list of SOMA FM channels. Would be nice to disable. Have to hit a button every time. Unlike others, though, Clementine keeps playing (my guess is it skips to the next playlist item which is another channel).

**Comment by ser** [comment]
it's really annoying, as i have an unstable internet connection, ii can see dozen of those messages a day and i need to click it :(

**Comment by gaga9999** [comment]
I have the same issue. It occurs, when the network connection drops or changes - what i would need is a retry setting. Clementine issues the error and skips to the next item in the playlist, when it looses connection to a stream-server.

**Comment by Rmano** [comment]
Same happening here. Makes a lot of radios basically busted, especially the (nice) Radio Swiss (classic, jazz, etc).

**Comment by rkachowski** [comment]
I'm finding this also, it also appears after pausing for a certain duration of time.

It seems like upon pause of an audio stream, Clementine stores the remaining audio buffer internally. Hitting unpause a few seconds later and Clementine will immediately playback where the track was before paused. Once the buffer is empty, the "Server does not support seeking" message is displayed.

**Comment by gaga9999** [comment]
4730 is closed. this is the actual issue.

**Comment by gaga9999** [comment]
it should just have an option : skip to next station at error (who wants that anyway?)  / retry station.

**Comment by zap0xfce2** [comment]
It seems in the latest version this "error" is not included. Try to compile a version by yourself: https://github.com/clementine-player/Clementine/wiki/Compiling-from-Source-(Mac-OS-X)

Even if this error still exists in this version you can remove it with the help of the source :)

**Comment by gaga9999** [comment]
it has gotten worse, it now scrolls down all streams sometimes and the popup takes the focus, even when i am in another application.
