### ISSUE TITLE
Subsonic only shows one folder

### ISSUE THREAD

**Issue by pizzaazzip** [clementine-player/Clementine#5122]
I have two folders in subsonic, one with all my flac files, one with mp3 and m4a files.  I am unable to see any mp3 or m4a files in Clementine so I assume the other folder not showing is the issue  Is there something I can do to get those to show up?

**Comment by Chocobozzz** [comment]
We use http://www.subsonic.org/pages/api.jsp#getAlbumList2 to fetch albums and we don't use `musicFolderId` so Clementine should get all the files independently of the folders.

**Comment by pizzaazzip** [comment]
Gotcha.  I'm assuming my server was all kinds of messed up so I gave up.  I might try to setup a server on a different OS some other time.

**Comment by Chocobozzz** [comment]
Okay, keep us informed :)
