### ISSUE TITLE
error wen try to "cmake"

### ISSUE THREAD

**Issue by udiNur** [clementine-player/Clementine#5134]
hi

im using ubuntu 15.10

i going in to Clementine-master/bin
i run this command "cmake .."

and this is the output:

udi@sys-72:~/Clementine-master/bin$  cmake ..                                                                                                                                                                        
-- The C compiler identification is GNU 5.2.1
-- The CXX compiler identification is GNU 5.2.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.28") 
-- Looking for Q_WS_X11
-- Looking for Q_WS_X11 - found
-- Looking for Q_WS_WIN
-- Looking for Q_WS_WIN - not found
-- Looking for Q_WS_QWS
-- Looking for Q_WS_QWS - not found
-- Looking for Q_WS_MAC
-- Looking for Q_WS_MAC - not found
CMake Error at /usr/share/cmake-3.2/Modules/FindPackageHandleStandardArgs.cmake:138 (message):
  Could NOT find Qt4 (missing: QT_QTOPENGL_INCLUDE_DIR QT_QTOPENGL_LIBRARY)
  (found suitable version "4.8.6", minimum required is "4.5.0")
Call Stack (most recent call first):
  /usr/share/cmake-3.2/Modules/FindPackageHandleStandardArgs.cmake:374 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.2/Modules/FindQt4.cmake:1333 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:36 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/udi/Clementine-master/bin/CMakeFiles/CMakeOutput.log".
See also "/home/udi/Clementine-master/bin/CMakeFiles/CMakeError.log".
udi@sys-72:~/Clementine-master/bin$ 

i already install libqca2-dev like #4848 
thanks

**Comment by hatstand** [comment]
The clue is right there:
Could NOT find Qt4 (missing: QT_QTOPENGL_INCLUDE_DIR QT_QTOPENGL_LIBRARY)
You're missing QtOpenGL

**Comment by udiNur** [comment]
@hatstand  how can i install QtOpenGL?
i already install libqt4-core libqt4-gui

**Comment by hatstand** [comment]
https://github.com/clementine-player/Clementine/wiki/Compiling-from-Source

**Comment by udiNur** [comment]
W: Failed to fetch http://ppa.launchpad.net/gstreamer-developers/ppa/ubuntu/dists/wily/main/binary-amd64/Packages  404  Not Found

W: Failed to fetch http://ppa.launchpad.net/gstreamer-developers/ppa/ubuntu/dists/wily/main/binary-i386/Packages  404  Not Found

E: Some index files failed to download. They have been ignored, or old ones used instead.
