### ISSUE TITLE
Removes authors from ID3 tag

### ISSUE THREAD

**Issue by JacksonMichael** [clementine-player/Clementine#5136]
Hello, Clementine still automatically removes authors form ID3 tag. I'm not able to save authors here. Is it bug or am I doing something wrongly?
Thank you.

**Comment by Chocobozzz** [comment]
Can you try with the latest builds? http://builds.clementine-player.org/

**Comment by JacksonMichael** [comment]
Great, now it works, thank you, friend! :-)
