### ISSUE TITLE
Cannot open soundcloud configuration panel

### ISSUE THREAD

**Issue by bobberb** [clementine-player/Clementine#5139]
As title, when clicking into the SoundCloud config from either preferences or the internet tab I am not able to enter my login credentials or bring up the settings area at all.

**Comment by Chocobozzz** [comment]
Can you try with the latest build (http://builds.clementine-player.org/)? And if the issue is still here can you pastebin some logs and make a screen?

**Comment by bobberb** [comment]
Can confirm this is fixed in the current git
