### ISSUE TITLE
Error in vk.com auth

### ISSUE THREAD

**Issue by skobkin** [clementine-player/Clementine#5142]
Last two days I getting auth error in browser when clicking "Login" button on the vk.com options page.

Browser redirecting to `https://oauth.vk.com/error?err=2` and I getting following JSON instead of self-closing page that gets Clementine authenticated:

```js
{"error":"invalid_request","error_description":"Security Error"}
```

I think it can be some vk.com API changes.

**Comment by narunlifescience** [comment]
I don't think there was any recent changes in API. I could sign in to vk.com..

**Comment by Pastafarianist** [comment]
I could sign in to my vk account today (using a freshly-built version of Clementine from the latest code in the repository) but the plugin is broken in various ways which make it unusable anyway.

**Comment by skobkin** [comment]
@Pastafarianist I've just updated clementine from latest sources. Still getting error.

**Comment by skobkin** [comment]
I checked vk.com auth with Chromium instead of Opera Developer. Seems like Opera devs broken something. Clementine now working normally.
