### ISSUE TITLE
FFTW3 lib not found

### ISSUE THREAD

**Issue by mvidelgauz** [clementine-player/Clementine#5143]
Hello,
I just downloaded sources and trying to build under Windows. After installing several other required packages I can't pass "FFTW3 lib not found" error of CMake. Adding FFTW3_DIR does not help.
The FFTW3 package was downloaded from ftp://ftp.fftw.org/pub/fftw/fftw-3.3.4-dll64.zip (I aslo have ftp://ftp.fftw.org/pub/fftw/fftw-3.3.4-dll32.zip)

Her is full; CMake output:
Found Qt4: S:/Qt4/4.8.6/bin/qmake.exe (found suitable version "4.8.6", minimum required is "4.5.0") 
Found Qt4: S:/Qt4/4.8.6/bin/qmake.exe (found version "4.8.6") 
Boost version: 1.55.0
Could NOT find PROTOBUF (missing:  PROTOBUF_LIBRARY PROTOBUF_INCLUDE_DIR) 
FFTW3 lib not found. Set FFTW3_DIR to find it.
Checking for module 'libcdio'
  Package 'libcdio' not found
Checking for module 'libchromaprint'
  Package 'libchromaprint' not found
Checking for module 'gio-2.0'
  Package 'gio-2.0' not found
Checking for module 'glib-2.0'
  Package 'glib-2.0' not found
Checking for module 'gobject-2.0'
  Package 'gobject-2.0' not found
Checking for module 'gstreamer-0.10'
  Package 'gstreamer-0.10' not found
Checking for module 'gstreamer-app-0.10'
  Package 'gstreamer-app-0.10' not found
Checking for module 'gstreamer-base-0.10'
  Package 'gstreamer-base-0.10' not found
Checking for module 'gstreamer-cdda-0.10'
  Package 'gstreamer-cdda-0.10' not found
Checking for module 'gstreamer-tag-0.10'
  Package 'gstreamer-tag-0.10' not found
Checking for module 'indicate-qt'
  Package 'indicate-qt' not found
Checking for module 'libgpod-1.0>=0.7.92'
  Package 'libgpod-1.0>=0.7.92' not found
Checking for module 'libmtp>=1.0'
  Package 'libmtp>=1.0' not found
Checking for module 'libmygpo-qt>=1.0.7'
  Package 'libmygpo-qt>=1.0.7' not found
Checking for module 'libxml-2.0'
  Package 'libxml-2.0' not found
Checking for module 'qca2'
  Package 'qca2' not found
Checking for module 'QJson'
  Package 'QJson' not found
CMake Error at C:/Program Files (x86)/CMake/share/cmake-3.4/Modules/FindPkgConfig.cmake:360 (message):
  A required package was not found
Call Stack (most recent call first):
  C:/Program Files (x86)/CMake/share/cmake-3.4/Modules/FindPkgConfig.cmake:522 (_pkg_check_modules_internal)
  CMakeLists.txt:66 (pkg_check_modules)

**Comment by hatstand** [comment]
Building on windows is not supported, you're free to try but it will be very difficult. You're better off [cross compiling from an Ubuntu VM](https://github.com/clementine-player/Clementine/wiki/Compiling-from-Source-%28Windows%29)

**Comment by mvidelgauz** [comment]
Thank you hatstand, I'll try that cross compiling
