### ISSUE TITLE
ID3v2 ratings are not updated when modified externally

### ISSUE THREAD

**Issue by LeCluz** [clementine-player/Clementine#5145]
Clementine v1.2.3

Steps to repro:
Make sure the following options are enabled:

Update the library when Clementine starts
-Monitor the library for changes
-When Clementine Starts: Remember from last time
-Save ratings in file tags when possible

Modify the rating ratings to a song to 2 stars for example, from a 3rd party product (directly within Windows for example, or Winamp with the option "write ratings to file" enable)

In Clementine, select the song and right click > Edit track information. The rating value is not reflected.

However, this works fine when the library is originally built, when importing the songs the first time. This proves Clementine can read the tags successfully.

**Comment by ArnaudBienner** [comment]
Looks like what is described in issue #3666

**Comment by svnpenn** [comment]
https://github.com/clementine-player/Clementine/issues/1175
