### ISSUE TITLE
[OSX] Musics with special characters in their name not recognized in library scanning

### ISSUE THREAD

**Issue by atitan** [clementine-player/Clementine#5151]
Clementine 1.2.3-1450-gd50cfd5
Mac OSX 10.11.2

Folder name: 
[120704][PCCG-01280] TVアニメ「ゆるゆり♪♪」OPテーマ「いぇす! ゆゆゆ☆ゆるゆり♪♪」／七森中☆ごらく部 [Flac+Cue+BK+Vob]
File name:
七森中☆ごらく部 - いぇす！ゆゆゆ☆ゆるゆり♪♪.cue
七森中☆ごらく部 - いぇす！ゆゆゆ☆ゆるゆり♪♪.flac

This music disappeared in the library list.
I have to rename both folder and files to something it understands in order to get the library scanning works.

Besides, there's no problem playing files with this kind of name, but you'll have to add it directly to the playlist.

Thanks.

**Comment by santigl** [comment]
I couldn't replicate it in Linux with that directory and filename. Could you post the ID3 tags of the file?

**Comment by atitan** [comment]
The flac file doesn't have an ID3 tag. It relies on cue sheet to provide information.

**Comment by santigl** [comment]
Right, because it is a unique file with tracks, isn't it? 

And it isn't show at all in the library? Not even under *Unknown* artist?

**Comment by atitan** [comment]
Yes, the flac is an entire CD copy, which splits tracks using indexes in the cue sheet.

Here's the cue just for reference:
```
REM GENRE Anime(J)
REM DATE 2012
REM DISCID 2903B204
REM COMMENT "ExactAudioCopy v1.0b3"
PERFORMER "七森中☆ごらく部"
TITLE "いぇす！ゆゆゆ☆ゆるゆり♪♪"
FILE "bbb.flac" WAVE
  TRACK 01 AUDIO
    TITLE "いぇす！ゆゆゆ☆ゆるゆり♪♪"
    PERFORMER "七森中☆ごらく部"
    ISRC JPPC01201720
    INDEX 01 00:00:00
  TRACK 02 AUDIO
    TITLE "レッツラブ～でいきましょう♪"
    PERFORMER "七森中☆ごらく部"
    ISRC JPPC01201721
    INDEX 00 03:58:24
    INDEX 01 04:00:69
  TRACK 03 AUDIO
    TITLE "いぇす！ゆゆゆ☆ゆるゆり♪♪ [からおけ]"
    PERFORMER "七森中☆ごらく部"
    ISRC JPPC01201722
    INDEX 00 07:51:67
    INDEX 01 07:54:37
  TRACK 04 AUDIO
    TITLE "レッツラブ～でいきましょう♪ [からおけ]"
    PERFORMER "七森中☆ごらく部"
    ISRC JPPC01201723
    INDEX 00 11:52:65
    INDEX 01 11:54:35
```

OK, to clarify this, I have separated the music into another folder.
The following images show what happened when changing the folder and file name(as well the filename in cue sheet).

Before
![](https://i.imgur.com/QDLzKIj.png)

After
![](https://i.imgur.com/3SIaeWG.png)

**Comment by santigl** [comment]
I will try to recreate it in Linux with the info stored in a .cue.

Have you checked what happened when you changed only the directory name, before renaming the files?

**Comment by atitan** [comment]
I did. It seems that both folder and file name are unaccepted.
Changing only one of them won't work.

![](https://i.imgur.com/kCdIs0d.png)

**Comment by santigl** [comment]
Interesting. And have you tried launching it from a command line with the option `--verbose`? Maybe it spits out some error message with a clue.

I don't have access to a Mac, but I'll test it on Windows as a tie breaker.

**Comment by atitan** [comment]
Tried the option, but nothing happened. So I turned to syslog, only found messages about Qt on clementine startup.

I installed clementine on a Windows 7 machine, it works fine with that music.
Maybe it's a system specific issue.

**Comment by santigl** [comment]
Yes, I got the same result in Windows 7, too. We can say it's related to the system.

**Comment by naokiiwakami** [comment]
The character "ご" that appears twice in the path seems to be triggering the problem.  This character has two ways of representing in UTF-8/unicode that are U+3054 (ご) and pair of U+3053 (こ) and U+3099 (゛).  That confuses the logic to check existence of media files pointed by cue files.  It's a common problem that many languages have, so QString class provides a method to normalize unicode.
I reproduced this problem in my environment and verified that normalizing paths in media existing check solves the problem.

Here is my fix.
https://github.com/naokiiwakami/Clementine/commit/4cb57c05432caa33dde40bd170706f50383f4426

**Comment by santigl** [comment]
Cool! That's interesting.

You think that in Windows and Linux the normalization is happening at the file system or OS level?

**Comment by naokiiwakami** [comment]
I did some experiment and found that each OS handles unicode file names differently.

- OSX normalizes unicode characters to NFD when creating a file.  Displays NFC characters.
- Linux does not normalize a name string when creating a file.  Displays NFC characters.
- Windows does not normalize a name string when creating a file.  Displays an NFC character for a NFC code point.  Displays NFD characters for a pair of NFD code points.
See this page for more information about unicode normalization: https://en.wikipedia.org/wiki/Unicode_equivalence

I saw the problem happens when a file path has a NFD character.  Since all of Linux, OSX, and Windows can have NFD characters in file names, this problem is reproducible on all supported OS's.  But I think occurrence is much infrequent on Linux and Windows because they create NFC file names by using their input methods.  NFD happens only when you import file names from OSX.  On the other hand, you may see the problem often on OSX.

FYI, here is the experiment I did.  I created a file "ぎ" ('gi' in Japanese) and a directory "ご" ('go') on Linux, OSX, and Windows, and exchanged them vir tar balls.  Both "ぎ" and "ご" have equivalences.
On Linux:
```
[niwakami@localhost readdir]$ ls -F
linux/  osx/  osx.tar.gz  readdir*  readdir.c  windows/  windows.tar.gz
[niwakami@localhost readdir]$ ls -F linux osx windows
linux:
ぎ  ご/

osx:
ぎ  ご/

windows:
ぎ  ご/
[niwakami@localhost readdir]$ ./readdir linux
type=unknown(0), name=ぎ (e3 81 8e)
type=unknown(0), name=ご (e3 81 94)
[niwakami@localhost readdir]$ ./readdir osx
type=unknown(0), name=ぎ (e3 81 8d e3 82 99)
type=unknown(0), name=ご (e3 81 93 e3 82 99)
[niwakami@localhost readdir]$ ./readdir windows
type=unknown(0), name=ぎ (e3 81 8e)
type=unknown(0), name=ご (e3 81 94)
```
On OSX:
```
naoki-macbook:readdir naoki$ ls -F osx windows
osx:
ぎ	ご/

windows:
ぎ	ご/
naoki-macbook:readdir naoki$ ./readdir osx
type=file, name=ぎ (e3 81 8d e3 82 99) // hex values represent unicode byte stream
type=dir, name=ご (e3 81 93 e3 82 99)
naoki-macbook:readdir naoki$ ./readdir windows
type=file, name=ぎ (e3 81 8d e3 82 99)
type=dir, name=ご (e3 81 93 e3 82 99)
naoki-macbook:readdir naoki$ ./readdir windows_on_parallels
type=file, name=ぎ (e3 81 8d e3 82 99) // osx normalizes file name when creating a file
type=dir, name=ご (e3 81 93 e3 82 99)
```
On Windows (cygwin):
```
> ls -F osx windows
osx:
き゛  こ゛/

windows:
ぎ  ご/
> ./readdir osx
type=file, name=き゛ (e3 81 8d e3 82 99)
type=dir, name=こ゛ (e3 81 93 e3 82 99)
> ./readdir windows
type=file, name=ぎ (e3 81 8e)
type=dir, name=ご (e3 81 94)
```

**Comment by atitan** [comment]
Nice research.
This explains why sometimes I got "not found" when trying to access files transferred from OSX to Linux using scp via http.
