### ISSUE TITLE
Add the tag/column "original year" if available

### ISSUE THREAD

**Issue by tatapoum** [clementine-player/Clementine#5154]
Hi, I have some reedition CD and Picard Tagger gives two dates tags :
- Date which is used now 
- Original year which can be different of the date if this is a reedition CD

Would it be possible to integrate this field in the DB ? And to use it in the advanced grouping option ?

**Comment by paperbagcorner** [comment]
I think this is implemented in the development version. See pull request #4925.

**Comment by tatapoum** [comment]
Yes, you are right. I only searched in issues, not in pull requests.
I close this.
