### ISSUE TITLE
libechonest2.1 on Ubuntu 16.04

### ISSUE THREAD

**Issue by nazar-pc** [clementine-player/Clementine#5155]
I know it is kind of early, but on Ubuntu 16.04 there are first changes that break compatibility with Clementine from Wily repository.
libechonest2.1 is now transitional package and is in fact empty, while libechonest2.3 contains libraries and paths were changed accordingly to `/usr/lib/x86_64-linux-gnu/libechonest.so.2.3` and `/usr/lib/x86_64-linux-gnu/libechonest.so.2.3.1`. I've created symlink to them as `/usr/lib/x86_64-linux-gnu/libechonest.so.2.1` and Clementine works now, so libraries are binary compatible.

May I ask for starting building packages for 16.04? I'll post any incompatibilities as they arrive.

**Comment by Chocobozzz** [comment]
So I think this issue can be closed. Feel free to reopen. http://builds.clementine-player.org/ubuntu-wily/

**Comment by fitojb** [comment]
@Chocobozzz Your closing of this issue makes no sense (where’s your rationale?).

**Comment by Chocobozzz** [comment]
Oup's sorry, confused with the real version of Wily.

**Comment by davidsansome** [comment]
I've actually just been adding Xenial (16.04) builders to buildbot this week.  The builds are here now: http://builds.clementine-player.org/ubuntu-xenial/

**Comment by nazar-pc** [comment]
Awesome, will they appear in ppa as well?

**Comment by davidsansome** [comment]
Yep I just ran http://buildbot.clementine-player.org/builders/Ubuntu%20dev%20PPA%20Xenial so it should show up in the PPA in about an hour
