### ISSUE TITLE
Entries under "vk" in "Internet sources" are displayed twice

### ISSUE THREAD

**Issue by Pastafarianist** [clementine-player/Clementine#5165]
![image](https://cloud.githubusercontent.com/assets/1315874/11918991/6b51d006-a756-11e5-8ef0-1149f0272c5b.png)

Clementine compiled from the repository a few minutes ago. Gentoo Linux.

**Comment by narunlifescience** [comment]
Strange.. I have no problems here on arch

**Comment by Pastafarianist** [comment]
The problem went away after a restart. I'm not sure if I should close the issue.

**Comment by andykaycodes** [comment]
The same happened to me after clementine-1.2.3-1450-gd50cfd5 for some reason logged out from VK and I had to log in again. Right-clicking VK -> Update solved the issue. Maybe the developers should add automatic updating after re-login?

I have rolled back to clementine-1.2.3-1425-g7aca13c so far, never had any issues with that build.

**Comment by ivan-leontiev** [comment]
Hi guys. Thanks for the report. I can confirm the issue happened with the latest build on Arch.
Steps to reproduce:
  1. Restart Clementine
  2. Go to the Tools->Preferences. Then go to the vk.com internet provider settings.
  3. Login or relogin to the vk.com. 
  4. Close settings widow and try to expand Vk.com service item.

I will send PR as soon as possible.
