### ISSUE TITLE
RadioTunes.com no longer work

### ISSUE THREAD

**Issue by Israphel** [clementine-player/Clementine#5185]
Not exactly Clementine's fault, but if you play any stream from RadioTunes.com (Available on the Internet Tab), it just repeats: "get our free app, go to our page or give us your money"

If you copy the stream URL from the Firefox Console and add it as a custom stream on Clementine, it works.

**Comment by Abraka** [comment]
not working here...if I copy stream url It give me "error when playing". What stream URL work for you?

**Comment by Chocobozzz** [comment]
Seems that there are some issues with servers of Digally Imported. 

Moreover it they closed their streaming to 3rd party clients if you don't have a premium account (https://diradio.uservoice.com/forums/183400-digitally-imported-feedback/suggestions/11272656-restore-3rd-party-clients).

**Comment by Abraka** [comment]
thx for heads up...on provided link is working solution - http://pastebin.com/2b0HUaEx

**Comment by Abraka** [comment]
hm those a.sh.l.s already block that playlist I post above.

**Comment by Israphel** [comment]
everytime I got a working url, they block it...

also won't work with adblock or ublock.

**Comment by kumencz** [comment]
Command:
`curl -H "Host: pub1.radiotunes.com" -H "Referer: http://www.radiotunes.com/tophits" -H "User-Agent: Mozilla/5.0" http://pub1.radiotunes.com/radiotunes_tophits_aacplus?type=.flv -v | mpv -`
working for me now.
Is it helpful?

For mplayer users:
`curl -H "Host: pub1.radiotunes.com" -H "Referer: http://www.radiotunes.com/tophits" -H "User-Agent: Mozilla/5.0" http://pub1.radiotunes.com/radiotunes_tophits_aacplus?type=.flv -v | mplayer -`

**Comment by Israphel** [comment]
That curl works for me. Can't we get that inside Clementine?

**Comment by Abraka** [comment]
It works but quality of stream is really bad,

**Comment by Chocobozzz** [comment]
If Digitally Imported doesn't allow free streams on third party clients, just buy a premium account or listen to another radio provider. 
I'm sad about this too but Clementine can't "break the rules".

**Comment by kumencz** [comment]
Absolutely right way! 
Now I can't play music online as unregistered user. Sad end.

**Comment by Israphel** [comment]
Well, Icecast is better anyway

**Comment by mckaygerhard** [comment]
"cant break the rules" so curls can and clementine that has many things not? ironic! lest get anarch
