### ISSUE TITLE
is this project dead...last version is 3 years old?!?

### ISSUE THREAD

**Issue by Abraka** [clementine-player/Clementine#5191]
Its 3 years since last version 1.2.3 came out, so question is, should users of clementine move on to another player or are there any plans for update(in this millenium)? Base on activity on github, there are some pulls, but 3 years without new version...thats sad even for opensource project!

**Comment by Chocobozzz** [comment]
1 year and a half, not 3 years

https://github.com/clementine-player/Clementine/releases

**Comment by gomera** [comment]
we are almost there now ...

**Comment by AnthonyWC** [comment]
3 years now. :(
