### ISSUE TITLE
Tracks not getting added to my library

### ISSUE THREAD

**Issue by okelk** [clementine-player/Clementine#5192]
New Tracks don't get added to my library anymore. doesn't matter if i just put them into my library folder or move them into the library using clementine. A full library rescan doesn't help either.

I'm using clementine 1.2.2 under mac OS X 10.10.2 my Library is located on en external usb harddrive.

**Comment by narunlifescience** [comment]
Did you try 1.3rc1 pre-release https://github.com/clementine-player/Clementine/releases ?

**Comment by okelk** [comment]
I did try the 1.3rc1 right now... full library scan took longer than it ever did (still ok for the size of it though) but everything was found as far as I can tell.
Thanks!
