### ISSUE TITLE
No mans with latest debs

### ISSUE THREAD

**Issue by Yanpas** [clementine-player/Clementine#5199]
1.3rc1:amd64.deb doesn't ship man files, is it ok?

**Comment by hatstand** [comment]
There are no man pages.

**Comment by mk-pmb** [comment]
> There are no man pages.

Ok, that explains why I couldn't find it even with quite thorough searching. So is there another list of the command line options? Unfortunately, `clementine.exe --help` doesn't produce any output in the 1.3.1 windows build on win8.

There's an [Ubuntu man page](http://web.archive.org/web/20160809230459/http://manpages.ubuntu.com/manpages/precise/man1/clementine.1.html), potentially rendered from [this file](https://github.com/AlexanderP/dsc-file/blob/ea1a41bfb784795fb395c107953532399f91e253/debian-clementine/clementine.sgml) I found [searching Github for `"manual page documents briefly" clementine`](https://github.com/search?utf8=✓&q="manual+page+documents+briefly"+clementine&type=Code&ref=searchresults), but I can't find a simple plaintext version of it anywhere.

If there's no text editor friendly command list yet, could you host one and have your release scripts maintain it?
