### ISSUE TITLE
Panel icon theme.

### ISSUE THREAD

**Issue by elmat0** [clementine-player/Clementine#5208]
I've read elsewhere in this bug tracker that the tray icon can be changed by adding `clementine-panel.png` and `clementine-panel-grey.png` to a theme. This is great and works as expected, though I'd like to know if it is possible to also replace the play and pause button that gets overlayed on top? I presume they are coming from `tiny-start.png` and `tiny-pause.png`, although replacing those doesn't seem to have any effect.

I am trying to use clementine on elementary (monochrome panel icons) and the alternative of capturing all the potential icon image names to use [via sni-qt](https://github.com/mank319/elementaryPlus/issues/264) seems rather daunting.

**Comment by narunlifescience** [comment]
no that wont help those two icons will be always loaded from clementine resource files..

**Comment by narunlifescience** [comment]
If possible, I will make a pull request to fix this..

**Comment by elmat0** [comment]
That would be great! Even if it just looks for say, `clementine-panel-pause.png` and `clementine-panel-play.png` before falling back to the others.

**Comment by narunlifescience** [comment]
I left out these icons in commit #5051 intentionally because they were in pairs.. will try to make all the remaining hard coded icons modifiable..

**Comment by narunlifescience** [comment]
@elmat0 this issue should be resolved now.. could you please check

**Comment by Chocobozzz** [comment]
Without news of the reporter, closing this issue. Thanks @narunlifescience
