### ISSUE TITLE
Remove song from playlist after playing

### ISSUE THREAD

**Issue by otoman** [clementine-player/Clementine#5211]
Hi
I got an idea... Feature "Remove song from playlist after playing"? I think I'm not only who would love this function :)

**Comment by santigl** [comment]
You propose that as a global on/off setting, or a per-track "play and delete" function?

**Comment by otoman** [comment]
I think global on/off is better...

**Comment by TheUbuntuGuy** [comment]
The Dynamic Playlist mode already sort of does this. Once a track is played, it it removed from the playlist after a 2 track delay. I'm not sure I get the exact use case for what you are proposing. I just don't want to go adding a bunch of similar obscure features.

**Comment by otoman** [comment]
This is exactly, what I'm looking for :) Thank you
