### ISSUE TITLE
Can't double-click artist/albums to queue/play them

### ISSUE THREAD

**Issue by jagerman** [clementine-player/Clementine#5226]
In 1.2.3, you can double-click an expandable artist or album in the library view to enqueue everything under it; in current git HEAD this doesn't work anymore: the first click of the double-click sequence starts an expansion/collapse, and second double-click starts the opposite collapse/expansion, but nothing gets queued.

In 1.2.3, the first click of the double-click would expand/collapse (without a sliding animation), and the second click of the sequence would queue.

The change that broke it is 8020749375597435acd6f5cd72bdcd0276b4076e -- the commit that added animated expansion.  When I revert this change and recompile, I get back the old behaviour.

The animation is nice, but not at the cost of not being able to quickly queue/play an album!

**Comment by Ferroin** [comment]
+1 on this, and ideally adding the ability to just disable the animations.  Some people don't care about it looking fancy,  and would rather not spend the processor cycles on animations.

**Comment by ivan-leontiev** [comment]
Hi, I have fixed this issue in PR #5213 with animations preserved.

**Comment by narunlifescience** [comment]
Sorry guys! just tested #5213, it seems to fix this issue.. thanks @ivan-leontiev 
@hatstand could you please check #5213 & merge or revert 8020749 please.. I think this should be fixed in the new release

**Comment by jagerman** [comment]
#5213 (in particular b85d09cd9c488582fff83e7115e5c7dd5c739df0) looks like a much better fix to this than reverting the animation.  Thanks @ivan-leontiev !

**Comment by ArnaudBienner** [comment]
Fixed now #5213 has been merged

**Comment by narunlifescience** [comment]
Thanks @ArnaudBienner !

**Comment by mmccoy37** [comment]
I have built and installed 1.3.1 and I am experiencing this bug, and have been experiencing it for a while. That is why I built latest today.

Double click just opens and closes the album. I am running Debian testing. 

![bug-1](https://cloud.githubusercontent.com/assets/5104620/14805204/ddff63bc-0b37-11e6-9982-79094d62505e.gif)
