### ISSUE TITLE
Transcode to MP3 reports Could not create the GStreamer element "xingmux" - make sure you have all the required GStreamer plugins installed

### ISSUE THREAD

**Issue by afxmac** [clementine-player/Clementine#5231]
Using 1.3RC1 on OS X 10.11, trying to transcode FLAC files to MP3 results in a failed transformation, the log shows:

Sat Jan 30 19:41:24 2016: Transcoding 1 files using 8 threads
Sat Jan 30 19:41:24 2016: Starting /Volumes/music/Annie Lennox/The Unplugged Collection Volume One/14-Why.flac
Sat Jan 30 19:41:24 2016: Using 'lamemp3enc' (rank 256)
Sat Jan 30 19:41:24 2016: Adding xingmux and id3v2mux to the pipeline
Sat Jan 30 19:41:24 2016: Setting lamemp3enc property: target = 1
Sat Jan 30 19:41:24 2016: Setting lamemp3enc property: cbr = true
Sat Jan 30 19:41:24 2016: Could not create the GStreamer element "xingmux" - make sure you have all the required GStreamer plugins installed
Sat Jan 30 19:41:24 2016: Couldn't find an encoder for audio/mpeg, mpegversion=(int)1, layer=(int)3, check you have the correct GStreamer plugins installed

**Comment by Morthawt** [comment]
I have this issue since I formatted my computer and installed the brand spanking new version of clementine. Now I cannot transcode... I tried installing some gstreamer thing but it still is not working even though I manually ticked all options on the gstreamer installer.

**Comment by rome-legacy** [comment]
same issue, first-time mac installation 1.31

**Comment by stevec99** [comment]
Any fix for this?

**Comment by conspacer** [comment]
This issue is still unfixed, latest Clementine on W10, latest gStreamer installed with all options... same error:
> Could not create the GStreamer element "xingmux" - make sure you have all the required GStreamer plugins installed
> Couldn't find an encoder for audio/mpeg, mpegversion=(int)1, layer=(int)3, check you have the correct GStreamer plugins installed

**Comment by stevec99** [comment]
Yeah, I’ve given up hope

**Comment by darrien28** [comment]
Hi Clementine folks....

I think it would be a fairly fundamental thing to have the ability to transcode to MP3.    

Please guys, make some kind of response - even if it's simply to tell us that you're not going to fix this problem so we can go buy something else somewhere else....!!!   :-(  

I've done heaps of searching but can't seem to find any fix or plugins that actually fix the xingmux problem.  :-(      I managed it once ages ago, but now - it's not working.

Please do respond.  C'mon!!!

Danny.

**Comment by darrien28** [comment]
I'm not sure why it was closed when it's not resolved?  I've asked hatstand for some help for less technical people like me.  I can say if we've paid for something hen it should be fixed and work!

**Comment by stevec99** [comment]
He submitted a fix https://github.com/clementine-player/Clementine/commit/913cc29186745733d518fd211c939d17fe6224b6
