### ISSUE TITLE
spotify song queued doesn't play after a library song 

### ISSUE THREAD

**Issue by gitnoob16** [clementine-player/Clementine#5234]
Hi, when I queue some tracks, including some from my local library and others from spotify the song from spotify doesn't play and appears a text "saving in cache 0%" which keeps in that number. When I click manually the "next song" button it plays normally.

**Comment by ArnaudBienner** [comment]
I thought I fixed something like this recently.
Which version are you using?

**Comment by gitnoob16** [comment]
Hi thanks for the answer, I use 1.2.3 version in linux, I also tried 1.2 and 1.2.3 in windows and I have the same issue, only happens when a spotify song is queued after a local song. When I queue spotify songs exclusively I dont have the issue.

Thanks for your help

**Comment by ArnaudBienner** [comment]
Could you please try the release candidate for the next release and let us know if the problem is fixed?
https://github.com/clementine-player/Clementine/releases/tag/1.3rc1
Thanks a lot :)

**Comment by gitnoob16** [comment]
Hi 1.3 rc1 in windows works great and the problem seems to be fixed but with linux I can't even login to spotify, there is a message that says "connecting to spotify", that's weird because I tried with my correct password and with an incorrect password and the message is the same, so it seems that is not connecting to spotify, can you suggest me something? I'm using linux mint 17.3 and the clementine_1.3.0-rc1-trusty_amd64.deb donwload.

By the way, thanks you for your answer, I appreciate your help, finally I can use a very decent player and unninstall the spotify player!

**Comment by ArnaudBienner** [comment]
OK, thanks for letting us know :)
If you experience another issue, please open a separate bug (it's confusing to reference multiple things in the same place)
