### ISSUE TITLE
Clementine is Crashing in Windows 10

### ISSUE THREAD

**Issue by sonokamome** [clementine-player/Clementine#5235]
Hello. I seem to be having trouble with Clementine suddenly. I was starting up Clementine (version 1.2.3) when suddenly on the Window title, all the titles of the tracks already on the track listing were flashing in sequential order and then the program would crash and close.

I'm not sure what could have caused this behavior.

I have done the following:

1. I have uninstalled Clementine
2. I have deleted the HKCU_Program folder tree in the registry of Windows (Windows 10 Pro x64)
3. I have deleted the Clementine folder that's in the /Windows/Users/<username/>/.config/Clementine

And then reinstalled Clementine only to find that it still is giving the same problems with the same behavior and I'm not sure what is going on.

I'm tempted to use a newer development release version (1.2.3 - xxxx) to see what happens next although I'm doubtful that will help.

**Comment by amuttsch** [comment]
The latest dev builds work on windows 10 for me. Please try them and report back, thanks.

**Comment by sonokamome** [comment]
I turned off my computer and then came back to it just now, followed by reinstalling 1.2.3-1515-gac0aff5. And now it seems to be working alright.

I did forget to mention that I defragged the hard disk that Clementine was installed in so that could have been the reason why it was behaving so oddly. 

Well in any case, I'm glad that it's back to to normal as this is my primary audio player along wtih Foobar2000 being my secondary when I need it (.opus playback to be more specific).

So consider this ticket closed.

**Comment by sonokamome** [comment]
I wanted to follow up with an observation I've seen with Windows 10 Pro x64.

It seems that this problem stems from having _**Fast Boot**_ on (which I think is set on default to be on).

But say I either turn it off or, go on _**Power Shell**_ and use the command "`Stop-Computer`" to then do a complete shutdown, and then Clementine goes back to functioning normally.
