### ISSUE TITLE
Clementine stopped scrobbling Soundclound and certain radio streams, missing search results for Soundcloud and further ones 

### ISSUE THREAD

**Issue by Manzanar** [clementine-player/Clementine#5236]
All, 

I'm using two computers with clementine, Unbuntu 14.1 on a laptop and a MAC with OSX Mavericks 10.9.5 that was recently updated. All is working fine on the Ubuntu system. 
Short time ago the following problems appeared on the mac: 
1) Streaming of radio stations possible but scrobbling to Last.fm does not work any longer (but this works on ubuntu!) - e.g. no scrobbling from byte.fm and Soma, but playing works. Could be related to the playtime indicator that is not moving with streams?
2) No search results in Soundcloud. All Soundcloud content in playlists has been deleted from the player. No search results even with other providers - only Magnatune gives results back. 

Is that the result of a Mac Update?

**Comment by liftarn** [comment]
I'm running MS Windows and also notice that SoundCLoud don't scrobble while the library does.

**Comment by rollopack** [comment]
Same radio scrobbling problem on windows, with developper build to.
No problem with the scrobbling from the library.

**Comment by Manzanar** [comment]
Problem with soundcloud results was solved with OSX Version 1.3.1. 
Scrobbling problems remained.
