### ISSUE TITLE
spotify search doesn't work sometimes (problem on libSpotify server side)

### ISSUE THREAD

**Issue by thingthesecond** [clementine-player/Clementine#5238]
hello dear people, 
everything was working fine til yesterday, now not anymore.
before all this, i could just type "bowie" in the search section and would get results of my library first, then soundcloud, then spotify. there i would see different artists with bowie in their name, a drop down menue would allow me to browse through some of his albums and songs. i could specify my search with "bowie heathen" and would get his heathen album.
alternatively i could click "internet", find spotify and search. here there would be no categorisation with albums. searching "bowie" would give me a variation of songs connected to that word. searching "bowie heathen" probably would have given me the songs of that album.

since yesterday nothing works anymore. i have tried a lot of times. i am still logged in on spotify, i checked in properties. i changed the spotify password and logged in again, still no good.
weirdly my spotify-playlists are shown and it's possible to play them, also single songs out of them. but typing "bowie" gives no results. one time out of 30 times it worked, but when i specified my search it disappeared again and didn't come back when i search again. 
with a less specific search like "iggy" it doesn't work at all, none of 100 tries.

am i the only one with this problem?
any idea what could have happened?

thanks a lot,
cheers,
samantha

**Comment by alexander-b** [comment]
Same here.

**Comment by ArnaudBienner** [comment]
Which version are using? On which OS?
I have the problem on windows, but OS X was working find last time I tried.

**Comment by alexander-b** [comment]
1.2.3 on GNU+Linux (Gentoo) here.

**Comment by L0n3Sn1p3r** [comment]
Having the same problem. 1.2.3 on Arch Linux, tried updating libspotify to 12.1.51. Doesnt help.
Spotify Playback still works tho, I can add music from my Spotify playlists to the queue and it plays properly.

**Comment by ArnaudBienner** [comment]
Thanks for the info.
Actually, I was wrong: the problem appears on all platforms (OS X, Linux, Windows), definitely sounds like a problem on Spotify side.
I will contact them to see what's going on.

**Comment by alexander-b** [comment]
I think it might have resolved itself by now.

**Comment by L0n3Sn1p3r** [comment]
I can confirm, as of now it works fine.

**Comment by ArnaudBienner** [comment]
Great! I confirm it's fixed here too.

**Comment by alexander-b** [comment]
I think you may have jumped the gun/jinxed it. It's back to broken here now.

**Comment by alexander-b** [comment]
And back working again. Hopefully for good this time. :]

**Comment by thingthesecond** [comment]
yes thank you, all the same with me, working again, then broke again, then working again. must be something the people from spotify do, maybe testing something. i just hope it's not their intention to keep us away from using spotify on other platforms than their own. and i hope i didnt give them the idea by asking them about what happened and how i use their service...

**Comment by matthewtraughber** [comment]
This is still an issue (Clementine 1.2.3 on Fedora 23). Spotify playlists work, but search is not returning any results (on Search or Internet tabs).

**Comment by alexander-b** [comment]
Yes, it keeps reappearing.

**Comment by P-D-G** [comment]
I've tried with multiple Clementine and libspotify versions, and can confirm it doesn't seem to come from the client's side. For completeness, here is an extract of the console log when searching on spotify : http://pastebin.com/st7H9edN

**Comment by ArnaudBienner** [comment]
"Louise Ataque"? Good music taste ;)
We should try to contact Spotify about this. But the contact I had there doesn't seem to work at Spotify anymore, and on their developer page, they say they don't support libspotify (but don't have replacement (sic)) so I'm not sure how to contact them.
But I will have another look.

**Comment by thingthesecond** [comment]
three days now....got cold turkey
i wish all you wonderful experts find a way soon, me i dont understand deeper technical things yet...

**Comment by Chocobozzz** [comment]
I found a clue on twitter: https://twitter.com/kingosticks/status/697906633662398464. So libspotify seems to use the old metadata API.

Maybe we should rewrite the search function using the new search API (https://developer.spotify.com/web-api/migration-guide/)?

**Comment by ArnaudBienner** [comment]
As per discussion "Can't search in Spotify catalogs through Clementine v1.2.3": fixed on Spotify side, hopefully for good now.

"Guys, I wrote to Spotify and they fixed it for like 5 minutes! They are great and together with Clementine they both rocks!
Spotify catalog search with Clementine is available again! Enjoy! If you are experiencing search difficulties write to them @spotifycares in Twitter - their support is pretty good! "

**Comment by thingthesecond** [comment]
phantastic! thank you sooo much!!!!!
