### ISSUE TITLE
build Clementine for Windows in MXE

### ISSUE THREAD

**Issue by pavelvat** [clementine-player/Clementine#5240]
See:
http://mxe.cc/
https://github.com/mxe/mxe/
Table of all supported package http://mxe.cc/build-matrix.html
1)Install MXE http://mxe.cc/#tutorial
2)```cd /path/to/install/mxe/```
3)```make fftw libcdio chromaprint protobuf qjson gstreamer gst-plugins-base gst-plugins-good gst-plugins-bad gst-plugins-ugly taglib cryptopp libechonest glew qt boost MXE_TARGETS='i686-w64-mingw32.shared'```
4)```cd /path/to/src/of/clementine/ && mkdir builddir && cd builddir```
5)Run cmake: ```/path/to/install/mxe/usr/bin/i686-w64-mingw32.shared-cmake /path/to/src/of/clementine/```
Problems with cmake configure:
1)Clementine/CMakeLists.txt: line ```pkg_check_modules(QJSON REQUIRED QJson)``` don't work:
```
-- checking for module 'QJson'
--   package 'QJson' not found
```
if replace it to line: ```find_package(QJSON REQUIRED)``` it's worked.
2)cryptopp don't detected:
```
CMake Error at CMakeLists.txt:279 (message):
  Either crypto++ must be available or the non-GPL Spotify code must be
  compiled in
```

**Comment by hatstand** [comment]
You probably need to set `PKG_CONFIG_PATH` to something useful. You're generally going to have a bad time doing this anyway and we already documented and semi-support a different way on the wiki.

**Comment by pavelvat** [comment]
>we already documented and semi-support a different way on the wiki.

In my opinion the use MXE is much more convenient.

Following the instructions of the wiki https://github.com/clementine-player/Clementine/wiki/Compiling-from-Source-%28Windows%29, I get an error when build the gst-plugins-base:
```configure.ac:1: error: Autoconf version 2.69 or higher is required```
