### ISSUE TITLE
Clementine forgets audio output preference

### ISSUE THREAD

**Issue by Llamatron2112** [clementine-player/Clementine#5241]
Hello,
I'm on Arch and using a mixed pulseaudio/jack setup to manage my two cards. I want to use the jack output for clementine. Setting the jack output it in the preference works, but after closing and re-opening the preferences, automatic mode is selected, and is applied if I save the preferences.

It works fine on stable 1.2.3, getting this behavious from master and release-1.3 (not sure if they're the same or not)

**Comment by santigl** [comment]
When you re-open the window and automatic mode is selected, are the two cards still displayed on the drop-down list?

Also, are you playing a file between changes?

**Comment by Llamatron2112** [comment]
To be more acurate:

In my Output Device dropdown menu, the two first entries show an icon and correspond to my Pulseaudio sinks (internal soundcard & jack sink), followed by several "Default device on..." without any icon.

If I select any of the two first ones, the audio plays through Pulseaudio to the selected output, and the change stays when I reopen the preferences.

If I select any of the "Default device on..." items, the change is applied, for example with "Default device on Output audio to a JACK Server" Clementine connects directly to the JACK server, but when I open the preferences again, then "Choose Automatically" is selected.

I tried playing audio (or not) between the preferences window opening and it doesn't change anything.

The reason why I'd like to connect to JACK directly is avoiding potential resampling and remixing through two sound servers.

**Comment by tahiro86j** [comment]
I seem to be having the same issue on UbuntuStudio 16.04. Any developments on the issue?

**Comment by gilFuser** [comment]
same here. Annoying.

**Comment by wolftune** [comment]
I'm having a similar issue. I can't get Clementine to play anything at all. I'm on KDE Neon. Whenever I choose a setting in the audio preferences, close the window, open the preferences again, it's always back to auto, and nothing ever plays.

**Comment by nikolavitas** [comment]
Same here: Clementine 1.2.3, Kubuntu 16.04 with the latest updates, MacBook Pro mid 2013. 

No matter what I set as a preference for the output device, Clementine forgets it immediately.

**Comment by themaddoctor** [comment]
Same. Clementine 1.3.1

**Comment by dkowis** [comment]
Ubuntu 18.04 here, Clementine installed at: Version: 1.3.1+git276-g3485bbe43+dfsg-1.1build1

For me the behavior happens also when I click next or make non-automated changes between tracks. I have to go into the audio settings in KDE and switch the default output from the internal speaker to the bluetooth headphones again. None of the other audio outputs are doing this, it's only happening to clementine so far. I've even gone so far as to configure clementine to prefer the bluetooth output in it's settings 
![image](https://user-images.githubusercontent.com/28048/41373837-1a98a4a6-6f17-11e8-850a-8d22202c047f.png)

**Comment by jonaski** [comment]
I can confirm this and see the problem. I'm fixing it now.
