### ISSUE TITLE
Undo/disable column sorting

### ISSUE THREAD

**Issue by tweedbeats** [clementine-player/Clementine#5244]
I use this amazing player to create very specifically ordered playlists that end up being in the hundreds of tracks. The problem happens if I accidentally click any of the sorting columns, and the order of the playlist gets lost. Not sure how this can be prevented, perhaps an undo operation would suffice? Adding an option to disable column sorting (in the column menu) might be another way of stopping the problem. Looks like issue 4844 is related to this one.

**Comment by paperbagcorner** [comment]
Have you tried Ctrl-Z?

**Comment by tweedbeats** [comment]
@paperbagcorner 
Ohh very nice! I didn't think of that, and I just noticed the undo/redo arrows, yikes. I think I tried to right-click the column, and I'm pretty sure I checked the Playlist menu. Maybe add the "Undo Last Sort" in either location for semi-blind people like me? Thanks anyway!

**Comment by paperbagcorner** [comment]
The undo options are in the menu you get by right clicking in the body of the playlist.
![playlist](https://cloud.githubusercontent.com/assets/6204713/13012418/78c8e54c-d1ab-11e5-823d-f41f40bbc990.png)
