### ISSUE TITLE
Deezer

### ISSUE THREAD

**Issue by lobodetaipas** [clementine-player/Clementine#5245]
Ok its been 3 years of the last request for it.
I think now it finally can happen

**Comment by Chocobozzz** [comment]
Do they have a streaming API?

**Comment by lobodetaipas** [comment]
I dont know technical details, but they havê in they develeopers section
Em 10/02/2016 10:53, Bigard Florian <notifications@github.com> escreveu:Do they have a streaming API?

**Comment by Chocobozzz** [comment]
Duplicate of https://github.com/clementine-player/Clementine/issues/3531

It seems they still don't have a streaming api for desktop application.

**Comment by lbssousa** [comment]
Deezer has released a "Native SDK" in April 2016:

http://developers.deezer.com/sdk/native

Maybe it has what you want for integrating the service with Clementine.
