### ISSUE TITLE
Clementine segfaults on exit

### ISSUE THREAD

**Issue by coconutlulz** [clementine-player/Clementine#5250]
Build from 729dc8e281e30614ddc8914163a8b8b390363423.

To reproduce:
- Open Clementine.
- Press Ctrl+Q (or select 'exit' from the menu).
- Terminal output:
`15:59:58.823 DEBUG DeviceKitLister:36               virtual DeviceKitLister::~DeviceKitLister()`

`15:59:58.824 DEBUG CoverProviders:54                Unregistered cover provider "last.fm"`

`[1]    28154 segmentation fault  ./clementine`

**Comment by hatstand** [comment]
Actual stack trace:
```
#0  0x00000000009fb6f6 in std::default_delete<PodcastBackend>::operator()(PodcastBackend*) const ()
#1  0x00000000009f9821 in std::unique_ptr<PodcastBackend, std::default_delete<PodcastBackend> >::~unique_ptr() ()
#2  0x00000000009f8dc8 in Lazy<PodcastBackend>::~Lazy() ()
#3  0x00000000009f46b8 in Application::~Application() ()
#4  0x00000000009f0773 in main ()
```

**Comment by coconutlulz** [comment]
Oops, sorry, I should have provided that. Thanks!
