### ISSUE TITLE
Frequency adjustment (16k) of the equalizer

### ISSUE THREAD

**Issue by Dankuyn** [clementine-player/Clementine#5255]
Hello,
Since early versions of Clementine (Linux and Windows), I note that your audio has a poor sound treble. After trying various settings, I got to the problem: the equalizer in the range of 16k, which is reversed. Bringing the control decreases the treble. (Forgive my poor English).

Thanks!

**Comment by TheUbuntuGuy** [comment]
Duplicate of #695. It's a bug with gstreamer, not Clementine.
