### ISSUE TITLE
Allow user to pick a specific icon theme for Clementine, independent of system icon theme

### ISSUE THREAD

**Issue by lavacano201014** [clementine-player/Clementine#5258]
Related to issue #2298 (whose original Google Code page, and therefore the screenshot attached to it, has disappeared, [so here's a new one using Plasma 5's default Breeze](https://cloud.githubusercontent.com/assets/4407155/13059223/7dbc5a00-d3dd-11e5-81bc-7408d86ac4e2.png)), but I wouldn't go so far as to call it a duplicate.

Sometimes, the system icons don't get along with Clementine. In my case, the system icons are just too small. Sure, I could put in the effort to replace the icons that don't fit. But it would be way easier on me if I could just configure Clementine to ignore my system icon settings and use the Oxygen icon set that I happen to have still installed and know for a fact works just fine with Clementine.

If this is already present in the program and I'm just blind, feel free to point it out. :V

**Comment by narunlifescience** [comment]
Linux :

   1. Create a folder “customiconset” inside ~/.config/Clementine/
    2. copy the.zip contents to ~/.config/Clementine/customiconset
    3. restart clementine..

download zip file from http://www.filedropper.com/customiconset
