### ISSUE TITLE
Clementine minimises to task bar on startup and stays there

### ISSUE THREAD

**Issue by Clementine-Issue-Importer** [clementine-player/Clementine#526]
_From [masterperas](https://code.google.com/u/111103910354402213754/) on July 20, 2010 10:11:26_

When i run clementine it immediatly minimizes to task bar and will not maximize again. I can play musics and skip tracks and the application is responsive but i can never open the window back up.

im using Clementine 0.4 on Windows XP.

Any way to run clementine in debug mode or get logs so i can provide more info?

_Original issue: http://code.google.com/p/clementine-player/issues/detail?id=526_

**Comment by kiwiheretic** [comment]
I am having the same issue on Zorin 16
