### ISSUE TITLE
Unable to build on ubuntu trusty

### ISSUE THREAD

**Issue by Yanpas** [clementine-player/Clementine#5264]
I'm using Linux Mint 17.3 (ubuntu 14.04) and I fail to build latest clementine. I follow guides on github wiki, but all to no avail

```
Linking CXX static library libprojectM.a
[  6%] Built target projectM
[  6%] Generating moc_qsql_sqlite.cxx
moc: Cannot open options file specified with @
Usage: moc [options] <header-file>
  -o<file>           write output to file rather than stdout
  -I<dir>            add dir to the include path for header files
  -E                 preprocess only; do not generate meta object code
  -D<macro>[=<def>]  define macro, with optional definition
  -U<macro>          undefine macro
  -i                 do not generate an #include statement
  -p<path>           path prefix for included file
  -f[<file>]         force #include, optional file name
  -nn                do not display notes
  -nw                do not display warnings
  @<file>            read additional options from file
  -v                 display version of moc
make[2]: *** [3rdparty/qsqlite/moc_qsql_sqlite.cxx] Ошибка 1
make[1]: *** [3rdparty/qsqlite/CMakeFiles/qsqlite.dir/all] Ошибка 2
make: *** [all] Ошибка 2
```

Ignoring errors leads to huge amount of such kind of errors

**Comment by Chocobozzz** [comment]
Did you install all these packages? https://github.com/clementine-player/Buildbot/blob/master/slave-ubuntu-trusty-64/Dockerfile#L7

Or you can use a prebuild package: https://builds.clementine-player.org/

**Comment by Yanpas** [comment]
`libqca2-plugin-ossl` was missing in official dependencies list. I've installed it, but that doesn't solve building error.

I want to commit something to Clementine, so I need to be able to build it myself

**Comment by DT-pas19** [comment]
Strangely enough, this moc "**Cannot open options file specified with @**" error appears if a path to a build folder contains non-latin characters.
For example, I'm using Debian sid with russian localization. The error occurred in case of compilation in the Documents folder (in russian, _Документы_ - the name which clearly has non-latin characters). A directory change resolved the problem.

**Comment by Yanpas** [comment]
@DT-pas19 thanks! That was the root of the problem. Guess this note should be added to **how to build** wikipage
