### ISSUE TITLE
DI.fm streams are not available

### ISSUE THREAD

**Issue by murderered** [clementine-player/Clementine#5268]
When opening a stream from Digitally Imported as non-premium user, a message is played that DI.fm is not more available outside their website. Playing via website works, so i think they've changed their policy for streaming to external players.

The DI module should not list streams which are not accessible (resulting in no streams for users without verified premium). According to [their premium service description](https://www.di.fm/premium) streaming to external players is still possible - for premium people.

**Comment by hatstand** [comment]
Already fixed
