### ISSUE TITLE
Crash after stream playback

### ISSUE THREAD

**Issue by Araeos** [clementine-player/Clementine#5271]
## Reproduction
1. Open Clementine
2. Play an audio stream (online radio)
3. While playing the stream play any file on the local disk (mp3)

## Expected Behaviour
Stop playing the stream, start playing the file

## Actual Behaviour
In most cases Clementine crashes at the exact moment the file is started.
When debugging, Visual Studio 2015 reports a integer division by zero error.

P.S.: I cannot find any log file on windows nor any documentation on generating one.

## Additional Information
- OS: Windows 10
- Clementine Version 1.3 rc2 & rc1 (both)

**Comment by narunlifescience** [comment]
I think this issue got fixed with the commit b0322e7. could you try the latest developer build and report back https://builds.clementine-player.org/

**Comment by Araeos** [comment]
The newest version I can find through your link is from February 17th (rc2), which crashes on my system as described above.
Since the release is not tagged on github, I wouldn't know if the commit is included in that release.

**Comment by narunlifescience** [comment]
oops.. I just mentioned the wrong commit.. the right one is pull request #5263. that was committed after feb 17th.. so you will have to wait for a new developer build..

**Comment by narunlifescience** [comment]
I could find new builds here https://builds.clementine-player.org/win32/release/ 	latest: ClementineSetup-1.2.3-1574-g357af22.exe (build date 29-Feb-2016). even though it is not a 1.3 release candidate , this should include the fix #5263. why not you check with this version ?

**Comment by Araeos** [comment]
I just tried v1.2.3 r1570 and r1574. It seems this bug got fixed in between, supporting the fix for issue #5263. So consider this issue as a duplicate.
Thanks for your support.
