### ISSUE TITLE
Could not demultiplex stream with .wma file

### ISSUE THREAD

**Issue by matkoniecz** [clementine-player/Clementine#5273]
What steps will reproduce the problem? 1. Add an .wma file to your playlist
2. Play it back
3. After about 1-2 minutes in the playback will abort with this error message:

Could not demultiplex stream.

I am running Clementine 1.2 on Ubuntu 14.04.4 LTS

uname -r
3.13.0-79-generic

lsb_release -a

No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.4 LTS
Release:	14.04
Codename:	trusty

Seems to be similar to #3593 (or even exactly this issue).

If useful I may provide wma file that is causing this problem but it seems that it is basically https://github.com/clementine-player/clementine/issues/3593#issuecomment-45401099 .

**Comment by narunlifescience** [comment]
try 1.3 pre release version from https://github.com/clementine-player/Clementine/releases

**Comment by matkoniecz** [comment]
I tried on clean Ubuntu 15.10 install, now it fails with http://askubuntu.com/questions/456072/clementine-wont-play-wma-with-your-gstreamer-installation-is-missing-a-plugi and none of solutions that were supposed to be fixes are working.

**Comment by matkoniecz** [comment]
Clementine 1.3 rc1 works correctly.
