### ISSUE TITLE
SQLite says there is no tokenizer=unicode

### ISSUE THREAD

**Issue by tureba** [clementine-player/Clementine#5278]
Hi,

I get the following when launching Clementine (branch release-1.3) from the command line:

> 18:28:16.769 WARN  Database:274                     Couldn't register FTS3 tokenizer 
> 18:28:16.771 DEBUG Database:444                     Applying database schema update 13 from ":/schema/schema-13.sql" 
> 18:28:16.772 ERROR Database:573                     db error:  QSqlError(1, "No foi possvel obter a linha", "**unknown tokenizer: unicode**") 
> 18:28:16.772 ERROR Database:574                     faulty query:  "CREATE VIRTUAL TABLE songs_fts USING fts3(
>   ftstitle, ftsalbum, ftsartist, ftsalbumartist, ftscomposer, ftsgenre, ftscomment,
>   **tokenize=unicode**
> )" 
> 18:28:16.772 ERROR Database:575                     bound values:  QMap() 
> 18:28:16.772 ERROR unknown                          Unable to update music library database
> 

I have SQLite 3.11.0 installed. According to the SQLite docs (even much older ones), it should probably be **unicode61** instead:

> [...]
> USING fts3(
>   ftstitle, ftsalbum, ftsartist, ftsalbumartist, ftscomposer, ftsgenre, ftscomment,
>   **tokenize=unicode61**
> )" 

Recompiling Clementine with that change in place on every schema file of the source tree made Clementine start perfectly.

Cheers,
Arthur

**Comment by Chocobozzz** [comment]
Hi,

what is your distribution ?

**Comment by hatstand** [comment]
The important line is:
`18:28:16.769 WARN Database:274 Couldn't register FTS3 tokenizer`
Did you try to link against your own copy of sqlite? This is a bad idea.

**Comment by tureba** [comment]
Bad idea why? Doesn't Clementine work on stock sqlite? I thought only the qsqlite interface was embedded.
I have it linked to the system's sqlite (/lib/libsqlite3.so.0). Why is that a problem and what are the alternatives?

**Comment by hatstand** [comment]
Clementine requires some sqlite3 APIs that aren't available/visible on all platforms (`sqlite3_tokenizer_module`).

You know we do make these decisions for a reason... :-)

**Comment by tureba** [comment]
I see. Thanks. That probably means SQLITE_ENABLE_FTS3_TOKENIZER in compile time. I'll try to enable it and see if things work better.
Cheers.

**Comment by tureba** [comment]
For future reference, my testing shows Clementine release-1.3 builds and works fine with system sqlite3 built with:

> -DSQLITE_ENABLE_FTS{3,3_PARENTHESIS,3_TOKENIZER}

Packagers like to know this kind of stuff. :-)

**Comment by davidgfnet** [comment]
How did you fix it? I just build the thing as before, no weird flags or anything, but it doesn't work.
Is it cause my system sqlite3 is missing the FTS3? I moved to fedora 24 and it used to work for 23. Do I need to download, build and install sqlite3 myself? I thought clementine would do that for me or something. Thanks!

**Comment by davidgfnet** [comment]
I just downloaded latest sqlite3, built it with FTS5 support (--enable-fts5 --enable-static) and manually recreated clementine binary linking to the .a library but same problem. It is very weird. Maybe I should rebuild using the right includes just in case the interface has changed or something.

**Comment by tureba** [comment]
> How did you fix it?

Back then we were using sqlite 3.10 so I just recompiled it with the tokenizer flag I described and it worked. Nowadays it's 3.13 and we need the patch of #5297 on clementine itself, though I'm not aware of any other tweak that's required (I've stopped using clementine a while back for several reasons, so I'm not keeping track of it now). Good luck with fts5 - I never attempted to use it.

**Comment by renn0xtek9** [comment]
Is there any way I can work this around / fix it I am using KDE on Ubuntu based (KDE Neon) 
Clementine is from the repositories..

**Comment by jonaski** [comment]
Use the patch from #5669

**Comment by renn0xtek9** [comment]
Can anyone provide extensive instead of evasive instructions on how to solve this ? 
This script on a fresh install does not work 
`https://github.com/renn0xtek9/VMRequests/blob/master/RequestsScripts/Scripts/CompileClementine.sh`
nor does this one 
`https://github.com/renn0xtek9/VMRequests/blob/master/RequestsScripts/Scripts/CompileClementine-qt5.sh`
That is three years already ...
