### ISSUE TITLE
cmake doesn't find libcrypto++

### ISSUE THREAD

**Issue by tureba** [clementine-player/Clementine#5279]
Hi,

Using Clementine branch release-1.3

It seems that cmake has a hard time finding libcrypto++:
> CMake Error at CMakeLists.txt:278 (message):
>   Either crypto++ must be available or the non-GPL Spotify code must be
>   compiled in
> -- Configuring incomplete, errors occurred!

In reality, I have crypto++ 5.6.2 installed and very easy to find:
>  % ls -l /lib/libcrypto{pp,++}*
> lrwxrwxrwx  1 root root       14 Mar  5 23:32 /lib/libcrypto++.so.9 -> libcryptopp.so
> -rw-rw-r--+ 1 root root 17300750 Mar  5 23:32 /lib/libcryptopp.a
> -rwxrwxr-x+ 1 root root  4629048 Mar  5 23:32 /lib/libcryptopp.so

So I suspect the pkg_search_module macro needs to be tweaked somehow.

Since I personally don't care about crypto++/spotify (and I loathe third party blobs), I just changed the severity of the message in line 278 to WARNING. It moved on, compiled fine and I am using it now. If there are missing funcionalities, I didn't find them yet.

BTW, if Spotify support is listed as optional, then the build should really move on in cases like this, disabling some stuff, shouldn't it?

Cheers,
Arthur

**Comment by hatstand** [comment]
You need the headers too.

We will not make this optional as then distro packagers reliably screw it up.

**Comment by tureba** [comment]
Yes, headers are all in /usr/include/cryptopp.

**Comment by hatstand** [comment]
then you'll need to debug why `pkgconfig` isn't finding it. This works fine on Fedora & Ubuntu & Debian.

**Comment by tureba** [comment]
Upstream cryptopp doesn't ship a pc. So each distro makes its own, which are not exactly interchangable. Until upstream cryptopp ships their own pc, any distro's pc cannot be trusted as the absolutely correct way.
Anyway, if Clementine needs cryptopp in pkg-config, It'd be nice to have it written down in the How To Compile pages, for instance.

**Comment by hatstand** [comment]
I don't think we care about supporting any more distros TBH. Feel free to send a pull request for the wiki though.

**Comment by tureba** [comment]
Not a problem. It's a bone to pick with cryptopp. As soon as they publish a pc of their own, you guys will get to worry less about distro specifics.
I'll see if I can put some stoke that fire some more.
Thanks again
