### ISSUE TITLE
Moving to Qt 4.8.6, code style and make warnings

### ISSUE THREAD

**Issue by JulianVolodia** [clementine-player/Clementine#5281]
@hatstand , @Chocobozzz maybe we want to upgrade ver. of Qt4 from 4.5 to 4.8.6?

**Why we using 4.5 ver. still?** Should we always test on 4.5? ;)
Or maybe move dependency to newer version?

I tested with Qt 4.8.6 and **fixed warnings** (https://github.com/clementine-player/Clementine/pull/5280) on that.

It will be great if you tell me what **code style** here is preferred (I noticed a few lines with additional space with qtcreator standard settings).

Best regards :)

**Comment by hatstand** [comment]
Ubuntu Precise is still on 4.8.1

**Comment by JulianVolodia** [comment]
I asked for sth @hatstand . If you depend on 4.5 min and tell that you use 4.8.1 on Ubuntu Precise Pangolin - i think it's problem, don't you? ;)

I asked if we should test from that version. Even dependency on **4.8** will be better ;)

**Comment by JulianVolodia** [comment]
@hatstand I sending new PR - please check is it working for you :)
