### ISSUE TITLE
Clementine-Qt crashes on startup

### ISSUE THREAD

**Issue by EQLucky** [clementine-player/Clementine#5282]
Whenever I try to start clementine, it show the following:
17:20:35.059 ERROR Database:577                     db error:  QSqlError("1", "Unable to fetch row", "unknown tokenizer: unicode")
17:20:35.059 ERROR Database:578                     faulty query:  "CREATE VIRTUAL TABLE songs_fts USING fts3(\n  ftstitle, ftsalbum, ftsartist, ftsalbumartist, ftscomposer, ftsgenre, ftscomment,\n  tokenize=unicode\n)"
17:20:35.059 ERROR Database:579                     bound values:  QMap()                                          
__logging_message__17:20:35.059 ERROR unknown                          Unable to update music library database     
Aborted (core dumped)  

I can reproduce it everytime. I've tried to start it again after deleting ~/home/user/.config/clementine-Qt5/clementine.db, but happened the same.

**Comment by Chocobozzz** [comment]
What is your distribution? Can you provide the logs from the begining (on pastebin for example)?

**Comment by Chocobozzz** [comment]
Maybe related to https://github.com/clementine-player/Clementine/issues/5278.

**Comment by hatstand** [comment]
Don't change build flags that you don't understand.
