### ISSUE TITLE
Build Clementine on the SliTaz Linux 5.0 

### ISSUE THREAD

**Issue by x09** [clementine-player/Clementine#5299]
Hi,

I try build clementine from sources for SliTaz Linux

> root@slitaz5:~/Clementine-1.2.3/bin# uname -a
> Linux slitaz5 3.2.71-slitaz #4 SMP Sun Feb 14 00:50:12 Europe 2016 i686 GNU/Linux

> root@slitaz5:~/Clementine-1.2.3/bin# cat /etc/slitaz-release 
> 5.0

Download sources, unpack 

> tar zxvf Clementine-1.2.3.tar.gz

go to folder

> cd Clementine-1.2.3 && mkdir build && cd build
> cmake ../

> root@slitaz5:~/Clementine-1.2.3/build# cmake ../
> -- The C compiler identification is GNU 4.6.3
> -- The CXX compiler identification is GNU 4.6.3
> -- Check for working C compiler: /usr/bin/cc
> -- Check for working C compiler: /usr/bin/cc -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Check for working CXX compiler: /usr/bin/c++
> -- Check for working CXX compiler: /usr/bin/c++ -- works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- Found PkgConfig: /usr/bin/pkg-config (found version "0.28") 
> -- Looking for Q_WS_X11
> -- Looking for Q_WS_X11 - found
> -- Looking for Q_WS_WIN
> -- Looking for Q_WS_WIN - not found
> -- Looking for Q_WS_QWS
> -- Looking for Q_WS_QWS - not found
> -- Looking for Q_WS_MAC
> -- Looking for Q_WS_MAC - not found
> -- Found Qt4: /usr/bin/qmake (found suitable version "4.8.6", minimum required is "4.5.0") 
> -- Found Qt4: /usr/bin/qmake (found version "4.8.6") 
> CMake Error at /usr/share/cmake-3.1/Modules/FindPackageHandleStandardArgs.cmake:138 (message):
>   Could NOT find OpenGL (missing: OPENGL_INCLUDE_DIR)
> Call Stack (most recent call first):
>   /usr/share/cmake-3.1/Modules/FindPackageHandleStandardArgs.cmake:374 (_FPHSA_FAILURE_MESSAGE)
>   /usr/share/cmake-3.1/Modules/FindOpenGL.cmake:181 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
>   CMakeLists.txt:48 (find_package)
> 
> -- Configuring incomplete, errors occurred!
> See also "/root/Clementine-1.2.3/build/CMakeFiles/CMakeOutput.log".
> See also "/root/Clementine-1.2.3/build/CMakeFiles/CMakeError.log".

But libQtOpenGL is installed.

> root@slitaz5:~/Clementine-1.2.3/bin# pkg-config --list-all | grep -i opengl
> QtOpenGL             Qtopengl - Qtopengl Library
> glu                  glu - Mesa OpenGL Utility library
> glw                  glw - Mesa OpenGL widget library
> root@slitaz5:~/Clementine-1.2.3/bin# tazpkg list libQtOpenGL

> root@slitaz5:~/Clementine-1.2.3/bin# tazpkg -s libQtOpenGL
> 
> Search result for "libQtOpenGL"
>
> Installed packages
>  --------------------------------------------------------------------------------
> libQtOpenGL             4.8.6             development
>  1 installed package found for "libQtOpenGL"

> root@slitaz5:~/Clementine-1.2.3/bin# pkg-config --cflags-only-I QtOpenGL
> -I/usr/include/QtOpenGL -I/usr/include/QtGui -I/usr/include/QtCore 

> root@slitaz5:~/Clementine-1.2.3/build# ls -1 /usr/include/QtOpenGL
> QGLBuffer
> QGLColormap
> QGLContext
> QGLFormat
> QGLFramebufferObject
> QGLFramebufferObjectFormat
> QGLFunctions
> QGLFunctionsPrivate
> QGLPixelBuffer
> QGLScreen
> QGLScreenSurfaceFunctions
> QGLShader
> QGLShaderProgram
> QGLWidget
> QMacCompatGLenum
> QMacCompatGLint
> QMacCompatGLuint
> QMacGLCompatTypes
> QtOpenGL
> qgl.h
> qglbuffer.h
> qglcolormap.h
> qglframebufferobject.h
> qglfunctions.h
> qglpixelbuffer.h
> qglscreen_qws.h
> qglshaderprogram.h

it's problem SliTaz, Clementine sources, or me ?

**Comment by hatstand** [comment]
It's looking for opengl not qtopengl. You probably need something like mesa-common-dev
