### ISSUE TITLE
Cannot log in to last.fm - 503 on auth page

### ISSUE THREAD

**Issue by xiongchiamiov** [clementine-player/Clementine#5301]
### Before posting

Please follow the steps below and check the boxes with [x] once you did the step.

- [x] I checked the issue tracker for similar issues
- [x] I checked the [changelog](https://github.com/clementine-player/Clementine/blob/master/Changelog) if the issue is already resolved
- [ ] I tried the latest Clementine build from [here](https://builds.clementine-player.org/) (No Arch builds, and I [compile from git](https://aur.archlinux.org/packages/clementine-git) anyways.)

### System information

Please provide information about your system and the version of Clementine used.

- Operating System: Arch Linux
- Clementine version: 25326b4 (`master` as of this writing)

### Expected behaviour / actual behaviour

I was listening to music with clementine, scrobbling away successfully, then came back after an hour's pause and found my new songs weren't being sent.  There was no GUI error (but that's a separate issue), but restarting clementine through the terminal and watching stdout/stderr I saw messages about my session having expired.  I logged out through the preferences, but now I can no longer log back in.

When I click the login button, rather than asking for a username and password, as previously, now clementine opens a browser window to `https://www.last.fm/api/auth/?api_key=<a key>&token=<a token>`.  This produces a 503 that merely says "An error occurred while processing your request.".  As you might expect, returning to clementine, it says the token is invalid, and I'm not logged in.

The api key stays the same every time, but the token changes each time I try this process again.

I'm not sure what exactly is supposed to happen, but I figure whatever it is, it should be successful at getting clementine authed with last.fm.

### Steps to reproduce the problem (only for bugs)

Open clementine's preferences and navigate to last.fm section.  If currently logged in, log out.  Click login button.

----

Since this is only a problem when initially authenticating with last.fm, I'm not sure when exactly it started happening.  Unfortunately, my old builds don't run because of disappeared shared libraries, so I'll have to rebuild at old shas to find a reference point.

**Comment by TheUbuntuGuy** [comment]
The last.fm desktop API has been down since last Thursday. There is nothing wrong with Clementine. See http://status.last.fm/ for updates.

**Comment by xiongchiamiov** [comment]
Fuck, they need some SREs.  Thanks.

**Comment by TheUbuntuGuy** [comment]
Since this is still not fixed on their end, there is a workaround to get Clementine authenticated. Their servers currently do not accept HTTPS requests at all, but if you click 'Login' in Clementine, and you get the page with the 'An error occurred while processing your request' message, change the URL to 'http://' and you should be able to login and get Clementine a working session key for the time being.

**Comment by obsidiannonparity** [comment]
That work around does not seem to be working anymore as I do not even get to the auth page now. Just a authentication failed(yes it is correct and works on the web login)
