### ISSUE TITLE
Digitally Imported not available?

### ISSUE THREAD

**Issue by rubinchyk** [clementine-player/Clementine#5305]
Now 'Digitally Imported' not available for listening throw Clementine?!

**Comment by narunlifescience** [comment]
Digitally Imported is only available for premium users (#5193)

**Comment by FadeMind** [comment]
@narunlifescience  @rubinchyk 

NOT exactly. 

DI.FM is available for free listen at di.fm in LQ sound and with advertisment.
Streaming out of website via API was banned for free users due Copyright Owners demand and it still available for Premium sub.
