### ISSUE TITLE
QEglContext::swapBuffers(): "Bad surface (0x300D)" and empty window

### ISSUE THREAD

**Issue by hollaho** [clementine-player/Clementine#5307]
I am using clementine since a while on plasma-5.5.5/qt-5.5.1-r1/qt-4.8.7-r1 but since a week it opens with an empty window and shows a huge row of errors:
22:07:24.049 WARN  unknown                          QPainter::begin: Paint device returned engine == 0, type: 2 
22:07:29.067 DEBUG unknown                          hijackWindow() context created for MainWindow(0x7ffd066af4d0, name = "MainWindow") 1  
22:07:29.108 DEBUG unknown                          Created Window Surface FBO QSize(1740, 799) with samples 8  
22:07:29.188 WARN  unknown                          QEglContext::swapBuffers(): "Bad surface (0x300D)"  
22:07:29.226 WARN  unknown                          QEglContext::swapBuffers(): "Bad surface (0x300D)"  
22:07:29.322 WARN  unknown                          QEglContext::swapBuffers(): "Bad surface (0x300D)"  
22:07:29.352 WARN  unknown                          QEglContext::swapBuffers(): "Bad surface (0x300D)"  
22:07:29.386 WARN  unknown                          QEglContext::swapBuffers(): "Bad surface (0x300D)"  
22:07:29.413 WARN  unknown                          QEglContext::swapBuffers(): "Bad surface (0x300D)"  

- [x] I checked the issue tracker for similar issues
- [x] I checked the [changelog](https://github.com/clementine-player/Clementine/blob/master/Changelog) if the issue is already resolved
- [x] I tried the latest Clementine build from [here](https://builds.clementine-player.org/)

### System information

Please provide information about your system and the version of Clementine used.

- Operating System: gentoo
- Clementine version: (~)1.3_rc1-r1

### Expected behaviour / actual behaviour
See above, it open with an empty window and throws errors.

### Steps to reproduce the problem (only for bugs)
Happens now every time when I start it. It starts minimized, once I open it I get the empty window...

**Comment by hatstand** [comment]
Given Gentoo apparently hates our users... you kind of get what you asked for:
https://gitweb.gentoo.org/repo/gentoo.git/tree/media-sound/clementine/clementine-1.2.3.ebuild#n141

**Comment by Ferroin** [comment]
For what it's worth, I find that the live ebuild (listed as version 9999) works just fine on my Gentoo systems.

You might also try re-emerging Clementine.

**Comment by hollaho** [comment]
I have re-emerged 1.3_rc1-r1 several times - same error. Will now try the git-master 9999 version and report how that does it.

**Comment by hollaho** [comment]
The git-master 9999 version drops the same errors:
21:58:36.157 WARN  unknown                          QEglContext::swapBuffers(): "Bad surface (0x300D)"  
21:58:36.342 WARN  unknown                          QEglContext::swapBuffers(): "Bad surface (0x300D)" 

and an empty window appears when opened.

**Comment by Ferroin** [comment]
This is starting to sound like a bug with Qt, not Clementine.  Either way, I'd suggest opening an issue on the Gentoo Bugzilla

**Comment by hollaho** [comment]
I can - after a long bug hunt - confirm this is a qt:4 related bug. Basically the EGL support of qt4 is still broken resp. buggy. I did need to compile qt4 qith -egl, while qt5 requires +egl due to wayland support of plasma5 desktop. Not what is intuitive, but it works only this way.

Only people compiling qt4 and qt5 mixed environments for plasma5 will be hit by this bug if they choose the "wrong" configure options...
