### ISSUE TITLE
Quit from gnome-status-panel has no effect.

### ISSUE THREAD

**Issue by hashhar** [clementine-player/Clementine#5308]
Hitting quit from the context menu (right click) on the gnome-status-icons in the bottom right doesn't stop clementine. The GUI closes but the file stream keeps on playing.

Morever there seems to be no way to get back to that instance of Clementine. The only solution is a `pkill clementine`.

This is on the daily development branch.

**Comment by hashhar** [comment]
Compiling it locally on my system solves the issue. Should I close this now?

**Comment by Chocobozzz** [comment]
Yep, thanks for keeping us in touch. If someone else has this type of bug, just ask for reopening this issue. :)
