### ISSUE TITLE
Clementine 1.2.3_7 'Open audio CD…' bus error on FreeBSD 11.0-CURRENT

### ISSUE THREAD

**Issue by grahamperrin** [clementine-player/Clementine#5310]
Spun off from [[PC-BSD Testing] Clementine 1.2.3_7 'Open audio CD…' bus error on 11.0-CURRENT](http://lists.pcbsd.org/pipermail/testing/2016-March/010499.html), which was addressed to the maintainer named at http://www.freshports.org/audio/clementine-player/ (but the list archive does not show addressees). A highlight from that post: 

>> … (Can you reproduce the problem with FreeBSD 11.0-CURRENT?)
>> 
>> The same CD does play in VLC media player. … 

Off-list, Sean wrote: 

> … can confirm the same failure case … can play a CD with vlc so I know my permissions and such are fine. 

I'll follow-up to the PC-BSD Testing list with reference to this issue. 

Thanks
Graham

**Comment by hatstand** [comment]
We need a stack trace to do anything useful with this.

**Comment by seanbruno** [comment]
This appears to be fixed in 1.3.1 and will be pushed to FreeBSD ports this weekend.

**Comment by grahamperrin** [comment]
Fix confirmed – there's no longer a bus error – with PC-BSD 11.0-CURRENTMAY2016. Thanks. 

(The application will not play the CD, but that's a separate issue.)
