### ISSUE TITLE
Crashes when double click on "Spotify" or "Soundcloud" icons in search results

### ISSUE THREAD

**Issue by ccheek21** [clementine-player/Clementine#5311]
### Before posting

Please follow the steps below and check the boxes with [x] once you did the step.

- [x] I checked the issue tracker for similar issues
- [x] I checked the [changelog](https://github.com/clementine-player/Clementine/blob/master/Changelog) if the issue is already resolved
- [x] I tried the latest Clementine build from [here](https://builds.clementine-player.org/)

### System information

Please provide information about your system and the version of Clementine used.

- Operating System: Arch Linux
- Clementine version: 1.2.3

### Expected behaviour / actual behaviour

When I use the search feature and it returns results from Spotify and Soundcloud, if I double click on the Spotify or Soundcloud group headers in the search results, Clementine crashes. 

### Steps to reproduce the problem (only for bugs)

1) Configure Spotify and/or Soundcloud
2) Search for a song
3) Double click on the Spotify or Soundcloud icon in the search results
4) Observe crash

**Comment by ivan-leontiev** [comment]
This issue has been fixed by the 8be65b85654ed0afb1bc085f363b6b2f83656335 commit. Try the latest build.
