### ISSUE TITLE
Radio-Browser as an online source for streaming radio stations

### ISSUE THREAD

**Issue by stragu** [clementine-player/Clementine#5321]
### System information

All.
- Clementine version: 1.2.3
### Expected behaviour / actual behaviour

It would be great to have the [Radio-Browser](http://www.radio-browser.info/gui/#) radio board available as an online source ("internet provider") for streaming radios, straight from the Clementine GUI (i.e. in the "Search" tab).

Thank you for your great work!

**Comment by xylo** [comment]
The API of Radio-Browser offers quite some options, but the most interesting one is the search option in my opinion.

**Comment by gerroon** [comment]
+1

This would be so nice to have as radio source.

**Comment by coubass** [comment]
I second this request.

This would make it easy to listen to basically any radio station available online with Clementine.

Besides, here's a double:
https://github.com/clementine-player/Clementine/issues/5878
