### ISSUE TITLE
End of podcast crash in 1.3.0rc2

### ISSUE THREAD

**Issue by supine** [clementine-player/Clementine#5332]
Process:         clementine [36077]
Path:            /Applications/clementine.app/Contents/MacOS/clementine
Identifier:      org.clementine-player.clementine
Version:         1.3 rc2 (4096.1.3.0.0)
Code Type:       X86-64 (Native)
Parent Process:  launchd [406]
Responsible:     clementine [36077]
User ID:         1935832884

Date/Time:       2016-04-15 15:04:49.484 +0200
OS Version:      Mac OS X 10.9.5 (13F1712)
Report Version:  11
Anonymous UUID:  1CE01435-7092-B8E7-A3C3-BCEFDF8A1277

Crashed Thread:  0  Dispatch queue: com.apple.main-thread

Exception Type:  EXC_ARITHMETIC (SIGFPE)
Exception Codes: EXC_I386_DIV (divide by zero)

[clementine-crash.txt](https://github.com/clementine-player/Clementine/files/221025/clementine-crash.txt)

**Comment by hatstand** [comment]
Fixed in newer builds I think. See #5261

**Comment by supine** [comment]
I installed http://buildbot.clementine-player.org/builders/Mac%20Release/builds/89 and confirming it's fixed.
