### ISSUE TITLE
Portable version writing temp files to C:\Data

### ISSUE THREAD

**Issue by vatterspun** [clementine-player/Clementine#5354]
### System information

Operating Systems: Win7x86 and WIn8x64
Versions: v1.3.0 and v1.3.1 (Portable ... by which I mean these versions: https://builds.clementine-player.org/win32/portable/ )
### Expected behaviour / actual behaviour

**Expected**: should write any temp files to an appropriate system temp folder (e.g. C:\Users\USER\AppData\Local\Temp)

**Actual**: On launch, writes what appears to be temp data to _c:\data_

**Comment by smaragdus** [comment]
I can confirm that.

**Comment by amuttsch** [comment]
In which folder did you install Clementine and what files are put into C:\data ?

**Comment by smaragdus** [comment]
I installed the portable version of Clementine 1.3.1 in "C:\Portable Programs\Clementine". Anytime I start
Clementine it creates "C:\data" with sub-folder "C:\data\cache", another sub-folder "C:\data\cache\networkcache" with two sub-folders "C:\data\cache\networkcache\data7" and "C:\data\cache\networkcache\prepared". My system- Windows 8 x64.

**Comment by vatterspun** [comment]
> In which folder did you install Clementine and what files are put into C:\data ?

I saved to C:\Users\USER\Desktop\Clementine.  Attaching a screenshot and a file list:

![image 2](https://cloud.githubusercontent.com/assets/1289134/14729516/2e373e2c-0804-11e6-8bf2-051b480f6cc1.png)

[file list.txt](https://github.com/clementine-player/Clementine/files/231007/file.list.txt)

**Comment by midaspt** [comment]
I can confirm this issue is still present in the latest Windows **portable** build...
(https://builds.clementine-player.org/win32/portable/Clementine-PortableSetup-1.3.1-284-g8a6cc8b.exe)

Moreover, it isn't limited to the **C:** drive root folder -- as I have **Clementine** portable folder located in my **D:** drive, the '_data_' folder is being (re-)created a its root.

Expected behavior would be for the folder to be located inside the program's folder, i.e. alongside Clementine executable.

**Comment by kekkc** [comment]
Interestingly all other caches are using the correct location (moodbarcache & pixmapcache are both stored in ClementinPortable/data/cache). Just networkcache creates a new data folder within the root folder of the drive ClementinePortable is used on.

**Comment by amuttsch** [comment]
Please try the new build once it's available and report if it works on windows.

**Comment by kekkc** [comment]
Cool, fixed with https://builds.clementine-player.org/win32/portable/Clementine-PortableSetup-1.3.1-287-g652f38a.exe

Many thanks ;)

**Comment by vatterspun** [comment]
>> Please try the new build once it's available and report if it works on windows.

> Cool, fixed with https://builds.clementine-player.org/win32/portable/Clementine-PortableSetup-1.3.1-287-g652f38a.exe

Confirmed.  Thanks for addressing this issue.

**Comment by almarshenwan** [comment]
How to recover deleted "Data" folder?
it was including other important folders and files.. I tried many data recovery software..
