### ISSUE TITLE
Ratings lost after update

### ISSUE THREAD

**Issue by davidsmind** [clementine-player/Clementine#5355]
### Before posting

Please follow the steps below and check the boxes with [x] once you did the step.

- [ x] I checked the issue tracker for similar issues
- [ x] I checked the [changelog](https://github.com/clementine-player/Clementine/blob/master/Changelog) if the issue is already resolved
- [ ] I tried the latest Clementine build from [here](https://builds.clementine-player.org/) (I cannot do this as I lost my ratings database)

### System information

Please provide information about your system and the version of Clementine used.

- Operating System: Gentoo linux
- Clementine version: Version 1.3

### Expected behaviour / actual behaviour

I used portage to update from Version 1.2.3 to Version 1.3 and I lost thousands of ratings (which were not written into the files)

### Steps to reproduce the problem (only for bugs)

Upgrade from version 1.2.3 to 1.3 and allow 1.3 to re-read your library.

**Comment by davidsmind** [comment]
Conversely I have the backup DB. Is their an efficiant way to migrate my old ratings over to the new DB? I'm ok using sqlite browser and running a big ol query (as I have backups)

**Comment by hatstand** [comment]
Use 1.3.1 and cp the backup database over the current one.
