### ISSUE TITLE
Files with characters like 'á' or 'è' can't be played

### ISSUE THREAD

**Issue by nostalgicamigo** [clementine-player/Clementine#5363]
### Before posting

Please follow the steps below and check the boxes with [x] once you did the step.

- [x] I checked the issue tracker for similar issues
- [x] I checked the [changelog](https://github.com/clementine-player/Clementine/blob/master/Changelog) if the issue is already resolved
- [x] I tried the latest Clementine build from [here](https://builds.clementine-player.org/)

### System information

Please provide information about your system and the version of Clementine used.

- Operating System: ArchLinux latest (kernel 4.5.1)
- Clementine version: 1.3.1-2

### Expected behaviour / actual behaviour

Adding audio file's to playlist should work independent of the filename.
I have a audio file with the name "Piège.mp3" and the character "è" makes it that clementine can't play it.

### Steps to reproduce the problem (only for bugs)
Rename any audio file to "è.mp3" Either drag-and-drop it to clementine playlist or click on "Playlist"->"add file" and add it through there. It will not work.

**Comment by santigl** [comment]
I can't seem to recreate it in Debian 64 bits with 931b6aa.

You can see that behaviour with any file? Is it safe to discard that the problem is with the metadata?

**Comment by nostalgicamigo** [comment]
Yes, it's not with metadata - I renamed a file that works to "é.mp3" and then it can't be added to the playlist anymore.

**Comment by Ferroin** [comment]
This is probably going to sound like a stupid question, but are you using a UTF-8 locale?  If not, that might be causing the issue.

**Comment by nostalgicamigo** [comment]
I actually checked that this morning, my locale is personaly set, only LC_ALL isn't defined (as I set each "LC_" manually in KDE)
```
pc@user $ locale -a
locale: Cannot set LC_COLLATE to default locale: No such file or directory
C
POSIX
en_US.utf8
pc@user $ locale
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=pt_PT.UTF-8
LC_TIME=pt_PT.UTF-8
LC_COLLATE=pt_PT.UTF-8
LC_MONETARY=pt_PT.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT=pt_PT.UTF-8
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

**Comment by nostalgicamigo** [comment]
I went to /etc/locale.gen and added "pt_PT.UTF-8" and generated with "locale-gen". Now it is working. I think it's related to "locale: Cannot set LC_COLLATE to default locale: No such file or directory".

If anybody has a system with overriden values for the "LC_", maybe this was the problem, not clementine's.

**Comment by SamuelGilbert42** [comment]
I think this is actually an ArchLinux issue.  I had the same problem with impacted Clementine after an update (pacman -Suy).  I found a work-around, but it's not a complete solution.

[Locale name mismatch](https://bbs.archlinux.org/viewtopic.php?id=211317) in Archlinux forums
