### ISSUE TITLE
Clementine crashes while searching VK's music

### ISSUE THREAD

**Issue by ShirinkinArseny** [clementine-player/Clementine#5376]
1. Log in to VK using clementine.
2. Go to VK website -> settings -> Security -> Log out from every devices
3. Try to search music in VK via clementine
4. Segfault!

After restart clementine reauthes successfully.

Clementine 1.3 rc1, Linux 4.0.5-gentoo

**Comment by dee1337** [comment]
similar problems with clementine 1.3.1 on windows when i try to connect vk with clementine. clementine crashes during request access

**Comment by gordon-morehouse** [comment]
Does VK support exist any more? I don't see it in 1.3.1-333-gf854bc5 and I recall seeing it was removed. If so, this can probably be closed.
