### ISSUE TITLE
making echonest optional

### ISSUE THREAD

**Issue by 0-wiz-0** [clementine-player/Clementine#5384]
When compiling clementine 1.3.1 from source, it insists on having echonest installed.
This dependency is not recorded on https://github.com/clementine-player/Clementine/wiki/Compiling-from-Source (except hidden in the Ubuntu apt-get line).
Please document it, or, even better, make it optional, since e.g. https://en.wikipedia.org/wiki/The_Echo_Nest only talks about this company in the past tense (as it was bought by spotify).

**Comment by diogocp** [comment]
Probably better to remove it completely, since

> As of May 31st, The Echo Nest platform will no longer serve requests and developers will need to move over to the Spotify API.

http://developer.echonest.com/

**Comment by Chocobozzz** [comment]
This is already done on the master branch: https://github.com/clementine-player/Clementine/commit/a8a0f2e4fdd3d4b2fd23b8628a3abc27c290d01d
