### ISSUE TITLE
Playing music through Vk is broken.

### ISSUE THREAD

**Issue by Object905** [clementine-player/Clementine#5398]
- Operating System: Arch Linux
- Clementine version: 1.3.1

Playing music through Vk just got broken few days ago.
Neither with "Internet" tab nor "Search" playing not working.
When trying to play anything from vk got message: "A network error occurred, or the server closed the connection unexpectedly."
Same issue with other accounts.
Nothing printed out in stdout/stderr either.

**Comment by Object905** [comment]
Same behavior on windows, 1.3.1.

**Comment by l4l** [comment]
Did you login in vk (in prefs)?
Works fine for me on arch and same version

**Comment by Object905** [comment]
I tried with 3 different accounts, but none of them was working.
Problem solved, tho. Seems if was on VK side.
