### ISSUE TITLE
Last.fm tracks are not scrobbled if their names start with numbers

### ISSUE THREAD

**Issue by anton-khodak** [clementine-player/Clementine#5400]
### Before posting

Please follow the steps below and check the boxes with [x] once you did the step.

- [x] I checked the issue tracker for similar issues
- [x] I checked the [changelog](https://github.com/clementine-player/Clementine/blob/master/Changelog) if the issue is already resolved
- [x] I tried the latest Clementine build from [here](https://builds.clementine-player.org/)

### System information

Please provide information about your system and the version of Clementine used.

- Operating System: Xubuntu 15.10
- Clementine version: 1.3.1

### Expected behaviour / actual behaviour
Last.fm tracks with leading numbers not scrobbling
### Steps to reproduce the problem (only for bugs)
Rename any scrobbable track to a name containing digits at the start, i.e. 
"Sad but true" -> "02-Sad but true" or "2Sad but true"
BUT 
if "4" is leading, a track is being scrobbled

**Comment by lenrocd** [comment]
Hmm... you mean filenames containing digits in front ?
Or ... author/artist ID3 tag ?

In the first case, I have virtually all my files with digits in the beginning of the filenames, and I have absolutely no problem with Clementine scrobbling these songs to last.fm

The other case ... I definitely do NOT have any file with such tag (it's wrong anyway, right ?), and I can't confirm how Clementine work.

Would you care to elaborate ?
Maybe in your particular situation there was a different problem ?

**Comment by anton-khodak** [comment]
I checked my ID3 tags and there were no titles for that tracks... But they did have titles in playlists, how is that possible?
