### ISSUE TITLE
Dependancy errors installing 1.3.1 on Raspbian

### ISSUE THREAD

**Issue by olligobber** [clementine-player/Clementine#5402]
- Operating System: Raspbian with Debian 7.10
- Clementine version: 1.3.1

I attempted to install the Raspberry Pi package from https://www.clementine-player.org/downloads using `sudo dpkg -i clementine.deb` but got several dependancy errors.

`dpkg: dependency problems prevent configuration of clementine: clementine depends on libechonest2.1 (>= 2.1.0); however: Package libechonest2.1 is not installed. clementine depends on libfftw3-double3; however: Package libfftw3-double3 is not installed. clementine depends on libglew1.10 (>= 1.10.0); however: Package libglew1.10 is not installed. clementine depends on libimobiledevice4 (>= 0.9.7); however: Package libimobiledevice4 is not installed. clementine depends on liblastfm1 (>= 1.0.7); however: Package liblastfm1 is not installed. clementine depends on libprotobuf9; however: Package libprotobuf9 is not installed. clementine depends on libstdc++6 (>= 4.9); however: Version of libstdc++6:armhf on system is 4.7.2-5+rpi1. clementine depends on libtag1c2a (>= 1.9.1); however: Version of libtag1c2a:armhf on system is 1.8.0-1. clementine depends on gstreamer1.0-plugins-base; however: Package gstreamer1.0-plugins-base is not installed. clementine depends on gstreamer1.0-plugins-good; how dpkg: error processing clementine (--install): dependency problems - leaving unconfigured `

Trying to use apt-get to fix dependencies just uninstalls clementine 1.3.1.
The version obtained using `sudo apt-get install clementine` is 1.0.

**Comment by olligobber** [comment]
`dpkg: dependency problems prevent configuration of clementine:
 clementine depends on libechonest2.1 (>= 2.1.0); however:
  Package libechonest2.1 is not installed.
 clementine depends on libfftw3-double3; however:
  Package libfftw3-double3 is not installed.
 clementine depends on libglew1.10 (>= 1.10.0); however:
  Package libglew1.10 is not installed.
 clementine depends on libimobiledevice4 (>= 0.9.7); however:
  Package libimobiledevice4 is not installed.
 clementine depends on liblastfm1 (>= 1.0.7); however:
  Package liblastfm1 is not installed.
 clementine depends on libprotobuf9; however:
  Package libprotobuf9 is not installed.
 clementine depends on libstdc++6 (>= 4.9); however:
  Version of libstdc++6:armhf on system is 4.7.2-5+rpi1.
 clementine depends on libtag1c2a (>= 1.9.1); however:
  Version of libtag1c2a:armhf on system is 1.8.0-1.
 clementine depends on gstreamer1.0-plugins-base; however:
  Package gstreamer1.0-plugins-base is not installed.
 clementine depends on gstreamer1.0-plugins-good; how
dpkg: error processing clementine (--install):
 dependency problems - leaving unconfigured
`

**Comment by amuttsch** [comment]
See https://github.com/clementine-player/Clementine/wiki/Clementine-on-Raspberry-Pi for information how to install the dependencies.

**Comment by olligobber** [comment]
Following those instructions I get the following errors:

`sudo apt-get install libcrypto++ libechonest2.1 libgpod4 liblastfm1 libprotobuf9 libqjson0 libqt4-opengl libqt4-sql gstreamer1.0-plugins-ugly gstreamer1.0-pulseaudio

Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'libcrypto++-doc' for regex 'libcrypto+'
Note, selecting 'libcryptokit-ocaml-dev' for regex 'libcrypto+'
Note, selecting 'libcrypto++-utils' for regex 'libcrypto+'
Note, selecting 'libcrypto++8-dbg' for regex 'libcrypto+'
Note, selecting 'libcryptokit-ocaml-dev-3jzv6' for regex 'libcrypto+'
Note, selecting 'libcryptokit-ocaml-3jzv6' for regex 'libcrypto+'
Note, selecting 'libcrypto++9' for regex 'libcrypto+'
Note, selecting 'libcrypto++9-dbg' for regex 'libcrypto+'
Note, selecting 'libcryptokit-ocaml' for regex 'libcrypto+'
Note, selecting 'libcrypto++-dev' for regex 'libcrypto+'
Note, selecting 'libcryptokit-ocaml' instead of 'libcryptokit-ocaml-3jzv6'
Note, selecting 'libcryptokit-ocaml-dev' instead of 'libcryptokit-ocaml-dev-3jzv6'
Package libechonest2.1 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package liblastfm1 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package libprotobuf9 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'libechonest2.1' has no installation candidate
E: Package 'liblastfm1' has no installation candidate
E: Package 'libprotobuf9' has no installation candidate

------------------------------------------------------------------------

sudo dpkg -i clementine_1.3.1.jessie_armhf.deb

dpkg: dependency problems prevent configuration of clementine:
 clementine depends on libechonest2.1 (>= 2.1.0); however:
  Package libechonest2.1 is not installed.
 clementine depends on libfftw3-double3; however:
  Package libfftw3-double3 is not installed.
 clementine depends on libglew1.10 (>= 1.10.0); however:
  Package libglew1.10 is not installed.
 clementine depends on libimobiledevice4 (>= 0.9.7); however:
  Package libimobiledevice4 is not installed.
 clementine depends on liblastfm1 (>= 1.0.7); however:
  Package liblastfm1 is not installed.
 clementine depends on libprotobuf9; however:
  Package libprotobuf9 is not installed.
 clementine depends on libstdc++6 (>= 4.9); however:
  Version of libstdc++6:armhf on system is 4.7.2-5+rpi1.
 clementine depends on libtag1c2a (>= 1.9.1); however:
  Version of libtag1c2a:armhf on system is 1.8.0-1.
 clementine depends on gstreamer1.0-plugins-base; however:
  Package gstreamer1.0-plugins-base is not installed.
 clementine depends on gstreamer1.0-plugins-good; how
dpkg: error processing clementine (--install):
 dependency problems - leaving unconfigured
Processing triggers for desktop-file-utils ...
Processing triggers for hicolor-icon-theme ...
Processing triggers for gconf2 ...
Errors were encountered while processing:
 clementine`

**Comment by amuttsch** [comment]
You have to update your Raspian to Jessie. Otherwise you have to get the dependencies through other sources (ppa, sources etc).
