### ISSUE TITLE
Can't play Spotify songs: gdpdepay error

### ISSUE THREAD

**Issue by fedebarabas** [clementine-player/Clementine#5406]
I can't play spotify songs. Whenever I try, I get this pop up error:

GStreamer could not create the element: gdpdepay. Please make sure that you have installed all necessary GStreamer plugins (e.g. OGG and MP3)

Despite this text, I'm able to play mp3 and ogg local files without problems.

### System information

- Operating System: Ubuntu GNOME 16.04
- Clementine version:  1.3.1 (from PPA)

**Comment by fedebarabas** [comment]
Solved by installing ubuntu-restricted-extras

**Comment by jccultima123** [comment]
Not working on bionic 18.04 even after installing `ubuntu-restricted-extras`

**Comment by khipukamayuq** [comment]
@jccultima123  @jccultima123 I'm on Ubuntu 18.04 with the same issue. Clementine 1.3.1. Downloaded the Spotify plugin, logged in but getting the same gdpdepay error.

Previously installed:
```bash
apt-get install libgstreamer1.0-0 gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly gstreamer1.0-libav gstreamer1.0-doc gstreamer1.0-tools gstreamer1.0-x gstreamer1.0-alsa gstreamer1.0-gl gstreamer1.0-gtk3 gstreamer1.0-qt5 gstreamer1.0-pulseaudio
```
Also installed `ubuntu-restricted-extras`. Still getting the same error.

**Comment by khipukamayuq** [comment]
Disregard. Reboot fixed. Can play Spotify tunes, but can't search Spotify library.
