### ISSUE TITLE
Freeze when playing songs from disconnected samba share

### ISSUE THREAD

**Issue by nostalgicamigo** [clementine-player/Clementine#5408]
### System information

Please provide information about your system and the version of Clementine used.

- Operating System: Linux 4.6.1-2-ARCH x86_64 GNU/Linux
- Clementine version: 1.3.1

### Expected behaviour / actual behaviour
Playing music from a remote samba directory that isn't connected should not freeze clementine.
Clementine stops responding forever when I try to play music that is on a remote samba share but not connected on that moment.

### Steps to reproduce the problem (only for bugs)
Have a samba share with songs.
Add songs from the samba share to a playlist in clementine.
Unmount the samba share.
Play the songs that were added from the samba share - Clementine freezes.

**Comment by hatstand** [comment]
That's how remote filesystems work on Linux

**Comment by nostalgicamigo** [comment]
So the "freeze" is a feature?
An OSD displaying an error should be the best solution, while keeping the program usable. Song can't be played - user is warned and can continue to work with Clementine.
