### ISSUE TITLE
Spotify cache in .config folder and this cannot be changed

### ISSUE THREAD

**Issue by MaxStirner** [clementine-player/Clementine#5430]
- Operating System: Arch 
- Clementine version: 1.3.1

### Expected behaviour / actual behaviour
The standard cache directory for spotify files should be ~/.cache/Clementine/spotify-files or something similar. However it turns out that it is in .config/Clementine/spotify-files. My backup routine is broken now since the .config folder now has a size of several GB.

It is also not possible to change that directory, neither from the preferences dialog nor in .config/Clementine/Clementine.conf

**Comment by hatstand** [comment]
Use the XDG_CACHE_HOME environment variable.
