### ISSUE TITLE
Last.fm work around (probably?) stoped working (redirecting last.fm to libre.fm via the hosts file from 1.3.0+)

### ISSUE THREAD

**Issue by JulianVolodia** [clementine-player/Clementine#5433]
To be investigated (high prior I think) - taken from #1 

@ar-jan
> Looks like the workaround of redirecting last.fm scrobbling to libre.fm via the hosts file stopped working from version 1.3.0 onwards :(
>
> If you try the Last.fm Sign in button under Preferences, with 213.138.110.197 post.audioscrobbler.com in the hosts file, you only get a popup saying "Last.fm authentication faile[d]".
 
@mattl
> @ar-jan Libre.fm was down some a few days, so possibly related to that?
 
@ar-jan 
> @mattl I think it's unrelated: my scrobble history in libre.fm ends about 2 months ago, and I tried logging in again yesterday, but failed. I recall seeing something about a new login method for last.fm, so my guess is that when this was implemented for last.fm, the hosts file redirect option stopped working.

**Comment by ar-jan** [comment]
Thanks for opening an issue. I wasn't sure if the hosts redirect workaround is officially supported so I made it a comment.

My latest testing where the workaround fails was on Ubuntu 14.04 with Clementine 1.3.1 from ppa:me-davidsansome/clementine.

If I recall correctly there used to be a username and password field, whereas now a browser window is opened leading you to last.fm to sign in and authorize Clementine, which I suppose is the reason libre.fm no longer works.

**Comment by JulianVolodia** [comment]
> Thanks for opening an issue. I wasn't sure if the hosts redirect workaround is officially supported so I made it a comment.
@ar-jan no problem I think. I won't blame - just be curious about clean. Some people don't like opening new issues - in my though this is strange, but in the other hand, I am strange 4 them :P

> ...workaround fails was on Ubuntu 14.04 with Clementine 1.3.1 from ppa:me-davidsansome/clementine.

*Thanks!* I will try to repeat that...

**Comment by JulianVolodia** [comment]
@hatstand why?

**Comment by hatstand** [comment]
If people care enough to actually use libre.fm instead of last.fm, then someone should care enough to actually implement it. We're not going to support random workarounds.

**Comment by JulianVolodia** [comment]
So... what you think - which way we could help?
support libre, find out why that not work?
