### ISSUE TITLE
Edit Track Information GUI too tall exceeds 800pixels

### ISSUE THREAD

**Issue by godfree2** [clementine-player/Clementine#5437]
### Before posting

Please follow the steps below and check the boxes with [x] once you did the step.

- [ x] I checked the issue tracker for similar issues
- [x ] I checked the [changelog](https://github.com/clementine-player/Clementine/blob/master/Changelog) if the issue is already resolved
- [n ] I tried the latest Clementine build from [here](https://builds.clementine-player.org/)
requires libglew but I have 1.13

### System information

Please provide information about your system and the version of Clementine used.

- Operating System:
Sparky LXDE (debian testing)

- Clementine version: 
1.3.1rc1
### Expected behaviour / actual behaviour
sized to allow entry selection buttons on bottom of window

**Comment by santigl** [comment]
Thanks for reporting this problem, @godfree2 . It has been corrected in this last commit. Now the window is shorter and the labels align properly.
