### ISSUE TITLE
Feature Request: Add dialog to display streams' audio details (testers needed)

### ISSUE THREAD

**Issue by santigl** [clementine-player/Clementine#5455]
This is a combination of a feature request with a request for testers/critics.

I have implemented a class called `StreamDiscoverer` that acquires the audio details for a given stream url. Those details are: codec, bitrate, sample rate, number of channels and bit depth (this last one seems to not be too reliable in my setup, though).

It uses GStreamer's [gstdiscoverer](https://gstreamer.freedesktop.org/data/doc/gstreamer/head/gst-plugins-base-libs/html/gst-plugins-base-libs-gstdiscoverer.html).

I also added a menu action that is displayed only when right-clicking a single stream in the playlist. That action launches an instance of the `StreamDiscoverer` class, which tries to do its work and, if successful, displays a dialog with the details.

The reason why I implemented the `StreamDiscoverer` class  is that I couldn't find a way of getting those specific details from the current engine functions. But it also has the advantage of allowing to get information for stream items that aren't playing.

This is how it currently looks (the strings in Spanish are the ones that already have translations):
![streamdetails2](https://cloud.githubusercontent.com/assets/11447309/17266517/a0341c66-55cf-11e6-8192-a4548e8b048c.png)

I'm need of help to test it on Windows and Mac, and also to make everything satisfy the project's coding standards.

EDIT: I changed the code to work completely asynchronously. The changes are now here: https://github.com/santigl/Clementine/tree/stream-details-async

**Comment by santigl** [comment]
Current to-do list:
* Define a type that encapsulates the details to pass along the `DataReady()` signal. This would allow the Discoverer to be given multiple urls at once. (Should it be defined in its own file?)
* Investigate what's the deal with the reported bit depth. According to GStreamer's docs, it should be the number of bits per sample for *each* channel.  For the stream in the screenshot, mplayer reports `AUDIO: 44100 Hz, 2 ch, s16le, 128.0 kbit`. I tried with a mono stream and GStreamer still shows "32 bits".

**Comment by gaga9999** [comment]
hy, is there a way to include this into a working clementine installation? thx!

**Comment by santigl** [comment]
Hi, @gaga9999. Unfortunately, it is still pending testing on the different platforms before being added as a feature.
