### ISSUE TITLE
Portable Version 1.3.1-216-g04f73d1 keeps getting "Internal data flow error"

### ISSUE THREAD

**Issue by jlanzarotta** [clementine-player/Clementine#5461]
Hello,

I am attempting to run the latest portable version on Windows 7 x64.
Filename: Clementine-PortableSetup-1.3.1-216-g04f73d1.exe
Build Data: 18-Jul-2016 12:04

When I attempt to listen to a song or a Internet radio, I keep getting,

Clementine Error: Internal data flow error.

Any ideas?

Thanks.

**Comment by BKPepe** [comment]
Have same problem.

**Comment by santigl** [comment]
This seems to be related to #5533.
