### ISSUE TITLE
Abort at stratup due to faulty query

### ISSUE THREAD

**Issue by davidgfnet** [clementine-player/Clementine#5463]
Hey there, getting this:

```
09:03:38.495 INFO  main:329                         Clementine 1.3.1-223-g0b5fb0c 
09:03:38.615 WARN  Database:274                     Couldn't register FTS3 tokenizer 
09:03:38.616 DEBUG Database:444                     Applying database schema update 13 from ":/schema/schema-13.sql" 
09:03:38.616 ERROR Database:573                     db error:  QSqlError(1, "Unable to fetch row", "unknown tokenizer: unicode") 
09:03:38.616 ERROR Database:574                     faulty query:  "CREATE VIRTUAL TABLE songs_fts USING fts3(
  ftstitle, ftsalbum, ftsartist, ftsalbumartist, ftscomposer, ftsgenre, ftscomment,
  tokenize=unicode
)" 
09:03:38.616 ERROR Database:575                     bound values:  QMap() 
09:03:38.616 ERROR unknown                          Unable to update music library database 
Aborted (core dumped)
```

At latest HEAD (af8ba894). I was trying to build qt5 branch and aborted for similar reasons (but no debug info on the cmdline) so I went ahead and build master to test further. I deleted my home config area (rm -rf ~/.config/Clementine/) and yet still crashes. Any idea? I can debug it further myself, just need a couple of comments.

Thanks!

**Comment by Chocobozzz** [comment]
Maybe https://github.com/clementine-player/Clementine/issues/5278 is relevant

**Comment by davidgfnet** [comment]
It seems so. An ldd shows that I use my system's sqlite! How do we avoid this? CMake picks it up by default!

**Comment by davidgfnet** [comment]
Nevermind found the issue. Fedora 24 ships with sqlite3 with fts3 (no fts5 support, since you have to explicitely enable it) but seems that sqlite3 has changed "unicode" to "unicode61" so now I had to patch the sql schema files to have "tokenize=unicode61" to make it work :)
