### ISSUE TITLE
vk.com russian titles wrong codepage while playing

### ISSUE THREAD

**Issue by atommixz** [clementine-player/Clementine#5470]
### Before posting

Please follow the steps below and check the boxes with [x] once you did the step.
- [x] I checked the issue tracker for similar issues
- [x] I checked the [changelog](https://github.com/clementine-player/Clementine/blob/master/Changelog) if the issue is already resolved
- [x] I tried the latest Clementine build from [here](https://builds.clementine-player.org/)
### System information

Please provide information about your system and the version of Clementine used.
- Operating System: Arch Linux
- Clementine version: 1.3.1
### Expected behaviour / actual behaviour

if I add titles in playlist it's have correct titles, but if I start playing it, codepage setting is wrong
Example:
Correct titles (before playing start):
Artist - Турбомода
Title - Мама
Incorect titles (if I start playing):
Artist - Òóðáîìîäà
Title - Ìàìà

Same behavior in title bar and playlist.

If I push Stop button, titles turn in correct.
### Steps to reproduce the problem (only for bugs)

add to playlist some russians titles from vk.com plugin and push Play button.

**Comment by CPAllianceP** [comment]
Same
