### ISSUE TITLE
Fix Queue 

### ISSUE THREAD

**Issue by RedSoxFan04** [clementine-player/Clementine#5478]
My main problem with Clementine is that you can’t switch songs easily - playback is tied to the queue. If you’re playing a song and try to play a different song, it just adds the song you clicked on to the queue instead of playing it. I’d like to be able to switch songs just by clicking on the song I want to switch to.

**Comment by mananaBanana** [comment]
You can choose what happens to a song on double-click in the `Preferences`. You can either add it to the end of the currently playing queue or directly play it.

**Comment by RedSoxFan04** [comment]
I can only see options for: Append to the playlist
					   Replace the Playlist		
				           Open in new playlist
				           Add to the queue 

Which one do I choose?

**Comment by mananaBanana** [comment]
If you use these settings, it will append the song to the playlist *and* start playing that song right away.
* Append to the playlist.
* Always start playing.

Like [this] (https://imgur.com/a/T78fj).
