### ISSUE TITLE
Crash on Open

### ISSUE THREAD

**Issue by Thedaythemusicdied** [clementine-player/Clementine#5481]
Version 1.3.1 crashes when opened with Lion 10.7.5.

Please follow the steps below and check the boxes with [x] once you did the step.

- [x] I checked the issue tracker for similar issues
- [x] I checked the [changelog](https://github.com/clementine-player/Clementine/blob/master/Changelog) if the issue is already resolved
- [x] I tried the latest Clementine build from [here](https://builds.clementine-player.org/)

### System information

Please provide information about your system and the version of Clementine used.

- Operating System:
- Clementine version:

**Comment by Chocobozzz** [comment]
Without logs we cannot help

**Comment by hatstand** [comment]
Lion is too old & Mavericks is free.

**Comment by Thedaythemusicdied** [comment]
Yes, it is old.  That is why Clementine should work.  All the bugs 
should have been worked out.
If I upgrade there is a lot of installed software which may not be 
compatible.  (It also works perfectly fine.)

**Comment by hatstand** [comment]
We don't have the time to support old versions. You are free to compile clementine yourself and it will probably work.
