### ISSUE TITLE
Can't log in to Gpodder

### ISSUE THREAD

**Issue by mratmartinez** [clementine-player/Clementine#5491]
- Operating System: Lubuntu 16.04
- Clementine version: 1.2.3

Error downloading.
http://gpodder.net/api/2/devices/mratmartinez@anche.no/clementine-mrat.json - server replied: Not Found

**Comment by stragu** [comment]
Have you tried with the latest Clementine version? I have no issue logging in with Clementine 1.3.1

**Comment by mratmartinez** [comment]
Tried with Arch. Worked perfectly. 

Sorry, me bad
