### ISSUE TITLE
Podcast episodes not listed

### ISSUE THREAD

**Issue by j605** [clementine-player/Clementine#5494]
### Before posting

Please follow the steps below and check the boxes with [x] once you did the step.

- [x] I checked the issue tracker for similar issues
- [x] I checked the [changelog](https://github.com/clementine-player/Clementine/blob/master/Changelog) if the issue is already resolved
- [x] I tried the latest Clementine build from [here](https://builds.clementine-player.org/)

### System information

Please provide information about your system and the version of Clementine used.

- Operating System: Arch Linux
- Clementine version: 1.3.1(built from HEAD)

### Expected behaviour / actual behaviour
To download episodes listed in feed[https://feedpress.me/usererror] but clementine does not list episodes at all.

### Steps to reproduce the problem (only for bugs)
Add the feed using add podcast dialog.

**Comment by stragu** [comment]
I confirm that I can't see any episode listed from the feed you provided, in Clementine 1.3.1, on KXStudio 14.04.

I also tested with this feed: https://studio-dessai.github.io/feed.xml

I add the feed, right-click on it and "update this podcast" and nothing happens.

**Comment by Chocobozzz** [comment]
@j605 The `enclosure` tag of your RSS doesn't have a valid `type` attribute.

@stragu It's not a valid RSS feed for downloading podcasts (no `enclosure` tag).

**Comment by j605** [comment]
@Chocobozzz I will report it to the podcast creator, thanks.

**Comment by stragu** [comment]
@Chocobozzz My bad, I was using the wrong feed. The right one is the following:

https://studio-dessai.github.io/podcast.xml

... and this one does work as expected, loading episodes and everything.

Thanks for looking into it, and sorry about the confusion!

**Comment by j605** [comment]
The bug is fixed in feedpress. Thanks for all the help.
