### ISSUE TITLE
Cover art window does not update after a while

### ISSUE THREAD

**Issue by jaywink** [clementine-player/Clementine#5498]
### Before posting

Please follow the steps below and check the boxes with [x] once you did the step.
- [x] I checked the issue tracker for similar issues
- [x] I checked the [changelog](https://github.com/clementine-player/Clementine/blob/master/Changelog) if the issue is already resolved
- [x] I tried the latest Clementine build from [here](https://builds.clementine-player.org/)
### System information

Please provide information about your system and the version of Clementine used.
- Operating System: Ubuntu 16.04.1 LTS
- Clementine version: 1.3.1-237-g20ed72f~xenial (latest build)
### Expected behaviour / actual behaviour

Expected: When changing tracks, expect for cover art and track title (in cover art window) to update.

What happens: After usually three track changes, cover art window does not update any more.
### Steps to reproduce the problem (only for bugs)
- Launch clementine
- Start playing a track
- Click "Next" until cover art stops updating (for me usually third change).

Possibly related: track title does not update in Clementine Android player either. Desktop window title does update as shown in the screenshot. My tracks are all accessed via an NFS drive, if that matters. I can't say when this started happening, possibly after 1.3.1 since it used to work before at some point. The screenshot below shows the wrong title.

![selection_302](https://cloud.githubusercontent.com/assets/1174866/18814971/b4b46050-832a-11e6-88ae-12fe2a99ea65.png)

**Comment by paulsommer** [comment]
Got the same error. It's not after 3 changes, but sooner or later the covers stop changing.

**Comment by gordon-morehouse** [comment]
I'm seeing this in 1.3.1-333-gf854bc5 on both Android Remote and the Linux Mint lock screen. My music is on a local filesystem and it's not 3 changes for me either. I haven't figured out how to reproduce it yet, if possible.

**Comment by gordon-morehouse** [comment]
I should add that "song details" in Android Remote also displays the details for the same (incorrect) song as the cover art display. This state persists across reboots of the Android device, etc.

**Comment by nigels-com** [comment]
Is this the same problem that my "Artist Info" is empty?

<img width="791" alt="screen shot 2017-06-18 at 4 37 41 pm" src="https://user-images.githubusercontent.com/545677/27258694-c3c20804-5444-11e7-8ae3-99fd044b6621.png">

**Comment by jaywink** [comment]
I haven't seen this issue in a long time so closing 🎉 Thanks for an awesome player!
