### ISSUE TITLE
artist biographies and photos are not showing in version 1.3.1.

### ISSUE THREAD

**Issue by JohnMGD** [clementine-player/Clementine#5503]
### Before posting

Please follow the steps below and check the boxes with [x] once you did the step.

- [ *] I checked the issue tracker for similar issues
- [ ] I checked the [changelog](https://github.com/clementine-player/Clementine/blob/master/Changelog) if the issue is already resolved
- [* ] I tried the latest Clementine build from [here](https://builds.clementine-player.org/)

### System information

Please provide information about your system and the version of Clementine used.

- Operating System:MacOSX 10.12 Sierra
- Clementine version: 1.3.1.

### Steps to reproduce the problem (only for bugs)artist biographies and photos are not showing anymore

**Comment by stragu** [comment]
I can confirm this, I am using Clementine 1.3.1 on Ubuntu 14.04-based KXStudio 14.04.
Song info tab works fine, Artist info tab show nothing (see screenshot).
![no-artist-info](https://cloud.githubusercontent.com/assets/1747497/19018646/6e4c34b0-88ae-11e6-91ea-f70e686c52ff.png)

**Comment by nenadandric** [comment]
It is the same on Windows 10 (also Clementine 1.3.1)

**Comment by JohnMGD** [comment]
So...knowing that this appears in not only my operating system, what can be done about it ?? Developers of CLEMENTINE, what can you guys (girls) do about it ????
Please help !!

**Comment by hatstand** [comment]
Did you actually try the latest version from here? https://builds.clementine-player.org/

**Comment by nenadandric** [comment]
Actually, when I download the latest vesion from there, isnted of official website, Clementine doesn't play at all. I either get "Internal data flow error" (with 1.3.1-217-g17beaa7) or "GStreamer encountered a general stream error" (with 1.3.1-216-g04f73d1), but that's another issue

**Comment by stragu** [comment]
Hi @hatstand 
I installed clementine_1.3.1-238-gac90f0b~trusty_amd64.deb
I can see the Artist info populated now, but I can't play any audio now, I get a "GStreamer encountered a general stream error." for every track I try to play. The terminal says:

```
09:58:59.424 ERROR GstEnginePipeline:645            4 "gstbaseparse.c(3243): gst_base_parse_loop (): /GstPipeline:pipeline/GstURIDecodeBin:uridecodebin-54/GstDecodeBin:decodebin4/GstMpegAudioParse:mpegaudioparse2:
streaming stopped, reason not-linked" 
09:58:59.544 WARN  GstEngine:690                    Gstreamer error: "GStreamer encountered a general stream error." 
09:58:59.545 ERROR logging:56                       Source ID 14 was not found when attempting to remove it 
```

Any idea what that could be?

**Comment by JohnMGD** [comment]
QUESTION::   What has posting here for use, if the makers of CLEMENTINE don't bother about the problems we post ?????? So Guys, "DO SOMETHING ABOUT IT" if you ever going to read this that is !!!! :(

**Comment by stragu** [comment]
Hey, @JohnMGD, please be respectful and patient. Developers here are not paid for their work, and they develop this app in their spare time, they do not need you to "shout" at them.

First of all, you never replied to Hatstand's question about trying the latest builds on https://builds.clementine-player.org/
Please try that and report here if you still witness the issue or not. 

So far, everyone who has tried can see that the issue with artist info is fixed in the more recent builds. 

About the second Gstreamer issue, it should belong to a separate issue.

Cheers

**Comment by JohnMGD** [comment]
Hello Stragu,
I like to apologise, for my inpatients, and I missed the latest builds link, sorry again, will better my life ;) I downloaded the latest build now and will install it, will let you know the result !!

**Comment by JohnMGD** [comment]
Just installed the latest build of CLEMENTINE, version 1.3.1 build 224 from August 2016, and all is working again like it should, great work ! Again like to apologise !!
