### ISSUE TITLE
Will there ever be a build for Windows again?

### ISSUE THREAD

**Issue by kekkc** [clementine-player/Clementine#5515]
### Before posting

Please follow the steps below and check the boxes with [x] once you did the step.
- [X] I checked the issue tracker for similar issues
- [X] I checked the [changelog](https://github.com/clementine-player/Clementine/blob/master/Changelog) if the issue is already resolved
- [X] I tried the latest Clementine build from [here](https://builds.clementine-player.org/) --> actually no, because this is the issue
### System information

na
### Expected behaviour / actual behaviour

New developer builds will deploy on Windows (and not just LUX)
### Steps to reproduce the problem (only for bugs)

Open https://builds.clementine-player.org/ or http://buildbot.clementine-player.org/builders/Windows%20Portable?numbuilds=90 (latest build is from 18.07.)

**Comment by santigl** [comment]
It seems that now the [Mac builds](http://buildbot.clementine-player.org/builders/Mac%20Release) are also failing.

**Comment by hatstand** [comment]
... and it's back
