### ISSUE TITLE
playlist tabs with delete-x nuisance

### ISSUE THREAD

**Issue by francois43** [clementine-player/Clementine#5516]
Hi, tabs for playlists contain 3 things: star for saving, its name, and "X" for deleting, which is very close to the end of that name. This design leads to serious errors. When I am in the process of populating several playlists, they are not yet saved. Changing to another playlist makes you sometimes klick on the X accidentally, and BANG! it is gone forever. Gone also is that hour or so work that you put into it. 

Solution: have an additional popup asking if you want to delete that playlist (as it should have had anyway). I know tabs in Thunderbird and the likes  do not have that, but then, I never deleted a tab in Thunderbird accidentally. Somehow it is the Clementine playlist tab that enables this mistake. Please, it happened several times now. 

thanks

**Comment by francois43** [comment]
Hi all, my excuses! It is already solved. When a playlist has not yet been saved, a popup will be there. When it has been saved before, the tab disappears, but the playlist lives in the left window when choosing Playlist in the left column. I just confused tabs with the playlist itself, so too speak, and forgetting I saved them in an earlier session...

**Comment by ArnaudBienner** [comment]
So from my understanding there is no no problem here.
Closing the bug then.
