### ISSUE TITLE
soundcloud login opens infinite number of winebrowser

### ISSUE THREAD

**Issue by fuzunspm** [clementine-player/Clementine#5518]
when i want to login to soundcloud, it opens winebrowsers endlessly and making system halt/crash. I'm using kubuntu 16.10 and clementine 1.3.1

**Comment by SirSharpest** [comment]
This isn't a clementine issue from the sound of it but rather an issue your system has with allowing wine to handle your default web links

**Comment by fuzunspm** [comment]
you were right
