### ISSUE TITLE
Windows: GStreamer general stream error (No Sound)

### ISSUE THREAD

**Issue by santigl** [clementine-player/Clementine#5533]
Now that Windows builds are being created again (thank you for closing #5515, @hatstand), I tried running the current master branch [Windows release](http://builds.clementine-player.org/win32/release/ClementineSetup-1.3.1-244-gd19ee71.exe). Unfortunately, I found that the sound output isn't working.

GStreamer throws the following error message:
> GStreamer encountered a general stream error.
 >Internal data flow error.

I could observe that in Windows 7 64 bits. However, with the 1.3.1 release build, the sound works with no problems in the same system.

Looking at the commit list since the 1.3.1 release, the only one that modified GStreamer related code was https://github.com/clementine-player/Clementine/commit/bcf29dc6707e55f7b82f244f05ef5fbd2e008f6b (submitted on May 15, 2016).

The newer build previous to those changes is http://buildbot.clementine-player.org/builders/Windows%20Release/builds/100, done on April 25th. I tried running that .exe, and the output works correctly.

(The Linux version, at least on Debian 64 bits, seems to not be affected.)

**Comment by kancaras** [comment]
I noticed the same. Then i set audio output device manualy in settings and theres no error anymore, but playback doesnt start either, playlist just goes through all the tracks very fast.

Im also on windows 7 64 bit.

**Comment by santigl** [comment]
I [committed](https://github.com/santigl/Clementine/commit/33d8dc5ef54ab263361d74f5c6c30e19c9af2ae6) a change that should fix the issue.

It removes the current restriction to convert the audio to 32 bits. That allows the audiosink to autonegotiate a bit depth value with the decoder, choosing a value that is supported by the hardware.

I tested it in Linux and it didn't break the output. If @hatstand or @ArnaudBienner want to merge it to a temporary separate branch, we could get a binary from the build bot and test it on Windows.

**Comment by santigl** [comment]
Thanks to @hatstand, we have a Windows [build with the patch](http://builds.clementine-player.org/win32/release/ClementineSetup-1.3.1-246-g33d8dc5.exe).

I just gave it a try on Windows 7 64 bits, and the audio works again.

**Comment by kekkc** [comment]
Cool build, works for me too (first dev build after July that's usable again on Windows ;) )

**Comment by SpiralBrad** [comment]
Works here too; had the same problem with the other builds. Good fix.

**Comment by santigl** [comment]
With 1c0891202d582b8a7ca96f73e517b24120b6ac09, this should be now corrected in new builds. (Thanks, @hatstand!)
