### ISSUE TITLE
Add Support for chromecast

### ISSUE THREAD

**Issue by dkiser** [clementine-player/Clementine#5546]
### Before posting

Please follow the steps below and check the boxes with [x] once you did the step.

- [x ] I checked the issue tracker for similar issues
- [x ] I checked the [changelog](https://github.com/clementine-player/Clementine/blob/master/Changelog) if the issue is already resolved
- [x ] I tried the latest Clementine build from [here](https://builds.clementine-player.org/)

### System information

Please provide information about your system and the version of Clementine used.

- Operating System: OSX
- Clementine version: 1.2.2

### Expected behaviour / actual behaviour

GIVEN Clementine player is running
WHEN music is playing
THEN I expect to see a cast icon show up in greyed out form if no chromecast is found
AND
THEN I expect to see a cast icon in a color other than grey if one or more chromecast devices is found

GIVEN Clementine player is running with at least one chromecast found
WHEN I click on the enabled cast icon
THEN I expect to pick from a list of device to cast to

GIVEN User clicks on an activated chromecast icon
WHEN I the device to cast to
THEN audio streams to the chosen chromecast device
AND
THEN I expect to see an identifier of song title and clementine on the Screen for video enabled cast devices
AND
THEN I expect the screen to have some sort of screensaver (milkdrop?!) for video enabled cast devices

**Comment by hatstand** [comment]
There's no desktop API for chromecast. Feel free to reopen later if/when one materialises.

**Comment by Ferroin** [comment]
To further expand on this, check https://en.wikipedia.org/wiki/Google_Cast#Operation
In short, the normal method of usage requires tight integration with Google (and therefore is unfeasable), and the alternative method requires reverse-engineering a closed protocol (which would put Clementine in a potentially problematic legal position).  The only possibility of getting this legally is if Google decides to publicly document the alternative method, which is not at all likely to happen.

**Comment by triune** [comment]
FWIW: http://www.webupd8.org/2016/03/how-to-stream-audio-to-chromecast-or.html PulseAudio to CC works perfectly for me to stream Clementine to any TV in my house ;)

**Comment by earthsound** [comment]
Another option is mkchromecast + Soundflower. Once installed, choose Soundflower as the input/output. 
http://mkchromecast.com/
https://github.com/mattingalls/Soundflower/

Airfoil works, too, for $29 ($26 if you visit from the soundcast github page).

**Comment by kishoreuk2008** [comment]
Actually there's another way to cast your pc songs to chromecast using chrome browser. First you need to download the Enjoy music player from the chrome apps section: https://chrome.google.com/webstore/detail/enjoy-music-player/hncfgilfeieogcpghjnnhddghgdjbekl?utm_source=chrome-ntp-icon
This will be saved as a chrome app. When you open the app you will have option to add the folders to scan for music. When you check on the bottom right corner of the app you will see the cast icon. Then you have to select the enable and a port will be asked, you can set the default port for tab and click on the link below the port you will be redirected to a new tab where all the music will be played. It also has nice visualizer you might like it. Enjoy

**Comment by triune** [comment]
@kishoreuk2008 that has nothing to do with Clementine.

**Comment by tincho** [comment]
HI!
(thank you all for working on Clementine!)

+1 to this feature request

I don't know about Chromecast API, but VLC 3 (beta) has a feature using: 
Video -> Renderer -> (check Scan... then the devices appear as) -> Chromecast-Audio-NNN 

I'd like very much using Clementine and stream its output to the Chromecast (and only Clementine's, not all audio from all apps), as VLC is not my favorite for playing music.

Best!

**Comment by lokke3** [comment]
I'm in the same boat. I was using VLC as my audio player, and clementine is better in every way other than not supporting chromecast.

**Comment by fivestones** [comment]
I'd also sure love chromecast support in clementine. When this issue was opened there wasn't really a feasible way, but VLC's chromecast support indicates to me that now there is a feasible way.

**Comment by fivestones** [comment]
bump

**Comment by hatstand** [comment]
Don't do that. It doesn't help.

**Comment by fivestones** [comment]
@hatstand What should I do instead? You wrote in 2016, "Feel free to reopen later if/when [a desktop api for chromecast] materialises." And other apps, like VLC, among many others, are doing casting to a chromecast from a desktop app. I can't just reopen this issue. So I brought up the fact that other desktop apps support this without any trouble, and after almost 2 months, when no one had made any kind of response (e.g., reopening the issue), I said "bump" because I figured no one had seen it and maybe a bump would bring it back to the top.

What *does* help, that I can do?

Thanks!

**Comment by hatstand** [comment]
There is still no official desktop API for Chromecast AFAIK but I think we'd accept a PR that used some unofficial open source implementation now that that's commonplace.

**Comment by bzz11g** [comment]
Any news about support for Chromecast?

**Comment by rvdavid** [comment]
> @hatstand What should I do instead? You wrote in 2016, "Feel free to reopen later if/when [a desktop api for chromecast] materialises." And other apps, like VLC, among many others, are doing casting to a chromecast from a desktop app. I can't just reopen this issue. So I brought up the fact that other desktop apps support this without any trouble, and after almost 2 months, when no one had made any kind of response (e.g., reopening the issue), I said "bump" because I figured no one had seen it and maybe a bump would bring it back to the top.
> 
> What _does_ help, that I can do?
> 
> Thanks!

Thanks! 
Switching to VLC. I'll check back from time to time for when Chromecast is supported for Clementine.
