### ISSUE TITLE
Windows Installer requires administrator priveleges

### ISSUE THREAD

**Issue by AngleWyrm** [clementine-player/Clementine#5557]
This is a problem with the way programmer convenience works in the Windows environment, and needlessly excludes part of the audience.

**A good philosophy for work delegation**
If the software does not specifically represent some sort of security threat that should be managed by a systems administrator, then leave installation to the user.

**Comment by fitojb** [comment]
???

There’s no “exclusion” here. Clementine offers a portable version if you don’t want to perform a system-wide installation.

**Comment by Ferroin** [comment]
Clementine's installer installs the application system-wide, not for an individual user, therefore it requires access to file paths that can't be written to by a regular user.

**Comment by schultzter** [comment]
Maybe it's just me, but where do I download the portable version?! I can't find it any where in the downloads page! Yes, Google will find "download clementine portable" but these days downloading stuff from _alternative_ sites is too risky! Thanks,

**Comment by garciaadrian** [comment]
Grab it from the official build site [https://builds.clementine-player.org](here) @schultzter
