### ISSUE TITLE
Enable search-by-artist and search-by-album when right-clicking on a song in playlist or search. 

### ISSUE THREAD

**Issue by JacobHenner** [clementine-player/Clementine#5567]
### Before posting

Please follow the steps below and check the boxes with [x] once you did the step.

- [X] I checked the issue tracker for similar issues
- [X] I checked the [changelog](https://github.com/clementine-player/Clementine/blob/master/Changelog) if the issue is already resolved
- [X] I tried the latest Clementine build from [here](https://builds.clementine-player.org/)

### System information

Please provide information about your system and the version of Clementine used.

- Operating System: Arch
- Clementine version: 1.3.1

### Expected behaviour / actual behaviour

Clementine should allow the user to search by artist or search by album by right-clicking on a search result, or a song in a playlist, and selecting the corresponding option. 

Example: User searches for song X, knowing it's on album Y. Instead of having to then search for album Y manually, the user right clicks on the result for song X, and selects "search by/for album", which returns the entire album.

**Comment by JacobHenner** [comment]
This would be resolved by #5649

**Comment by ronjouch** [comment]
Thanks @JacobHenner, awesome much appreciated UX feature 🙂. Tested on a git build, both searches work great for me!
