### ISSUE TITLE
Spotify plugin search crashes Clementine

### ISSUE THREAD

**Issue by gbrauen** [clementine-player/Clementine#5574]
### Before posting

Please follow the steps below and check the boxes with [x] once you did the step.

- [ x] I checked the issue tracker for similar issues
- [ x] I checked the [changelog](https://github.com/clementine-player/Clementine/blob/master/Changelog) if the issue is already resolved
- [ x] I tried the latest Clementine build from [here](https://builds.clementine-player.org/)

### System information

Please provide information about your system and the version of Clementine used.

- Operating System: Ubuntu 16.04 GNOME
- Clementine version: clementine 1.3.1-228-gd9b3a93~xenial [origin: LP-PPA-me-davidsansome-clementine] - also with latest - same behaviour so reverted to released version

### Expected behaviour / actual behaviour

Clementine is my main music player because it nicely integrates spotify streaming and playback of local files. Until recently. Mid-December 2016 both of my installations of Clementine on Ubuntu 16.04 (different hardware architectures) stopped working after package upgrades - not sure which package has caused the problem.

Expected behaviour:
1. Select Internet tab in Clementine; Click on Spotify.
    * Expected result: my spotify playlists should be listed.
2. Type search token into spotify search box.
    * Expected result: matching search results should be listed.

Actual results:
For matching steps above:
1. Spotify playlists are no longer listed. No information from my spotify account is ever listed.
2. Whenever I complete a search token by typing a space, for example "join ", spotify crashes.

Crash report: `clementine crashed with SIGSEGV in QStandardItem::rowCount()`

I deleted the spotify plugin (all of ~/.config/Clementine/spotify*) and restarted.  Problem persists once plugin reinstalled. The spotify plugin connects and logs in to my spotify account without problem.

#### SegvAnalysis
> Segfault happened at: 0x7f261c3b7100 <_ZNK13QStandardItem8rowCountEv>:	mov    0x8(%rdi),%rax
> PC (0x7f261c3b7100) ok
> source "0x8(%rdi)" (0x00000008) not located in a known VMA region (needed readable region)!
> destination "%rax" ok

#### SegvReason
> Reading NULL VMA

#### Signal
> 11

#### Disassembly
> => 0x7f261c3b7100 <_ZNK13QStandardItem8rowCountEv>:	mov    0x8(%rdi),%rax
>    0x7f261c3b7104 <_ZNK13QStandardItem8rowCountEv+4>:	mov    0x28(%rax),%eax
>    0x7f261c3b7107 <_ZNK13QStandardItem8rowCountEv+7>:	retq   
>    0x7f261c3b7108:	nopl   0x0(%rax,%rax,1)
>    0x7f261c3b7110 <_ZNK13QStandardItem11columnCountEv>:	mov    0x8(%rdi),%rax
>    0x7f261c3b7114 <_ZNK13QStandardItem11columnCountEv+4>:	mov    0x2c(%rax),%eax
>    0x7f261c3b7117 <_ZNK13QStandardItem11columnCountEv+7>:	retq   
>    0x7f261c3b7118:	nopl   0x0(%rax,%rax,1)
>    0x7f261c3b7120 <_ZNK13QStandardItem11hasChildrenEv>:	push   %rbx
>    0x7f261c3b7121 <_ZNK13QStandardItem11hasChildrenEv+1>:	mov    %rdi,%rbx
>    0x7f261c3b7124 <_ZNK13QStandardItem11hasChildrenEv+4>:	callq  0x7f261c3b7100 <_ZNK13QStandardItem8rowCountEv>
>    0x7f261c3b7129 <_ZNK13QStandardItem11hasChildrenEv+9>:	xor    %edx,%edx
>    0x7f261c3b712b <_ZNK13QStandardItem11hasChildrenEv+11>:	test   %eax,%eax
>    0x7f261c3b712d <_ZNK13QStandardItem11hasChildrenEv+13>:	jle    0x7f261c3b713c <_ZNK13QStandardItem11hasChildrenEv+28>
>    0x7f261c3b712f <_ZNK13QStandardItem11hasChildrenEv+15>:	mov    %rbx,%rdi
>    0x7f261c3b7132 <_ZNK13QStandardItem11hasChildrenEv+18>:	callq  0x7f261c3b7110 <_ZNK13QStandardItem11columnCountEv>

### Steps to reproduce the problem (only for bugs)

See steps 1 and 2 under expected behaviour above.

**Comment by szekeres2016** [comment]
I also experience issues with libspotify, something must have changed aabout the API or something similar because it can't load any of my playlists, and it crashes on search so not using it at the moment just to be safe.

**Comment by Chocobozzz** [comment]
Please copy/paste the Clementine output with DEBUG logs.

**Comment by szekeres2016** [comment]
Installing the plugin:

09:41:47.340 INFO  SpotifyBlobDownloader:91         Downloading  QUrl( "https://spotify.clementine-player.org/version16-64bit/blob" )  
09:41:47.341 INFO  SpotifyBlobDownloader:91         Downloading  QUrl( "https://spotify.clementine-player.org/version16-64bit/blob.sha512" )  
09:41:47.341 INFO  SpotifyBlobDownloader:91         Downloading  QUrl( "https://spotify.clementine-player.org/version16-64bit/libspotify.so.12.1.51" )  
09:41:47.342 INFO  SpotifyBlobDownloader:91         Downloading  QUrl( "https://spotify.clementine-player.org/version16-64bit/libspotify.so.12.1.51.sha512" )  
09:41:47.846 DEBUG SpotifyBlobDownloader:212        Verifying "blob" against "blob.sha512" true 
09:41:47.857 DEBUG SpotifyBlobDownloader:212        Verifying "libspotify.so.12.1.51" against "libspotify.so.12.1.51.sha512" true 
09:41:47.857 INFO  SpotifyBlobDownloader:146        Writing "/home/peter/.config/Clementine/spotifyblob/version16-64bit/blob" 
09:41:47.858 INFO  SpotifyBlobDownloader:146        Writing "/home/peter/.config/Clementine/spotifyblob/version16-64bit/libspotify.so.12.1.51" 
09:41:47.860 DEBUG SpotifyBlobDownloader:165        Linking "/home/peter/.config/Clementine/spotifyblob/version16-64bit/libspotify.so.12.1.51" to "/home/peter/.config/Clementine/spotifyblob/version16-64bit/libspotify.so" 
09:41:47.860 DEBUG SpotifyBlobDownloader:165        Linking "/home/peter/.config/Clementine/spotifyblob/version16-64bit/libspotify.so.12.1.51" to "/home/peter/.config/Clementine/spotifyblob/version16-64bit/libspotify.so.12" 
09:41:47.860 DEBUG SpotifyBlobDownloader:165        Linking "/home/peter/.config/Clementine/spotifyblob/version16-64bit/libspotify.so.12.1.51" to "/home/peter/.config/Clementine/spotifyblob/version16-64bit/libspotify.so.12.1" 
09:41:47.861 INFO  SpotifyService:356               Starting "/home/peter/.config/Clementine/spotifyblob/version16-64bit/blob" 
09:41:47.884 DEBUG SpotifyClient:84                 Using: "/home/peter/.config/Clementine/spotify-cache" for Spotify cache 
09:41:47.885 DEBUG SpotifyClient:86                 Using: "/home/peter/.config/Clementine/spotify-settings" for Spotify settings 
09:41:47.885 DEBUG SpotifyClient:114                Connecting to port 44926 
09:41:47.885 INFO  SpotifyServer:53                 Connection from port 54892 
09:41:47.886 DEBUG SpotifyClient:321                Setting playback settings: bitrate 1 normalisation false 
09:41:47.886 WARN  SpotifyClient:343                Tried to relogin but no stored credentials 

After logging in to the service:

09:43:23.911 ERROR SpotifyService:235               Spotify blob process failed: 1 
09:43:23.924 INFO  SpotifyService:356               Starting "/home/peter/.config/Clementine/spotifyblob/version16-64bit/blob" 
09:43:23.949 DEBUG SpotifyClient:84                 Using: "/home/peter/.config/Clementine/spotify-cache" for Spotify cache 
09:43:23.950 DEBUG SpotifyClient:86                 Using: "/home/peter/.config/Clementine/spotify-settings" for Spotify settings 
09:43:23.950 DEBUG SpotifyClient:114                Connecting to port 41771 
09:43:23.950 INFO  SpotifyServer:53                 Connection from port 37902 
09:43:23.951 DEBUG SpotifyClient:321                Setting playback settings: bitrate 1 normalisation false 
09:43:23.951 DEBUG SpotifyClient:167                libspotify: "08:43:23.951 I [offline_authorizer.cpp:297] Unable to login offline: no such user" 
09:43:23.961 DEBUG SpotifyClient:167                libspotify: "08:43:23.961 I [ap:1752] Connecting to AP ap.spotify.com:4070" 
09:43:24.054 DEBUG SpotifyClient:167                libspotify: "08:43:24.054 I [ap:1226] Connected to AP: 194.14.177.35:4070" 
09:43:24.290 DEBUG SpotifyClient:167                libspotify: "08:43:24.289 I [user_cache:135] UserCache::initiateGetUsers() will query for 1 users" 
09:43:24.355 DEBUG SpotifyClient:167                libspotify: "08:43:24.355 I [offline-mgr:2084] Storage has been cleaned" 
09:43:24.878 DEBUG SpotifyClient:432                Got playlist 0 false 0  
09:43:24.878 INFO  SpotifyClient:436                Playlist is not loaded yet, waiting... 
09:43:24.879 DEBUG SpotifyClient:432                Got playlist 0 false 0  
09:43:24.879 INFO  SpotifyClient:436                Playlist is not loaded yet, waiting... 
09:43:24.879 DEBUG SpotifyClient:432                Got playlist 0 false 0  
09:43:24.879 INFO  SpotifyClient:436                Playlist is not loaded yet, waiting... 
09:43:24.879 DEBUG SpotifyClient:432                Got playlist 0 false 0  
09:43:24.879 INFO  SpotifyClient:436                Playlist is not loaded yet, waiting... 
09:43:24.879 DEBUG SpotifyClient:432                Got playlist 0 false 0  
09:43:24.879 INFO  SpotifyClient:436                Playlist is not loaded yet, waiting... 
09:43:24.880 DEBUG SpotifyClient:432                Got playlist 0 false 0  
09:43:24.880 INFO  SpotifyClient:436                Playlist is not loaded yet, waiting... 
09:43:24.880 DEBUG SpotifyClient:432                Got playlist 0 false 0  
09:43:24.880 INFO  SpotifyClient:436                Playlist is not loaded yet, waiting... 
09:43:24.880 DEBUG SpotifyClient:432                Got playlist 0 false 0  
09:43:24.880 INFO  SpotifyClient:436                Playlist is not loaded yet, waiting... 
09:43:24.880 DEBUG SpotifyClient:432                Got playlist 0 false 0  
09:43:24.880 INFO  SpotifyClient:436                Playlist is not loaded yet, waiting... 
09:43:24.881 DEBUG SpotifyClient:432                Got playlist 0 false 0  
09:43:24.881 INFO  SpotifyClient:436                Playlist is not loaded yet, waiting... 
09:43:24.881 DEBUG SpotifyClient:432                Got playlist 0 false 0  
09:43:24.881 INFO  SpotifyClient:436                Playlist is not loaded yet, waiting... 
09:43:24.881 DEBUG SpotifyClient:432                Got playlist 0 false 0  
09:43:24.881 INFO  SpotifyClient:436                Playlist is not loaded yet, waiting... 
09:43:24.881 DEBUG SpotifyClient:432                Got playlist 0 false 0  
09:43:24.881 INFO  SpotifyClient:436                Playlist is not loaded yet, waiting... 
09:43:24.881 DEBUG SpotifyClient:432                Got playlist 0 false 0  
09:43:24.881 INFO  SpotifyClient:436                Playlist is not loaded yet, waiting... 
09:43:24.881 DEBUG SpotifyClient:432                Got playlist 0 false 0  
09:43:24.881 INFO  SpotifyClient:436                Playlist is not loaded yet, waiting... 
09:43:24.881 DEBUG SpotifyClient:432                Got playlist 0 false 0  
09:43:24.881 INFO  SpotifyClient:436                Playlist is not loaded yet, waiting... 
09:43:24.938 DEBUG SpotifyClient:432                Got playlist 0 false 0  
09:43:24.938 INFO  SpotifyClient:436                Playlist is not loaded yet, waiting... 
09:43:24.940 DEBUG SpotifyClient:432                Got playlist 0 false 0  
09:43:24.940 INFO  SpotifyClient:436                Playlist is not loaded yet, waiting... 
09:43:25.030 DEBUG SpotifyClient:167                libspotify: "08:43:25.030 E [ap:4172] ChannelError(5, 1, playlist)" 
09:43:25.030 DEBUG SpotifyClient:432                Got playlist 0 false 0  
09:43:25.031 INFO  SpotifyClient:436                Playlist is not loaded yet, waiting... 
09:43:25.031 DEBUG SpotifyClient:432                Got playlist 0 false 0  
09:43:25.031 INFO  SpotifyClient:436                Playlist is not loaded yet, waiting... 
09:43:25.229 DEBUG SpotifyClient:432                Got playlist 0 false 0  
09:43:25.229 INFO  SpotifyClient:436                Playlist is not loaded yet, waiting... 
09:43:25.229 DEBUG SpotifyClient:432                Got playlist 0 false 0  
09:43:25.229 INFO  SpotifyClient:436                Playlist is not loaded yet, waiting... 
09:43:25.232 DEBUG SpotifyClient:432                Got playlist 0 false 0  
09:43:25.232 INFO  SpotifyClient:436                Playlist is not loaded yet, waiting... 
09:43:25.232 DEBUG SpotifyClient:432                Got playlist 0 false 0  
09:43:25.232 INFO  SpotifyClient:436                Playlist is not loaded yet, waiting... 
09:43:25.288 DEBUG SpotifyClient:432                Got playlist 0 false 0  
09:43:25.288 INFO  SpotifyClient:436                Playlist is not loaded yet, waiting... 
09:43:25.288 DEBUG SpotifyClient:432                Got playlist 0 false 0  
09:43:25.288 INFO  SpotifyClient:436                Playlist is not loaded yet, waiting... 
09:43:25.288 DEBUG SpotifyClient:167                libspotify: "08:43:25.288 I [user_cache:135] UserCache::initiateGetUsers() will query for 1 users" 
09:43:25.289 DEBUG SpotifyClient:432                Got playlist 0 false 0  
09:43:25.289 INFO  SpotifyClient:436                Playlist is not loaded yet, waiting... 
09:43:25.289 DEBUG SpotifyClient:432                Got playlist 0 false 0  
09:43:25.289 INFO  SpotifyClient:436                Playlist is not loaded yet, waiting... 
09:43:26.426 DEBUG SpotifyClient:167                libspotify: "08:43:26.426 E [ap:4172] ChannelError(3, 1, link-tracks)" 
09:43:26.704 DEBUG SpotifyClient:167                libspotify: "08:43:26.704 E [ap:4172] ChannelError(0, 1, link-tracks)" 
09:43:26.884 DEBUG SpotifyClient:167                libspotify: "08:43:26.884 E [ap:4172] ChannelError(0, 1, link-tracks)" 
09:43:27.049 DEBUG SpotifyClient:167                libspotify: "08:43:27.049 E [ap:4172] ChannelError(0, 1, link-tracks)" 
09:43:35.035 DEBUG SpotifyClient:432                Got playlist 0 false 0  
09:43:35.035 INFO  SpotifyClient:436                Playlist is not loaded yet, waiting... 
09:43:35.035 DEBUG SpotifyClient:432                Got playlist 0 false 0  
09:43:35.035 INFO  SpotifyClient:436                Playlist is not loaded yet, waiting... 
09:43:38.004 DEBUG SpotifyClient:167                libspotify: "08:43:38.004 E [ap:4172] ChannelError(4, 1, playlist)" 
09:43:38.004 DEBUG SpotifyClient:432                Got playlist 0 false 0  
09:43:38.004 INFO  SpotifyClient:436                Playlist is not loaded yet, waiting... 
09:43:38.004 DEBUG SpotifyClient:432                Got playlist 0 false 0  
09:43:38.004 INFO  SpotifyClient:436                Playlist is not loaded yet, waiting... 
09:43:38.072 DEBUG SpotifyClient:432                Got playlist 0 false 0  
09:43:38.072 INFO  SpotifyClient:436                Playlist is not loaded yet, waiting... 
09:43:38.072 DEBUG SpotifyClient:432                Got playlist 0 false 0  
09:43:38.072 INFO  SpotifyClient:436                Playlist is not loaded yet, waiting... 
09:43:38.073 DEBUG SpotifyClient:432                Got playlist 0 false 0  
09:43:38.073 INFO  SpotifyClient:436                Playlist is not loaded yet, waiting... 
09:43:38.073 DEBUG SpotifyClient:432                Got playlist 0 false 0  
09:43:38.073 INFO  SpotifyClient:436                Playlist is not loaded yet, waiting... 
09:43:45.095 DEBUG SpotifyClient:167                libspotify: "08:43:45.095 E [ap:4172] ChannelError(9, 0, playlist)" 
09:43:45.193 DEBUG SpotifyClient:167                libspotify: "08:43:45.193 E [ap:4172] ChannelError(0, 1, playlist)" 
09:43:45.193 DEBUG SpotifyClient:432                Got playlist 0 false 0  
09:43:45.193 INFO  SpotifyClient:436                Playlist is not loaded yet, waiting... 
09:43:45.193 DEBUG SpotifyClient:432                Got playlist 0 false 0  
09:43:45.193 INFO  SpotifyClient:436                Playlist is not loaded yet, waiting... 
09:43:50.196 DEBUG SpotifyClient:432                Got playlist 0 false 0  
09:43:50.197 INFO  SpotifyClient:436                Playlist is not loaded yet, waiting... 
09:43:50.197 DEBUG SpotifyClient:432                Got playlist 0 false 0  
09:43:50.197 INFO  SpotifyClient:436                Playlist is not loaded yet, waiting... 
09:43:50.341 DEBUG SpotifyClient:167                libspotify: "08:43:50.341 E [ap:4172] ChannelError(0, 1, playlist)" 
09:43:50.341 DEBUG SpotifyClient:432                Got playlist 0 false 0  
09:43:50.341 INFO  SpotifyClient:436                Playlist is not loaded yet, waiting... 
09:43:50.341 DEBUG SpotifyClient:432                Got playlist 0 false 0  
09:43:50.341 INFO  SpotifyClient:436                Playlist is not loaded yet, waiting... 
09:43:55.740 DEBUG SpotifyClient:167                libspotify: "08:43:55.740 E [ap:4172] ChannelError(0, 0, playlist)" 
09:44:00.741 DEBUG SpotifyClient:432                Got playlist 0 false 0  
09:44:00.741 INFO  SpotifyClient:436                Playlist is not loaded yet, waiting... 
09:44:00.741 DEBUG SpotifyClient:432                Got playlist 0 false 0  
09:44:00.741 INFO  SpotifyClient:436                Playlist is not loaded yet, waiting... 
09:44:10.741 DEBUG SpotifyClient:432                Got playlist 0 false 0  
09:44:10.741 INFO  SpotifyClient:436                Playlist is not loaded yet, waiting... 
09:44:10.741 DEBUG SpotifyClient:432                Got playlist 0 false 0  
09:44:10.742 INFO  SpotifyClient:436                Playlist is not loaded yet, waiting... 
09:44:11.158 DEBUG SpotifyClient:167                libspotify: "08:44:11.158 E [ap:4172] ChannelError(2, 1, playlist)" 
09:44:11.158 DEBUG SpotifyClient:167                libspotify: "08:44:11.158 E [ap:4172] ChannelError(1, 0, playlist)" 
09:44:11.158 DEBUG SpotifyClient:432                Got playlist 0 false 0  
09:44:11.158 INFO  SpotifyClient:436                Playlist is not loaded yet, waiting... 
09:44:11.158 DEBUG SpotifyClient:432                Got playlist 0 false 0  
09:44:11.158 INFO  SpotifyClient:436                Playlist is not loaded yet, waiting...

**Comment by Chocobozzz** [comment]
Try to unfollow "Discover Weekly" Spotify playlist. I seems there is a problem when Clementine try to fetch this playlist.

**Comment by szekeres2016** [comment]
Nice, it worked! Thank you, is there any reason a playlist start acting like that?

**Comment by gbrauen** [comment]
Yes, that fixes the problem for me now as well. Thanks!

**Comment by gbrauen** [comment]
This problem has returned. I now get the same behaviour as described in the original post (no playlists listed when I click on Spotify in the Internet tab; search crashes Clementine; same crash report details). Checked the spotify client, I see that "Your Daily Mix" has shown up in my playlists.  There seems to be no option to unfollow / remove this, like we did above with "Discover Weekly", or I would try that.

Running from terminal, when I click on I get the following logs:

> 10:06:10.415 INFO  SpotifyService:356               Starting "/home/glenn/.config/Clementine/spotifyblob/version16-64bit/blob" 
> 10:06:10.433 DEBUG SpotifyClient:84                 Using: "/home/glenn/.config/Clementine/spotify-cache" for Spotify cache 
> 10:06:10.433 DEBUG SpotifyClient:86                 Using: "/home/glenn/.config/Clementine/spotify-settings" for Spotify settings 
> 10:06:10.433 DEBUG SpotifyClient:114                Connecting to port 46678 
> 10:06:10.434 INFO  SpotifyServer:53                 Connection from port 48724 
> 10:06:10.434 DEBUG SpotifyClient:321                Setting playback settings: bitrate 1 normalisation true 
> 10:06:10.440 DEBUG SpotifyClient:167                libspotify: "15:06:10.440 I [offline-mgr:2084] Storage has been cleaned" 
> 10:06:10.444 DEBUG SpotifyClient:167                libspotify: "15:06:10.444 I [ap:1752] Connecting to AP ap.spotify.com:4070" 
> 10:06:10.484 DEBUG SpotifyClient:167                libspotify: "15:06:10.484 I [ap:1226] Connected to AP: 193.235.32.18:4070" 
> 10:06:10.913 DEBUG SpotifyClient:167                libspotify: "15:06:10.913 E [ap:4172] ChannelError(4, 0, playlist)" 
> 10:06:11.104 DEBUG SpotifyClient:167                libspotify: "15:06:11.104 E [ap:4172] ChannelError(4, 1, playlist)" 
> 10:06:11.104 DEBUG SpotifyClient:167                libspotify: "15:06:11.104 E [ap:4172] ChannelError(1, 1, playlist)" 
> 10:06:11.134 DEBUG SpotifyClient:167                libspotify: "15:06:11.134 E [ap:4172] ChannelError(6, 1, playlist)" 
> 10:06:11.230 DEBUG SpotifyClient:167                libspotify: "15:06:11.229 E [ap:4172] ChannelError(7, 1, playlist)" 
> 10:06:21.341 DEBUG SpotifyClient:167                libspotify: "15:06:21.341 E [ap:4172] ChannelError(1, 1, playlist)" 
> 10:06:21.371 DEBUG SpotifyClient:167                libspotify: "15:06:21.371 E [ap:4172] ChannelError(0, 1, playlist)" 
> 10:06:21.371 DEBUG SpotifyClient:167                libspotify: "15:06:21.371 E [ap:4172] ChannelError(4, 1, playlist)" 
> 10:06:21.418 DEBUG SpotifyClient:167                libspotify: "15:06:21.418 E [ap:4172] ChannelError(2, 1, playlist)" 
> 10:06:21.418 DEBUG SpotifyClient:167                libspotify: "15:06:21.418 E [ap:4172] ChannelError(5, 0, playlist)" 
> 10:06:36.746 DEBUG SpotifyClient:167                libspotify: "15:06:36.746 E [ap:4172] ChannelError(1, 1, playlist)" 
> 10:06:36.773 DEBUG SpotifyClient:167                libspotify: "15:06:36.773 E [ap:4172] ChannelError(0, 1, playlist)" 
> 10:06:41.890 DEBUG SpotifyClient:167                libspotify: "15:06:41.890 E [ap:4172] ChannelError(1, 1, playlist)" 
> 10:06:42.173 DEBUG SpotifyClient:167                libspotify: "15:06:42.173 E [ap:4172] ChannelError(0, 1, playlist)" 
> 10:07:11.335 DEBUG SpotifyClient:167                libspotify: "15:07:11.335 E [ap:4172] ChannelError(4, 1, playlist)" 
> 10:07:12.074 DEBUG SpotifyClient:167                libspotify: "15:07:12.074 E [ap:4172] ChannelError(2, 1, playlist)" 
> 10:07:17.142 DEBUG SpotifyClient:167                libspotify: "15:07:17.142 E [ap:4172] ChannelError(0, 1, playlist)" 
> 10:07:17.399 DEBUG SpotifyClient:167                libspotify: "15:07:17.399 E [ap:4172] ChannelError(1, 1, playlist)" 
> 10:07:17.428 DEBUG SpotifyClient:167                libspotify: "15:07:17.428 E [ap:4172] ChannelError(2, 1, playlist)" 
> 10:07:47.709 DEBUG SpotifyClient:167                libspotify: "15:07:47.709 E [ap:4172] ChannelError(0, 0, playlist)" 
> 10:08:08.088 DEBUG SpotifyClient:167                libspotify: "15:08:08.088 E [ap:4172] ChannelError(1, 1, playlist)" 
> 10:08:11.982 DEBUG SpotifyClient:167                libspotify: "15:08:11.982 E [ap:4172] ChannelError(0, 1, playlist)" 
> 10:08:17.303 DEBUG SpotifyClient:167                libspotify: "15:08:17.303 E [ap:4172] ChannelError(0, 1, playlist)" 
> 10:08:29.285 DEBUG SpotifyClient:167                libspotify: "15:08:29.285 E [ap:4172] ChannelError(0, 1, playlist)" 
> 10:09:17.221 DEBUG SpotifyClient:167                libspotify: "15:09:17.221 E [ap:4172] ChannelError(0, 0, playlist)"
> ...

When I enter a search:

> 10:16:58.569 DEBUG SpotifyService:764               Got 200 results 
> 10:17:05.588 DEBUG SpotifyClient:167                libspotify: "15:17:05.588 I [offline-mgr:2032] 0 files are locked. 0 images are locked" 
> 10:17:05.588 DEBUG SpotifyClient:167                libspotify: "15:17:05.588 I [offline-mgr:2058] 0 files unlocked. 0 images unlocked" 
> Segmentation fault (core dumped)
