### ISSUE TITLE
vk.com search and playback stopped working due to API change

### ISSUE THREAD

**Issue by tobsz** [clementine-player/Clementine#5591]
### Before posting

Please follow the steps below and check the boxes with [x] once you did the step.

- [x] I checked the issue tracker for similar issues
- [x] I checked the [changelog](https://github.com/clementine-player/Clementine/blob/master/Changelog) if the issue is already resolved
- [x] I tried the latest Clementine build from [here](https://builds.clementine-player.org/)

### System information

Please provide information about your system and the version of Clementine used.

- Operating System: Win10 / Arch
- Clementine version: 1.3.1

### Expected behaviour / actual behaviour

Since the last API change of vk.com the clementine plugin stopped working. The search yields no results but one entry in cyrillic text. When you play it some guys says something in Russian. Login is still possible.

### Steps to reproduce the problem (only for bugs)

Use the vk.com plugin and try to search for a song.

**Comment by selumin** [comment]
Vk has disabled public API for music (more info could be found here: https://vk.com/dev/audio_api).
So Vk plugin is useless now.

**Comment by amidj** [comment]
Hello,
Maybe this is possible to regain access though this project [https://github.com/alashow/datmusic-api](https://github.com/alashow/datmusic-api).
