### ISSUE TITLE
Crash:  Dyld Error Message: Symbol not found: ___sincos_stret   Referenced from: /Applications/clementine.app/Contents/MacOS/clementine   Expected in: /usr/lib/libSystem.B.dylib

### ISSUE THREAD

**Issue by B-IT-GIT** [clementine-player/Clementine#5597]
Exception Type:  EXC_BREAKPOINT (SIGTRAP)
Exception Codes: 0x0000000000000002, 0x0000000000000000

Dyld Error Message:
  Symbol not found: ___sincos_stret
  Referenced from: /Applications/clementine.app/Contents/MacOS/clementine
  Expected in: /usr/lib/libSystem.B.dylib

**Comment by hatstand** [comment]
Please use the template.
