### ISSUE TITLE
Error while loading shared libraries: libprotobuf.so.10: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Tuplad** [clementine-player/Clementine#5625]
Getting the following error since an update:

clementine: error while loading shared libraries: libprotobuf.so.10: cannot open shared object file: No such file or directory

I'm using Manjaro Linux and have libprotobuf installed. Using clementine-git from AUR.

**Comment by hatstand** [comment]
We don't maintain the Arch builds.

**Comment by Chocobozzz** [comment]
@Tuplad Just reinstall clementine-git, protobuf has been updated so you need to recompile.

**Comment by Tuplad** [comment]
@Chocobozzz just tried, error after error. I'll try the github version.
