### ISSUE TITLE
Unrecognized command line options

### ISSUE THREAD

**Issue by GuineaPiet** [clementine-player/Clementine#5634]
Running Arch and trying to compile clementine-qt5 branch, causes the following errors:

cc1plus: error: unrecognized command line option ‘-Wno-unknown-warning-option’ [-Werror]
cc1plus: error: unrecognized command line option ‘-Wno-unused-private-field’ [-Werror]
cc1plus: all warnings being treated as errors
make[2]: *** [src/CMakeFiles/clementine_lib.dir/build.make:3741: src/CMakeFiles/clementine_lib.dir/core/appearance.cpp.o] Error 1
cc1plus: error: unrecognized command line option ‘-Wno-unknown-warning-option’ [-Werror]
cc1plus: error: unrecognized command line option ‘-Wno-unused-private-field’ [-Werror]
cc1plus: all warnings being treated as errors
make[2]: *** [src/CMakeFiles/clementine_lib.dir/build.make:3549: src/CMakeFiles/clementine_lib.dir/analyzers/analyzercontainer.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:727: src/CMakeFiles/clementine_lib.dir/all] Error 2
make: *** [Makefile:128: all] Error 2

All dependencies are installed

**Comment by Chocobozzz** [comment]
I don't have problems to compile Clementine on ArchLinux. Try to update Arch', delete the build directory and retry to recompile.
