### ISSUE TITLE
The position slider disappears after approximately 30 minutes

### ISSUE THREAD

**Issue by sboukortt** [clementine-player/Clementine#5638]
### Before posting

Please follow the steps below and check the boxes with [x] once you did the step.

- [x] I checked the issue tracker for similar issues
- [x] I checked the [changelog](https://github.com/clementine-player/Clementine/blob/master/Changelog) if the issue is already resolved
- [x] I tried the latest Clementine build from [here](https://builds.clementine-player.org/)

### System information

Please provide information about your system and the version of Clementine used.

- Operating System: Arch Linux
- Clementine version: 652f38ac8411b93f63a502e0698dbc6e186a1dda

### Expected behaviour / actual behaviour

Initially, the slider appears correctly:
![correct](https://cloud.githubusercontent.com/assets/16757512/23339797/2aa64396-fc2a-11e6-8ca2-4b7f61fe99b0.png)

But after a while, it is nowhere to be found anymore:
![incorrect](https://cloud.githubusercontent.com/assets/16757512/23339801/373d25e8-fc2a-11e6-86af-deb87a3ba60f.png)

It seems that it can also be reproduced by moving the slider manually (instead of waiting for half an hour) and that more precisely, it happens around 30:48 (tried on two different tracks with different lengths).

Moving the slider back before 30:48 makes it visible again.

**Comment by santigl** [comment]
I could recreate that same behavior in Debian 64 bits.

It only happens with the moodbar turned on. Also, the ~30:48 point seems to be an absolute value (I tested it with a 3 hours+ file and the cursor disappeared at around that same point).

**Comment by santigl** [comment]
Found the issue: [this calculation](https://github.com/clementine-player/Clementine/blob/e5ab3e786f9adde12cec3cc90cfe8c1cc6b06320/src/moodbar/moodbarproxystyle.cpp#L278) could overflow, making the moodbar's slider wrap around.

Would you test my commit, @sboukortt, and see that it works for you too?

**Comment by sboukortt** [comment]
The fix seems to work, thanks!

**Comment by pabloab** [comment]
I still have this problem on Ubuntu 16.04 64 bits with [last version](https://github.com/clementine-player/Clementine/releases/download/1.3.1/clementine_1.3.1-xenial_amd64.deb) available for download:
![image](https://cloud.githubusercontent.com/assets/657836/26012805/2754c28e-372c-11e7-8e53-435cd35c3cbe.png)
Also sometimes while trying to jump to any point of the file the position cursor jumps to the beginning of the track.
Using the file generated by this command: `youtube-dl --ignore-errors --output "%(title)s.%(ext)s" --extract-audio --audio-format mp3 --audio-quality 0 "https://www.youtube.com/watch?v=Ea2PnNrlaKE"`.

**Comment by santigl** [comment]
It is probably still not updated on Ubuntu.

You can try downloading and installing a newer version from here: http://builds.clementine-player.org/ubuntu-xenial/clementine_1.3.1-333-gf854bc5~xenial_amd64.deb
