### ISSUE TITLE
OneDrive sync stopped

### ISSUE THREAD

**Issue by alangaraujo** [clementine-player/Clementine#5639]
### Before posting

Please follow the steps below and check the boxes with [x] once you did the step.

- [x] I checked the issue tracker for similar issues
- [x] I checked the [changelog](https://github.com/clementine-player/Clementine/blob/master/Changelog) if the issue is already resolved
- [x] I tried the latest Clementine build from [here](https://builds.clementine-player.org/)

### System information

Please provide information about your system and the version of Clementine used.

- Operating System: Arch Linux
- Clementine version: 1.3.1

### Expected behaviour / actual behaviour

I linked it with my OneDrive account and worked for a few days.

Now, isn't linking anymore, even I reinstall everything (libraries included), revoke and accept Clementine to access my Microsoft Account again.

The OneDrive login window still showing the login button and the Microsoft Account page says Clementine has access to my files.

**Comment by hatstand** [comment]
Did you actually try the latest build?

**Comment by alangaraujo** [comment]
Yes, I did. With clementine-git 1.3.1.r287.g652f38ac8-1

**Comment by alangaraujo** [comment]
Did it again with r289 build and still not linking.

**Comment by alangaraujo** [comment]
I gave up, installed onedrive-d daemon to download and sync my music.

It's not perfect, but suit my needs.

Thank you
