### ISSUE TITLE
Ugly tray icon on xfce

### ISSUE THREAD

**Issue by Winterwolf** [clementine-player/Clementine#5641]
- Operating System: Linux Mint 18.1 Xfce edition
- Clementine version: 1.3.1, 1.3.2

![example](http://i.imgur.com/IKjXQ4E.png)

**UPD:** I found some solution: icon and menu will looks good if clementine started from `dbus-launch clementine`. But when it started from sound menu, it's still buggy!

**Comment by yerbestpal** [comment]
I have this same problem on Ubuntu Mate 16.10.

**Comment by jonaski** [comment]
I've never see this problem. I use opensuse with XFCE.
