### ISSUE TITLE
openSUSE Tumbleweed symbol lookup error

### ISSUE THREAD

**Issue by jgascon72** [clementine-player/Clementine#5642]
### System information

Please provide information about your system and the version of Clementine used.

- Operating System: openSUSE Tumbleweed 20170226
- Clementine version: clementine-1.3.1-4.1.x86_64

### Expected behaviour / actual behaviour
How reproducible: 100% 
Steps to Reproduce: 
1. "clementine" 
Actual results: clementine: clementine: symbol lookup error: clementine: undefined symbol: _ZN8CryptoPP6SHA5129TransformEPyPKy

Expected results: starts

**Comment by victorhck** [comment]
same issue here with the same OS

**Comment by hatstand** [comment]
This is a problem with the suse builds which we do not maintain.
