### ISSUE TITLE
Clementine reads file pieces multiple times (~x60).

### ISSUE THREAD

**Issue by nikola-sh** [clementine-player/Clementine#5652]
### Before posting

Please follow the steps below and check the boxes with [x] once you did the step.

- [x ] I checked the issue tracker for similar issues
- [x ] I checked the [changelog](https://github.com/clementine-player/Clementine/blob/master/Changelog) if the issue is already resolved
- [x ] I tried the latest Clementine build from [here](https://builds.clementine-player.org/)

### System information

Please provide information about your system and the version of Clementine used.

- Operating System: Windows 10 x64
- Clementine version: 1.3.1

###  Expected behaviour / Actual behaviour
Clementine reads mp3 file pieces multiple times.
It reads 64k at offset 3842, then 64k at offset 4469, etc. 
See attached pictures.

### Steps to reproduce the problem (only for bugs)
1. Start Process Monitor (https://technet.microsoft.com/en-us/sysinternals/processmonitor)
2. Play MP3 file by Clementine
3. See Process Monitor log
![procexp](https://cloud.githubusercontent.com/assets/11009211/23683079/2470fd60-03a8-11e7-90f1-d362609872fe.png)
![procmon](https://cloud.githubusercontent.com/assets/11009211/23683080/24728a90-03a8-11e7-8a51-0498bfe6b865.png)

**Comment by hatstand** [comment]
So?
