### ISSUE TITLE
Can't compile Clementine on Arch after system upgrade.

### ISSUE THREAD

**Issue by JacobHenner** [clementine-player/Clementine#5660]
### Before posting

Please follow the steps below and check the boxes with [x] once you did the step.

- [x] I checked the issue tracker for similar issues
- [x] I checked the [changelog](https://github.com/clementine-player/Clementine/blob/master/Changelog) if the issue is already resolved
- [x] I tried the latest Clementine build from [here](https://builds.clementine-player.org/)

### System information

Please provide information about your system and the version of Clementine used.

- Operating System: Arch Linux
- Clementine version: git revision 6c9bc43bbb0b23a1fd8801e2075cef44cc3aae8b

### Expected behaviour / actual behaviour

When trying to build Clementine, I experience the following error:  

```[ 14%] Generating core/moc_organise.cxx
/usr/include/glib-2.0/glib/gversionmacros.h:52: Parse error at "defined"
make[2]: *** [src/CMakeFiles/clementine_lib.dir/build.make:345: src/core/moc_organise.cxx] Error 1
make[1]: *** [CMakeFiles/Makefile2:782: src/CMakeFiles/clementine_lib.dir/all] Error 2
make: *** [Makefile:128: all] Error 2
```
Prior to a recent system upgrade (`pacman -Syu`), this was not the case. 

### Steps to reproduce the problem (only for bugs)

Attempt to build Clementine on an up to date Arch Linux machine, using the instructions provided in the README.

**Comment by Chocobozzz** [comment]
I suggest you to use the AUR package https://aur.archlinux.org/packages/clementine-git/

**Comment by hatstand** [comment]
Paste the *entire* error somewhere.

**Comment by JacobHenner** [comment]
@Chocobozzz I did not use the AUR package because I have been contributing, not just attempting to compile from source. However, I did notice the patch available there, and it seems to have worked. Thank you for that advice. 

@hatstand That was the entire error from the make output: 
![screenshot from 2017-03-14 08-35-02](https://cloud.githubusercontent.com/assets/144119/23900997/b5426f34-0891-11e7-9822-bdf6dd80684d.png)

The patch in AUR at https://aur.archlinux.org/cgit/aur.git/plain/moc-fix.diff?h=clementine-git seems to have remedied the issue for me, although it was not necessary a week or two ago.

**Comment by hatstand** [comment]
Looks like a bug in Qt: https://bugzilla.redhat.com/show_bug.cgi?id=1396755

I think that patch will work for us too.

**Comment by JacobHenner** [comment]
@hatstand I can submit the PR as long as it won't break on other systems. I'm unfamiliar with how this might affect other builds.

**Comment by hatstand** [comment]
Our buildbot will catch it on the platforms we care about so don't worry.

**Comment by JacobHenner** [comment]
@hatstand Sounds good. I'll take care of it during lunch.
