### ISSUE TITLE
Edit the wiki to remove the claim that you provide a Debian Download.

### ISSUE THREAD

**Issue by andy-twosticks** [clementine-player/Clementine#5691]
Or better yet, provide a Debian Download.

The downloads page has a link to builds for:

* Fedora (x6)
* Ubuntu (x10)
* Raspberry Pi
* Windows
* OSX
* Source code

... but no Debian.  (Am I supposed to use the Ubuntu PPA? Does that work?)

**Comment by hatstand** [comment]
https://builds.clementine-player.org/debian-jessie/

**Comment by andy-twosticks** [comment]
Thank you!

Now if it were on the wiki, you wouldn't have to have closed the issue?

(Since it isn't, why did you?)
