### ISSUE TITLE
CUE russian lang

### ISSUE THREAD

**Issue by skoropadskiy** [clementine-player/Clementine#5694]
Do not load to Media Library CUE files with Russian language in UTF-8 or CP-1251.

### System information

- Operating System: MAC OS 10.12.1
- Clementine version: 1.3.1

**Comment by isvladxxe** [comment]
problem with russian filename for file tag
when rename to Eng and convert cue to utf-8.  work fine
os win

**Comment by hatstand** [comment]
Just use UTF8
