### ISSUE TITLE
Cannot search song from Spotify

### ISSUE THREAD

**Issue by kentsangkm** [clementine-player/Clementine#5716]
### Before posting

Please follow the steps below and check the boxes with [x] once you did the step.

- [X] I checked the issue tracker for similar issues
- [X] I checked the [changelog](https://github.com/clementine-player/Clementine/blob/master/Changelog) if the issue is already resolved
- [X] I tried the latest Clementine build from [here](https://builds.clementine-player.org/)

### System information

Please provide information about your system and the version of Clementine used.

- Operating System: Ubuntu 16.04.2 LTS
- Clementine version: 1.3.1-329-g52f1982

### Preconditions
Spotify is logged in. 
Premium account is used.
I can listen to the Spotify song already in the playlist

### Expected behaviour / actual behaviour
Within the "Search" tab, while I input some keyword, a search to my library and spotify will be perform. I suppose if I keyin "Yesterday", a spotify search can be made.

But since mid Apr 2017, this feature is broken. Only the song from my library can be displayed. Here is the log from Clementine

13:59:49.741 DEBUG SpotifyClient:167                libspotify: "05:59:49.741 E [ap:4172] ChannelError(0, 1, search)" 
13:59:49.741 DEBUG SpotifyService:750               Old search result for "Hello" expecting "" 
13:59:51.528 DEBUG SpotifyClient:167                libspotify: "05:59:51.528 E [ap:4172] ChannelError(0, 1, search)" 
13:59:51.529 DEBUG SpotifyService:750               Old search result for "Hello" expecting ""

**Comment by optermon** [comment]
I have exactly the same issue, it seems that the same issue happened one year ago and the solution was to contact spotify support: https://github.com/clementine-player/Clementine/issues/5238

I doesn't matter the OS, I have clementine in Ubuntu 16.04 and Windows 10, the spotify search function doesn't work in any of them.

I'll be also grateful for any help, since Clementine is my favorite music player.

**Comment by diegombeltran** [comment]
I was getting some errors related to special Spotify playlists (Weekly, Mixes, "Best of", etc). Unsuscribing these playlists seems to fix rest of the playlists not showing in Clementine, but now, I cannot search.

**Comment by MelissaManley97** [comment]
Does the Spotify search also not work under the "Internet" tab? Or is this issue just related to the "Search" tab?

**Comment by kentsangkm** [comment]
Hi, both Internet and Search cannot search the song. But I can extract the
song playlist from the Internet tab. That is the most weird thing.

Just got the reply from spotify, they classify this is clementine issue,
and dont offer help but redirect me to a very old discussion thread only

https://community.spotify.com/t5/Desktop-Linux-Windows-Web-Player/Spotify-plugin-won-t-work-on-Clementine-v1-2-3/td-p/1359452

2017年4月25日 04:52，"MelissaManley97" <notifications@github.com>寫道：

**Comment by MelissaManley97** [comment]
Are you sure you have the latest release of Clementine? I was having the same issue a couple of months ago and made a fix that was accepted as a pull request in March.
[https://github.com/clementine-player/Clementine/pull/5682](https://github.com/clementine-player/Clementine/pull/5682)
I'm guessing you're having a similar issue to the one in that link? I believe that after pull requests are accepted they have a new release of the software, but I'm relatively new to Clementine so I'm not positive.

**Comment by kentsangkm** [comment]
Thanks for your suggestion. Yes, I aware of this 5682 also. The search
problem is first since from an older version. I updated the clementine
after I checked the 5682. But sadly the problem is still exist.

Will it be a problem bring from the resolved bug?

**Comment by alexander-b** [comment]
I can't search Spotify from the search tab. If I search from the Internet tab, I get 31658 segmentation fault  clementine. I'm on 1.3.1-r6.

**Comment by alexander-b** [comment]
Magically working as of today.

**Comment by mohsani** [comment]
seems like it's half broken or dead. cause sometimes it works and most of the times it won't!

**Comment by kentsangkm** [comment]
Hi all, I created a script to search song from spotify and import it

https://github.com/kentsangkm/clementine_spotify_search

**Comment by kentsangkm** [comment]
I wrote a new search provider for spotify. It is merged to the master
