### ISSUE TITLE
Bulk import playlists

### ISSUE THREAD

**Issue by technicaltitch** [clementine-player/Clementine#5722]
### Before posting

Please follow the steps below and check the boxes with [x] once you did the step.

- [x ] I checked the issue tracker for similar issues
- [x ] I checked the [changelog](https://github.com/clementine-player/Clementine/blob/master/Changelog) if the issue is already resolved
- [x ] I tried the latest Clementine build from [here](https://builds.clementine-player.org/)
Also asked on the google group (https://groups.google.com/forum/#!topic/clementine-player/mu2w6cAVdiQ).

### System information

Please provide information about your system and the version of Clementine used.

- Operating System: OS X 10.12
- Clementine version: 1.3.1

### Expected behaviour / actual behaviour

I'd like to import many playlists with minimal clicks.

Best: An 'Import Playlist Folder' menu option that permits you to select a folder, and all playlists within are imported directly to the playlist tab, in a folder structure mirroring that of the folder you are importing from.

Simpler perhaps: Shift + Apple + O should permit you to select multiple playlists, ideally importing them directly into clementine's playlists, rather than then having to star their tabs to save.

Background - I have 200+ m3u playlists I'd like to import into clementine. I'd be happy to import from some other format, eg, Traktor nml, itunes xml or whatever, am considering parsing text and writing to the SQLite db, but I think the above would be flexible, useful enhancements.

### Steps to reproduce the problem (only for bugs)
This is a feature request, not a bug.

**Comment by cgm707** [comment]
What is Shift+Apple+O? i don't see a Apple key.

**Comment by marcomoscardini** [comment]
I think what the @technicaltitch is asking for:
    Open "import multiple files at once"

If the return from the open dialog is an array of multiple files, loop to import each file separately.

**Comment by technicaltitch** [comment]
I'd missed @cgm707 's comment. Marco is right. @cgm707 there's this company called Apple, they make laptops among other things, and those laptops have a key on the keyboard specific to Apple laptops. If you need any further guidance try Google. If 'Google' doesn't mean anything to you either, get someone to enter your postal address here and we can write to each other - you could be in for an exciting few weeks.

PS. A vowel is preceded by 'an' rather than 'a', and capitalise 'I'. Well done for nailing both pedantry *and* hypocrisy in so few words.

**Comment by fitojb** [comment]
@technicaltitch: Hey, there is no such thing as an Apple key. There are, however, Command and Option keys, both of which may be referred to collectively as “Apple” keys.

Well done for nailing being a dick in a so blatant fashion.

**Comment by technicaltitch** [comment]
@fitojb I just suggested a feature I thought would be useful for Clementine. I am a DJ and there is still no good library management tool. I thought Clementine could aim for that niche.

cgm707 was then sarcastic, so I responded in kind, and you are now resorting to obscenities. The command key is also known as the Apple key, because it used to have an Apple on it. Option is also found on Windows keyboards, labelled Alt. A Google would have resolved your confusion, eg, https://superuser.com/a/135305. I'll close this as clearly the development team is very busy.

**Comment by SirJosh3917** [comment]
It's unfortunate that this issue seemed to get dragged in the mud by some unrelated conversation.

I'd personally like this feature, as I have a `playlist.m3u` file that gets continuously updated, so having an easy way to import it or keep it in sync would be nice. For context, I have a playlist from YouTube that I have a script regularly download into a folder and generate a `playlist.m3u` file with the music files ordered by the order in the YouTube playlist.

It appears that `clementime -c playlist_name /path/to/playlist.m3u` is good enough to import a single m3u file, but it's not enough for automation:

- It takes an incredibly long time to import a playlist of 1000+ songs (I have 1248)
- Using the command will open a GUI window and hang while it's open, making it not amendable for automation

Resolutions to these two issues would be much appreciated and a step forward to some sort of solution to bulk importing playlists.

**Comment by fitojb** [comment]
@SirJosh3917 Don’t you worry about others’ personal issues — I don’t care about pedant users with superiority/self-victimizing complexes, and he closed it himself. Your comment belongs in a new, separate ticket; it is good netiquette not to revive long-dead threads.

**Comment by hockeymikey** [comment]
Yeah this should be reopened. It's a shame there is no mass import of a folder of playlists.

**Comment by mwdle** [comment]
This would make a huge difference for me. It's too cumbersome to manually load my playlists individually.

It's sad to see that someone put in all the work and effort to implement this over 2 years ago and it seemingly never even got looked at. Please reopen this issue!
