### ISSUE TITLE
Clementine 1.3.1 crashes on startup in Windows 7 x64

### ISSUE THREAD

**Issue by mraper3** [clementine-player/Clementine#5735]
### Before posting

Please follow the steps below and check the boxes with [x] once you did the step.

- [X] I checked the issue tracker for similar issues
- [X] I checked the [changelog](https://github.com/clementine-player/Clementine/blob/master/Changelog) if the issue is already resolved
- [X] I tried the latest Clementine build from [here](https://builds.clementine-player.org/)

### System information

Please provide information about your system and the version of Clementine used.

- Operating System: Windows 7 x64 SP1
- Clementine version: 1.3.1 (installed from the link on the website)

### Expected behaviour / actual behaviour
Clementine crashes on startup.

Data from Event Viewer:
Faulting application name: clementine.exe, version: 1.3.0.0, time stamp: 0x571656ec
Faulting module name: BfLLR.dll, version: 6.0.0.35, time stamp: 0x4f3a9294
Exception code: 0xc0000409
Fault offset: 0x0000be9b
Faulting process id: 0x2340
Faulting application start time: 0x01d2ce9b75b18251
Faulting application path: C:\Program Files (x86)\Clementine\clementine.exe
Faulting module path: C:\Windows\system32\BfLLR.dll
Report Id: b3caea02-3a8e-11e7-b9c3-20689d5cb894

Additional files with info:

[WER15D6.tmp.appcompat.txt](https://github.com/clementine-player/Clementine/files/1006147/WER15D6.tmp.appcompat.txt)

[WERE66.tmp.WERInternalMetadata.txt](https://github.com/clementine-player/Clementine/files/1006153/WERE66.tmp.WERInternalMetadata.txt)

[WER1C2E.tmp.mdmp.txt](https://github.com/clementine-player/Clementine/files/1006157/WER1C2E.tmp.mdmp.txt)

### Steps to reproduce the problem (only for bugs)
Start Clementine from the Start menu.

**Comment by hatstand** [comment]
That would be your network card driver crashing.
