### ISSUE TITLE
Playing notifications not transient

### ISSUE THREAD

**Issue by nickspoon** [clementine-player/Clementine#5756]
The "now playing" notification in Clementine lacks the "transient" hint, which means that in Linux Mint 18 Sarah (Cinnamon 3.0.7), the notifications stay in the notification bar until explicitly cleared. This obviously leads to a huge number of notifications if you listen to music for a while!

The fix is very easy: just add the following line to OSD::ShowMessageNative in osd_x11.cpp:
`hints["transient"] = QVariant(true);`

**Comment by hatstand** [comment]
Send a pull request
