### ISSUE TITLE
[VK integration] music not retrieved nor played after authorized

### ISSUE THREAD

**Issue by dminca** [clementine-player/Clementine#5765]
### Before posting

Please follow the steps below and check the boxes with [x] once you did the step.

- [x] I checked the issue tracker for similar issues
- [x] I checked the [changelog](https://github.com/clementine-player/Clementine/blob/master/Changelog) if the issue is already resolved
- [x] I tried the latest Clementine build from [here](https://builds.clementine-player.org/)

### System information

Please provide information about your system and the version of Clementine used.

- Operating System: ArchLinux Kernel v4.11.5-1-ARCH
- Clementine version: v1.3.1

### Expected behaviour / actual behaviour
After authorizing VK the player should list & play music from Recommendation and My Music lists.

Instead, the player only lists a generic :ru: track from VK stating that the player is not supported.

### Steps to reproduce the problem (only for bugs)

![screenshot from 2017-06-19 10-47-19](https://user-images.githubusercontent.com/5355219/27274642-d94a6d36-54dc-11e7-90a6-b0d5cce3586b.png)

**Comment by Chocobozzz** [comment]
VK is not supported anymore (removed in master branch).
