### ISSUE TITLE
Library scan not picking up folders

### ISSUE THREAD

**Issue by benjaminquest** [clementine-player/Clementine#5769]
Hi, I observe a quite odd behaviour of Clementine recently. When I add new music to my library (external HD), it does not necessarily gets picked up by Clementine after a library scan or rescan or even a rebuilt.

I have now narrowed down the issue a bit. When I add a new Album of a Band that is already represented in the library, all is fine, Clementine picks that new album up. However, if I add an Album from a Band that is not yet represented in the library, it "slips through the radar". If I add the path to the new folder (for the new band), then Clementine picks it up correctly.

Library organization is /device/flac/$bandname/$albumname. I originally defined the folder in which to search for Clementine as /device/flac

It appears that Clementine can handle only a limited number of subfolders in the first level? The /flac folder currently has 516 "band folders". I have now added 8 extra paths within the /device/flac folder.

![grafik](https://user-images.githubusercontent.com/29624968/27426579-73fbbcd4-573c-11e7-8a1f-e5f921f63c00.png)

### System information
- Operating System: Manjaro stable
- Clementine version: 1.3.1

EDIT: I meanwhile found a further folder not picked up properly.

**Comment by bboutkov** [comment]
This happens maybe once a month for me - I think it has somehow to do with database corruption. For me the usual (annoying) fix is just to remove the clementine db and its backup and to rescan all folders.

Also, incase you haven't already, you should check to make sure that your inotify watch limit is high enough.

**Comment by benjaminquest** [comment]
@bboutkov : Thanks! That resolved my issue. I had to delete the entire folder ~ .config/clementine, since just renaming everything *.db database in that folder did not do the trick (Clementine errored out with: ERROR unknown       Unable to update music library database).

So is the error on the database side, or on Clementine's implementation side?

**Comment by benjaminquest** [comment]
@bboutkov : Thanks! That resolved my issue. I had to delete the entire folder ~ .config/clementine, since just renaming everything *.db database in that folder did not do the trick (Clementine errored out with: ERROR unknown       Unable to update music library database).

So is the error on the database side, or on Clementine's implementation side?
