### ISSUE TITLE
Change behaviour of Play Count updating

### ISSUE THREAD

**Issue by pwd-github** [clementine-player/Clementine#5771]
### System information
- Operating System: Ubuntu 17.04
- Clementine version: 1.3.1

### Expected behaviour / actual behaviour
When listening to a song, the Play Count gets updated at around the 60% mark. This behaviour isn't quite realistic and should be lowered to around the 40% mark or 90 seconds, whichever is reached first.

**Comment by wheresvic** [comment]
This should ideally be configurable as it is differs from person to person :)

**Comment by pwd-github** [comment]
Agreed. Configurable is definitely preferable.

**Comment by pwd-github** [comment]
Thank you so much @wheresvic
