### ISSUE TITLE
Ubuntu Zesty Zapus packages are missing in lauchpad repos

### ISSUE THREAD

**Issue by adem4ik** [clementine-player/Clementine#5778]
- Operating System: Kubuntu 17.04 amd64
- Clementine version: unknown

Ubuntu Zesty Zapus packages are missing in launchpad repos as on me-davidsansome/clementine-dev as on me-davidsansome/clementine. It would be really nice if you provide them.

**Comment by nazar-pc** [comment]
And I'd also like to see at least development builds for Artful (17.10)

**Comment by adem4ik** [comment]
seems like it was fixed for ppa:me-davidsansome/clementine-dev: https://launchpad.net/~me-davidsansome/+archive/ubuntu/clementine-dev?field.series_filter=zesty
