### ISSUE TITLE
Artist and Title flipped in M3U playlist import

### ISSUE THREAD

**Issue by computersarecool** [clementine-player/Clementine#5807]
### Before posting

Please follow the steps below and check the boxes with [x] once you did the step.

- [x] I checked the issue tracker for similar issues
- [x] I checked the [changelog](https://github.com/clementine-player/Clementine/blob/master/Changelog) if the issue is already resolved
- [x] I tried the latest Clementine build from [here](https://builds.clementine-player.org/)

### System information

Please provide information about your system and the version of Clementine used.

- Operating System: Windows 10
- Clementine version: 1.3.1

### Expected behaviour / actual behaviour
When loading a playlist from an .m3u file the "Artist" and "Title" fields are flipped.

### Steps to reproduce the problem (only for bugs)
Here are the first 4 lines of the .m3u file that I imported:

```
#EXTM3U
#EXTINF:452,Little By Little (Michael Cassette Remix) - Canyon Boulevard
H:\Music\all_music\Music\Canyon Boulevard\Unknown Album\Little By Little (Michael Cassette R.mp3
```
And here is an image of what it looks like in Clementine:
![capture](https://user-images.githubusercontent.com/5414692/29010406-f097dafe-7adf-11e7-9f30-cb5c8b631d6b.PNG)

However if I just drag the folder that contains the song,  the fields are sorted correctly.  As in this image:

![capture2](https://user-images.githubusercontent.com/5414692/29010415-04a4566c-7ae0-11e7-9236-d1c9dde06acf.PNG)

**Comment by hatstand** [comment]
Your m3u file is wrong.
