### ISSUE TITLE
Add moodbar for each song in playlist to select song by mood

### ISSUE THREAD

**Issue by UralZima** [clementine-player/Clementine#5809]
Hello. It would be very nice feature, often your music collection is mixed and you want to play something chilly or more fast and don't remember all song titles.
It may be an option or an icon to generate moods for current playlist (and show them as column)

Thanks!

**Comment by Moonbase59** [comment]
Hm … you mean _one_ mood _for the whole playlist_ or just show the moods next to the titles?

THAT you can easily do: Right-click the playlist’s title bar, select 'Mood' an move it whereever you want. The playlist will now calculate/show the mood for every song!

![screenshot - 25 08 2017 - 12 39 12](https://user-images.githubusercontent.com/3706922/29710865-88bac0d8-8992-11e7-97fa-707697632c79.png)

**Comment by UralZima** [comment]
WOW, amazing, thanks! I wanted to try something like that, but my columns was locked somehow and I didn't see a scrollbar and more columns, only first three. When I unchecked checkbox about fitting to window and restarted clementine, all was fixed! Thanks for awesome work!
