### ISSUE TITLE
[Archlinux] Compiling from Source:Error

### ISSUE THREAD

**Issue by ZeroDot1** [clementine-player/Clementine#5810]
### System information
```bash
System:    Host: A632-OS Kernel: 4.12.4-1-ARCH x86_64 (64 bit)
           Desktop: Xfce 4.12.4 Distro: Antergos Linux
Machine:   Device: desktop Mobo: MSI model: 760GM-P23(FX) (MS-7641) v: 3.0
           BIOS: American Megatrends v: V17.15 date: 04/28/2013
CPU:       Dual core AMD Athlon II X2 270 (-MCP-) cache: 2048 KB 
           clock speeds: max: 3400 MHz 1: 800 MHz 2: 3400 MHz
Graphics:  Card: NVIDIA GT215 [GeForce GT 240]
           Display Server: x11 (X.Org 1.19.3) driver: nvidia
           Resolution: 1920x1080@60.05hz
           OpenGL: renderer: GeForce GT 240/PCIe/SSE2
           version: 3.3.0 NVIDIA 340.102
Audio:     Card-1 NVIDIA High Definition Audio Controller
           driver: snd_hda_intel
           Card-2 Advanced Micro Devices [AMD/ATI] SBx00 Azalia (Intel HDA)
           driver: snd_hda_intel
           Sound: Advanced Linux Sound Architecture v: k4.12.4-1-ARCH
Network:   Card: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller
```
- Clementine version: clementine-player/Clementine/archive/master.zip

### Steps to reproduce the problem (only for bugs)
Compiling from Source
```bash
cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr
make
```
### Log:
Determining if the Q_WS_WIN exist failed with the following output:
Change Dir: /home/user/Clementine-master/Clementine-master/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_f439d/fast"
/usr/bin/make -f CMakeFiles/cmTC_f439d.dir/build.make CMakeFiles/cmTC_f439d.dir/build
make[1]: Verzeichnis „/home/user/Clementine-master/Clementine-master/CMakeFiles/CMakeTmp“ wird betreten
Building CXX object CMakeFiles/cmTC_f439d.dir/CheckSymbolExists.cxx.o
/usr/bin/c++   -I/usr/include/qt4   -o CMakeFiles/cmTC_f439d.dir/CheckSymbolExists.cxx.o -c /home/user/Clementine-master/Clementine-master/CMakeFiles/CMakeTmp/CheckSymbolExists.cxx
/home/user/Clementine-master/Clementine-master/CMakeFiles/CMakeTmp/CheckSymbolExists.cxx: In Funktion »int main(int, char**)«:
/home/user/Clementine-master/Clementine-master/CMakeFiles/CMakeTmp/CheckSymbolExists.cxx:8:19: Fehler: »Q_WS_WIN« wurde in diesem Gültigkeitsbereich nicht definiert
   return ((int*)(&Q_WS_WIN))[argc];
                   ^~~~~~~~
/home/user/Clementine-master/Clementine-master/CMakeFiles/CMakeTmp/CheckSymbolExists.cxx:8:19: Anmerkung: empfohlene Alternative: »Q_WS_X11«
   return ((int*)(&Q_WS_WIN))[argc];
                   ^~~~~~~~
                   Q_WS_X11
make[1]: *** [CMakeFiles/cmTC_f439d.dir/build.make:66: CMakeFiles/cmTC_f439d.dir/CheckSymbolExists.cxx.o] Fehler 1
make[1]: Verzeichnis „/home/user/Clementine-master/Clementine-master/CMakeFiles/CMakeTmp“ wird verlassen
make: *** [Makefile:126: cmTC_f439d/fast] Fehler 2

File /home/user/Clementine-master/Clementine-master/CMakeFiles/CMakeTmp/CheckSymbolExists.cxx:
/* */
#include <QtCore/qglobal.h>

int main(int argc, char** argv)
{
  (void)argv;
#ifndef Q_WS_WIN
  return ((int*)(&Q_WS_WIN))[argc];
#else
  (void)argc;
  return 0;
#endif
}

Determining if the Q_WS_QWS exist failed with the following output:
Change Dir: /home/user/Clementine-master/Clementine-master/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_73cc0/fast"
/usr/bin/make -f CMakeFiles/cmTC_73cc0.dir/build.make CMakeFiles/cmTC_73cc0.dir/build
make[1]: Verzeichnis „/home/user/Clementine-master/Clementine-master/CMakeFiles/CMakeTmp“ wird betreten
Building CXX object CMakeFiles/cmTC_73cc0.dir/CheckSymbolExists.cxx.o
/usr/bin/c++   -I/usr/include/qt4   -o CMakeFiles/cmTC_73cc0.dir/CheckSymbolExists.cxx.o -c /home/user/Clementine-master/Clementine-master/CMakeFiles/CMakeTmp/CheckSymbolExists.cxx
/home/user/Clementine-master/Clementine-master/CMakeFiles/CMakeTmp/CheckSymbolExists.cxx: In Funktion »int main(int, char**)«:
/home/user/Clementine-master/Clementine-master/CMakeFiles/CMakeTmp/CheckSymbolExists.cxx:8:19: Fehler: »Q_WS_QWS« wurde in diesem Gültigkeitsbereich nicht definiert
   return ((int*)(&Q_WS_QWS))[argc];
                   ^~~~~~~~
/home/user/Clementine-master/Clementine-master/CMakeFiles/CMakeTmp/CheckSymbolExists.cxx:8:19: Anmerkung: empfohlene Alternative: »Q_WS_X11«
   return ((int*)(&Q_WS_QWS))[argc];
                   ^~~~~~~~
                   Q_WS_X11
make[1]: *** [CMakeFiles/cmTC_73cc0.dir/build.make:66: CMakeFiles/cmTC_73cc0.dir/CheckSymbolExists.cxx.o] Fehler 1
make[1]: Verzeichnis „/home/user/Clementine-master/Clementine-master/CMakeFiles/CMakeTmp“ wird verlassen
make: *** [Makefile:126: cmTC_73cc0/fast] Fehler 2

File /home/user/Clementine-master/Clementine-master/CMakeFiles/CMakeTmp/CheckSymbolExists.cxx:
/* */
#include <QtCore/qglobal.h>

int main(int argc, char** argv)
{
  (void)argv;
#ifndef Q_WS_QWS
  return ((int*)(&Q_WS_QWS))[argc];
#else
  (void)argc;
  return 0;
#endif
}

Determining if the Q_WS_MAC exist failed with the following output:
Change Dir: /home/user/Clementine-master/Clementine-master/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_050e8/fast"
/usr/bin/make -f CMakeFiles/cmTC_050e8.dir/build.make CMakeFiles/cmTC_050e8.dir/build
make[1]: Verzeichnis „/home/user/Clementine-master/Clementine-master/CMakeFiles/CMakeTmp“ wird betreten
Building CXX object CMakeFiles/cmTC_050e8.dir/CheckSymbolExists.cxx.o
/usr/bin/c++   -I/usr/include/qt4   -o CMakeFiles/cmTC_050e8.dir/CheckSymbolExists.cxx.o -c /home/user/Clementine-master/Clementine-master/CMakeFiles/CMakeTmp/CheckSymbolExists.cxx
/home/user/Clementine-master/Clementine-master/CMakeFiles/CMakeTmp/CheckSymbolExists.cxx: In Funktion »int main(int, char**)«:
/home/user/Clementine-master/Clementine-master/CMakeFiles/CMakeTmp/CheckSymbolExists.cxx:8:19: Fehler: »Q_WS_MAC« wurde in diesem Gültigkeitsbereich nicht definiert
   return ((int*)(&Q_WS_MAC))[argc];
                   ^~~~~~~~
/home/user/Clementine-master/Clementine-master/CMakeFiles/CMakeTmp/CheckSymbolExists.cxx:8:19: Anmerkung: empfohlene Alternative: »Q_WS_X11«
   return ((int*)(&Q_WS_MAC))[argc];
                   ^~~~~~~~
                   Q_WS_X11
make[1]: *** [CMakeFiles/cmTC_050e8.dir/build.make:66: CMakeFiles/cmTC_050e8.dir/CheckSymbolExists.cxx.o] Fehler 1
make[1]: Verzeichnis „/home/user/Clementine-master/Clementine-master/CMakeFiles/CMakeTmp“ wird verlassen
make: *** [Makefile:126: cmTC_050e8/fast] Fehler 2

File /home/user/Clementine-master/Clementine-master/CMakeFiles/CMakeTmp/CheckSymbolExists.cxx:
/* */
#include <QtCore/qglobal.h>

int main(int argc, char** argv)
{
  (void)argv;
#ifndef Q_WS_MAC
  return ((int*)(&Q_WS_MAC))[argc];
#else
  (void)argc;
  return 0;
#endif
}

Determining if the pthread_create exist failed with the following output:
Change Dir: /home/user/Clementine-master/Clementine-master/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_cd0ad/fast"
/usr/bin/make -f CMakeFiles/cmTC_cd0ad.dir/build.make CMakeFiles/cmTC_cd0ad.dir/build
make[1]: Verzeichnis „/home/user/Clementine-master/Clementine-master/CMakeFiles/CMakeTmp“ wird betreten
Building C object CMakeFiles/cmTC_cd0ad.dir/CheckSymbolExists.c.o
/usr/bin/cc    -o CMakeFiles/cmTC_cd0ad.dir/CheckSymbolExists.c.o   -c /home/user/Clementine-master/Clementine-master/CMakeFiles/CMakeTmp/CheckSymbolExists.c
Linking C executable cmTC_cd0ad
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_cd0ad.dir/link.txt --verbose=1
/usr/bin/cc      -rdynamic CMakeFiles/cmTC_cd0ad.dir/CheckSymbolExists.c.o  -o cmTC_cd0ad 
CMakeFiles/cmTC_cd0ad.dir/CheckSymbolExists.c.o: In function `main':
CheckSymbolExists.c:(.text+0x1b): undefined reference to `pthread_create'
collect2: Fehler: ld gab 1 als Ende-Status zurück
make[1]: *** [CMakeFiles/cmTC_cd0ad.dir/build.make:98: cmTC_cd0ad] Fehler 1
make[1]: Verzeichnis „/home/user/Clementine-master/Clementine-master/CMakeFiles/CMakeTmp“ wird verlassen
make: *** [Makefile:126: cmTC_cd0ad/fast] Fehler 2

File /home/user/Clementine-master/Clementine-master/CMakeFiles/CMakeTmp/CheckSymbolExists.c:
/* */
#include <pthread.h>

int main(int argc, char** argv)
{
  (void)argv;
#ifndef pthread_create
  return ((int*)(&pthread_create))[argc];
#else
  (void)argc;
  return 0;
#endif
}

Determining if the function pthread_create exists in the pthreads failed with the following output:
Change Dir: /home/user/Clementine-master/Clementine-master/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_4b11f/fast"
/usr/bin/make -f CMakeFiles/cmTC_4b11f.dir/build.make CMakeFiles/cmTC_4b11f.dir/build
make[1]: Verzeichnis „/home/user/Clementine-master/Clementine-master/CMakeFiles/CMakeTmp“ wird betreten
Building C object CMakeFiles/cmTC_4b11f.dir/CheckFunctionExists.c.o
/usr/bin/cc   -DCHECK_FUNCTION_EXISTS=pthread_create   -o CMakeFiles/cmTC_4b11f.dir/CheckFunctionExists.c.o   -c /usr/share/cmake-3.8/Modules/CheckFunctionExists.c
Linking C executable cmTC_4b11f
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_4b11f.dir/link.txt --verbose=1
/usr/bin/cc  -DCHECK_FUNCTION_EXISTS=pthread_create    -rdynamic CMakeFiles/cmTC_4b11f.dir/CheckFunctionExists.c.o  -o cmTC_4b11f -lpthreads 
/usr/bin/ld: cannot find -lpthreads
collect2: Fehler: ld gab 1 als Ende-Status zurück
make[1]: *** [CMakeFiles/cmTC_4b11f.dir/build.make:98: cmTC_4b11f] Fehler 1
make[1]: Verzeichnis „/home/user/Clementine-master/Clementine-master/CMakeFiles/CMakeTmp“ wird verlassen
make: *** [Makefile:126: cmTC_4b11f/fast] Fehler 2

**Comment by hatstand** [comment]
Your system is screwed in some way, it's missing essentials like `pthread_create`
