### ISSUE TITLE
[FreeBSD] Protobuf 3.4.0 generates preprocessor failures

### ISSUE THREAD

**Issue by seanbruno** [clementine-player/Clementine#5818]
### Before posting

Please follow the steps below and check the boxes with [x] once you did the step.

- [X] I checked the issue tracker for similar issues
- [X] I checked the [changelog](https://github.com/clementine-player/Clementine/blob/master/Changelog) if the issue is already resolved
- [X] I tried the latest Clementine build from [here](https://builds.clementine-player.org/)

### System information

Please provide information about your system and the version of Clementine used.

- Operating System: FreeBSD 12-Current
- Clementine version: 1.3.1

### Expected behaviour / actual behaviour
This is a compilation issue, not a runtime issue.  This is more of heads-up than a problem for the project to fix.  I will investigate further, but wanted others to know about it.

### Steps to reproduce the problem (only for bugs)
Build Clementine for FreeBSD while attempting to use google protobuf 3.4.0

Compiler error log:
/usr/bin/c++  -DBOOST_BIND_NO_PLACEHOLDERS -DBUILD_QXT_CORE -DBUILD_QXT_GUI -DMYGPO_EXPORT="" -DNDEBUG -DQT_CORE_LIB -DQT_DBUS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_NO_CAST_TO_ASCII -DQT_NO_DEBUG -DQT_NO_DEBUG_OUTPUT -DQT_NO_URL_CAST_FROM_STRING -DQT_OPENGL_LIB -DQT_SQL_LIB -DQT_STRICT_ITERATORS -DQT_USE_QSTRINGBUILDER -DQT_WEBKIT_LIB -DQT_XML_LIB -DQXT_STATIC -I/usr/local/include -I/usr/local/include/taglib -isystem /usr/local/include/qt4 -isystem /usr/local/include/qt4/QtCore -I/usr/local/include/gstreamer-1.0 -I/usr/local/include/glib-2.0 -I/usr/local/lib/glib-2.0/include -I/usr/local/include/libxml2 -I3rdparty/vreen/vreen/include -isystem /usr/local/include/qt4/QtOpenGL -isystem /usr/local/include/qt4/QtWebKit -isystem /usr/local/include/qt4/QtGui -isystem /usr/local/include/qt4/QtDBus -isystem /usr/local/include/qt4/QtXml -isystem /usr/local/include/qt4/QtSql -isystem /usr/local/include/qt4/QtNetwork -I3rdparty/qsqlite -I. -Isrc -Isrc/../3rdparty/gmock/gtest/include -I3rdparty/libprojectm -I3rdparty/qtsingleapplication -I3rdparty/qtiocompressor -I3rdparty/qxt -I3rdparty/sha2 -I3rdparty/libmygpo-qt -Iext/libclementine-common -Iext/libclementine-tagreader -Iext/libclementine-remote -Iext/libclementine-spotifyblob -I/usr/local/include/gpod-1.0 -I/usr/local/include/gdk-pixbuf-2.0 -I/usr/local/include/libpng16 -O2 -pipe -Wno-inconsistent-missing-override -Wno-unused-variable -Wno-unused-function -fstack-protector -fno-strict-aliasing  -Wno-unknown-warning-option -Wno-undefined-var-template -Woverloaded-virtual -Wall -Wno-sign-compare -Wno-deprecated-declarations -Wno-unused-local-typedefs -Wno-unused-private-field -Wno-unknown-warning-option --std=c++0x -U__STRICT_ANSI__ -Werror -O2 -pipe -Wno-inconsistent-missing-override -Wno-unused-variable -Wno-unused-function -fstack-protector -fno-strict-aliasing  -Wno-unknown-warning-option -Wno-undefined-var-template -MD -MT src/CMakeFiles/clementine_lib.dir/core/application.cpp.o -MF src/CMakeFiles/clementine_lib.dir/core/application.cpp.o.d -o src/CMakeFiles/clementine_lib.dir/core/application.cpp.o -c src/core/application.cpp
In file included from src/core/application.cpp:28:
In file included from src/core/tagreaderclient.h:25:
In file included from ext/libclementine-tagreader/tagreadermessages.pb.h:9:
In file included from /usr/local/include/google/protobuf/stubs/common.h:45:
/usr/local/include/google/protobuf/stubs/port.h:263:5: error: macro expansion producing 'defined' has undefined behavior [-Werror,-Wexpansion-to-defined]
#if GOOGLE_PROTOBUF_USE_UNALIGNED
    ^
/usr/local/include/google/protobuf/stubs/port.h:259:40: note: expanded from macro 'GOOGLE_PROTOBUF_USE_UNALIGNED'
# define GOOGLE_PROTOBUF_USE_UNALIGNED defined(_M_X64) || \
                                       ^
/usr/local/include/google/protobuf/stubs/port.h:263:5: error: macro expansion producing 'defined' has undefined behavior [-Werror,-Wexpansion-to-defined]
/usr/local/include/google/protobuf/stubs/port.h:260:6: note: expanded from macro 'GOOGLE_PROTOBUF_USE_UNALIGNED'
     defined(__x86_64__) || defined(_M_IX86) || defined(__i386__)
     ^
/usr/local/include/google/protobuf/stubs/port.h:263:5: error: macro expansion producing 'defined' has undefined behavior [-Werror,-Wexpansion-to-defined]
/usr/local/include/google/protobuf/stubs/port.h:260:29: note: expanded from macro 'GOOGLE_PROTOBUF_USE_UNALIGNED'
     defined(__x86_64__) || defined(_M_IX86) || defined(__i386__)
                            ^
/usr/local/include/google/protobuf/stubs/port.h:263:5: error: macro expansion producing 'defined' has undefined behavior [-Werror,-Wexpansion-to-defined]
/usr/local/include/google/protobuf/stubs/port.h:260:49: note: expanded from macro 'GOOGLE_PROTOBUF_USE_UNALIGNED'
     defined(__x86_64__) || defined(_M_IX86) || defined(__i386__)
                                                ^
4 errors generated.
ninja: build stopped: subcommand failed.
*** Error code 1

Stop.
make: stopped in /usr/ports/audio/clementine-player

**Comment by hatstand** [comment]
looks like a bug in protobuf
