### ISSUE TITLE
[Solved]Unable to skip forward in Subsonic tracks in the FLAC format

### ISSUE THREAD

**Issue by pizzaazzip** [clementine-player/Clementine#5833]
Clementine Version: 1.3.1-364-ga056a73 (Windows 7 x64) & 1.3.1 (OS X Sierra)
Subsonic Version: 6.1.1 (build 2a8e8d) – May 31, 2017 Running on OS X El Capitan (10.11.6)

This occurred in SubSonic 6.1 as well, I'm unable to skip forward in any .flac songs using the scrubbing bar (or whatever it is called) on the bottom.  I can go to previous songs and next songs but if I want to start listening in the middle I'm unable to.  I just now discovered I can scrub files in the .mp3 format but most of my library is in .flac unfortunately.

**Comment by CactusPie** [comment]
Any response from the devs? I would REALLY love to see this bug fixed.

**Comment by pizzaazzip** [comment]
Not that I know of, I wish I can provide more information about this issue.

**Comment by CactusPie** [comment]
Well, I tested it with Ampache, since it emulates the Subsonic API. Not only did it work, it also allowed me to seek forward and backward in .flac files. Perhaps it's a Subsonic bug?

**Comment by pizzaazzip** [comment]
Makes sense, I don't have issues with DSub for my android phone but I think it encodes to a different format on the fly.  What do you run Ampache on?  Perhaps I should just set that up instead of SubSonic.

**Comment by CactusPie** [comment]
Ubuntu + NGINX. Compared to Subsonic it's a bit of a pain to set up, and I haven't tried any mobile clients with it yet, but it's worth checking out.

**Comment by pizzaazzip** [comment]
Thanks!

**Comment by CactusPie** [comment]
Just to let you know, the issue is caused by transcoding. After disabling transcoding in the web interface - it's done on the player-by-player basis, Clementine can seek in the FLAC files. Thanks goes to Tak-MK on the Madsonic forums who suggested the fix to me.

**Comment by pizzaazzip** [comment]
@CactusPie You're the best!  This fixed both of my problems!  I didn't even follow step 1, 3, & 4, just turning off the default for mp3 audio for my clementine player (I turned it off on DSub too, figured a)It will break it and I can just re-enable it & B)I have unlimited data on my phone so it shouldn't hurt me to in theory be grabbing bigger files.

Thanks again!
