### ISSUE TITLE
Integration of radio-browser.info

### ISSUE THREAD

**Issue by mase76** [clementine-player/Clementine#5846]
Hi!
Do you know radio-browser.info?
This is a great community driven database for internet radios with an open API.
It would be nice, when Clementine would integrate it.

**Comment by stuart12** [comment]
http://www.radio-browser.info/gui seems to list Clementine as a supported player but I cannot see how to add a playlist such as http://www.radio-browser.info/webservice/v2/pls/url/45416 to Clementine

**Comment by h3298** [comment]
The Clementine search feature does not find any stations in the Radio Browser database.  This is a duplicate of bug 5321.

**Comment by fitojb** [comment]
@hatstand please close this issue as duplicate
