### ISSUE TITLE
FR: http://www.radio-browser.info suppert

### ISSUE THREAD

**Issue by gerroon** [clementine-player/Clementine#5878]
Hi

http://www.radio-browser.info/ offers probably one of the best radio stations list around the web. I think that Clementine users can benefit from accessing the list directly within Clementine.

thanks

**Comment by h3298** [comment]
Duplicate of bug https://github.com/clementine-player/Clementine/issues/5321

**Comment by fitojb** [comment]
@hatstand please close this issue as duplicate
