### ISSUE TITLE
Last.fm login gets stuck 

### ISSUE THREAD

**Issue by ishanjain28** [clementine-player/Clementine#5902]
### Before posting

Please follow the steps below and check the boxes with [x] once you did the step.

- [x] I checked the issue tracker for similar issues
- [x] I checked the [changelog](https://github.com/clementine-player/Clementine/blob/master/Changelog) if the issue is already resolved
- [x] I tried the latest Clementine build from [here](https://builds.clementine-player.org/)

### System information

Please provide information about your system and the version of Clementine used.

- Operating System: Arch Linux(Linux y50 4.13.10-1-ARCH #1 SMP PREEMPT Fri Oct 27 16:16:03 CEST 2017 x86_64 GNU/Linux)
- Clementine version: Clementine 1.3.1

This issue is related to last.fm signin. 

#### Expected 
Clicking on Preferences -> Last.fm -> Login should open a tab and login to last.fm. 
#### Actual 
It doesn't logs me in and gets stuck forever waiting on last.fm. 

### Steps to reproduce the problem (only for bugs)
1. Open preferences-> Last.fm and click on Login. 
2. It opens a tab in firefox and the url is `https://secure.last.fm/login?next=/api/auth?api_key=75d20fb472be99275392aefa2760ea09&cb=http://localhost:35183/`. 
3. Last.fm disregards the authentication request and redirects to homepage. Login Fails. 

### Steps to fix this issue. 

Change the redirection url from `https://secure.last.fm/login?next=/api/auth?api_key=75d20fb472be99275392aefa2760ea09&cb=http://localhost:35183/` to `https://last.fm/api/auth?api_key=75d20fb472be99275392aefa2760ea09&cb=http://localhost:35183/` as mentioned in their [User Authentication docs](https://www.last.fm/api/desktopauth) and it works just fine.

**Comment by trougnouf** [comment]
The lastfm authentification URL has been correctly set to "https://www.last.fm/api/auth/?api_key=%1&token=%2" since a8cb9bbd2a199cc12b4d514826a5b4fed96fba9b (August 24th) , I just tested lastfm authentification on the qt5 build (same URL as master) and it works just fine.

**Comment by ishanjain28** [comment]
@trougnouf Is it possible that some one can try at this on Arch Linux? It happens every single time I tried to log in. My setup is ArchLinux, KDE, Clementine 1.3.1 and Firefox(latest version).

**Comment by trougnouf** [comment]
Clementine 1.3.1 dates back to April 2016 therefore it does not include this fix. You can install clementine-git or clementine-qt5-git on Arch from the aur. (Debian, Ubuntu, and Fedora should have up-to-date packages available on https://builds.clementine-player.org/ )

**Comment by ishanjain28** [comment]
@trougnouf I tried [clementine-1.3.1-391-gce22905](https://builds.clementine-player.org/source/clementine-1.3.1-391-gce22905.tar.xz) and last fm integration works ok. I'll close this issue now.
