### ISSUE TITLE
Clemtine somehow changes files when it plays them

### ISSUE THREAD

**Issue by androos** [clementine-player/Clementine#5907]
Proof of that is that different sync tools I have response any time I play a file. Exactly the file played or that was played is considered as changed and synced. 

Clementine seems to have no option to prevent it.

**Comment by androos** [comment]
'When Clemtine switches to the next file the last on is changed, the Creation Date and Modification Date is set. But Why?

**Comment by diogocp** [comment]
Check the music library preferences. There are options for saving ratings and statistics in file tags.

**Comment by androos** [comment]
Okay got it. Thx.

**Comment by diogocp** [comment]
@androos please close the issue if that solved it.
