### ISSUE TITLE
Clicking on audio file does nothing when Clementine is already running

### ISSUE THREAD

**Issue by ValdikSS** [clementine-player/Clementine#5959]
When Clementine is running, clicking on audio file (or running `clementine audiofile.mp3`) does not add that file to current playlist.
New Clementine instance connects to UNIX socket of already running instance, writes `\0\0\0\0`, gets `ack` and terminates.

Is this a bug, or this feature is not implemented?
Bug in Redhat bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1281649

### Expected behaviour
The file is added to current playlist.

### Actual behaviour
Nothing happens with the playlist.

### Steps to reproduce the problem (only for bugs)
1. Start Clementine
2. Click on any audio file and open it with Clementine

**Comment by vikramambrose** [comment]
Cannot reproduce with Ubuntu 16.04, Clementine 1.3.1-333

**Comment by sandfoxme** [comment]
Hi! I'm the original reporter in Red Hat's bugzilla
This seems to be a problem specific to Fedora. It is not reproducible in Windows and Debian

**Comment by sandfoxme** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1281649#c8
It seems this issue can be closed now
