### ISSUE TITLE
Clementine 1.3.1 fails to build against libchromaprint-1.4.2

### ISSUE THREAD

**Issue by rosset** [clementine-player/Clementine#5965]
### Before posting

Please follow the steps below and check the boxes with [x] once you did the step.

- [X] I checked the issue tracker for similar issues
- [X] I checked the [changelog](https://github.com/clementine-player/Clementine/blob/master/Changelog) if the issue is already resolved
- [X] I tried the latest Clementine build from [here](https://builds.clementine-player.org/)

### System information

Please provide information about your system and the version of Clementine used.

- Operating System: Fedora rawhide (development)
- Clementine version: 1.3.1

### Expected behaviour / actual behaviour
compile against libchromaprint-1.4.2-1.fc28.x86_64

### Steps to reproduce the problem (only for bugs)
[ 58%] Building CXX object src/CMakeFiles/clementine_lib.dir/musicbrainz/musicbrainzclient.cpp.o
cd /home/filiperosset/rpmbuild/my/clementine/Clementine-1.3.1/x86_64-redhat-linux-gnu/src && /usr/bin/ccache /usr/lib64/ccache/c++  -DBOOST_BIND_NO_PLACEHOLDERS -DMYGPO_EXPORT="" -DNDEBUG -DQT_CORE_LIB -DQT_DBUS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_NO_CAST_TO_ASCII -DQT_NO_DEBUG -DQT_NO_DEBUG_OUTPUT -DQT_NO_URL_CAST_FROM_STRING -DQT_OPENGL_LIB -DQT_SQL_LIB -DQT_STRICT_ITERATORS -DQT_USE_QSTRINGBUILDER -DQT_XML_LIB -I/usr/include/taglib -isystem /usr/include/QtCore -I/usr/include/gstreamer-1.0 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/libxml2 -I/home/filiperosset/rpmbuild/my/clementine/Clementine-1.3.1/x86_64-redhat-linux-gnu/3rdparty/vreen/vreen/include -isystem /usr/include/QtOpenGL -isystem /usr/include/QtGui -isystem /usr/include/QtDBus -isystem /usr/include/QtXml -isystem /usr/include/QtSql -isystem /usr/include/QtNetwork -I/home/filiperosset/rpmbuild/my/clementine/Clementine-1.3.1/3rdparty/qsqlite -I/home/filiperosset/rpmbuild/my/clementine/Clementine-1.3.1 -I/home/filiperosset/rpmbuild/my/clementine/Clementine-1.3.1/x86_64-redhat-linux-gnu/src -I/home/filiperosset/rpmbuild/my/clementine/Clementine-1.3.1/src -I/home/filiperosset/rpmbuild/my/clementine/Clementine-1.3.1/src/../3rdparty/gmock/gtest/include -I/home/filiperosset/rpmbuild/my/clementine/Clementine-1.3.1/x86_64-redhat-linux-gnu -I/usr/include/QtSolutions -I/usr/include/QxtCore -I/usr/include/QxtGui -I/home/filiperosset/rpmbuild/my/clementine/Clementine-1.3.1/3rdparty/libmygpo-qt -I/home/filiperosset/rpmbuild/my/clementine/Clementine-1.3.1/ext/libclementine-common -I/home/filiperosset/rpmbuild/my/clementine/Clementine-1.3.1/ext/libclementine-tagreader -I/home/filiperosset/rpmbuild/my/clementine/Clementine-1.3.1/x86_64-redhat-linux-gnu/ext/libclementine-tagreader -I/home/filiperosset/rpmbuild/my/clementine/Clementine-1.3.1/ext/libclementine-remote -I/home/filiperosset/rpmbuild/my/clementine/Clementine-1.3.1/x86_64-redhat-linux-gnu/ext/libclementine-remote -I/home/filiperosset/rpmbuild/my/clementine/Clementine-1.3.1/ext/libclementine-spotifyblob -I/home/filiperosset/rpmbuild/my/clementine/Clementine-1.3.1/x86_64-redhat-linux-gnu/ext/libclementine-spotifyblob -I/usr/include/gpod-1.0 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/p11-kit-1 -I/usr/include/libusb-1.0  -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fstack-clash-protection -Woverloaded-virtual -Wall -Wno-sign-compare -Wno-deprecated-declarations -Wno-unused-local-typedefs -Wno-unused-private-field -Wno-unknown-warning-option --std=c++0x -U__STRICT_ANSI__ -DNDEBUG   -o CMakeFiles/clementine_lib.dir/musicbrainz/musicbrainzclient.cpp.o -c /home/filiperosset/rpmbuild/my/clementine/Clementine-1.3.1/src/musicbrainz/musicbrainzclient.cpp
/home/filiperosset/rpmbuild/my/clementine/Clementine-1.3.1/src/musicbrainz/chromaprinter.cpp: In member function 'QString Chromaprinter::CreateFingerprint()':
/home/filiperosset/rpmbuild/my/clementine/Clementine-1.3.1/src/musicbrainz/chromaprinter.cpp:146:33: error: invalid conversion from 'void*' to 'const int16_t* {aka const short int*}' [-fpermissive]
   chromaprint_feed(chromaprint, reinterpret_cast<void*>(data.data()),
                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/filiperosset/rpmbuild/my/clementine/Clementine-1.3.1/src/musicbrainz/chromaprinter.cpp:27:0:
/usr/include/chromaprint.h:235:21: note:   initializing argument 2 of 'int chromaprint_feed(ChromaprintContext*, const int16_t*, int)'
 CHROMAPRINT_API int chromaprint_feed(ChromaprintContext *ctx, const int16_t *data, int size);
                     ^~~~~~~~~~~~~~~~
/home/filiperosset/rpmbuild/my/clementine/Clementine-1.3.1/src/musicbrainz/chromaprinter.cpp:152:58: error: invalid conversion from 'void**' to 'uint32_t** {aka unsigned int**}' [-fpermissive]
   int ret = chromaprint_get_raw_fingerprint(chromaprint, &fprint, &size);
                                                          ^~~~~~~
In file included from /home/filiperosset/rpmbuild/my/clementine/Clementine-1.3.1/src/musicbrainz/chromaprinter.cpp:27:0:
/usr/include/chromaprint.h:273:21: note:   initializing argument 2 of 'int chromaprint_get_raw_fingerprint(ChromaprintContext*, uint32_t**, int*)'
 CHROMAPRINT_API int chromaprint_get_raw_fingerprint(ChromaprintContext *ctx, uint32_t **fingerprint, int *size);
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/filiperosset/rpmbuild/my/clementine/Clementine-1.3.1/src/musicbrainz/chromaprinter.cpp:158:62: error: invalid conversion from 'void*' to 'const uint32_t* {aka const unsigned int*}' [-fpermissive]
                                    &encoded, &encoded_size, 1);
                                                              ^
In file included from /home/filiperosset/rpmbuild/my/clementine/Clementine-1.3.1/src/musicbrainz/chromaprinter.cpp:27:0:
/usr/include/chromaprint.h:331:21: note:   initializing argument 1 of 'int chromaprint_encode_fingerprint(const uint32_t*, int, int, char**, int*, int)'
 CHROMAPRINT_API int chromaprint_encode_fingerprint(const uint32_t *fp, int size, int algorithm, char **encoded_fp, int *encoded_size, int base64);
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/filiperosset/rpmbuild/my/clementine/Clementine-1.3.1/src/musicbrainz/chromaprinter.cpp:158:36: error: invalid conversion from 'void**' to 'char**' [-fpermissive]
                                    &encoded, &encoded_size, 1);
                                    ^~~~~~~~
In file included from /home/filiperosset/rpmbuild/my/clementine/Clementine-1.3.1/src/musicbrainz/chromaprinter.cpp:27:0:
/usr/include/chromaprint.h:331:21: note:   initializing argument 4 of 'int chromaprint_encode_fingerprint(const uint32_t*, int, int, char**, int*, int)'
 CHROMAPRINT_API int chromaprint_encode_fingerprint(const uint32_t *fp, int size, int algorithm, char **encoded_fp, int *encoded_size, int base64);
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
At global scope:
cc1plus: warning: unrecognized command line option '-Wno-unknown-warning-option'
cc1plus: warning: unrecognized command line option '-Wno-unused-private-field'
{standard input}: Assembler messages:
{standard input}: Error: .size expression for chromaprinter.cpp does not evaluate to a constant
make[2]: *** [src/CMakeFiles/clementine_lib.dir/build.make:7370: src/CMakeFiles/clementine_lib.dir/musicbrainz/chromaprinter.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/home/filiperosset/rpmbuild/my/clementine/Clementine-1.3.1/x86_64-redhat-linux-gnu'
make[1]: *** [CMakeFiles/Makefile2:675: src/CMakeFiles/clementine_lib.dir/all] Error 2
make: *** [Makefile:133: all] Error 2
make[1]: Leaving directory '/home/filiperosset/rpmbuild/my/clementine/Clementine-1.3.1/x86_64-redhat-linux-gnu'
make: Leaving directory '/home/filiperosset/rpmbuild/my/clementine/Clementine-1.3.1/x86_64-redhat-linux-gnu'
erro: Status de saída de /var/tmp/rpm-tmp.2pwrrB inválido (%build)
    Status de saída de /var/tmp/rpm-tmp.2pwrrB inválido (%build)

**Comment by jonaski** [comment]
This is fixed in commit #5553
You need to get the code from git:
git clone https://github.com/clementine-player/Clementine

**Comment by rosset** [comment]
yeap, this patch was also backported to fedora, thanks.
