### ISSUE TITLE
OneDrive doesn't return flac files

### ISSUE THREAD

**Issue by gigaSproule** [clementine-player/Clementine#5972]
I have a lot of flac files on OneDrive, but none of them are being returned. My guess is that [this bit of code](https://github.com/clementine-player/Clementine/blob/790fc2ff2895d15631b3806e30801439d268c434/src/internet/skydrive/skydriveservice.cpp#L128) is filtering out flac files due to OneDrive not treating flac files as audio files. Is there anyway to fix this?

**Comment by hatstand** [comment]
Might just work if you remove that line.

**Comment by gigaSproule** [comment]
Thanks, I'll give it a go

**Comment by gigaSproule** [comment]
That still didn't work. I'll try digging around a bit and see if I can get it working.

**Comment by hatstand** [comment]
This line might be important too: https://github.com/clementine-player/Clementine/blob/790fc2ff2895d15631b3806e30801439d268c434/src/internet/skydrive/skydriveservice.cpp#L145

**Comment by gigaSproule** [comment]
With the filter commented out and replacing that if statement with if folder else, it is then able to get all of the flac files. I'm having difficulties actually playing any files (mp3 or flac), but I can only imagine that's an issue with my machine setup.

It does of course then take a long time to get through my OneDrive files/folders, but at least I'm able to get all my files. Is this something that can be changed? Should I raise a PR?

**Comment by hatstand** [comment]
Raising a PR is easiest. Maybe we just remove the filter and just put up with the slowness.

**Comment by gigaSproule** [comment]
I tried it on another machine and it was playing perfectly fine, so I can only assume that it was actually my laptop's audio not working properly.
