### ISSUE TITLE
Songs dont finish

### ISSUE THREAD

**Issue by Crainedotexe** [clementine-player/Clementine#5978]
### System information

- Operating System: Linux Mint 18.3 Sylvia
- Clementine version: 1.3.1-133-gf854bc5~xenial

### Expected behaviour / actual behaviour
Song should play too full extend and then go on to next song / All Songs play to ~50% of their run time and then skips to next song

**Comment by UnwarySage** [comment]
I am having this very same problem, also on Linux Mint 1.8.3
I can't get my exact clementine version, but the About menu puts me at Version 1.2.3

It's generally the last 5-30 seconds of the song, and it doesn't seem to happen all the time, maybe only on two out of every three songs.

**Comment by russkel** [comment]
I am experiencing something similar to this on OS X 1.3.1-416. Some songs will play to the last few seconds and then keep playing past the end of the song (playing nothing) and never move to the next song.

**Comment by Crainedotexe** [comment]
After attempting to reinstall clementine, I decided to reinstall my Linux distribution, this solved the issue!
