### ISSUE TITLE
[FAQ] how update translations ?

### ISSUE THREAD

**Issue by EGD** [clementine-player/Clementine#6003]
### Before posting

Please follow the steps below and check the boxes with [x] once you did the step.

- [x] I checked the issue tracker for similar issues

Please, add an update instruction to the FAQ or in Wiki.

**Comment by hatstand** [comment]
https://clementine-player.org/participate
https://www.transifex.com/davidsansome/clementine/

**Comment by EGD** [comment]
I wanted to update the translations in the qt5 version, but I could not figure out how to update the po files.
