### ISSUE TITLE
2 years since last release

### ISSUE THREAD

**Issue by vazhnov** [clementine-player/Clementine#6009]
It's been about 2 years since last release:
> Clementine 1.3.1
> released this on Apr 19, 2016

https://github.com/clementine-player/Clementine/releases

Let's create new version!
Also, it would be great to have some approximate plan for next minor releases.

**Comment by alexanderdd** [comment]
how about making full-screen mode (party mode) part of a next release?

https://github.com/clementine-player/Clementine/issues/1284

**Comment by a17r** [comment]
https://github.com/clementine-player/Clementine/issues/3463 should be top most priority, otherwise clementine is going to be dropped from new distro releases.

**Comment by ValdikSS** [comment]
https://github.com/clementine-player/Clementine/issues/5958

**Comment by vazhnov** [comment]
Duplicate of #5958
