### ISSUE TITLE
throws an exception in visualizations and crashes

### ISSUE THREAD

**Issue by themaddoctor** [clementine-player/Clementine#6014]
### Before posting

Please follow the steps below and check the boxes with [x] once you did the step.

- [x] I checked the issue tracker for similar issues
- [x] I checked the [changelog](https://github.com/clementine-player/Clementine/blob/master/Changelog) if the issue is already resolved
- [ ] I tried the latest Clementine build from [here](https://builds.clementine-player.org/)

### System information

Please provide information about your system and the version of Clementine used.

- Operating System:
linux 64
gcc 7.3

- Clementine version: 
1.3.1

### Expected behaviour / actual behaviour

projectM] Allocating idle preset...
[PresetFactory] path is Geiss & Sperl - Feedback (projectM idle HDR mix).milk
[PresetFactory] url is idle://Geiss & Sperl - Feedback (projectM idle HDR mix).milk
[PresetFactory] path is r/share/appdata/clementine/projectm-presets/Mstress & Juppy - Dancers In The Dark.milk
[PresetFactory] url is /usr/share/appdata/clementine/projectm-presets/Mstress & Juppy - Dancers In The Dark.milk
08:29:33.871 WARN  unknown                          QPainter::end: Painter ended with 2 saved states
08:29:33.871 WARN  unknown                          Qt has caught an exception thrown from an event handler. Throwing
08:29:33.871 WARN  unknown                          exceptions from an event handler is not supported in Qt. You must
08:29:33.871 WARN  unknown                          reimplement QApplication::notify() and catch all exceptions there.
08:29:33.871 WARN  unknown
terminate called after throwing an instance of 'int'
Aborted

### Steps to reproduce the problem (only for bugs)
select Tools -> Visualizations
crashes immediately

**Comment by hatstand** [comment]
Try a newer build

**Comment by themaddoctor** [comment]
Your builds are not appropriate for my system, thank you.


On 3/5/18, John Maguire <notifications@github.com> wrote:
> Try a newer build
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/clementine-player/Clementine/issues/6014#issuecomment-370432739


-- 
Thomas Kaeding

my public key: http://pgp.mit.edu/pks/lookup?op=get&search=0x81B0FCA32599BE6F

**Comment by themaddoctor** [comment]
I found the error anyway. Thanks.


On 3/5/18, thomas kaeding <thomas.a.kaeding@gmail.com> wrote:
> Your builds are not appropriate for my system, thank you.
>
>
> On 3/5/18, John Maguire <notifications@github.com> wrote:
>> Try a newer build
>>
>> --
>> You are receiving this because you authored the thread.
>> Reply to this email directly or view it on GitHub:
>> https://github.com/clementine-player/Clementine/issues/6014#issuecomment-370432739
>
>
> --
> Thomas Kaeding
>
> my public key:
> http://pgp.mit.edu/pks/lookup?op=get&search=0x81B0FCA32599BE6F
>


-- 
Thomas Kaeding

my public key: http://pgp.mit.edu/pks/lookup?op=get&search=0x81B0FCA32599BE6F
