### ISSUE TITLE
Qt5: audioCD support brocken

### ISSUE THREAD

**Issue by EGD** [clementine-player/Clementine#6015]
- [x] I checked the issue tracker for similar issues
- [x] I checked the [changelog](https://github.com/clementine-player/Clementine/blob/master/Changelog) if the issue is already resolved
- [x] I tried the latest Clementine build from [here](https://builds.clementine-player.org/)

### System information

- Operating System: openSUSE Tumbleweed
- Clementine version: 1.3.99 rev 5966ff51c (qt5)
- Qt version: 5.10.0

### Expected behaviour / actual behaviour
doesn't show CD tracks in Devices (after double click), only count of tracks
> INFO  DeviceManager:559                Connecting QUrl("cdda:///dev/sr0")
> INFO  ConnectedDevice:45               connected QUrl("cdda:///dev/sr0") "/dev/sr0" false
> INFO  CddaSongLoader:159               MusicBrainz discid:  "oEZVFTXDVkBVf5B0j4.yuES7YYM-"
> INFO  CddaSongLoader:159               MusicBrainz discid:  "oEZVFTXDVkBVf5B0j4.yuES7YYM-"

if choose `Music → Open Audio CD` i get this errors:
> ERROR GstEnginePipeline:645            1 "gsturidecodebin.c(1425): gen_source_element (): /GstPipeline:pipeline/GstURIDecodeBin:uridecodebin-0:\nNo element accepted URI 'cdda://0.0.0.1'"
> WARN  GstEngine:693                    Gstreamer error: "Could not handle CDDA URI"

### Steps to reproduce the problem (only for bugs)
probe to play CD

1.3.1 version play audio CD correct

**Comment by jonaski** [comment]
I can confirm this. Works in master, but not the qt5 branch. I also use opensuse, but 42.3

**Comment by EGD** [comment]
@jonaski, hi, i build qt5 brunch in [this repo](https://download.opensuse.org/repositories/home:/EGDFree/openSUSE_Leap_42.3/).

**Comment by jonaski** [comment]
I see the problem now. In CddaSongLoader::GetUrlFromTrack() it creates the url from cdda://tracknumber, like cdda://1, but when it converts the qstring to qurl it ends up as cdda://0.0.0.1, qurl behaves differently in Qt5. I will see if I can fix it.

**Comment by EGD** [comment]
very dirty hack
```c++
diff --git a/src/engines/gstenginepipeline.cpp b/src/engines/gstenginepipeline.cpp
index bff43aeac..ea6528904 100644
--- a/src/engines/gstenginepipeline.cpp
+++ b/src/engines/gstenginepipeline.cpp
@@ -181,8 +181,16 @@ bool GstEnginePipeline::ReplaceDecodeBin(const QUrl& url) {
         spotify_server, "StartPlayback", Qt::QueuedConnection,
         Q_ARG(QString, url.toString()), Q_ARG(quint16, port));
   } else {
+    QByteArray uri;
+    if (url.scheme() == "cdda") {
+        QString track = url.toString().split('.').takeLast();
+        uri = QString("%1://%2").arg(url.scheme()).arg(track).toUtf8();
+    } else {
+        uri = url.toEncoded();
+    }
+
     new_bin = engine_->CreateElement("uridecodebin");
-    g_object_set(G_OBJECT(new_bin), "uri", url.toEncoded().constData(),
+    g_object_set(G_OBJECT(new_bin), "uri", uri.constData(),
                  nullptr);
     CHECKED_GCONNECT(G_OBJECT(new_bin), "drained", &SourceDrainedCallback,
                      this);
```

**Comment by EGD** [comment]
QUrl class [impossible](https://bugreports.qt.io/browse/QTBUG-66943?focusedCommentId=394326&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-394326) to create URL like _cdda://1_.

**Comment by jonaski** [comment]
Fixed. See #6260
