### ISSUE TITLE
Clementine no longer loads channels list from DI.FM services

### ISSUE THREAD

**Issue by Pulfer** [clementine-player/Clementine#6017]
Clementine no longer loads channels list from DI.FM services. Likely API of DI.FM recently changed. It applies to Digitally Imported, JAZZRADIO.COM, ROCKRADIO.COM and RadioTunes.com.

**Comment by Deleetdk** [comment]
I have the same issue. Upgrading to Clementine 1.3.1 did not help. Deleting the `.config/Clementine` folder does not help either. I'm on Mint 18.2.

**Comment by Pulfer** [comment]
Wireshark provides this info:

11	5.116137992	8.8.8.8	192.168.1.2	DNS	142	Standard query response 0xc6c6 No such name A api.v2.audioaddict.com SOA alphadc.di.int

So the code fails:

const char* DigitallyImportedClient::kChannelListUrl =
    "http://api.v2.audioaddict.com/v1/%1/mobile/"
    "batch_update?asset_group_key=mobile_icons&stream_set_key=";

https://github.com/clementine-player/Clementine/blob/master/src/internet/digitally/digitallyimportedclient.cpp#L40

**Comment by Pulfer** [comment]
I created this pull request to fix the issue: https://github.com/clementine-player/Clementine/pull/6023
