### ISSUE TITLE
Fedora version cannot play m4a

### ISSUE THREAD

**Issue by gappleto97** [clementine-player/Clementine#6035]
### Before posting

Please follow the steps below and check the boxes with [x] once you did the step.

- [x] I checked the issue tracker for similar issues
- [x] I checked the [changelog](https://github.com/clementine-player/Clementine/blob/master/Changelog) if the issue is already resolved
- [x] I tried the latest Clementine build from [here](https://builds.clementine-player.org/)

### System information

Please provide information about your system and the version of Clementine used.

- Operating System: Fedora 27
- Clementine version: 1.3.1

### Expected behaviour / actual behaviour

Since all gstreamer plugins provided by Fedora and RPMFusion are installed, it should not be missing a plugin

### Steps to reproduce the problem (only for bugs)

1. Play m4a file
2. Notice it says there's a missing GStreamer plugin

### Notes: 

I tried to use the Fedora 26 version posted on the latest build website but it would not install because `dnf` decided that no library provides `protobuf`.

I tried solutions that I found in other bug reports to no avail.

**Comment by jonaski** [comment]
Do you have the 1.0 version of plugins-bad, not 0.10
Try deleting .cache/gstreamer-1.0 in your home dir.
Whats the exact error? Run clementine from the shell and paste the error here.

**Comment by gappleto97** [comment]
My apologies, I thought that I had closed this when I found the solution. It turns out the answer is that I needed `gstreamer1-plugins-bad-nonfree`

**Comment by aminvakil** [comment]
In Fedora 29 repos `gstreamer1-plugins-bad-nonfree` is not available.

Also `gstreamer1-plugins-bad-free` doesn't help playing .m4a files.

What should be installed in Fedora 29 then?

**Comment by aminvakil** [comment]
I realized RPM Fusion nonfree is needed to be installed and then `gstreamer1-plugins-bad-nonfree` is available.

RPM Fusion can be installed this way:
`sudo dnf install https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm`

And then `sudo dnf install gstreamer1-plugins-bad-nonfree`.

**Comment by sefernet** [comment]
FYI , in Fedora now the package to install is  "rpmfusion-nonfree-obsolete-packages" (which contain "gstreamer1-plugins-bad-free")

But more important is the default system library is "ffmpeg-libs".

Another tip, is check if "mpv" play the track to varify that its works.

I came here because I had this problem but with audacious (I resolve with "audacious-plugins-freeworld-ffaudio")

Sorry the late post, and my english...
