### ISSUE TITLE
Clementine cannot play songs or Internet streams

### ISSUE THREAD

**Issue by tukkek** [clementine-player/Clementine#6039]
Hi, I'm sharing what could be a Debian-only issue since I last updated my system yesterday. I haven't been able to post a Debian bug report today so I'm deciding to create this issue here because right now Clementine is literally broken as a player on Debian testing (buster), so I thought I had to let someone know...

Thanks for the great player, hope this can be resolved soon, if there's anything to be done about it (other than by the Debian maintainers)!

### Before posting

Please follow the steps below and check the boxes with [x] once you did the step.

- [x] I checked the issue tracker for similar issues
- [ ] I checked the [changelog](https://github.com/clementine-player/Clementine/blob/master/Changelog) if the issue is already resolved
- [ ] I tried the latest Clementine build from [here](https://builds.clementine-player.org/)

### System information

[reportbug-clementine-20180405-15192-ajnm6m3e.txt](https://github.com/clementine-player/Clementine/files/1880851/reportbug-clementine-20180405-15192-ajnm6m3e.txt)

### Expected behaviour / actual behaviour

Up until my updating the system yesterday, Clementine was working perfectly. After the update, it cannot play any music files or remote streams anymore.

The error message is something about a missing GStreamer plugin (note that I have 4 GStreamer plugin packages installed currently). There doesn't seem to be any relevant console output besides the error dialog. I am not sure if Clementine maintains an independent log file, so I haven't checked.

Other players seem to work fine, so it's definitely not a system issue (VLC, mplayer...).

### Steps to reproduce the problem (only for bugs)

Open Clementine, try to play any local song or Internet stream.

**Comment by tukkek** [comment]
Since making this report I noticed the Amarok player is also suffering from a similar problem and I've opened a bug report for them too https://bugs.kde.org/show_bug.cgi?id=392766

The fact both players depend on GStreamer shows the problem is with that common package, most likely, but I'd appreciate if anyone could help ascertain the nature of the bug so a proper bug report can be made (perhaps to GStreamer maintainers directly). Thanks!

**Comment by jonaski** [comment]
VLC and mplayer are not using gstreamer, they have their own backend.
What plugins you need depends on what audio format you are trying to play.
Make sure you got all plugins: base, good, bad, ugly and possible gstreamer libav, and that they are all the same version, ie if you have 1.14, make sure all are 1.14.

**Comment by tukkek** [comment]
It has been solved after a few updates of gstreamer-related and gstreamer-plugins-good on Debian. If anyone here is at all involved with the Debian packaging, I suggest to make the Clementine package depend on the gstreamer-plugins-good package to make sure it's always installed. Otherwise it would be nice to contact the package maintainer about this.

Since the problem is fixed I'll close this report. I'll leave any follow-ups to those interested (I'm pretty busy right now, otherwise I'd look into it myself). Thanks Jonas!
