### ISSUE TITLE
Clementine doesnt work in Gnome Shell - Fedora 27

### ISSUE THREAD

**Issue by Joseluismantilla** [clementine-player/Clementine#6041]
### Before posting

Please follow the steps below and check the boxes with [x] once you did the step.

- [x] I checked the issue tracker for similar issues
- [x] I checked the [changelog](https://github.com/clementine-player/Clementine/blob/master/Changelog) if the issue is already resolved
- [x] I tried the latest Clementine build from [here](https://builds.clementine-player.org/)

### System information

Please provide information about your system and the version of Clementine used.

- Operating System: Fedora 27
- Clementine version: 1.3.1

### Expected behaviour / actual behaviour
Unfortunately clementine does not work in Gnome-shell -- please try it in xorg and wayland--, it does not open its interface and I can not reproduce anything, I have the system updated without errors - it seems that some dependencies or requirements are missing by being added.

### Steps to reproduce the problem (only for bugs)
$ clementine
10:04:57.996 WARN  unknown                          libpng warning: iCCP: known incorrect sRGB profile 
10:04:58.017 WARN  unknown                          QPixmap: It is not safe to use pixmaps outside the GUI thread 
10:04:58.017 WARN  unknown                          QPixmap: It is not safe to use pixmaps outside the GUI thread 
10:04:58.017 WARN  unknown                          QPixmap: It is not safe to use pixmaps outside the GUI thread 
10:04:58.017 WARN  unknown                          QPixmap: It is not safe to use pixmaps outside the GUI thread 
10:04:58.017 WARN  unknown                          QPixmap: It is not safe to use pixmaps outside the GUI thread 
10:04:58.017 WARN  unknown                          QPixmap: It is not safe to use pixmaps outside the GUI thread 
10:04:58.017 WARN  unknown                          QPixmap: It is not safe to use pixmaps outside the GUI thread 
10:04:58.017 WARN  unknown                          QPixmap: It is not safe to use pixmaps outside the GUI thread 
10:04:58.017 WARN  unknown                          QPixmap: It is not safe to use pixmaps outside the GUI thread 
10:04:58.746 WARN  unknown                          QPainter::begin: Paint device returned engine == 0, type: 2 
10:04:58.888 WARN  unknown                          "sni-qt/13956" WARN  10:04:58.888 void StatusNotifierItemFactory::connectToSnw() Invalid interface to SNW_SERVICE  
10:04:58.888 WARN  unknown                          No systemtrayicon available 
10:04:58.889 WARN  unknown                          Object::connect: No such signal QtSingleApplication::messageReceived(QByteArray) 
10:04:58.889 WARN  unknown                          Object::connect:  (sender name:   'clementine') 
10:04:58.889 WARN  unknown                          Object::connect:  (receiver name: 'MainWindow') 
10:04:58.947 WARN  unknown                          QSortFilterProxyModel: invalid inserted rows reported by source model 
10:04:59.377 ERROR unknown                          JSonScanner::yylex - error while reading from io device  
10:04:59.377 ERROR unknown                          json_parser - syntax error found,  forcing abort, Line 1 Column 1

**Comment by rdieter** [comment]
Try the workaround(s) mentioned in fedora's bugzilla,
https://bugzilla.redhat.com/show_bug.cgi?id=1517748#c4

It appears clementine doesn't gracefully handle the case where DE doesn't provide system tray support.

**Comment by Joseluismantilla** [comment]
Yes, I have found two solutions that are:
1) You can try editing ~/.config/Clementine/Clementine.conf and include

[MainWindow]
showtray=false  
2) rm -f ~/.config/Clementine/Clementine.conf  (optionally, rm -rf ~/.cache/Clementine

Thanks
