### ISSUE TITLE
Clementine Does Not Preserve Metadata When Ripping From CD

### ISSUE THREAD

**Issue by sonic2kk** [clementine-player/Clementine#6045]
### System information
- Operating System: Ubuntu 16.04 LTS
- Clementine version: 1.3.1

### Expected behaviour / actual behaviour
Clementine displays the metadata for the CD correctly when I import it into my library, presumably taking it from the CD. When I attempt to rip the music from the disc, it rips with no metadata. In the dialog box which shows the destination folder, etc it does not display metadata in the table for each track; instead it simply says "Track 1", "Track 2" and so on. Again, track information displays and displays correctly when _imported_, but not when _ripped_. I found [the exact same issue](https://askubuntu.com/questions/865920/why-doesnt-clementine-pick-up-track-information-when-ripping-cd) on an Ask Ubuntu post, however it is still pending an answer.

As reference, RhythmBox is able to rip the songs fine, although it is quite slow. Asunder hangs at different times and seems to rip the audio quickly before hanging. The optical drive seems to be reading a lot of data too, in order to keep up with the transcoding speed. The drive does not go nearly as fast with Clementine or RhythmBox. 

On my laptop running Xubuntu 16.04, Asunder works perfectly fine with ripping the audio from the discs. I ripped the same discs just the other day, and it also kept the metadata. The optical drive I'm using is connected via SATA, and not through USB. The discs are also in immaculate condition, so reading the discs themselves should not be an issue either.

How can I rip the audio files from the disc and preserve the metadata?

**Comment by sonic2kk** [comment]
I hate to do this but, bump. Has anyone got any recommendations for things to try at least?

**Comment by kstripp** [comment]
Same issue on Debian Sid with Clementine 1.3.1

**Comment by whayden** [comment]
I am having the same issue in Manjaro
