### ISSUE TITLE
Column header contents/widths are not saved on systems with proprietary nvidia drivers

### ISSUE THREAD

**Issue by aerusso** [clementine-player/Clementine#6061]
### Before posting

Please follow the steps below and check the boxes with [x] once you did the step.

- [x] I checked the issue tracker for similar issues
- [x] I checked the [changelog](https://github.com/clementine-player/Clementine/blob/master/Changelog) if the issue is already resolved
- [x] I tried the latest Clementine build from [here](https://builds.clementine-player.org/) **This specifically is caused by #6057**

### System information

This affects users with nvidia proprietary drivers.

### Analysis

#6057 changes the time of save for column widths, current tab, etc., to Clementine shutdown. The early termination code introduced in 5237c005c9 (and c2723008a2) (specifically to address an unrelated nvidia driver bug that caused problems during Clementine shutdown) means that this information will not be saved.

I see two options:

1. Revert c2723008a2, and add more versions to the blacklist as needed. There are probably very few people still using those buggy drivers anyway (I have an old nvidia card, and do not have this problem).
2. Perform the save before terminating early. This seems like a lot of work for something that is already fixed "the right way" elsewhere.

### Steps to reproduce the problem (only for bugs)

Have an library containing `libnvidia-tls.so.` in its name. Change the header widths, current playlist, etc.. Shut Clementine down, and restart it. The settings are not preserved.

**Comment by BeerSerc** [comment]
I can confirm that on my gentoo system, using proprietary nvidia drivers, this problem occured, and reverting c272300 fixed the problem.

**Comment by aerusso** [comment]
#6334 closes this issue.
