### ISSUE TITLE
Clementine 1.3.1 corrupts tracks/files making them unreadable / Kubuntu 17.10~18.04

### ISSUE THREAD

**Issue by sylvainsab** [clementine-player/Clementine#6071]
Hi,

Having known Linux/BSD since long and tested through many kinds of distros, I'm now back on the simpler Kubuntu for its centralizing interface. The only thing I was not satisfied with was the music player's design and I found Clementine which satisfies me greatly on this part.

Unfortunately, there is a recurrent bug : sometimes opening tracks displays an error instead and then the track or sometimes whole albums is/are made unreadable by any software (I've notably tried VLC that goes with the Kubuntu default software suite).

Since, I've been keeping an "uncorrupt music library" folder and gone further : it seems the bug MAY come from the "fading" function I use and switching too fast from one music track to another. I try to have a safer use of the software as of now, yet I'm quite sure it also used to happen when opening track when no one is playing.

I'll attach a screenshot next time the error pops up.

**Comment by sylvainsab** [comment]
Here you go, an error pop-up appears saying "Could not decode stream" after reading the file once.
![image](https://user-images.githubusercontent.com/34339895/41342038-8d74b97c-6efb-11e8-846b-58cf90abee2f.png)

**Comment by jonaski** [comment]
Is it ogg? See my comment on #5524

**Comment by sylvainsab** [comment]
@jonaski yes, ogg files.
