### ISSUE TITLE
Qt5 branch: build broken

### ISSUE THREAD

**Issue by EGD** [clementine-player/Clementine#6093]
build log:

> -- Checking for module 'taglib'
> --   Found taglib, version 1.11.1
> -- Using builtin taglib because your system's version is too old
>  CMake Error at CMakeLists.txt:119 (add_subdirectory):
>   add_subdirectory given source "3rdparty/taglib" which is not an existing
>   directory.

**Comment by EGD** [comment]
```diff
--- clementine-player/CMakeLists.txt	2018-06-30 20:25:48.267824333 +0300
+++ clementine-player/CMakeLists.txt.new	2018-06-30 21:07:34.988797934 +0300
@@ -94,7 +94,7 @@ find_path(LASTFM51_INCLUDE_DIRS lastfm5/
 find_path(SPARSEHASH_INCLUDE_DIRS google/sparsetable)
 
 # Only use system taglib if it's greater than 1.11.1 because of audio file detection by content.
-if (TAGLIB_VERSION VERSION_GREATER 1.11.1 OR WIN32)
+if (TAGLIB_VERSION VERSION_GREATER_EQUAL 1.11.1 OR WIN32)
   option(USE_SYSTEM_TAGLIB "Use system taglib" ON)
 else()
   option(USE_SYSTEM_TAGLIB "Use system taglib" OFF)

**Comment by jonaski** [comment]
You removed 3rdparty/taglib somehow

**Comment by jonaski** [comment]
If you want to build using your systems taglib use: cmake .. -DUSE_SYSTEM_TAGLIB=ON

**Comment by EGD** [comment]
Ok, `USE_BUILTIN_TAGLIB` renamed to `USE_SYSTEM_TAGLIB`, but `TAGLIB_VERSION VERSION_GREATER 1.11.1` never true (in this moment last available taglib version is 1.11.1).

**Comment by jonaski** [comment]
It was done intentionally, since the current release 1.11.1 lacks some functionality, but to not use the git version in 3rdparty if and when there is a newer version.

**Comment by EGD** [comment]
Ok, thanks.
