### ISSUE TITLE
scrobbling from debian buster

### ISSUE THREAD

**Issue by good-old-music** [clementine-player/Clementine#6095]
I use Debian Buster and the update after 22nd June to 1.3.1+git542-gf00d9727+dfsg-1+b1 seems to have removed the option to scrobble tracks to lastFM, is this you, me not finding the switch or Debian altering the code for some reason?

**Comment by jonaski** [comment]
There have been no changes to the code that would change this.
All I can think of is that it has been compiled without lastfm support, this will be the case if liblastfm is not found on the system.
Do you have last.fm under Preferences / Internet Providers?

**Comment by good-old-music** [comment]
No, it's not there, I added liblastfm a couple of days back but no luck, I'll have to try and revert to the last working version or recompile it myself (ouch) TY

**Comment by good-old-music** [comment]
as I said, Ouch.
Something about echonest? how do I fix this? 
Sorry if I'm being a pain, (incomprehensible to me) error logs linked at bottom

bin# cmake ../
-- The C compiler identification is GNU 7.3.0
-- The CXX compiler identification is GNU 7.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Deprecation Warning at CMakeLists.txt:2 (cmake_policy):
  The OLD behavior for policy CMP0011 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.


-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29") 
-- Looking for Q_WS_X11
-- Looking for Q_WS_X11 - found
-- Looking for Q_WS_WIN
-- Looking for Q_WS_WIN - not found
-- Looking for Q_WS_QWS
-- Looking for Q_WS_QWS - not found
-- Looking for Q_WS_MAC
-- Looking for Q_WS_MAC - not found
-- Found Qt4: /usr/bin/qmake (found suitable version "4.8.7", minimum required is "4.5.0") 
-- Found Qt4: /usr/bin/qmake (found version "4.8.7") 
CMake Warning (dev) at /usr/share/cmake-3.11/Modules/FindOpenGL.cmake:270 (message):
  Policy CMP0072 is not set: FindOpenGL prefers GLVND by default when
  available.  Run "cmake --help-policy CMP0072" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.

  FindOpenGL found both a legacy GL library:

    OPENGL_gl_LIBRARY: /usr/lib/x86_64-linux-gnu/libGL.so

  and GLVND libraries for OpenGL and GLX:

    OPENGL_opengl_LIBRARY: /usr/lib/x86_64-linux-gnu/libOpenGL.so
    OPENGL_glx_LIBRARY: /usr/lib/x86_64-linux-gnu/libGLX.so

  OpenGL_GL_PREFERENCE has not been set to "GLVND" or "LEGACY", so for
  compatibility with CMake 3.10 and below the legacy GL library will be used.
Call Stack (most recent call first):
  CMakeLists.txt:51 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found OpenGL: /usr/lib/x86_64-linux-gnu/libOpenGL.so   
-- Boost version: 1.62.0
-- Found Gettext: /usr/bin/msgmerge (found version "0.19.8.1") 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found Protobuf: /usr/lib/x86_64-linux-gnu/libprotobuf.so;-lpthread (found version "3.0.0") 
-- Checking for module 'libcdio'
--   Found libcdio, version 2.0.0
-- Checking for module 'libchromaprint'
--   Found libchromaprint, version 1.4.3
-- Checking for one of the modules 'cryptopp;libcrypto++'
-- Checking for module 'gio-2.0'
--   Found gio-2.0, version 2.56.1
-- Checking for module 'glib-2.0'
--   Found glib-2.0, version 2.56.1
-- Checking for module 'gobject-2.0'
--   Found gobject-2.0, version 2.56.1
-- Checking for module 'gstreamer-1.0'
--   Found gstreamer-1.0, version 1.14.1
-- Checking for module 'gstreamer-app-1.0'
--   Found gstreamer-app-1.0, version 1.14.1
-- Checking for module 'gstreamer-audio-1.0'
--   Found gstreamer-audio-1.0, version 1.14.1
-- Checking for module 'gstreamer-base-1.0'
--   Found gstreamer-base-1.0, version 1.14.1
-- Checking for module 'gstreamer-tag-1.0'
--   Found gstreamer-tag-1.0, version 1.14.1
-- Checking for module 'libgpod-1.0>=0.7.92'
--   Found libgpod-1.0, version 0.8.3
-- Checking for module 'libmtp>=1.0'
--   Found libmtp, version 1.1.13
-- Checking for module 'libmygpo-qt>=1.0.9'
--   No package 'libmygpo-qt' found
-- Checking for module 'libpulse'
--   Found libpulse, version 11.1
-- Checking for module 'libxml-2.0'
--   Found libxml-2.0, version 2.9.4
-- Checking for module 'QJson'
--   Found QJson, version 0.8.1
-- Checking for module 'libspotify>=12.1.45'
--   No package 'libspotify' found
-- Checking for module 'taglib>=1.6'
--   Found taglib, version 1.11.1
-- Performing Test TAGLIB_HAS_OPUS
-- Performing Test TAGLIB_HAS_OPUS - Success
-- Found Qt4: /usr/bin/qmake (found version "4.8.7") 
-- Checking for module 'k8json'
--   No package 'k8json' found
-- Using internal copy of k8json
-- Performing Test COMPILER_SUPPORTS_PIC_FLAG
-- Performing Test COMPILER_SUPPORTS_PIC_FLAG - Success
CMake Warning (dev) at /usr/share/cmake-3.11/Modules/CMakePushCheckState.cmake:65 (if):
  Policy CMP0054 is not set: Only interpret if() arguments as variables or
  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  Quoted variables like "LIBRARY_EXTRA_SOURCES" will no longer be
  dereferenced when the policy is set to NEW.  Since the policy is not set
  the OLD behavior will be used.
Call Stack (most recent call first):
  /usr/share/cmake-3.11/Modules/FindQt4.cmake:758 (cmake_push_check_state)
  3rdparty/vreen/vreen/cmake/CommonUtils.cmake:149 (find_package)
  3rdparty/vreen/vreen/cmake/CommonUtils.cmake:208 (__check_source_files)
  3rdparty/vreen/vreen/src/api/CMakeLists.txt:1 (add_simple_library)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Performing Test COMPILER_SUPPORTS_CXX_11_FLAG
-- Performing Test COMPILER_SUPPORTS_CXX_11_FLAG - Success
-- Performing Test COMPILER_SUPPORTS_STD_LIBCXX_FLAG
-- Performing Test COMPILER_SUPPORTS_STD_LIBCXX_FLAG - Failed
-- Added static library vreen
-- Using internal copy of vreen
CMake Deprecation Warning at 3rdparty/libprojectm/CMakeLists.txt:7 (cmake_policy):
  The OLD behavior for policy CMP0005 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.


CMake Deprecation Warning at 3rdparty/libprojectm/CMakeLists.txt:11 (cmake_policy):
  The OLD behavior for policy CMP0017 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.


-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Found X11: /usr/lib/x86_64-linux-gnu/libX11.so
-- Performing Test SUPPORTS_OPENMP
-- Performing Test SUPPORTS_OPENMP - Success
-- Using builtin sha2 library
-- Performing Test SUPPORTS_NOBOOL
-- Performing Test SUPPORTS_NOBOOL - Success

Building Clementine version: 1.3.1

The following components will be built:
   Box support
   D-Bus support
   Devices: Audio CD support
   Devices: DeviceKit backend
   Devices: GIO device backend
   Devices: MTP support
   Devices: iPod classic support
   Dropbox support
   Google Drive support
   Last.fm support
   Moodbar support
   Pulse audio integration
   Seafile support
   Skydrive support
   Visualisations
   Vk.com support
   Wiimote support

The following components WILL NOT be built:
   Amazon Cloud Drive support (disabled in CMake config)
   Crash reporting (disabled in CMake config)
   Sparkle integration (missing Mac OS X, Sparkle)
   Spotify support: non-GPL binary helper (missing libspotify)

CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
ECHONEST_INCLUDE_DIRS
   used as include directory in directory /home/dom/Downloads/Clementine-1.3.1/src
   used as include directory in directory /home/dom/Downloads/Clementine-1.3.1/src
   used as include directory in directory /home/dom/Downloads/Clementine-1.3.1/src
   used as include directory in directory /home/dom/Downloads/Clementine-1.3.1/src
   used as include directory in directory /home/dom/Downloads/Clementine-1.3.1/src
   used as include directory in directory /home/dom/Downloads/Clementine-1.3.1/src
   used as include directory in directory /home/dom/Downloads/Clementine-1.3.1/src
   used as include directory in directory /home/dom/Downloads/Clementine-1.3.1/src
ECHONEST_LIBRARIES
    linked by target "clementine_lib" in directory /home/dom/Downloads/Clementine-1.3.1/src

-- Configuring incomplete, errors occurred!
See also "/home/dom/Downloads/Clementine-1.3.1/bin/CMakeFiles/CMakeOutput.log".
See also "/home/dom/Downloads/Clementine-1.3.1/bin/CMakeFiles/CMakeError.log".


[CMakeError.log](https://github.com/clementine-player/Clementine/files/2163289/CMakeError.log)
[CMakeOutput.log](https://github.com/clementine-player/Clementine/files/2163290/CMakeOutput.log)

**Comment by jonaski** [comment]
Get the newer code with: git clone https://github.com/clementine-player/Clementine
It no longer requires echonest, and have lot's of bugfixes.
Otherwise you need to install the the echonest library and -dev package.

**Comment by good-old-music** [comment]
Yes, perfect Thanks alot, I had a good search for libechonest earlier and could only find it for wheezy or Jessie so gave that a miss. Anyway, installed, working and scrobbling. 
Been using clementine for a long while and love the layout - for large album collections (2500) it's ideal.
Cheers and ready for you to close the ticket.
