### ISSUE TITLE
System's alert sound is played when navigating via arrow keys

### ISSUE THREAD

**Issue by Clementine-Issue-Importer** [clementine-player/Clementine#611]
_From [aaron.koensgen](https://code.google.com/u/111577004655758503565/) on August 07, 2010 11:03:07_

What steps will reproduce the problem? 1. Expand/collapse entries in the collection browser by pressing the left or right arrow key
(or) 2. Press the left or right array key to scroll horizontally in the playlist view What is the expected output? What do you see instead? I don't expect to hear anything. Instead I hear the default alert sound of the operating system. What version of the product are you using? On what operating system? r1575 on Mac OS X 10.6.4

_Original issue: http://code.google.com/p/clementine-player/issues/detail?id=611_

**Comment by Chocobozzz** [comment]
Closing this old issue. Feel free to ask for reopening it.
