### ISSUE TITLE
CMake Warning: Policy CMP0072 is not set

### ISSUE THREAD

**Issue by EGD** [clementine-player/Clementine#6156]
### System information
- Operating System: openSUSE Tumbleweed
- Clementine version: HEAD of qt5 branch

### Actual behaviour
> CMake Warning (dev) at /usr/share/cmake/Modules/FindOpenGL.cmake:270 (message):
>   Policy CMP0072 is not set: FindOpenGL prefers GLVND by default when
>   available.  Run "cmake --help-policy CMP0072" for policy details.  Use the
>   cmake_policy command to set the policy and suppress this warning.
> 
>   FindOpenGL found both a legacy GL library:
> 
>     OPENGL_gl_LIBRARY: /usr/lib64/libGL.so
> 
>   and GLVND libraries for OpenGL and GLX:
> 
>     OPENGL_opengl_LIBRARY: /usr/lib64/libOpenGL.so
>     OPENGL_glx_LIBRARY: /usr/lib64/libGLX.so
> 
>   OpenGL_GL_PREFERENCE has not been set to "GLVND" or "LEGACY", so for
>   compatibility with CMake 3.10 and below the legacy GL library will be used.
> Call Stack (most recent call first):
>   CMakeLists.txt:52 (find_package)
> This warning is for project developers.  Use -Wno-dev to suppress it.

**Comment by amhndu** [comment]
This could be closed now. With #6160 merged.
