### ISSUE TITLE
QT5 Branch testing: Main Window shows "&" in front of Icons-Text on left menu (Search, Library...)

### ISSUE THREAD

**Issue by plntyk** [clementine-player/Clementine#6170]
- [x] I checked the issue tracker for similar issues
- [x] I checked the [changelog](https://github.com/clementine-player/Clementine/blob/master/Changelog) if the issue is already resolved
- [ ] I tried the latest Clementine build from [here](https://builds.clementine-player.org/)

- Operating System: Arch Linux
- Clementine version: git qt5 fb00835468295925a6945a286406a2eec6bdb67a

Main Window shows 
"&Suche", "&Bibliothek", "&Dateien" and the others - on every Icon there is a "&" in front of the Text
using the German UI so technically unsure about Wiedergabeliste because it's too long

**Comment by fitojb** [comment]
Duplicate of #6118

**Comment by plntyk** [comment]
Indeed, Duplicate of #6118 which itself seem to be a duplicate of #5931

Workaround in #5931 from Upstream https://bugs.kde.org/show_bug.cgi?id=337491
fixed the display issue - thank you for pointing to a workaround

Because of that I am closing this issue
