### ISSUE TITLE
Can't play WMA "Lossless" Files

### ISSUE THREAD

**Issue by Clementine-Issue-Importer** [clementine-player/Clementine#619]
_From [ezequielaristan](https://code.google.com/u/112725302908219433246/) on August 09, 2010 23:24:19_

What steps will reproduce the problem? 1. Open Clementine Player
2. Try to play a WMA Lossless file What is the expected output? What do you see instead? It should play the file, instead I get a "Internal data stream error" What version of the product are you using? On what operating system? Clementine 0.4 on Windows 7 Please provide any additional information below. All files were ripped from my original CD with Windows Media Player, without DRM or something like that, and it plays perfectly in other players.

_Original issue: http://code.google.com/p/clementine-player/issues/detail?id=619_

**Comment by anandpathaksharma** [comment]
Clementine version 1.2.3, same issues. WMA files in playlist cause Clementine to freeze. Let me know if you'd like me to provide logs (you'll need to explain how to get them).

PS: Just want to say that I love Clementine (started using it on my Ubuntu dev machine) and, now that I'm developing on Windows, I ditched Winamp in favour of Clementine. You folks are awesome, thank you for this awesome player! :+1: :smile:

**Comment by Chocobozzz** [comment]
Can you try with the latest build ? http://builds.clementine-player.org/

**Comment by anandpathaksharma** [comment]
Hi there, wow, fast response! Will do!

Actually, just after writing my comment, I uninstalled 1.2.3 and downgraded to 1.1.1. Things working nicely in this version without any issue. I'll uninstall 1.1.1 and try the latest build then get back to you right now.

Thanks @Chocobozzz  :o)

**Comment by anandpathaksharma** [comment]
Hey there @Chocobozzz,

Confirmed, the latest build works like a charm!!! For posterity's sake, here's the direct link to the build (in case anyone else needs to find it/them):

  - Windows Clementine Releases: http://builds.clementine-player.org/win32/release/
  - Build that worked for me and doesn't freeze when playing WMAs: http://builds.clementine-player.org/win32/release/ClementineSetup-1.2.3-1047-gb50c512.exe

Thanks again, you rock! :grinning:

**Comment by Chocobozzz** [comment]
Thanks for your feedbacks :)

So I think we can close this issue.
