### ISSUE TITLE
[regression] Sidebar tabs position is no longer persisted

### ISSUE THREAD

**Issue by ronjouch** [clementine-player/Clementine#6209]
### Before posting

- [x] I checked the issue tracker for similar issues
- [x] I checked the [changelog](https://github.com/clementine-player/Clementine/blob/master/Changelog) if the issue is already resolved
- [x] I tried the latest Clementine build from [here](https://builds.clementine-player.org/)

### System information

- Operating System: Ubuntu Linux 18.04.1 LTS x64
- Clementine version: `master` as of November 22: 1.3.1-517-g 3bc6f7059, built with default options (`cd bin && cmake .. && make -j -l4`).

### Steps to reproduce & expected/actual behaviour

1. Right-click on sidebar tabs (Library, Song info, Search, Files, ...) and pick a non-default position, e.g. `Tabs on top`.
2. Quit Clementine.
3. Start Clementine.

**Expected**: Clementine should honor my setting and start with `Tabs on top`:

![screenshot_clementine-tabsontop_2018-11-22-10 20 05](https://user-images.githubusercontent.com/522085/48911252-55d2dc00-ee40-11e8-8686-6a1b960256d2.png)

**Actual**: Clementine starts with `Plain sidebar`, forgetting my previously-set preference:

![screenshot_clementine-plainsidebar_2018-11-22-10 20 36](https://user-images.githubusercontent.com/522085/48911273-63886180-ee40-11e8-910d-e81039c2b809.png)

Problem is a regression that I'd say happened somewhere in November 2018.

**Comment by jonaski** [comment]
I'm aware of this. It's the same with the window positions and the columns, I'll submit a pr for it as soon as I get the time, probably next week.

**Comment by ronjouch** [comment]
@jonaski I confirm https://github.com/clementine-player/Clementine/pull/6217 / 289ea31f8cf43e11921e525e87323158f831796c fixes the issue. Closing. Thanks!
