### ISSUE TITLE
[Feature Request] Export playlists in bash or batch export

### ISSUE THREAD

**Issue by TheBlackKoala** [clementine-player/Clementine#6214]
### **Summary**
I would like to request the ability to do some kind of batch export of playlists.

### **Details**
While using clementine is great it is a great hindrance having to export every single playlist one at a time. Either introducing bulk export or a way to export the playlists through bash would make this a lot more enjoyable. Even a "save playlists to folder on exit" or the likes would suffice.

If anyone could point me to where the playlists are being stored in the clementine-database i would happily take a jab at making a script for it.

**Comment by jonaski** [comment]
```
cd ~/.config/Clementine/
sqlite3 clementine.db
select * from playlists;
select * from playlist_items;
```

You can dump there entire database of data including all schema using:

```
.output clementne-db-file.txt
.dump
```

To dump only the schema use:

```
.output clementne-schema-file.txt
.schema
```

Get out out, use: .exit

**Comment by TheBlackKoala** [comment]
thank you!
I am working on a script and will share it here when it is done

**Comment by TheBlackKoala** [comment]
I made a python-script that goes in and exports all playlists in the Clementine-database to .m3u-files of the same name as the playlist. It also creates a relative path for each file, the relative path is then created for each file instead of the full path (if you want the full path then just skip the relPath function).
I hope that someone other than me might find it interesting :)
[exportAllPlaylists.zip](https://github.com/clementine-player/Clementine/files/2636015/exportAllPlaylists.zip)
