### ISSUE TITLE
BSOD on Windows while trying to play a track

### ISSUE THREAD

**Issue by dsd3mon** [clementine-player/Clementine#6233]
### Before posting

Please follow the steps below and check the boxes with [x] once you did the step.

- [x] I checked the issue tracker for similar issues
- [x] I checked the [changelog](https://github.com/clementine-player/Clementine/blob/master/Changelog) if the issue is already resolved
- [ ] I tried the latest Clementine build from [here](https://builds.clementine-player.org/) -- I was not able to run latest windows build

### System information

- Operating System: Win 10 1803
- Clementine version: 1.3.1

### Expected behaviour / actual behaviour
Clementine plays a track / BSOD appears with BAD_POOL_CALLER code.

### Steps to reproduce the problem 
- Run Clementine
- Add a track to a playlist
- Play a track

This wasn't happening with previous win10 builds

**Comment by hatstand** [comment]
This is a driver or hardware problem.
