### ISSUE TITLE
Soundcloud is missing

### ISSUE THREAD

**Issue by dayfuaim** [clementine-player/Clementine#6239]
### Before posting

- [x] I checked the issue tracker for similar issues
- [x] I checked the [changelog](https://github.com/clementine-player/Clementine/blob/master/Changelog) if the issue is already resolved
- [x] I tried the latest Clementine build from [here](https://builds.clementine-player.org/) __Of course. I'm on it.__

### System information

Please provide information about your system and the version of Clementine used.

- Operating System: Mac OSX 10.10.5
- Clementine version: 1.3.1-537-g3c8a558

### Actual behaviour
![2018-12-15 19 47 52](https://user-images.githubusercontent.com/1274699/50045371-be5d5380-00a2-11e9-8ade-0baed9c3dcbe.png)

As soon as I remember, this behaviour was also on several previous versions.
Soundcloud-related records ARE in `org.clementine-player.clementine.plist`.
[org.clementine-player.clementine.plist.zip](https://github.com/clementine-player/Clementine/files/2682880/org.clementine-player.clementine.plist.zip)

### Expected behaviour
Soundcloud is on "Internet services" and is operational.

### Steps to reproduce the problem (only for bugs)
1. Clean install of last version from https://builds.clementine-player.org/.
2. "Preferences -> Internet services"

**Comment by jonaski** [comment]
There isn't any soundcloud support anymore.

**Comment by derVedro** [comment]
> There isn't any soundcloud support anymore.

why?

**Comment by fitojb** [comment]
Soundcloud closed its APIs to third-party consumption; there’s nothing that Clementine can do about it.
