### ISSUE TITLE
A library behind a symlinked folder is not scanned fully

### ISSUE THREAD

**Issue by Clementine-Issue-Importer** [clementine-player/Clementine#624]
_From [loonyphoenix](https://code.google.com/u/103981342661184886950/) on August 12, 2010 16:39:12_

What steps will reproduce the problem? On my system it is:
1. Symlink /media/data/music/ as ~/music/
2. Direct Clementine to update the library from ~/music
3. Watch only about a third of the library being added What is the expected output? What do you see instead? If I scan the library folder directly, it has ~6000 tracks, so I'm expecting ~6000 tracks in my library. It has only about 2000. What version of the product are you using? On what operating system? 0.4.2

_Original issue: http://code.google.com/p/clementine-player/issues/detail?id=624_

**Comment by Chocobozzz** [comment]
Obsolete.
