### ISSUE TITLE
Smart playlists only add 20 songs to the playlist

### ISSUE THREAD

**Issue by SicroAtGit** [clementine-player/Clementine#6241]
The following smart playlists do not add more than 20 songs to the playlist:
- Least liked titles
- Dynamic random mix
- Played sometime
- Favourite titles
- Most Played
- Newest titles
- Never played
- Last played

These intelligent playlists do not have this limitation:
- 50 random titles
- All titles

If this behavior is intended by the developers, it would be good if the number of titles to be added to the playlist could be set.

I am using the German version of the program and have translated the playlist names into English, so they may differ from the original English names.

- Operating System: Manjaro Linux
- Clementine version: 1.3.1

**Comment by tormol** [comment]
It can be changed:
Right click name of smart playlist -> Click edit smart playlist -> Click Next -> Limits

**Comment by SicroAtGit** [comment]
Thank you, I see it now, too.
