### ISSUE TITLE
Php version mismatch on Raspbian Stretch

### ISSUE THREAD

**Issue by ksdehoff** [clementine-player/Clementine#6267]
I am installing on the nov 2018 version of raspbian stretch.  It installs PHP7.  apt-install of ampache-common results in an unresolvable dependency - wanting a php-gettext 1.0.11 or earlier but the OS has php-gettest 1.0.12-0.1 installed.

Is there a way around this other than backing out to Jessie?

**Comment by tigerfoot** [comment]
@ksdehoff could you close this issue, which obviously has not been reported to the right project :-)
