### ISSUE TITLE
Ridiculously high CPU usage on Clementine's official website

### ISSUE THREAD

**Issue by RodrigoLeiteF** [clementine-player/Clementine#6277]
### Before posting

Please follow the steps below and check the boxes with [x] once you did the step.

- [x] I checked the issue tracker for similar issues
- [x] I checked the [changelog](https://github.com/clementine-player/Clementine/blob/master/Changelog) if the issue is already resolved

### System information

Please provide information about your system and the version of Clementine used.

- Operating System: Debian Buster
- Clementine version: Irrelevant

### Expected behaviour / actual behaviour
Expected behavior: Normal CPU usage
Actual behavior: 240+% CPU usage

![image](https://user-images.githubusercontent.com/16887983/51807207-22129900-226b-11e9-90df-586232c27620.png)

### Steps to reproduce the problem (only for bugs)
1. Go to https://www.clementine-player.org/pt_BR/

**Comment by RodrigoLeiteF** [comment]
Update: Issue only seems to happen on Chromium (Version 72.0.3626.7, not sure about others). No issues on Chrome or Firefox.

**Comment by hatstand** [comment]
The website doesn't do anything significant and I can't reproduce.
