### ISSUE TITLE
crash on update

### ISSUE THREAD

**Issue by soundsbeard** [clementine-player/Clementine#6282]
### System information
- Operating System: manjaro (kernel 4.19.16-1)
- Clementine version: 1.3.1

### Expected behaviour / actual behaviour
updating database goes to 99% and then clementine crashes

running through the terminal gives that:
15:46:27.892 WARN  unknown                          libpng warning: iCCP: known incorrect sRGB profile 
15:46:27.915 WARN  unknown                          QxtGlobalShortcut failed to register: "Media Next"  
15:46:27.915 WARN  unknown                          QxtGlobalShortcut failed to register: "Media Play"  
15:46:27.915 WARN  unknown                          QxtGlobalShortcut failed to register: "Media Previous"  
15:46:27.915 WARN  unknown                          QxtGlobalShortcut failed to register: "Media Stop"  
15:46:28.209 ERROR unknown                          JSonScanner::yylex - error while reading from io device  
15:46:28.209 ERROR unknown                          json_parser - syntax error found,  forcing abort, Line 1 Column 1  
Segmentation fault (core dumped)

**Comment by jbroadus** [comment]
I was just looking at this json error. It's due to a bug in qjson, but isn't causing this crash (the "abort" in the message is just referring to parsing). Are you able to run in gdb and dump a backtrace?

**Comment by soundsbeard** [comment]
> I was just looking at this json error. It's due to a bug in qjson, but isn't causing this crash (the "abort" in the message is just referring to parsing). Are you able to run in gdb and dump a backtrace?

im not experienced in coding, i've installed gdb, and then i ran 'gdb clementine' and it ends with
Reading symbols from clementine...(no debugging symbols found)...done.
but i don't think this is what you've asked for.
if you could tell me exact steps i have do to, i would reproduce them to give a backtrace you needed.

**Comment by jbroadus** [comment]
You're almost there. At the prompt, type "run". It should run normally until it segfaults. At that point, type "bt" and you should get a backtrace.

**Comment by soundsbeard** [comment]
> You're almost there. At the prompt, type "run". It should run normally until it segfaults. At that point, type "bt" and you should get a backtrace.

https://pastebin.com/Y3bAB5Dv

**Comment by jbroadus** [comment]
Seems like it must be stack corruption. Each LibraryWatcher::ScanSubdirectory frame indicates a recursive call into a subdirectory. The visible part of the stack shows 22 iterations. Does that sound accurate for your music library? Anything unusual about your music directory (mounts to other filesystems, etc)? If you run again, does it generate the same backtrace?

I just tried with a couple hundred levels of subdirectory, and that worked fine. But if it found a way into an infinite recursion, that would eventually crash.

**Comment by soundsbeard** [comment]
> Anything unusual about your music directory (mounts to other filesystems, etc)? 

you were right.
some time ago i messed up with manjaro's system language packages and regional settings, and it resulted into troubles with libre office file with cyrillic symbols in the path.
i was not able to connect this issue with clementine failure, bc i didn't use clementine for a long time after that.
i've tried to add a single folder with english symbols only to a library and rescaned it, everything worked fine.
thank you so much for the time you have devoted to my problem!

**Comment by jbroadus** [comment]
Glad it's working, but this is probably something that should be handled more gracefully in the scan. Thanks for the additional information!
