### ISSUE TITLE
Distortion after unpausing when using Jack Audio server

### ISSUE THREAD

**Issue by MalkavianBilbao** [clementine-player/Clementine#6289]
### Before posting

Please follow the steps below and check the boxes with [x] once you did the step.

- [X] I checked the issue tracker for similar issues
- [X] I checked the [changelog](https://github.com/clementine-player/Clementine/blob/master/Changelog) if the issue is already resolved
- [X] I tried the latest Clementine build from [here](https://builds.clementine-player.org/)

### System information

Please provide information about your system and the version of Clementine used.

- Operating System: Linux Devuan Beowulf (testing)
- Clementine version: 1.3.1-558-g8dd5750 and last available Devuan/Debian one: 1.3.1+git609-g623a53681

### Expected behaviour / actual behaviour
When using Jack Audio server as output, after a long pause, when I unpause music sounds distorted. It is solved clicking in timebar or stopping the song and beginning it again, but happens again if you pause and after long time unpause again. Using ALSA doesn't happen. I don't use pulseaudio. Other programs haven't got that problem.

### Steps to reproduce the problem (only for bugs)
Uses Jack Audio server as output. Pause, wait 15 minutes (or more for being sure, maybe less is enough, I'm not sure). Unpause.

**Comment by tomachinz** [comment]
Define "distortion"? Are you able to sample this audio and check the waveform? Is the tempo the music affected (indicator buffering / time gaps be the cause, this will create square type high frequency crackling)? If the tempo and tuning is the same but the volume is different this would be less intense for quiet music does that sound OK? An audio recording may help.

**Comment by MalkavianBilbao** [comment]
Here you have recording of a part of a song with distortion after unpausing and without it. The recording has got microcuts, don't know why, but they don't happened through my speakers.

https://drive.google.com/drive/folders/10a3npoxjRZ1HPOSqKXS3Ej3run_mvXiy?usp=sharing

**Comment by tomachinz** [comment]
I see what you mean. I'd look into increasing your audio card driver buffer size. 
![image](https://user-images.githubusercontent.com/1026291/53310148-75324700-3910-11e9-814d-eac8a606e86e.png)
