### ISSUE TITLE
SoundCloud integration broken

### ISSUE THREAD

**Issue by hugodahl** [clementine-player/Clementine#6294]
### Before posting

Please follow the steps below and check the boxes with [x] once you did the step.

- [x] I checked the issue tracker for similar issues
- [x] I checked the [changelog](https://github.com/clementine-player/Clementine/blob/master/Changelog) if the issue is already resolved
- [x] I tried the latest Clementine build from [here](https://builds.clementine-player.org/)

### System information

Please provide information about your system and the version of Clementine used.

- Operating System: Windows 10.1809 Pro, x64, 
- Clementine version: 1.3.1

### Expected behaviour / actual behaviour
Clicking **Login** to SoundCloud should bring up a SoundCloud login/OAuth page in a browser, but instead, shows a page with the following message:
`invalid_client: The client identifier provided is invalid.`

### Steps to reproduce the problem (only for bugs)
1. Start Clementine
2. Go to Options (**Tools**->**Preferences** or <kbd>Ctrl</kbd>+<kbd>P</kbd>)
3. Click **SoundCloud** in the **Internet Providers** section
4. Click **Login**
5. View opened browser page

**Comment by paperbagcorner** [comment]
Soundcloud is not open to api registration, see issues #5766, #5538. The support for it has therefore been removed in https://github.com/clementine-player/Clementine/commit/551158.

**Comment by b1tninja** [comment]
Can we add a UI / config somewhere to set the client id and secret? Not that anyone would go find some client id / secret by searching github... but some of us might already have api keys

**Comment by hatstand** [comment]
You can change them in the source and recompile if you really want.

**Comment by JulianVolodia** [comment]
@hugodahl @b1tninja what could be done for you? Tell in #5766 if have any constructive thoughts.
