### ISSUE TITLE
Buildbot and website Latest developer builds is down

### ISSUE THREAD

**Issue by nfriese** [clementine-player/Clementine#6307]
- [X] I tried the latest Clementine build from [here](https://builds.clementine-player.org/)

Error:
503 Service Unavailable

The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.

**Comment by ispmarin** [comment]
Same behavior here.

**Comment by hatstand** [comment]
It's back.

**Comment by nfriese** [comment]
Sorry
the buildbot and the website Latest developer builds are again down.
Please restart.

Thanks
