### ISSUE TITLE
Clementine has been forked - and will probably survive as Strawberry

### ISSUE THREAD

**Issue by desputinski** [clementine-player/Clementine#6325]
Hi,
as development for Clementine seems to be stagnating (which is sad), there is a new project as a clone of Clementine on the horizon:
https://github.com/jonaski/strawberry

best regards
desputin

**Comment by sylvainsab** [comment]
I confirm this. I reckon qualified people who would like to help this music player to survive should help and join the continued/up-to-date project.

**Comment by sylvainsab** [comment]
I confirm this. I reckon qualified people who would like to help this music player to survive should help and join [the continued up-to-date project](https://github.com/jonaski/strawberry/).

**Comment by ErebosGR** [comment]
But Strawberry doesn't have an Android remote app, does it?
That's the only reason I use Clementine.

**Comment by sylvainsab** [comment]
I remember something along those lines.
I now use KDEconnect.

**Comment by trougnouf** [comment]
Also lacking dynamic playlist, saving statistics to file, and automatic scoring, so all the features that I use Clementine for.

**Comment by sylvainsab** [comment]
You can open this as an issue in the "newer" software if you want.

Anyway, I people's choices are theirs, as for me I've never been a fan of "forks", I tend to see them as a main factor in the dissipation of worthwhile efforts...

**Comment by a17r** [comment]
I don't understand why they decided to fork it from a state in 2013.

**Comment by gianlucapettinello** [comment]
I see that clementine git is updated regularly so no death. Or at least resurrection :)

**Comment by desputinski** [comment]
Hm, but I wonder why, if a programmer puts time and efforts into clementine nobody is pushing for a new release. That seems a bit strange and uncoordinated...

**Comment by a17r** [comment]
@desputinski See also https://github.com/clementine-player/Clementine/issues/3463 for reference.

In absence of a Qt5-based release, distros are forced to either drop Clementine or package a snapshot. At this point, most are probably doing the latter.

**Comment by rmpbklyn** [comment]
> I see that clementine git is updated regularly so no death. Or at least resurrection :)

but the latest release shows 1.3.1,  where you see newer?

**Comment by JulianVolodia** [comment]
Dear Contributors, @jonaski and @hatstand, @hatstand and @jonaski (and all other) what's up? What are your preferences and what are your long term plans for this project if could be said so.

Best!

**Comment by hatstand** [comment]
Getting Windows, Linux and mac qt5 builds running on CircleCI would put us in a good position to actually have releases again as it removes the burden of manual work involved. I think only windows is blocking that right now but I haven't had time to sort out its issues.

**Comment by JulianVolodia** [comment]
@hatstand thanks for quick respond!

**Comment by rodneyrod** [comment]
New version is out, this can be closed.

**Comment by JulianVolodia** [comment]
Hi @desputinski could you close issue?

**Comment by JulianVolodia** [comment]
hi @desputinski thanks
