### ISSUE TITLE
Artist Info not displayed

### ISSUE THREAD

**Issue by tla2k12** [clementine-player/Clementine#6327]
### Before posting

Please follow the steps below and check the boxes with [x] once you did the step.

- [x] I checked the issue tracker for similar issues
- [x] I checked the [changelog](https://github.com/clementine-player/Clementine/blob/master/Changelog) if the issue is already resolved
- [x] I tried the latest Clementine build from [here](https://builds.clementine-player.org/)

### System information

Please provide information about your system and the version of Clementine used.

- Operating System: Fedora release 29 (Twenty Nine) Linux 5.0.5-200.fc29.x86_64 #1 SMP Wed Mar 27 20:58:04 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- Clementine version: 1.3.1-580-g641ab64cc

### Expected behaviour / actual behaviour
Expected: When playing a track, selecting "Artist Info" in the left pane should display information on the artist currently playing.
Actual: Nothing is displayed in the left pane when "Artist Info" is selected

### Steps to reproduce the problem (only for bugs)

The console output (when starting clementine from the command line) displays the following when selecting "Artist Info" (not sure if the JSON errors are related or not):
15:20:42.468 DEBUG ArtistBiography:65               Biography url:   QUrl( "https://data.clementine-player.org/fetchbio?artist=Kristin Hersh&lang=en" )  
15:20:43.980 ERROR unknown                          JSonScanner::yylex - error while reading from io device  
15:20:43.980 ERROR unknown                          json_parser - syntax error found,  forcing abort, Line 1 Column 1  
15:20:43.987 ERROR unknown                          JSonScanner::yylex - error while reading from io device  
15:20:43.987 ERROR unknown                          json_parser - syntax error found,  forcing abort, Line 1 Column 1  
15:21:07.471 INFO  SongInfoFetcher:102              Request timed out from info provider "ArtistBiography" 

Opening the Biography URL above manually in chrome returns:
{"stackTrace": [["/var/task/fetch_bio.py", 45, "fetch_bio", "return result['detailedDescription']"]], "errorType": "KeyError", "errorMessage": "'detailedDescription'"}

**Comment by hatstand** [comment]
Looks like Google is no longer returning 'detailedDescription' from the KG API: https://developers.google.com/knowledge-graph/reference/rest/v1/ even though it should.

**Comment by tla2k12** [comment]
Calling the API manually via the Google link you provided seems to return data.  Perhaps Clementine is not calling with the API with the correct arguments?

![Google API](https://user-images.githubusercontent.com/1469425/55868297-16e9bc80-5b7c-11e9-97c2-bf943cc73270.png)

**Comment by hatstand** [comment]
It's returning incomplete data

**Comment by anonvoy** [comment]
It's working again for me, using version 1.3.1.git20190416 on OpenSUSE 15.0.

**Comment by zezinho42** [comment]
Looks like this problem is back : https://data.clementine-player.org/fetchbio?artist=Led Zeppelin&lang=pt returns a "KeyError"
