### ISSUE TITLE
Complete tags automatically causes crash

### ISSUE THREAD

**Issue by alongdecline** [clementine-player/Clementine#6333]
### Before posting

Please follow the steps below and check the boxes with [x] once you did the step.

- [x] I checked the issue tracker for similar issues
- [x] I checked the [changelog](https://github.com/clementine-player/Clementine/blob/master/Changelog) if the issue is already resolved
- [x] I tried the latest Clementine build from [here](https://builds.clementine-player.org/)

### System information

Please provide information about your system and the version of Clementine used.

- Operating System: Pop!_OS 19.4
- Clementine version: 1.3.1

### Expected behaviour / actual behaviour
The ability to fetch tags is a great aspect of Clementine, but since updated my operating system, Clementine crashes and shuts down immediately when I try to "Complete tags automatically..."

This happens every screen; playlist, library, track editing.

**Comment by gianlucapettinello** [comment]
Same issue for me. Is there a way we can bisect the problem?

**Comment by gianlucapettinello** [comment]
Jonaski patch fixes the issue! Great man
