### ISSUE TITLE
segmentation fault  when playing track arch linux

### ISSUE THREAD

**Issue by Yanpas** [clementine-player/Clementine#6337]
### Before posting

Please follow the steps below and check the boxes with [x] once you did the step.

- [ x] I checked the issue tracker for similar issues
- [ x] I checked the [changelog](https://github.com/clementine-player/Clementine/blob/master/Changelog) if the issue is already resolved
- [ x] I tried the latest Clementine build from [here](https://builds.clementine-player.org/)

### System information

Please provide information about your system and the version of Clementine used.

- Operating System: arch linux
- Clementine version: 1.3.1

### Steps to reproduce the problem (only for bugs)
1. Select the track attached
[b.zip](https://github.com/clementine-player/Clementine/files/3115613/b.zip)

2. Press play
3. crash

bt:
```
Thread 22 "id3demux0:sink" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffa1ffb700 (LWP 473)]
0x00007ffff6811e5c in gst_date_time_new () from /usr/lib/libgstreamer-1.0.so.0
(gdb) bt
#0  0x00007ffff6811e5c in gst_date_time_new () at /usr/lib/libgstreamer-1.0.so.0
#1  0x00007ffff73b8f29 in gst_tag_list_new_from_id3v1 () at /usr/lib/libgsttag-1.0.so.0
#2  0x00007fffe21bb46f in  () at /usr/lib/gstreamer-1.0/libgstid3demux.so
#3  0x00007ffff73a0e44 in  () at /usr/lib/libgsttag-1.0.so.0
#4  0x00007ffff73a1bb5 in  () at /usr/lib/libgsttag-1.0.so.0
#5  0x00007ffff67c91d3 in  () at /usr/lib/libgstreamer-1.0.so.0
#6  0x00007ffff6940cc6 in  () at /usr/lib/libglib-2.0.so.0
#7  0x00007ffff6947c21 in  () at /usr/lib/libglib-2.0.so.0
#8  0x00007ffff6b2ba92 in start_thread () at /usr/lib/libpthread.so.0
#9  0x00007ffff45c2cd3 in clone () at /usr/lib/libc.so.6
```

**Comment by 83bytes** [comment]
I have the same issue. the exact same back-trace too. 
I ran a "auto update tag" thing..
I think that must've messed something up ?

**Comment by Yanpas** [comment]
Not sure, I've tried to remove .config/Clementine/*.db and .cache/Clementine - still crashes

**Comment by Yanpas** [comment]
Maybe it's due to [recent gstreamer update](https://www.archlinux.org/packages/extra/x86_64/gstreamer/), don't know.

Anyway here is a place after which progrem crashes:
![image](https://user-images.githubusercontent.com/7345761/56770245-1c6e1600-67bc-11e9-904e-2fb07f9a5aec.png)

**Comment by Yanpas** [comment]
Gstreamer issue
https://gitlab.freedesktop.org/gstreamer/gstreamer/issues/384

**Comment by Yanpas** [comment]
Fixed is gstreamer master.

Arch issue https://bugs.archlinux.org/task/62490
