### ISSUE TITLE
Cannot rate tracks outside of library folder

### ISSUE THREAD

**Issue by AllKind** [clementine-player/Clementine#6341]
### Before posting

Please follow the steps below and check the boxes with [x] once you did the step.

- [x] I checked the issue tracker for similar issues
- [x] I checked the [changelog](https://github.com/clementine-player/Clementine/blob/master/Changelog) if the issue is already resolved
- [x] I tried the latest Clementine build from [here](https://builds.clementine-player.org/)

### System information

Please provide information about your system and the version of Clementine used.

- Operating System: Linux Mint 19.1 Cinnamon
- Clementine version: Version 1.3.1-591-gb11316ff0

### Expected behaviour / actual behaviour

Adding files which are outside of the path of the music library to a playlist, all their tags can be edited, but rating them is not possible. Observing this behavious since I started using clementine as of version 1.3.

Best regards,
Allkind

**Comment by aicouto** [comment]
i had the same problem on the same system. [possible solution here](https://github.com/clementine-player/Clementine/issues/5635#issuecomment-491410175).

**Comment by AllKind** [comment]
@aicouto Sorry that didn't help... And purging and re-installing isn't really a good solution.

**Comment by aicouto** [comment]
@AllKind as I said, I solved THE SAME PROBLEM on THE SAME PLATFORM doing this. if you are behind the source of the problem this is not my problem.

MP3 files use ID3 while Flac files use Vorbis. as I only use MP3 I have no idea how Clementine writes Flac files.

I use the [kid3](https://community.linuxmint.com/software/view/kid3-qt) program to save file metadata, I use Clementine just to record comments and play data automatically.

**Comment by hatstand** [comment]
Clementine supports playing files from outside the library out of convenience but it's not really how it's intended to be used. If you want ratings, use the library.
