### ISSUE TITLE
Music stuttering after pausing

### ISSUE THREAD

**Issue by DrLoutr** [clementine-player/Clementine#6358]
When i unpause a track (while being connected to a bluetooth speaker) it starts stuttering until the very end of the track or until i decide to play the next or previous track. Happened to me on mp3 tracks.
Specs: Ubuntu 19.04, 
            Matebook X Pro, 
            No additional software installed other than 19.04 standard

**Comment by JohnnyDoorn** [comment]
Same here on Manjaro. For now I just made a keyboard shortcut to skip the song a couple of seconds, which also seems to fix the problem. I'm not sure if this is a clementine issue or related to pulseaudio.

**Comment by jonaski** [comment]
Possible the same as https://github.com/clementine-player/Clementine/issues/6320
I've also experienced stuttering after unpausing when you use queue2 for the probe queue.

**Comment by Iridias** [comment]
Same for me. Only happens in Clementine.
Other players do not suffer from this issue.

Spec: Clementine 1.3.1, PulseAudio 12.2 on ArchLinux, Bose QC35

**Comment by Mrcuve0** [comment]
It could be related to PulseAudio instead of Clementine itself.

Try this solution I found [in the archWiki's troubleshooting section](https://wiki.archlinux.org/index.php/PulseAudio/Troubleshooting#Pops_when_starting_and_stopping_playback).

I followed the second solution, the one proposed as "better solution", restarted pulseaudio using `systemctl restart --user pulseaudio.service` and, for now, the issue seems disappeared.

It's strange however, if the problem is PulseAudio related, why the bug seems affecting only Clementine?

**Comment by mbarchein** [comment]
Same problem on Debian 10 with bluetooth headset. Changing the track or seeking in the current track solves the problem. Also, this only happens after a "long" pause (more than 30-60 seconds of audio paused). Sometimes after unpausing audio doesn't start instead of the stuttering problem.

**Comment by JulianVolodia** [comment]
@mbarchein I understand that you don't see issue on any other player and using wired device problem isn't exists?

Are you testing against current version? Could you test against bleeding-edge?

Best, and always appreciate support.

**Comment by Mrcuve0** [comment]
I just re-experienced the bug, here's the scenario:

1) I paused last song of the album (also last song of the playing queue) Please note the "Loop all" in enabled.
2) I waited quite some time, maybe 10 minutes
3) I unpaused the song using my keyboard media-buttons and the crackling/stuttering bug appeared
4) I decided to let roll the last few seconds of the song and see if the first song would be played normally.
5) The first song has been played but the crackling continues
6) Now, I decided to pause this new song, using again the dedicated button in keyboard --> The song pauses
7) Finally, if I try to resume the song this time the procedure fails: the song is still paused no matter how many times I press play on the keyboard (also tried with the GUI button, same behavior)
8) Moving anywhere in the track with my mouse let the song resume.

Hope this scenario helps. To me, it seems it's definitely related to Clementine itself (points 7 and 8 make me tell so), maybe DBus related or something related to the playing stream itself? (like issue #6320 seems to pinpoint)
