### ISSUE TITLE
Clementine fails to load - Multiple address sanitizer / memory leak errors

### ISSUE THREAD

**Issue by CommonOddity** [clementine-player/Clementine#6366]
### Before posting

Please follow the steps below and check the boxes with [x] once you did the step.

- [x] I checked the issue tracker for similar issues
**The only one that comes close is https://github.com/clementine-player/Clementine/issues/6365
However there is no mention of Clementine crashing**
- [x] I checked the [changelog](https://github.com/clementine-player/Clementine/blob/master/Changelog) if the issue is already resolved
**Doesn't appear to be relevant - couldn't find anything recent**
- [x] I tried the latest Clementine build from [here](https://builds.clementine-player.org/)
**Latest OpenSuSE Tumbleweed build from repo**

### System information

Please provide information about your system and the version of Clementine used.

- Operating System:

**OpenSuSE Tumbleweed (latest packages, zypper dup'd and up'd)**

- Clementine version: 

Information for package clementine:
-----------------------------------
Repository     : openSUSE-Tumbleweed-Oss              
Name           : clementine                           
Version        : 1.3.1+git20190423-2.2                
Arch           : x86_64                               
Vendor         : openSUSE                             
Installed Size : 37.9 MiB                             
Installed      : Yes                                  
Status         : up-to-date                           
Source package : clementine-1.3.1+git20190423-2.2.src 

### Expected behaviour / actual behaviour
Expected behavior:
- Start Clementine
- Bring up the Clementine window to start using it
Actual behavior:
- Start Clementine
- Bring up the Clementine window to start using it
- Window appears for maybe ~ 1 - 2 seconds
- Clementine immediately crashes

### Steps to reproduce the problem (only for bugs)
- Start Clementine
- Bring up the Clementine window to start using it

### Notes / addenda

[clementinelogs.txt](https://github.com/clementine-player/Clementine/files/3357430/clementinelogs.txt)

I've uploaded the --verbose logs from when the crash happens. I don't see anything happening in the kernel ring buffer.

I have another rig downstairs also running OpenSuSE Tumbleweed. I am going to perform a zypper dup/up to bring all the packages up to snuff and then I'll see if I can recreate the issue there.

Let me know if you require anything else from me to help investigate.

**Comment by CommonOddity** [comment]
Dug a little deeper.

Seeing https://bugzilla.opensuse.org/show_bug.cgi?id=1137785 was created. Someone else is reporting something similar.

Going to poke around some more. This might be related to the OpenSuSE Tumbleweed version only, and with very specific configuration details.

This might be indeed related to the tag reader and the option to save tag info on the fly.

**Comment by CommonOddity** [comment]
Update: It appears that a patch was deployed by David Plater in his home repo for Tumbleweed (clementine-1.3.1+git20190713-148.1, and a later version, clementine-1.3.1+git20190713-154.1) that fixed the issue.

It's got something to do with a Window re-sizing memory leak, if I understood correctly.

**Comment by plater** [comment]
The memory leaks are wip in https://bugzilla.suse.com/show_bug.cgi?id=1141444 I've still got to create a matching github issue.  The sanitize=address flag has been dropped and the current Tumbleweed clementine has some memory leaks fixed but the home:plater one has a lot more. You shold close this bug.

**Comment by CommonOddity** [comment]
Closing issue accordingly.
