### ISSUE TITLE
Download page mention Ubuntu 12.04 (EOL), without ubuntu 18.04

### ISSUE THREAD

**Issue by matkoniecz** [clementine-player/Clementine#6369]
### Before posting

Please follow the steps below and check the boxes with [x] once you did the step.

- [x] I checked the issue tracker for similar issues
- [x] I checked the [changelog](https://github.com/clementine-player/Clementine/blob/master/Changelog) if the issue is already resolved
- [x] I tried the latest Clementine build from [here](https://builds.clementine-player.org/) (not applicable)

### System information

Please provide information about your system and the version of Clementine used.

- Operating System: Ubuntu 18.04
- Clementine version: not applicable

### Expected behaviour / actual behaviour
EOL versions are not mentioned on the website, active versions are

### Steps to reproduce the problem (only for bugs)
Open https://www.clementine-player.org/downloads

**Comment by fitojb** [comment]
Issues with the site should be reported at https://github.com/clementine-player/Website

**Comment by matkoniecz** [comment]
Thanks, moved https://github.com/clementine-player/Website/issues/9
