### ISSUE TITLE
Support for ogg tracks with multiple genre tags

### ISSUE THREAD

**Issue by Clementine-Issue-Importer** [clementine-player/Clementine#637]
_From [lukanovsak](https://code.google.com/u/115301340821795566339/) on August 17, 2010 18:11:56_

Ogg vorbis comments support multiple genre tags.

Clementine should also support this in the library, when it is sorted by genre. That is, such a track, tagged with, let's say, "Jazz" and "Country", should be found in both those genres.

_Original issue: http://code.google.com/p/clementine-player/issues/detail?id=637_

**Comment by Chocobozzz** [comment]
Duplicate of https://github.com/clementine-player/Clementine/issues/409
