### ISSUE TITLE
[crash]crash on mac 10.14.6

### ISSUE THREAD

**Issue by jeffery9** [clementine-player/Clementine#6381]
### Before posting

Please follow the steps below and check the boxes with [x] once you did the step.

- [x] I checked the issue tracker for similar issues
- [x] I checked the [changelog](https://github.com/clementine-player/Clementine/blob/master/Changelog) if the issue is already resolved
- [x] I tried the latest Clementine build from [here](https://builds.clementine-player.org/)

### System information

Please provide information about your system and the version of Clementine used.

- Operating System:  mac 10.14.6
- Clementine version:  1.3.1

**Comment by joequincy** [comment]
I also experience an immediate hard crash on launch with the current release version (1.3.1) under OSX 10.14.6 (the OS detects the crash and presents a debug log, which sadly is no longer in my clipboard).

However the `clementine-1.3.1-611-gda04471.dmg` build ([here](https://builds.clementine-player.org/mac/clementine-1.3.1-611-gda04471.dmg)) from 09-Jul-2019 is launching fine and I have not experienced any issues with it so far.

**Comment by devzsolt** [comment]
@joequincy thanks for the tip, this specific build indeed works, the latest 1.3.1 from brew crashes

**Comment by kiv57** [comment]
I just switched from itunes to clementine, same behaviour as described. I confirm the build described by @joequincy works fine.

**Comment by JulianVolodia** [comment]
Dear @kiv57 , @devzsolt , @joequincy and @jeffery9 ,

from some time (like a 2 weeks?) there is freshly baked DMGs artifacts for you available on the top of https://builds.clementine-player.org/mac/
Latest is ._clementine-1.3.1-944-g1e28f4e7d.dmg

Please recheck and respond if you still reproduce the issue.

**Comment by kiv57** [comment]
Hi,
Last build (clementine-1.3.1-959-g672b90659.dmg) works fine.
Sorry for the delay!

I'll try to do some other tests on my (little) free time. Thank you for your work!
