### ISSUE TITLE
Clementine not available for Raspbian Buster

### ISSUE THREAD

**Issue by Lonerider2010** [clementine-player/Clementine#6389]
Searched for Clementine to run on Raspbian Buster on a Raspberry Pi 4B.
Did not find it on [https://builds.clementine-player.org/](https://builds.clementine-player.org/), not on
[Debian package search](https://packages.debian.org/search?suite=default&section=all&arch=any&searchon=names&keywords=clementine), here armhf is missing. 
So I tried to compile it myself according to [Clementine on Raspberry Pi](https://github.com/clementine-player/Clementine/wiki/Clementine-on-Raspberry-Pi), but that failed, maybe because the libs have changed in Raspbian Buster.
So how can I get Clementine running on the Raspberry Pi 4B with Raspbian Buster?

**Comment by alwayslivid** [comment]
Tried to compile the past 3 releases (as of the time of this writing) up to no avail.

**Comment by hatstand** [comment]
https://builds.clementine-player.org/debian-buster/
