### ISSUE TITLE
Win32: Current builds (that come with the installer) crash at startup

### ISSUE THREAD

**Issue by cmorty** [clementine-player/Clementine#6394]
### Before posting

Please follow the steps below and check the boxes with [x] once you did the step.

- [x] I checked the issue tracker for similar issues
- [x] I checked the [changelog](https://github.com/clementine-player/Clementine/blob/master/Changelog) if the issue is already resolved
- [x] I tried the latest Clementine build from [here](https://builds.clementine-player.org/)

### System information

Please provide information about your system and the version of Clementine used.

- Operating System: Windows 10 
- Clementine version: 1.3.1-565 and  1.3.1-564

### Expected behaviour 
Application starts

### actual behaviour
During initialization (after loading libffi-6.dll) I get a window that the application coulndn't be started (0xc000007b)

1.3.1-388 seems to be working fine.

I also tried to use the debug builds, but those seem to have issues finding QT libs.

**Comment by hatstand** [comment]
Should be fixed in https://builds.clementine-player.org/windows/
