### ISSUE TITLE
After compiling from source clementine crashes with seg fault

### ISSUE THREAD

**Issue by poldi171254** [clementine-player/Clementine#6395]
I'm on the latest version of Ubuntu Desktop and after following the Wiki on how to compile from source I get the following error.
There were no issues during the cmake and/or make steps

`17:39:08.746 INFO  main:328                         Clementine 1.3.1-625-gb423808dd 
17:39:09.052 INFO  logging:63                       Failed to load module "canberra-gtk-module" 
17:39:09.116 DEBUG logging:67                       _g_io_module_get_default: Found default implementation gvfs (GDaemonVfs) for â 
17:39:09.195 WARN  unknown                          QSslSocket: cannot resolve CRYPTO_num_locks 
17:39:09.195 WARN  unknown                          QSslSocket: cannot resolve CRYPTO_set_id_callback 
17:39:09.195 WARN  unknown                          QSslSocket: cannot resolve CRYPTO_set_locking_callback 
17:39:09.195 WARN  unknown                          QSslSocket: cannot resolve sk_free 
17:39:09.195 WARN  unknown                          QSslSocket: cannot resolve sk_num 
17:39:09.195 WARN  unknown                          QSslSocket: cannot resolve sk_pop_free 
17:39:09.195 WARN  unknown                          QSslSocket: cannot resolve sk_value 
17:39:09.195 WARN  unknown                          QSslSocket: cannot resolve SSL_library_init 
17:39:09.195 WARN  unknown                          QSslSocket: cannot resolve SSL_load_error_strings 
17:39:09.195 WARN  unknown                          QSslSocket: cannot resolve SSLv3_client_method 
17:39:09.195 WARN  unknown                          QSslSocket: cannot resolve SSLv23_client_method 
17:39:09.195 WARN  unknown                          QSslSocket: cannot resolve SSLv3_server_method 
17:39:09.195 WARN  unknown                          QSslSocket: cannot resolve SSLv23_server_method 
17:39:09.195 WARN  unknown                          QSslSocket: cannot resolve X509_STORE_CTX_get_chain 
17:39:09.195 WARN  unknown                          QSslSocket: cannot resolve OPENSSL_add_all_algorithms_noconf 
17:39:09.195 WARN  unknown                          QSslSocket: cannot resolve OPENSSL_add_all_algorithms_conf 
17:39:09.195 WARN  unknown                          QSslSocket: cannot resolve SSLeay 
17:39:09.195 WARN  unknown                          QSslSocket: cannot call unresolved function CRYPTO_num_locks 
17:39:09.195 WARN  unknown                          QSslSocket: cannot call unresolved function CRYPTO_set_id_callback 
17:39:09.195 WARN  unknown                          QSslSocket: cannot call unresolved function CRYPTO_set_locking_callback 
17:39:09.195 WARN  unknown                          QSslSocket: cannot call unresolved function SSL_library_init 
17:39:09.196 WARN  unknown                          QSslSocket: cannot call unresolved function SSLv23_client_method 
17:39:09.196 WARN  unknown                          QSslSocket: cannot call unresolved function sk_num 
Segmentation fault (core dumped)`

**Comment by jonaski** [comment]
This isn't a Clementine problem, you don't have the correct version of openssl that Qt needs.

**Comment by poldi171254** [comment]
Thanks for the quick reply
This is the output from cmake; no errors reported as far as I can tell
[cmakeout.txt](https://github.com/clementine-player/Clementine/files/3553304/cmakeout.txt)

**Comment by poldi171254** [comment]
Thanks for the quick reply
This is the output from cmake; no errors reported as far as I can tell
[cmakeout.txt](https://github.com/clementine-player/Clementine/files/3553304/cmakeout.txt)

**Comment by poldi171254** [comment]
Found a workaround here [https://github.com/rvm/rvm/issues/4680](url).

Add 
`deb http://security.ubuntu.com/ubuntu bionic-security main` to the end of /etc/apt/sources.list
Update repos
Uninstall libssl-dev
Install libssl1.0-dev
Build clementine

Works for me
