### ISSUE TITLE
Buildbot's grid not accesible (err no 503)

### ISSUE THREAD

**Issue by JulianVolodia** [clementine-player/Clementine#6402]
Grid at http://buildbot.clementine-player.org/grid is not accessible.

Dear @hatstand is it possible to get access to and have reference documentation about building process for different distros versions?

I indeed want to see configuration of these.
Best regards.

**Comment by hatstand** [comment]
See the buildbot and Dependencies repos

**Comment by JulianVolodia** [comment]
Thanks, sorry.
