### ISSUE TITLE
Edit smart playlist - crash

### ISSUE THREAD

**Issue by Tomaqa** [clementine-player/Clementine#6434]
- [x] I checked the issue tracker for similar issues
- [x] I checked the [changelog](https://github.com/clementine-player/Clementine/blob/master/Changelog) if the issue is already resolved
- [x] I tried the latest Clementine build from [here](https://builds.clementine-player.org/)

### System information

Please provide information about your system and the version of Clementine used.

- Operating System: Arch Linux, GNU/Linux 4.19.60-1-lts
- Clementine version: clementine-qt5-git 1.3.1.r846.g668dd3a9d-1

### Steps to reproduce the problem (only for bugs)

Edit any smart playlist and click on 'Cancel' rightaway. Then do it once again - crash.

### Debug info

stderr:
```
Thu 07 Nov 2019 11:07:38 PM CET
23:07:38.094 INFO  main:319                         Clementine-qt5 1.3.1-846-g668dd3a9d
23:07:38.225 DEBUG NetworkProxyFactory:49           Detected system proxy URLs: ("", "", "", "")
23:07:38.225 DEBUG WorkerPool<HandlerType>:281      Starting worker 0x7fa41a7fb710 "/usr/bin/clementine-tagreader" "/tmp/clementine_1779196207"
23:07:38.229 DEBUG WorkerPool<HandlerType>:281      Starting worker 0x7fa41a7fb710 "/usr/bin/clementine-tagreader" "/tmp/clementine_1626245698"
23:07:38.232 DEBUG WorkerPool<HandlerType>:281      Starting worker 0x7fa41a7fb710 "/usr/bin/clementine-tagreader" "/tmp/clementine_653640422"
23:07:38.235 DEBUG WorkerPool<HandlerType>:281      Starting worker 0x7fa41a7fb710 "/usr/bin/clementine-tagreader" "/tmp/clementine_405572829"
23:07:38.238 DEBUG WorkerPool<HandlerType>:281      Starting worker 0x7fa41a7fb710 "/usr/bin/clementine-tagreader" "/tmp/clementine_300492113"
23:07:38.244 INFO  main:48                          TagReader worker connecting to "/tmp/clementine_1779196207"
23:07:38.246 INFO  main:48                          TagReader worker connecting to "/tmp/clementine_653640422"
23:07:38.247 INFO  main:48                          TagReader worker connecting to "/tmp/clementine_1626245698"
23:07:38.251 INFO  main:48                          TagReader worker connecting to "/tmp/clementine_405572829"
23:07:38.302 DEBUG WorkerPool<HandlerType>:281      Starting worker 0x7fa41a7fb710 "/usr/bin/clementine-tagreader" "/tmp/clementine_1917525123"
23:07:38.303 DEBUG WorkerPool<HandlerType>:281      Starting worker 0x7fa41a7fb710 "/usr/bin/clementine-tagreader" "/tmp/clementine_736520177"
23:07:38.304 DEBUG WorkerPool<HandlerType>:281      Starting worker 0x7fa41a7fb710 "/usr/bin/clementine-tagreader" "/tmp/clementine_1492987385"
23:07:38.306 DEBUG WorkerPool<HandlerType>:301      Worker 0x7fa404005f20 connected to "/tmp/clementine_1779196207"
23:07:38.306 DEBUG WorkerPool<HandlerType>:301      Worker 0x7fa404006840 connected to "/tmp/clementine_1626245698"
23:07:38.306 DEBUG WorkerPool<HandlerType>:301      Worker 0x7fa404004ee0 connected to "/tmp/clementine_653640422"
23:07:38.306 DEBUG WorkerPool<HandlerType>:301      Worker 0x7fa404009680 connected to "/tmp/clementine_405572829"
23:07:38.312 INFO  main:48                          TagReader worker connecting to "/tmp/clementine_300492113"
23:07:38.312 DEBUG WorkerPool<HandlerType>:301      Worker 0x7fa40400a990 connected to "/tmp/clementine_300492113"
23:07:38.316 INFO  main:48                          TagReader worker connecting to "/tmp/clementine_1917525123"
23:07:38.317 DEBUG WorkerPool<HandlerType>:301      Worker 0x7fa40400bc70 connected to "/tmp/clementine_1917525123"
23:07:38.317 INFO  main:48                          TagReader worker connecting to "/tmp/clementine_736520177"
23:07:38.318 DEBUG WorkerPool<HandlerType>:301      Worker 0x7fa40400cf80 connected to "/tmp/clementine_736520177"
23:07:38.319 INFO  main:48                          TagReader worker connecting to "/tmp/clementine_1492987385"
23:07:38.319 DEBUG WorkerPool<HandlerType>:301      Worker 0x7fa40400e450 connected to "/tmp/clementine_1492987385"
23:07:38.388 DEBUG QxtGlobalShortcutBackend:32      registering
23:07:38.614 DEBUG MainWindow:233                   Starting
__logging_message__23:07:38.823 WARN  unknown                          QCssParser::parseColorValue: Specified color without alpha value but alpha given: 'rgb 200, 200, 200, 75%'
__logging_message__23:07:38.999 WARN  unknown                          QCssParser::parseColorValue: Specified color without alpha value but alpha given: 'rgb 200, 200, 200, 75%'
23:07:39.002 DEBUG CoverProviders:35                Registered cover provider "MusicBrainz"
23:07:39.002 DEBUG CoverProviders:35                Registered cover provider "Discogs"
23:07:39.015 DEBUG MainWindow:313                   Initialising player
23:07:39.106 DEBUG MainWindow:319                   Creating models
23:07:39.241 INFO  Player:639                       Registered URL handler for "classicalradio"
23:07:39.242 DEBUG InternetModel:133                Adding internet service: "ClassicalRadio"
23:07:39.242 INFO  Player:639                       Registered URL handler for "di"
23:07:39.242 DEBUG InternetModel:133                Adding internet service: "DigitallyImported"
23:07:39.342 DEBUG InternetModel:133                Adding internet service: "Icecast"
23:07:39.352 DEBUG InternetModel:133                Adding internet service: "Jamendo"
23:07:39.354 INFO  Player:639                       Registered URL handler for "jazzradio"
23:07:39.354 DEBUG InternetModel:133                Adding internet service: "JazzRadio"
23:07:39.360 INFO  Player:639                       Registered URL handler for "magnatune"
23:07:39.362 DEBUG InternetModel:133                Adding internet service: "Magnatune"
23:07:39.369 DEBUG InternetModel:133                Adding internet service: "Podcasts"
23:07:39.370 INFO  Player:639                       Registered URL handler for "rockradio"
23:07:39.370 DEBUG InternetModel:133                Adding internet service: "RockRadio"
23:07:39.372 DEBUG InternetModel:133                Adding internet service: "SavedRadio"
23:07:39.372 INFO  Player:639                       Registered URL handler for "radiotunes"
23:07:39.372 DEBUG InternetModel:133                Adding internet service: "RadioTunes"
23:07:39.373 INFO  Player:639                       Registered URL handler for "somafm"
23:07:39.373 DEBUG InternetModel:133                Adding internet service: "SomaFM"
23:07:39.374 INFO  Player:639                       Registered URL handler for "intergalacticfm"
23:07:39.374 DEBUG InternetModel:133                Adding internet service: "Intergalactic FM"
23:07:39.381 DEBUG SpotifyService:108               Spotify system blob path: "/usr/bin/clementine-spotifyblob"
23:07:39.381 DEBUG SpotifyService:109               Spotify local blob path: "/home/tomaqa/.config/Clementine/spotifyblob/version16-64bit/blob"
23:07:39.382 DEBUG InternetModel:133                Adding internet service: "Spotify"
23:07:39.382 INFO  Player:639                       Registered URL handler for "subsonic"
23:07:39.500 DEBUG InternetModel:133                Adding internet service: "Subsonic"
23:07:39.688 DEBUG CddaLister:98                    No CD devices found
23:07:39.689 WARN  DeviceKitLister:55               Error enumerating DeviceKit-disks devices: "org.freedesktop.DBus.Error.ServiceUnknown" "The name org.freedesktop.UDisks was not provided by any .service files"
23:07:39.694 WARN  logging:60                       remote volume monitor with dbus name org.gtk.vfs.UDisks2VolumeMonitor is not supported
23:07:39.697 DEBUG logging:68                       _g_io_module_get_default: Found default implementation gvfs (GDaemonVfs) for ‘gio-vfs’
23:07:40.596 DEBUG MainWindow:337                   Creating UI
23:07:40.697 WARN  IconLoader:117                   Couldn't load icon "system-search"
23:07:40.697 WARN  IconLoader:117                   Couldn't load icon "system-search"
23:07:40.700 DEBUG MainWindow:895                   Creating equalizer
23:07:40.700 DEBUG MainWindow:924                   Creating now playing widget
23:07:40.716 DEBUG Playlist:173                     k_max_scrobble_point 240
23:07:40.719 DEBUG Playlist:173                     k_max_scrobble_point 240
23:07:40.720 DEBUG Playlist:173                     k_max_scrobble_point 240
23:07:40.721 DEBUG Playlist:173                     k_max_scrobble_point 240
23:07:40.725 DEBUG MainWindow:986                   Loading settings
23:07:40.728 INFO  NetworkRemote:87                 Starting network remote
23:07:40.728 INFO  NetworkRemote:95                 Listening on port  5500
23:07:40.730 WARN  {anonymous}:36                   Failed to create Avahi entry group: QDBusError("org.freedesktop.systemd1.NoSuchUnit", "Unit dbus-org.freedesktop.Avahi.service not found.")
23:07:40.730 INFO  {anonymous}:38                   This might be because 'disable-user-service-publishing' is set to 'yes' in avahi-daemon.conf
__logging_message__23:07:40.888 WARN  unknown                          QColor::fromHsv: HSV parameters out of range
23:07:40.898 DEBUG MainWindow:2212                  command line options received
23:07:40.898 DEBUG MainWindow:2293                  false
23:07:40.898 DEBUG MainWindow:1074                  Started
23:07:40.987 INFO  DeviceManager:172                Device added from database:  "DVD RW AD-7580S "
23:07:40.988 INFO  DeviceManager:172                Device added from database:  "XIAOMI"
23:07:40.988 INFO  DeviceManager:172                Device added from database:  "MI 3W"
23:07:40.988 INFO  DeviceManager:355                Device added: "Gio//ext3/ext4/113607307264"
23:07:40.989 WARN  IconLoader:48                    Icon name is null
23:07:40.989 WARN  IconLoader:48                    Icon name is null
23:07:40.989 WARN  IconLoader:48                    Icon name is null
23:07:40.989 INFO  DeviceManager:355                Device added: "Gio//msdos/535805952"
23:07:40.989 WARN  IconLoader:48                    Icon name is null
23:07:40.989 WARN  IconLoader:48                    Icon name is null
23:07:40.989 WARN  IconLoader:48                    Icon name is null
23:07:40.990 INFO  DeviceManager:355                Device added: "Gio//ext3/ext4/303293988864"
23:07:40.990 WARN  IconLoader:48                    Icon name is null
23:07:40.990 WARN  IconLoader:48                    Icon name is null
23:07:40.990 WARN  IconLoader:48                    Icon name is null
23:07:40.991 INFO  DeviceManager:355                Device added: "Gio/unmounted/140341881777280"
23:07:40.991 WARN  IconLoader:48                    Icon name is null
23:07:40.992 INFO  DeviceManager:355                Device added: "Gio/unmounted/140341881777168"
23:07:40.992 WARN  IconLoader:48                    Icon name is null
23:07:40.992 INFO  DeviceManager:355                Device added: "Gio/unmounted/140341680300816"
23:07:40.993 WARN  IconLoader:48                    Icon name is null
23:07:40.993 INFO  DeviceManager:355                Device added: "Gio/unmounted/140341680300704"
23:07:40.993 WARN  IconLoader:48                    Icon name is null
23:07:40.994 INFO  DeviceManager:355                Device added: "Gio//ext3/ext4/498953179136"
23:07:40.994 WARN  IconLoader:48                    Icon name is null
23:07:40.994 WARN  IconLoader:48                    Icon name is null
23:07:40.994 WARN  IconLoader:48                    Icon name is null
23:07:40.995 INFO  DeviceManager:355                Device added: "Gio//ext3/ext4/57072283648"
23:07:40.995 WARN  IconLoader:48                    Icon name is null
23:07:40.995 WARN  IconLoader:48                    Icon name is null
23:07:40.995 WARN  IconLoader:48                    Icon name is null
23:07:41.105 DEBUG PlaylistBackend:292              Saving playlist 139
23:07:41.117 DEBUG PlaylistBackend:292              Saving playlist 138
23:07:41.335 DEBUG PlaylistBackend:292              Saving playlist 137
23:07:41.788 DEBUG PlaylistBackend:292              Saving playlist 136
23:07:45.239 WARN  IconLoader:117                   Couldn't load icon "system-search"
__logging_message__23:07:47.140 WARN  unknown                          QCssParser::parseColorValue: Specified color without alpha value but alpha given: 'rgb 200, 200, 200, 75%'
__logging_message__23:07:47.167 WARN  unknown                          QCssParser::parseColorValue: Specified color without alpha value but alpha given: 'rgb 200, 200, 200, 75%'
23:07:47.168 DEBUG Playlist:173                     k_max_scrobble_point 240
23:07:47.169 DEBUG Playlist:173                     k_max_scrobble_point 240
__logging_message__23:07:47.191 WARN  unknown                          QCssParser::parseColorValue: Specified color without alpha value but alpha given: 'rgb 200, 200, 200, 75%'
__logging_message__23:07:47.192 WARN  unknown                          QCssParser::parseColorValue: Specified color without alpha value but alpha given: 'rgb 200, 200, 200, 75%'
23:07:47.209 DEBUG smart_playlists::Search:93       "SELECT ROWID,title, album, artist, albumartist, composer, track, disc, bpm, year, genre, comment, compilation, bitrate, samplerate, directory, filename, mtime, ctime, filesize, sampler, art_automatic, art_manual, filetype, playcount, lastplayed, rating, forced_compilation_on, forced_compilation_off, effective_compilation, skipcount, score, beginning, length, cue_path, unavailable, effective_albumartist, etag, performer, grouping, lyrics, originalyear, effective_originalyear FROM songs WHERE (title LIKE '%aq%') AND unavailable = 0 ORDER BY random()"
__logging_message__23:07:47.226 WARN  unknown                          QCssParser::parseColorValue: Specified color without alpha value but alpha given: 'rgb 200, 200, 200, 75%'
23:07:47.243 DEBUG smart_playlists::Search:93       "SELECT ROWID,title, album, artist, albumartist, composer, track, disc, bpm, year, genre, comment, compilation, bitrate, samplerate, directory, filename, mtime, ctime, filesize, sampler, art_automatic, art_manual, filetype, playcount, lastplayed, rating, forced_compilation_on, forced_compilation_off, effective_compilation, skipcount, score, beginning, length, cue_path, unavailable, effective_albumartist, etag, performer, grouping, lyrics, originalyear, effective_originalyear FROM songs WHERE (title LIKE '%aq%' AND grouping LIKE '%_%') AND unavailable = 0 ORDER BY random()"
23:07:47.266 INFO  MoodbarLoader:111                Loading cached moodbar data for "/home/tomaqa/Data/Audio/Music/Aqua/2000 - Aquarius/09 - Aquarius.MP3"
23:07:47.267 INFO  MoodbarLoader:111                Loading cached moodbar data for "/home/tomaqa/Data/Audio/Music/Ska-P/2013 - 99%/11 - Maquis.mp3"
__logging_message__23:07:53.982 WARN  unknown                          QCssParser::parseColorValue: Specified color without alpha value but alpha given: 'rgb 200, 200, 200, 75%'
23:07:53.983 DEBUG Playlist:173                     k_max_scrobble_point 240
23:07:53.984 DEBUG Playlist:173                     k_max_scrobble_point 240
__logging_message__23:07:54.003 WARN  unknown                          QCssParser::parseColorValue: Specified color without alpha value but alpha given: 'rgb 200, 200, 200, 75%'
23:07:54.020 DEBUG smart_playlists::Search:93       "SELECT ROWID,title, album, artist, albumartist, composer, track, disc, bpm, year, genre, comment, compilation, bitrate, samplerate, directory, filename, mtime, ctime, filesize, sampler, art_automatic, art_manual, filetype, playcount, lastplayed, rating, forced_compilation_on, forced_compilation_off, effective_compilation, skipcount, score, beginning, length, cue_path, unavailable, effective_albumartist, etag, performer, grouping, lyrics, originalyear, effective_originalyear FROM songs WHERE (title LIKE '%aq%') AND unavailable = 0 ORDER BY random()"
__logging_message__23:07:54.030 WARN  unknown                          QCssParser::parseColorValue: Specified color without alpha value but alpha given: 'rgb 200, 200, 200, 75%'
23:07:54.057 DEBUG smart_playlists::Search:93       "SELECT ROWID,title, album, artist, albumartist, composer, track, disc, bpm, year, genre, comment, compilation, bitrate, samplerate, directory, filename, mtime, ctime, filesize, sampler, art_automatic, art_manual, filetype, playcount, lastplayed, rating, forced_compilation_on, forced_compilation_off, effective_compilation, skipcount, score, beginning, length, cue_path, unavailable, effective_albumartist, etag, performer, grouping, lyrics, originalyear, effective_originalyear FROM songs WHERE (title LIKE '%aq%' AND grouping LIKE '%_%') AND unavailable = 0 ORDER BY random()"
23:07:54.069 INFO  MoodbarLoader:111                Loading cached moodbar data for "/home/tomaqa/Data/Audio/Music/Aqua/2000 - Aquarius/09 - Aquarius.MP3"
23:07:54.070 INFO  MoodbarLoader:111                Loading cached moodbar data for "/home/tomaqa/Data/Audio/Music/Ska-P/2013 - 99%/11 - Maquis.mp3"
```

backtrace:
```
#0  0x0000555556df6980 in  ()
#1  0x00007ffff77e4a2a in QMetaObject::cast(QObject const*) const () at /usr/lib/libQt5Core.so.5
#2  0x00007ffff5797e7a in  () at /usr/lib/libQt5Widgets.so.5
#3  0x00007ffff57a8271 in  () at /usr/lib/libQt5Widgets.so.5
#4  0x00007ffff572568a in QWidget::isActiveWindow() const () at /usr/lib/libQt5Widgets.so.5
#5  0x00007ffff572583f in QWidget::palette() const () at /usr/lib/libQt5Widgets.so.5
#6  0x00007ffff5725899 in QWidget::initPainter(QPainter*) const () at /usr/lib/libQt5Widgets.so.5
#7  0x00007ffff53627a5 in QPainter::initFrom(QPaintDevice const*) () at /usr/lib/libQt5Gui.so.5
#8  0x00007ffff536a598 in QPainter::begin(QPaintDevice*) () at /usr/lib/libQt5Gui.so.5
#9  0x00007ffff5736737 in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) () at /usr/lib/libQt5Widgets.so.5
#10 0x00007ffff570c20c in  () at /usr/lib/libQt5Widgets.so.5
#11 0x00007ffff570c4e4 in  () at /usr/lib/libQt5Widgets.so.5
#12 0x00007ffff575baf7 in  () at /usr/lib/libQt5Widgets.so.5
#13 0x00007ffff575c4fa in  () at /usr/lib/libQt5Widgets.so.5
#14 0x00007ffff56f94e5 in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
    at /usr/lib/libQt5Widgets.so.5
#15 0x00007ffff5702e11 in QApplication::notify(QObject*, QEvent*) () at /usr/lib/libQt5Widgets.so.5
#16 0x00007ffff77dbd12 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/libQt5Core.so.5
#17 0x00007ffff50d6305 in QGuiApplicationPrivate::processExposeEvent(QWindowSystemInterfacePrivate::ExposeEvent*) () at /usr/lib/libQt5Gui.so.5
#18 0x00007ffff50d6538 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () at /usr/lib/libQt5Gui.so.5
#19 0x00007ffff50b0b0c in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Gui.so.5
#20 0x00007fffec4b70ec in  () at /usr/lib/libQt5XcbQpa.so.5
#21 0x00007ffff696d3ee in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#22 0x00007ffff696f201 in  () at /usr/lib/libglib-2.0.so.0
#23 0x00007ffff696f241 in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#24 0x00007ffff7833b13 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
    at /usr/lib/libQt5Core.so.5
#25 0x00007ffff77da83c in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) ()
    at /usr/lib/libQt5Core.so.5
#26 0x00007ffff77e2676 in QCoreApplication::exec() () at /usr/lib/libQt5Core.so.5
#27 0x0000555555858522 in main(int, char**) (argc=<optimized out>, argv=<optimized out>)
    at /usr/src/debug/Clementine/src/main.cpp:470
```

**Comment by JulianVolodia** [comment]
Hey, if I see correctly you tried clementine-qt5-git which is not latest on master.

I am quite sure that the issue persist on latest master version, but because a lot of changes on master and issues are out there, I am asking you gently to re-check on bleeding edge from builder instance (build from master on CircleCI) or rebuild with makepkg changing your AUR package git source in PKGBUILD.

If it still crashing please say it, or best - try to fix it, bc I see you are the Power User. : - )

Best regards J

**Comment by JulianVolodia** [comment]
P.S. nice Thesis :)

**Comment by Tomaqa** [comment]
Unfortunately, I was able to reproduce the error on master too (1.3.1.r945.g440ac6dda-1), although with different backtrace:

`#0  0x0000555556c036c0 in  ()
#1  0x00007ffff77e3a2a in QMetaObject::cast(QObject const*) const () at /usr/lib/libQt5Core.so.5
#2  0x00007ffff596ee7a in  () at /usr/lib/libQt5Widgets.so.5
#3  0x00007ffff597f369 in  () at /usr/lib/libQt5Widgets.so.5
#4  0x00007ffff5a6ab12 in QMenuBar::eventFilter(QObject*, QEvent*) () at /usr/lib/libQt5Widgets.so.5
#5  0x00007ffff77daa23 in QCoreApplicationPrivate::sendThroughObjectEventFilters(QObject*, QEvent*) ()
    at /usr/lib/libQt5Core.so.5
#6  0x00007ffff58d04d4 in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
    at /usr/lib/libQt5Widgets.so.5
#7  0x00007ffff58d9e11 in QApplication::notify(QObject*, QEvent*) () at /usr/lib/libQt5Widgets.so.5
#8  0x00007ffff77dad12 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/libQt5Core.so.5
#9  0x00007ffff58d8a9a in  () at /usr/lib/libQt5Widgets.so.5
#10 0x00007ffff592eece in  () at /usr/lib/libQt5Widgets.so.5
#11 0x00007ffff5933453 in  () at /usr/lib/libQt5Widgets.so.5
#12 0x00007ffff58d04e5 in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
    at /usr/lib/libQt5Widgets.so.5
#13 0x00007ffff58d9e11 in QApplication::notify(QObject*, QEvent*) () at /usr/lib/libQt5Widgets.so.5
#14 0x00007ffff77dad12 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/libQt5Core.so.5
#15 0x00007ffff52a823c in QGuiApplicationPrivate::processEnterEvent(QWindowSystemInterfacePrivate::EnterEvent*) () at /usr/lib/libQt5Gui.so.5
#16 0x00007ffff52ad667 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () at /usr/lib/libQt5Gui.so.5
#17 0x00007ffff5287b0c in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Gui.so.5
#18 0x00007fffec8030ec in  () at /usr/lib/libQt5XcbQpa.so.5
#19 0x00007ffff6b6939e in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#20 0x00007ffff6b6b1b1 in  () at /usr/lib/libglib-2.0.so.0
#21 0x00007ffff6b6b1f1 in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#22 0x00007ffff7832b13 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
    at /usr/lib/libQt5Core.so.5
#23 0x00007ffff77d983c in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) ()
    at /usr/lib/libQt5Core.so.5
#24 0x00007ffff77e1676 in QCoreApplication::exec() () at /usr/lib/libQt5Core.so.5
#25 0x0000555555858772 in main(int, char**) (argc=<optimized out>, argv=<optimized out>)
    at /usr/src/debug/Clementine/src/main.cpp:461
`

**Comment by jbroadus** [comment]
I was able to reproduce this.

**Comment by jbroadus** [comment]
A backtrace with qt debug symbols:
#0  0x0000000000000000 in  ()
#1  0x00007ffff58e2fbe in QMetaObject::cast(QObject const*) const (this=this@entry=0x7ffff679b9c0 <QStyleSheetStyle::staticMetaObject>, obj=0x1e8ea00) at kernel/qmetaobject.cpp:381
#2  0x00007ffff58e2ff9 in QMetaObject::cast(QObject*) const (this=this@entry=0x7ffff679b9c0 <QStyleSheetStyle::staticMetaObject>, obj=<optimized out>) at kernel/qmetaobject.cpp:370
#3  0x00007ffff6332a48 in qobject_cast<QStyleSheetStyle*>(QObject*) (object=<optimized out>) at ../../include/QtCore/../../src/corelib/kernel/qobject.h:499
#4  qt_styleSheet(QStyle*) (style=<optimized out>) at styles/qstylesheetstyle_p.h:223
#5  QStyleSheetStyle::baseStyle() const (this=0x2b0f370) at styles/qstylesheetstyle.cpp:2763
#6  0x00007ffff6342ee9 in QStyleSheetStyle::baseStyle() const (this=0x2b0f370) at ../../include/QtCore/../../src/corelib/kernel/qvariant.h:392
#7  QStyleSheetStyle::styleHint(QStyle::StyleHint, QStyleOption const*, QWidget const*, QStyleHintReturn*) const (this=0x2b0f370, sh=QStyle::SH_MenuBar_AltKeyNavigation, opt=0x0, w=0x2785340, shret=<optimized out>)
    at styles/qstylesheetstyle.cpp:5408
#8  0x00007ffff642ab81 in QMenuBar::eventFilter(QObject*, QEvent*) (this=0x2785340, object=0x7fffffffce70, event=0x3317ed0) at widgets/qmenubar.cpp:1550
#9  0x00007ffff58d9c3e in QCoreApplicationPrivate::sendThroughObjectEventFilters(QObject*, QEvent*) (event=<optimized out>, receiver=<optimized out>) at kernel/qcoreapplication.cpp:1214
#10 QCoreApplicationPrivate::sendThroughObjectEventFilters(QObject*, QEvent*) (receiver=receiver@entry=0x7fffffffce70, event=event@entry=0x3317ed0) at kernel/qcoreapplication.cpp:1203
#11 0x00007ffff6296ac5 in QApplicationPrivate::notify_helper(QObject*, QEvent*) (this=<optimized out>, receiver=0x7fffffffce70, e=0x3317ed0) at kernel/qapplication.cpp:3694
#12 0x00007ffff62a0150 in QApplication::notify(QObject*, QEvent*) () at kernel/qapplication.cpp:3446
#13 0x00007ffff58d9df8 in QCoreApplication::notifyInternal2(QObject*, QEvent*) (receiver=0x7fffffffce70, event=0x3317ed0) at kernel/qcoreapplication.cpp:1088
#14 0x00007ffff58dcd9b in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) (receiver=0x0, event_type=0, data=0x1c692b0) at kernel/qcoreapplication.cpp:1825
#15 0x00007ffff592eff7 in postEventSourceDispatch(GSource*, GSourceFunc, gpointer) (s=0x1df9120) at kernel/qeventdispatcher_glib.cpp:276
#16 0x00007ffff744d4a0 in g_main_context_dispatch () at /usr/lib64/libglib-2.0.so.0
#17 0x00007ffff744d830 in g_main_context_iterate.isra () at /usr/lib64/libglib-2.0.so.0
#18 0x00007ffff744d8d3 in g_main_context_iteration () at /usr/lib64/libglib-2.0.so.0
#19 0x00007ffff592ed85 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) (this=0x1e4dda0, flags=...) at kernel/qeventdispatcher_glib.cpp:422
#20 0x00007ffff58d8cfb in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) (this=this@entry=0x7fffffffcd70, flags=..., flags@entry=...) at ../../include/QtCore/../../src/corelib/global/qflags.h:140
#21 0x00007ffff58e0a26 in QCoreApplication::exec() () at ../../include/QtCore/../../src/corelib/global/qflags.h:120
#22 0x0000000000a26356 in main ()

**Comment by jbroadus** [comment]
A backtrace with qt debug symbols:
#0  0x0000000000000000 in  ()
#1  0x00007ffff58e2fbe in QMetaObject::cast(QObject const*) const (this=this@entry=0x7ffff679b9c0 <QStyleSheetStyle::staticMetaObject>, obj=0x1e8ea00) at kernel/qmetaobject.cpp:381
#2  0x00007ffff58e2ff9 in QMetaObject::cast(QObject*) const (this=this@entry=0x7ffff679b9c0 <QStyleSheetStyle::staticMetaObject>, obj=<optimized out>) at kernel/qmetaobject.cpp:370
#3  0x00007ffff6332a48 in qobject_cast<QStyleSheetStyle*>(QObject*) (object=<optimized out>) at ../../include/QtCore/../../src/corelib/kernel/qobject.h:499
#4  qt_styleSheet(QStyle*) (style=<optimized out>) at styles/qstylesheetstyle_p.h:223
#5  QStyleSheetStyle::baseStyle() const (this=0x2b0f370) at styles/qstylesheetstyle.cpp:2763
#6  0x00007ffff6342ee9 in QStyleSheetStyle::baseStyle() const (this=0x2b0f370) at ../../include/QtCore/../../src/corelib/kernel/qvariant.h:392
#7  QStyleSheetStyle::styleHint(QStyle::StyleHint, QStyleOption const*, QWidget const*, QStyleHintReturn*) const (this=0x2b0f370, sh=QStyle::SH_MenuBar_AltKeyNavigation, opt=0x0, w=0x2785340, shret=<optimized out>)
    at styles/qstylesheetstyle.cpp:5408
#8  0x00007ffff642ab81 in QMenuBar::eventFilter(QObject*, QEvent*) (this=0x2785340, object=0x7fffffffce70, event=0x3317ed0) at widgets/qmenubar.cpp:1550
#9  0x00007ffff58d9c3e in QCoreApplicationPrivate::sendThroughObjectEventFilters(QObject*, QEvent*) (event=<optimized out>, receiver=<optimized out>) at kernel/qcoreapplication.cpp:1214
#10 QCoreApplicationPrivate::sendThroughObjectEventFilters(QObject*, QEvent*) (receiver=receiver@entry=0x7fffffffce70, event=event@entry=0x3317ed0) at kernel/qcoreapplication.cpp:1203
#11 0x00007ffff6296ac5 in QApplicationPrivate::notify_helper(QObject*, QEvent*) (this=<optimized out>, receiver=0x7fffffffce70, e=0x3317ed0) at kernel/qapplication.cpp:3694
#12 0x00007ffff62a0150 in QApplication::notify(QObject*, QEvent*) () at kernel/qapplication.cpp:3446
#13 0x00007ffff58d9df8 in QCoreApplication::notifyInternal2(QObject*, QEvent*) (receiver=0x7fffffffce70, event=0x3317ed0) at kernel/qcoreapplication.cpp:1088
#14 0x00007ffff58dcd9b in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) (receiver=0x0, event_type=0, data=0x1c692b0) at kernel/qcoreapplication.cpp:1825
#15 0x00007ffff592eff7 in postEventSourceDispatch(GSource*, GSourceFunc, gpointer) (s=0x1df9120) at kernel/qeventdispatcher_glib.cpp:276
#16 0x00007ffff744d4a0 in g_main_context_dispatch () at /usr/lib64/libglib-2.0.so.0
#17 0x00007ffff744d830 in g_main_context_iterate.isra () at /usr/lib64/libglib-2.0.so.0
#18 0x00007ffff744d8d3 in g_main_context_iteration () at /usr/lib64/libglib-2.0.so.0
#19 0x00007ffff592ed85 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) (this=0x1e4dda0, flags=...) at kernel/qeventdispatcher_glib.cpp:422
#20 0x00007ffff58d8cfb in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) (this=this@entry=0x7fffffffcd70, flags=..., flags@entry=...) at ../../include/QtCore/../../src/corelib/global/qflags.h:140
#21 0x00007ffff58e0a26 in QCoreApplication::exec() () at ../../include/QtCore/../../src/corelib/global/qflags.h:120
#22 0x0000000000a26356 in main ()

**Comment by jbroadus** [comment]
This is due to the misuse of QProxyStyle. When passed a base style, it takes ownership of the pointer. In our case, we're passing it a global resource in the PlaylistView constructor.

**Comment by jbroadus** [comment]
Please verify that this fix works for you. It appears that the same pattern is followed in MoodbarProxyStyle, but that object probably doesn't get destroyed.

**Comment by Tomaqa** [comment]
Works for me now. Thank you very much!

**Comment by JulianVolodia** [comment]
Hi @jbroadus could you make codeblock or spoiler on your comment because it referencing to other issues false-positively. Thanks.

**Comment by jbroadus** [comment]
@JulianVolodia Done

**Comment by JulianVolodia** [comment]
Thank you. I try to review all 2k issues, starting from oldest one. From pain start to be fun...
