### ISSUE TITLE
'Select All' in the right click context menu

### ISSUE THREAD

**Issue by Clementine-Issue-Importer** [clementine-player/Clementine#644]
_From [VinniE.D.VegaS](https://code.google.com/u/103764973526838443842/) on August 20, 2010 21:47:01_

I would like to have a 'Select All' in the right click context menu when right clicking in the library.

_Original issue: http://code.google.com/p/clementine-player/issues/detail?id=644_

**Comment by rmpbklyn** [comment]
> _From [keirangtp](https://code.google.com/u/117310112843043412265/) on December 23, 2010 15:06:10_
> 
> Alternatively, you can use the 'All tracks' smart playlist.
> 
> **Status:** WontFix

nope, want to copy to finder/burn app  folder  so select all is needed
