### ISSUE TITLE
 Possibility to have more than one library

### ISSUE THREAD

**Issue by tng99** [clementine-player/Clementine#6446]
Is this possible for you to implement this one? you need to have a separate database for each library.  

https://github.com/clementine-player/Clementine/issues/2851

**Comment by jonaski** [comment]
No

**Comment by tng99** [comment]
thanks
to other:
i try winamp, songbird, mediamonkey didnt help.
mediamonkey uses "collections" just like winamp's "smart view", where you setup the criteria manually
http://www.mediamonkey.com/forum/viewtopic.php?t=62982

I have 2 folders "d:\western music" and "d:\eastern music" (with unicode) , just wish I can create 2 separate libraries and choose which one is activated. I think Itunes has that option, not sure (itunes is so heavy and big , i dont want had it on my laptop. winamp is only 8MB)
