### ISSUE TITLE
Does not compile using site instructions

### ISSUE THREAD

**Issue by Nick-us** [clementine-player/Clementine#6461]
I downloaded as the site explains:
git clone https://github.com/clementine-player/Clementine.git && cd Clementine

I am following the instructions given.
I have all the dependencies requested.
[github.com/clementine-player/Clementine/wiki/Compiling-from-Source](url)

And then cmake returns Qt5 complaining error? There is no information requesting Qt5 dependency on the site:
```
Could not find a package configuration file provided by "Qt5" (requested
  version 5.6.0) with any of the following names:
    Qt5Config.cmake
    qt5-config.cmake
```
After all, is it necessary qt4 or qt5?
What is wrong to compile?

### System information: 
- Operating System: Slackware64-Current
- Clementine version: git clone https://github.com/clementine-player/Clementine.git

**Comment by jonaski** [comment]
Updated now: https://github.com/clementine-player/Clementine/wiki/Compiling-from-source-(Linux)

**Comment by JulianVolodia** [comment]
@Nick-us if this is done and works please close issue, because you have this power : - )

If you want you could try to play with CircleCI on your fork to build on Slackware box for check of support of this distro. :)))

Best!
