### ISSUE TITLE
Classical Covers

### ISSUE THREAD

**Issue by YvesMichel** [clementine-player/Clementine#6466]
I began to use Clementine today.
I like the way I can find the covers for my albums BUT for the classical albums, no way! I have to google the names of the Director and some more details to find those covers! Don't you have a site where we can find them?
Thanks in advance!

**Comment by fitojb** [comment]
Primephonic and Idagio come to mind; haven’t tried them out however.

**Comment by JulianVolodia** [comment]
Hmm, some like MusicBrainz?

**Comment by YvesMichel** [comment]
Thank you for your answers! But I was looking at an automatic cover searcher like the ones for the other genres we find **inside** Clementine. Seems very difficult to find for classical and opera music! I don't want to download music so Primephonic and Idagio are not my choice. I will have a look at MusicBrainz.
But thanks to you all!

**Comment by JulianVolodia** [comment]
Thanks for idea, I don't know if there is some feature of this in Clementine. I must check but don't know when.

@YvesMichel , I understanded that you want a feature inside it, but maybe someone will have better idea for working with your collection. If the clementine get more feature it will be harder to maintain. Take a look at MusicBrainz and hmmm... Picard? I don't remember if that get this done, but please check on your own.

If there is no other question about this source of Classical Covers as in topic please close issue. If you have idea how could work the feature you want to propose please change the name of this issue and describe what actually that should do and on which level. Later, this will be decided what to do with ppl more advanced and involved to Clementine development.
