### ISSUE TITLE
Does not compile using site instructions - Could not find a configuration file for package "Qt5" that is compatible   with requested version "5.6.0".

### ISSUE THREAD

**Issue by matkoniecz** [clementine-player/Clementine#6474]
I followed install from source guide, `cmake ..` failed, retried `cmake ..` resulted in:

```
mateusz@zombie:~/Desktop/Clementine/bin$ cmake ../
-- ccache found: will be used for compilation and linkage
-- Boost version: 1.58.0
-- Checking for module 'libmygpo-qt5>=1.0.9'
--   
-- Checking for module 'libspotify>=12.1.45'
--   
CMake Error at CMakeLists.txt:91 (find_package):
  Could not find a configuration file for package "Qt5" that is compatible
  with requested version "5.6.0".

  The following configuration files were considered but not accepted:

    /usr/lib/x86_64-linux-gnu/cmake/Qt5/Qt5Config.cmake, version: 5.5.1



-- Configuring incomplete, errors occurred!
See also "/home/mateusz/Desktop/Clementine/bin/CMakeFiles/CMakeOutput.log".
See also "/home/mateusz/Desktop/Clementine/bin/CMakeFiles/CMakeError.log".
```

log files:
https://gist.github.com/matkoniecz/2e62184dd099eba659caa42c3cbf3424
https://gist.github.com/matkoniecz/25ff309082e66ffb0f973d2da70b729f

### Before posting

Please follow the steps below and check the boxes with [x] once you did the step.

- [x] I checked the issue tracker for similar issues (#6461 was earlier and apparently about more severe problem and https://github.com/clementine-player/Clementine/search?q=Could+not+find+a+configuration+file+for+package+%22Qt5%22+that+is+compatible+++with+requested+version+%225.6.0%22.&unscoped_q=Could+not+find+a+configuration+file+for+package+%22Qt5%22+that+is+compatible+++with+requested+version+%225.6.0%22. returns no hits)
- [x] I checked the [changelog](https://github.com/clementine-player/Clementine/blob/master/Changelog) if the issue is already resolved (not relevant)
- [x] I tried the latest Clementine build from [here](https://builds.clementine-player.org/) (I cloned master at https://github.com/clementine-player/Clementine/commit/672b90659b608d992b449dbc688f01c093e43a5d )

### System information

Please provide information about your system and the version of Clementine used.

- Operating System: blank Lubuntu 18.04 install + `sudo apt-get update` + `sudo apt-get dist-upgrade` + Ubuntu package install listed on https://github.com/clementine-player/Clementine/wiki/Compiling-from-source-(Linux)
- Clementine version: https://github.com/clementine-player/Clementine/commit/672b90659b608d992b449dbc688f01c093e43a5d

### Expected behaviour / actual behaviour

install from source succeds

### Steps to reproduce the problem (only for bugs)

follow install instructions from source

### Trigger

Based on #6465 my understanding is that additional testing of recent versions is welcomed.

I plan on continuing after this bug is fixed or more info would be needed to fix it.

**Comment by hatstand** [comment]
Qt 5.5 is too old. You need a newer version of Qt or Ubuntu.

**Comment by matkoniecz** [comment]
Sorry, I mistakenly tested with an EOL version
