### ISSUE TITLE
Bad-looking macOS version

### ISSUE THREAD

**Issue by lassana** [clementine-player/Clementine#6483]
### Before posting

Please follow the steps below and check the boxes with [x] once you did the step.

- [x] I checked the issue tracker for similar issues
- [x] I checked the [changelog](https://github.com/clementine-player/Clementine/blob/master/Changelog) if the issue is already resolved
- [x] I tried the latest Clementine build from [here](https://builds.clementine-player.org/)

### System information

Please provide information about your system and the version of Clementine used.

- Operating System: macOS Mojave 10.14.6
- Clementine version: 1.3.1-967-g922e10bc4

### Expected behaviour / actual behaviour

I've tried the latest CI build on my Mac and except lack of media keys support (#6346), everything seems fine. This build even fixes high CPU usage for me (which is gooood!).

However, all controls are Windows-styled for some reason. Compare it to the previous version:

1.3.1 from Homebrew:

![Screen Shot 2019-12-27 at 11 04 40 PM](https://user-images.githubusercontent.com/2004960/71530995-c8dd3a80-28fd-11ea-8cdf-6eebf0a11bed.png)

1.3.1-967-g922e10bc4 from https://builds.clementine-player.org/mac/ :

![Screen Shot 2019-12-27 at 10 55 43 PM](https://user-images.githubusercontent.com/2004960/71531015-d98db080-28fd-11ea-9630-8ab3cce954a2.png)

It looks even worse when Dark Appearance is set, GUI is just too contrast:

![Screen Shot 2019-12-27 at 10 56 47 PM](https://user-images.githubusercontent.com/2004960/71531120-4dc85400-28fe-11ea-9f64-58bf1ab67dc1.png)

**Comment by icarapovic** [comment]
I am a developer but also know a bit around Illustrator and other design tools and principles. I would like to try to contribute UI elements to make it look better (on all platforms). If the maintainers see UI improvements as something they are willing to devote time to improve, I can sketch a few mockups and see how it will go on from there.

**Comment by briskycat** [comment]
I think this issue and #6523 are related.

**Comment by jonaski** [comment]
styles/libqmacstyle.dylib needs to be added to the PlugIns dir through the macdeploy script.

**Comment by hatstand** [comment]
@jonaski Thanks for that, should be fixed now.
