### ISSUE TITLE
Plays next song on reaching the middle of current (console: QTimeLine::setDuration: cannot set duration <= 0)

### ISSUE THREAD

**Issue by tincho** [clementine-player/Clementine#6484]
### Before posting

Please follow the steps below and check the boxes with [x] once you did the step.

- [x] I checked the issue tracker for similar issues
- [x] I checked the [changelog](https://github.com/clementine-player/Clementine/blob/master/Changelog) if the issue is already resolved
- [ ] I tried the latest Clementine build from [here](https://builds.clementine-player.org/)

### System information

Please provide information about your system and the version of Clementine used.

- Operating System: Ubuntu 18.04
- Clementine version: 1.3.1

### Expected behaviour / actual behaviour

Expected: the song should be played until the end, not the middle.

Actual: when either picking manually a song to start playing, or starts playing in the playlist, it passes to the next at almost exactly the middle of it.

Running from console with `--verbose` prints this message at the point of failure: 
`21:37:03.605 WARN  unknown                          QTimeLine::setDuration: cannot set duration <= 0 `

What's weird though is that if I seek to a point near the half, then this doesn't happen, instead it plays until (ALMOST) the end

### Steps to reproduce the problem (only for bugs)

1. Open Clementine
2. Add N songs to playlist
3. (In my case random/shuffle mode is enabled)
4. Play any song
5. Wait until almost the half of the time
6. Will pass to next

**Comment by JulianVolodia** [comment]
Hi @tincho, could you check lastest?

**Comment by tincho** [comment]
Hi! thanks for answering
Just updated to **clementine_1.3.9~bionic_amd64.deb** and bug persists :thinking:

**Comment by jbroadus** [comment]
Does it jump at the same point on a given track?

**Comment by TheUbuntuGuy** [comment]
Do you by any chance have the 'Intro Tracks' feature enabled? With it enabled, only the first half of a song is played (or the first 4 minutes if the track is longer than 8 minutes). It is found in the repeat options menu.

**Comment by tincho** [comment]
:man_facepalming: 
Precisely that @TheUbuntuGuy !
Although I really don't remember ever setting that feature, in fact, didn't even know it existed.
Dismiss the bug, thank you all

**Comment by JulianVolodia** [comment]
@tincho if you could edit your very first comment and say about this feature it will be great. Thanks.
