### ISSUE TITLE
Provide an alternative way to download the Spotify plugin (Connection refused)

### ISSUE THREAD

**Issue by alwayslivid** [clementine-player/Clementine#6493]
### Before posting

Please follow the steps below and check the boxes with [x] once you did the step.

- [x] I checked the issue tracker for similar issues
- [x] I checked the [changelog](https://github.com/clementine-player/Clementine/blob/master/Changelog) if the issue is already resolved
- [x] I tried the latest Clementine build from [here](https://builds.clementine-player.org/)

### System information

Please provide information about your system and the version of Clementine used.

- Operating System: Arch Linux with the 4.19.91-1-lts kernel
- Clementine version: 1.3.92-2-g9f99cab31

### Expected behaviour / actual behaviour

As I'm not precisely sure of what's causing the "Connection refused" error (despite having attempted to download the plugin under 2 different networks), I'd like to request alternative ways to manually download and instsall our own versions of the Spotify libraries and the plugin's source code.

![image](https://user-images.githubusercontent.com/30193966/71657267-ce94af00-2d47-11ea-92c2-32eb45ee0f14.png)

**Comment by obbardc** [comment]
same issue here, on debian sid

**Comment by alwayslivid** [comment]
> same issue here, on debian sid

Huh, so that could mean that the servers are down as of the writing of this reply.

**Comment by hatstand** [comment]
Fixed
