### ISSUE TITLE
Cannot login to Spotify

### ISSUE THREAD

**Issue by AlwaysLivid** [clementine-player/Clementine#6512]
### Before posting

Please follow the steps below and check the boxes with [x] once you did the step.

- [x] I checked the issue tracker for similar issues
- [x] I checked the [changelog](https://github.com/clementine-player/Clementine/blob/master/Changelog) if the issue is already resolved
- [x] I tried the latest Clementine build from [here](https://builds.clementine-player.org/)

### System information

Please provide information about your system and the version of Clementine used.

- Operating System: Arch Linux (Kernel: 5.4.7-arch1-1)
- Clementine version: 1.3.92-2-g9f99cab31

#### Expected behaviour

Being able to login to Spotify and stream music from its API.

#### Actual Behaviour

![image](https://user-images.githubusercontent.com/30193966/71778233-c04acb00-2fb3-11ea-98a2-3da08429f9fa.png)

![image](https://user-images.githubusercontent.com/30193966/71778245-fc7e2b80-2fb3-11ea-9850-d2c5c743b684.png)

### Steps to reproduce the problem (only for bugs)

- Open up the Preferences tab
- Click on Spotify in the Internet providers section
- Download the plugin as instructed
- Enter the credentials and try to login

**Comment by kimme** [comment]
Same here, and the system I'm using is...

OS: Pop!_OS 19.10 x86_64 
Kernel: 5.3.0-7625-generic 
Uptime: 1 day, 14 hours, 50 mins 
Packages: 3262 (dpkg), 27 (flatpak), 39 (snap) 
Shell: bash 5.0.3 
Resolution: 1920x1080 
DE: Cinnamon 4.0.10 
WM: Mutter (Muffin) 
WM Theme: Adapta-Nokto (Menta) 
Theme: Adapta-Nokto [GTK2/3] 
Icons: pop-os-branding [GTK2/3] 
Terminal: gnome-terminal 
CPU: AMD Ryzen 5 2600X (12) @ 3.700GHz 
GPU: AMD ATI Radeon RX 470/480/570/570X/580/580X/590 
Memory: 9044MiB / 16003MiB

**Comment by jlnostr** [comment]
Installing the `qt4` package from the AUR helped in my case.

**Comment by JonDVstRm** [comment]
Hi , can you confirm that after succesfull install on Arch Linux, spotify plugin is working with every options - especially search. I manage to get only Top tracks workin (other system other release)

Thx for answer

**Comment by AlwaysLivid** [comment]
> Hi , can you confirm that after succesfull install on Arch Linux, spotify plugin is working with every options - especially search. I manage to get only Top tracks workin (other system other release)
> 
> Thx for answer

Same here, but this seems more like of a libspotify issue, rather than anything else for the time being. Would be a good idea to open a new issue for it, @JonDVstRm.

> Installing the `qt4` package from the AUR helped in my case.

Can confirm that this works.

**Comment by JonDVstRm** [comment]
Thx for answer. I even tried to compile libspotify myself , but it wants a developer key. Just to be sure before I start experimenting with Arch Linux, the search option is working on your system or not ....

**Comment by AlwaysLivid** [comment]
> Thx for answer. I even tried to compile libspotify myself , but it wants a developer key. Just to be sure before I start experimenting with Arch Linux, the search option is working on your system or not ....

It's not working on my system. I'd advise you to open a new issue.
