### ISSUE TITLE
1.4.0rc1 No theming on Windows 10

### ISSUE THREAD

**Issue by adavier** [clementine-player/Clementine#6523]
### Before posting

Please follow the steps below and check the boxes with [x] once you did the step.

- [ x] I checked the issue tracker for similar issues
- [ x] I checked the [changelog](https://github.com/clementine-player/Clementine/blob/master/Changelog) if the issue is already resolved
- [ ] I tried the latest Clementine build from [here](https://builds.clementine-player.org/)

### System information

Please provide information about your system and the version of Clementine used.

- Operating System: Windows 10
- Clementine version:  1.4.0rc1

### Expected behaviour / actual behaviour
Clementine 1.4 does not apply any theming on windows resulting in a UI similar to that of Windows 95. Whereas Clementine 1.3 uses the Windows Vista Style.
Clementine 1.3
![image](https://user-images.githubusercontent.com/30839200/72184800-2a66d400-33e9-11ea-9103-296827b29c71.png)
Clementine 1.4
![image](https://user-images.githubusercontent.com/30839200/72184815-35216900-33e9-11ea-8b00-44de12e127a1.png)

### Steps to reproduce the problem (only for bugs)
Install Clementine 1.4 on windows. (I believe any version vista+ would exhibit this)

I also experience the same issue with Strawberry. I assume it is looking for the system specified theme, but windows 10 has no such setting. Kdenlive solves this by presenting style in the options menu 
![image](https://user-images.githubusercontent.com/30839200/72185077-d9a3ab00-33e9-11ea-9258-9b82f68d99ad.png)

**Comment by briskycat** [comment]
No theming on macOS 10.14 either. Looks like the relevant Qt plugins are missing.

**Comment by hatstand** [comment]
Does anyone know which DLL this is for windows?

**Comment by jonaski** [comment]
`styles\qwindowsvistastyle.dll`
