### ISSUE TITLE
/usr/bin/data usage + library scan errors

### ISSUE THREAD

**Issue by jnvandermeer** [clementine-player/Clementine#6583]
Dear developers,

I have installed Clementine 1.3.1 on Arch. Specifically version 1.3.1.r831.664c5a31f-3

Is it normal that the /usr/bin/data directory is used to store the databases jamendo.db and clementine.db? The location is highly unusual and I would expect more of a ~/.clementine folder. But this might be a packaging issue on Arch side.

Also, when I update my Music folder, it will miss each file. This is because the folders in the database miss one 'level' of folder.

Example: When a music file is in:
/data/Music/a/b/c/file.mp3

The database reads:
/data/Music/b/c/file.mp3

The name of the 'a' folder doesn't matter - it will be removed, so it cannot find anything. Is this something you came across?

Thanks for your help
Best wishes from Australia
Johan

### Before posting

Please follow the steps below and check the boxes with [x] once you did the step.

- [ x] I checked the issue tracker for similar issues
- [ x] I checked the [changelog](https://github.com/clementine-player/Clementine/blob/master/Changelog) if the issue is already resolved
- [ ] I tried the latest Clementine build from [here](https://builds.clementine-player.org/)

### System information

Please provide information about your system and the version of Clementine used.

- Operating System:
- Clementine version:

**Comment by jbroadus** [comment]
There was a portable feature added in 2013 that checks if a "data" directory exists in same location as the clementine executable. I'm not sure what the use case was for this or if it's still valid. I assume the data directory already existed?

See commit acb18cdcde.

**Comment by jbroadus** [comment]
Oh, and those paths in the database should be fixed at e7b066719

**Comment by jnvandermeer** [comment]
Thanks for your quick reply. 

I cannot remember what made the data directory in /usr/bin, but apparently Spotify and one other program used that. I'll try rebuilding in a few days.

**Comment by jbroadus** [comment]
The spotify files might be from Clementine integration, but a Google search shows a few packages that do use this directory, though none should (I assume the Clementine case was intended for a USB stick or something). Other people are probably hitting this as well, so maybe we should consider something more unique like clementine-data
