### ISSUE TITLE
Playlist search causes segmentation fault

### ISSUE THREAD

**Issue by TheBlackKoala** [clementine-player/Clementine#6591]
### Before posting

Please follow the steps below and check the boxes with [x] once you did the step.

- [X ] I checked the issue tracker for similar issues
- [X] I checked the [changelog](https://github.com/clementine-player/Clementine/blob/master/Changelog) if the issue is already resolved
- [x] I tried the latest Clementine build from [here](https://builds.clementine-player.org/) - i always have the latest build from AUR.

### System information

Please provide information about your system and the version of Clementine used.

- Operating System: 5.5.5-arch1-1
- Clementine version: Clementine 1.3.1-831-g664c5a31f

### Expected behaviour / actual behaviour
Search in playlists shows the resulting songs from resulting playlists (it seem to be a new feature and i love it!) - after the first search clementine is liable to clash with a segmentation fault

### Steps to reproduce the problem (only for bugs)
Search in the input-field in the playlist tab.
Search for something else.
Try a few times if it doesn't crash at first.

My longest playlist is a little more than 5k items and i have playlists sorted into folders (4 folders, 36 playlists in total).

**Comment by TheBlackKoala** [comment]
To clearify - the search that causes the segmentation fault is in the same place that you would search your library in the library tab but for playlists.

**Comment by jbroadus** [comment]
I was able to repro after adding folders.

**Comment by TheBlackKoala** [comment]
@jbroadus so without folders it does not occur? Might go without those until it has been resolved if that is the case.

**Comment by jbroadus** [comment]
Yeah, I wasn't able to repro without folders. Let me know if your experience is different. I'll try to dig a little more later.

**Comment by jbroadus** [comment]
The crash occurs while iterating over the QList expandList in PlaylistListFilterProxyModel.
```
  void refreshExpanded(QTreeView *tree) {
    tree->collapseAll();
    for(QModelIndex sourceIndex : expandList ) {
      QModelIndex mappedIndex = mapFromSource( sourceIndex );
      tree->setExpanded( mappedIndex, true );
    }
  }
```
The setExpanded eventually causes an overloaded function in the class to append expandList. QList is implemented as an array, not a linked list, so I think that when it grows beyond its preallocated size and reallocates the array, the iterators become garbage. The good news is that the data can be accessed efficiently using indexes, so the iterators aren't necessary.

**Comment by jbroadus** [comment]
@TheBlackKoala This fixes the issue for me. If you're able to test the latest, let me know if it works for you.

**Comment by TheBlackKoala** [comment]
As far as i can tell the commit has fixed the issue. I can't reproduce the problem either - not even writing something and deleting one character at a time which involves a lot of searches.

**Comment by DoubleCouponDay** [comment]
I can still reproduce this error consistently in version 1.4 rc1.

**Comment by jbroadus** [comment]
> I can still reproduce this error consistently in version 1.4 rc1.

Is that a recent build from here, or from a distro?

I just tried to repro on master and I don't see it.

**Comment by TheBlackKoala** [comment]
@jbroadus i just tried as well and failed. 1.4.0rc1-345-g9e8d4434a
