### ISSUE TITLE
Issue closed by error

### ISSUE THREAD

**Issue by ericlovestztot** [clementine-player/Clementine#6594]
Hello.
I posted this topic to signal a bug :
https://github.com/clementine-player/Clementine/issues/6542
It has been closed by an admin. I wrote 2 emails to this admin without any answer.
Since then, another user encounter the same problem.
Should you reopen my 1st post and close this one please.
Thank you.

**Comment by hatstand** [comment]
If you do not put in the effort to even use the issue template, then no one is likely to put in the effort to help you.

**Comment by ericlovestztot** [comment]
English is not my native language and it is hard for me to describe a problem and to understand all the rules. Which issue template are you talking about please ?

**Comment by ericlovestztot** [comment]
I found the template. This rule wasn't exist the last time I posted on this forum and you are very rude. You should understand that english can be a problem for few people. Anyway, thank you for the work you do.
