### ISSUE TITLE
Unable to donwload Mac builds from https://builds.clementine-player.org/mac/

### ISSUE THREAD

**Issue by llucps** [clementine-player/Clementine#6603]
I've been trying to download any build from https://builds.clementine-player.org/mac/ and I always get this error:

![Screenshot 2020-03-01 at 10 37 50](https://user-images.githubusercontent.com/25823659/75623295-d5ee0280-5ba8-11ea-830c-4f999ca74ba3.jpg)

I tried to download any build from Debian Buster folder.. and it works.

Thanks,

**Comment by hatstand** [comment]
Should work now
