### ISSUE TITLE
cannot open apple podcast list 1.3.1 on ubuntu 19.10

### ISSUE THREAD

**Issue by ogbuzz** [clementine-player/Clementine#6607]
each time I try to search on apple pocast, it's says that it was not able to get the podcast list

**Comment by jbroadus** [comment]
Probably fixed here:
https://github.com/clementine-player/Clementine/pull/6572/commits/b3e8c1e3ea37110d32ecdd3b3a897c077845b261

You could try the latest:
https://builds.clementine-player.org/ubuntu-eoan/clementine_1.4.0rc1-134-g90cf4988e~eoan_amd64.deb

**Comment by ogbuzz** [comment]
fixed with the latest deb, thanks
