### ISSUE TITLE
Icons in settings / sidebar have different sizes

### ISSUE THREAD

**Issue by gruniversal** [clementine-player/Clementine#6628]
### Before posting

Please follow the steps below and check the boxes with [x] once you did the step.

- [x] I checked the issue tracker for similar issues
- [x] I checked the [changelog](https://github.com/clementine-player/Clementine/blob/master/Changelog) if the issue is already resolved
- [ ] I tried the latest Clementine build from [here](https://builds.clementine-player.org/)

### System information

Please provide information about your system and the version of Clementine used.

- Operating System: Linux Mint 19 Tara (Ubuntu/Debian based)
- Clementine version: 1.3.1

### Expected behaviour / actual behaviour

All icons should have the same dimensions.

### Steps to reproduce the problem (only for bugs)

After switching to Linux Mint 19 (from 18.3) the icons in the settings and sidebar area have different sizes.

Screenshot: https://blog.gruniversal.de/wp-content/uploads/2020/03/Clementine-Icons.png

**Comment by jbroadus** [comment]
Not sure if this is a bug. When you have "Use system icons" selected, it uses default icons where available. Those are the smaller ones.

**Comment by gruniversal** [comment]
The option "use system icons" was not present in my version so I tried the release candidate:
https://github.com/clementine-player/Clementine/releases/tag/1.4.0rc1

This version has the option but it also works without enabling it.

Fixed! :)
