### ISSUE TITLE
Storing lyrics does not work for M4A files

### ISSUE THREAD

**Issue by SpectrumDT** [clementine-player/Clementine#6633]
I am running Clementine 1.3.1 under Kubuntu 19.10. I have both MP3, OGG and M4A files in my library. I have noticed that saving lyrics works for MP3 and OGG files but not M4A.

Steps:
1. Have M4A file in library.
2. Add M4A file from library to playlist.
3. Right-click it in the playlist and select "Edit track information".
4. Go to the "Lyrics" field.
5. Enter some text.
6. Click "Save.
7. Select "Edit track information" again.

Expected: The entered text should be there.
Actual: Lyrics field is empty.

This only fails for M4A files. It seems to work fine for MP3 and OGG files..

This appears to be closely related to this issue: https://github.com/clementine-player/Clementine/issues/3906

**Comment by jbroadus** [comment]
Should be fixed in the latest build.
