### ISSUE TITLE
Song artwork is not being changed from edit information window. 

### ISSUE THREAD

**Issue by jakubbalas** [clementine-player/Clementine#6648]
### Preface
I found out that there is a feature that has tremendous value for me - automatic album cover search. Unfortunately I can't get my mp3 artwork to change whatever I do.

I hereby solemnly swear that I went through all "Before posting" bits 

### System information
System 1:
- OSX Catalina (10.15.4)
- Clementine version: 1.3.1

System 2:
- Arch linux (Linux 5.6.6-arch1-1 x86_64)
- Clementine version: 1.4 rc1

Music collection is located on Dropbox, this info might have no impact but I thought it is worth mentioning. 

### Expected behaviour / actual behaviour
When Editing track information, Search for album cover, Load cover from Url, Load cover from disk, Unset cover should change the cover art.
Currently nothing will change

Change cover art button is also disabled ?! 

Minor improvement would also be to decouple cover manager window from edit track information window

### Steps to reproduce the problem (only for bugs)
Option A: Go to Edit Track Information and right-click cover art and select any of mentioned options. 

Option B: When song plays, right click artwork directly there to load options.

**Comment by jbroadus** [comment]
I can repro this on 1.3.1 (Dropbox doesn't seem to be a factor). What I see is that it always remembers the setting in the edit window, but doesn't update the thumbnail. However, It doesn't repro on my own build from master. You might want to try the latest mac build (1.4.0rc1-174-gcb64d9705) from https://builds.clementine-player.org/mac/

**Comment by jakubbalas** [comment]
@jbroadus sorry for being lame but when I download it and try to install, it says image not recognised. Is it my system or the image is not right ?  
<img width="368" alt="Screenshot 2020-05-04 12 32 42" src="https://user-images.githubusercontent.com/20398186/80957475-752ab280-8e03-11ea-9b4c-1e8902afce60.png">

SHA of the file downloaded:
$ openssl sha256 mac_._clementine-1.4.0rc1-174-gcb64d9705.dmg
SHA256(mac_._clementine-1.4.0rc1-174-gcb64d9705.dmg)= 896f254819069f8bd86e2e5b0a3ee54d7c21169cf644be9df3057bd15d81fbf8

**Comment by jakubbalas** [comment]
Thank you @jbroadus ! Looks like it is indeed fixed in that version. Does it mean that it should work also on linux and we can close this ticket ?

**Comment by jbroadus** [comment]
I didn't see the issue with the latest on Fedora, so probably safe to close. I'm not sure who builds the arch images and how often.

**Comment by jakubbalas** [comment]
Since then, due to few missclicks, I've accidentally  migrated to ubuntu and checked that the latest build works so I'm closing this issue.

Many thanks for help!
