### ISSUE TITLE
Mac clementine-1.4.0rc1-177-g096203ac8.dmg automatic cover art not working

### ISSUE THREAD

**Issue by waynepaulward** [clementine-player/Clementine#6657]
### Before posting

Please follow the steps below and check the boxes with [x] once you did the step.

- [x ] I checked the issue tracker for similar issues
- [x ] I checked the [changelog](https://github.com/clementine-player/Clementine/blob/master/Changelog) if the issue is already resolved
- [x ] I tried the latest Clementine build from [here](https://builds.clementine-player.org/)

### System information

Please provide information about your system and the version of Clementine used.

- Operating System: Mac Catalina Latest & Mojave Latest
- Clementine version: clementine-1.4.0rc1-177-g096203ac8.dmg

### Expected behaviour / actual behaviour

(playing from Airsonic server)
no cover art displayed with any songs although displayed on 1.3.1
play song doesn't automatically search for cover art although ticked 
and the art is in the server displays on other clients
tried playing local music this displays the image in the folder

### Steps to reproduce the problem (only for bugs)
tried untick and re-tick but doesn't work
although if you click search for album covers it will search give you the album cover but when change track it disappears

**Comment by jbroadus** [comment]
Looks like it works for Smart playlists, but not when you play a song directly. Is that what you see?

**Comment by waynepaulward** [comment]
Not sure about the playlists 
I load a song that’s on the local disk and the artwork plays
But if I tru to play a song from a internet device it doesnt go and get the artwork 
On 1.3.1 a round circle spins in the artwork indicating it’s getting the artwork on the test version it doesn’t look even if you tick it to automatically do this

**Comment by jbroadus** [comment]
@waynepaulward after you get this fix, you'll need to resync your catalog to repopulate your database with the corrected URLs.

**Comment by waynepaulward** [comment]
When it’s playing from subsonic or Airsonic is it possible to pull the artwork from the song folder or does it have to pull this from the internet do every song ?

**Comment by jbroadus** [comment]
Clementine is requesting the cover from the airsonic server, but I don't know if the server will ever redirect to another location.

**Comment by waynepaulward** [comment]
The artwork is displaying on the latest dmg
