### ISSUE TITLE
On KDE neon, Gwenview is used for "Show in file browser..."

### ISSUE THREAD

**Issue by SevenSystems** [clementine-player/Clementine#6674]
I'm running 1.4 rc2 on KDE neon 5.18 (Plasma 5.18.5, Frameworks 5.69.0, Qt 5.14.2).

When right-clicking on a file in the library and then "Show in file browser...", Clementine opens the file in Gwenview (image viewer) instead of the actual file browser (Dolphin, which is also correctly configured as the default file browser in KDE's System Settings).

Not sure why this is -- I've grepped for -i gwenview in Clementine's ~ config dir and haven't found anything. Not in Preferences either.

**Comment by jbroadus** [comment]
This is calling `Utilities::OpenInFileBrowser` which, on Linux, is calling QDesktopServices::openUrl
https://doc.qt.io/qt-5/qdesktopservices.html#openUrl

Maybe dolphin sees cover art files in the folders and opens the image viewer?

**Comment by SevenSystems** [comment]
Hah, thanks, that's hilarious. It's definitely a bug in KDE -- you can actually edit the File Associations in System Settings and there's one for "inode / directory". That one has listed Dolphin -> GwenView -> FileLight in that order, but still, GwenView seems to be preferred. Deleting GwenView from that list opens directories in Dolphin from that point on. Problem solved, KDE bug will be reported! :)
