### ISSUE TITLE
For release 1.4.0rc1-231-g60a46d193 Bionic and Buster builds are the same as the last release 1.4.0rc1-230.....

### ISSUE THREAD

**Issue by Oldbwl** [clementine-player/Clementine#6691]
### Before posting

Please follow the steps below and check the boxes with [x] once you did the step.

- [ ] I checked the issue tracker for similar issues
- [ ] I checked the [changelog](https://github.com/clementine-player/Clementine/blob/master/Changelog) if the issue is already resolved
- [ ] I tried the latest Clementine build from [here](https://builds.clementine-player.org/)

### System information

Please provide information about your system and the version of Clementine used.

- Operating System:
- Clementine version:

**Comment by Oldbwl** [comment]
The title refers

**Comment by hatstand** [comment]
There were no code changes.
