### ISSUE TITLE
Windows Store paid version

### ISSUE THREAD

**Issue by burtek** [clementine-player/Clementine#6708]
Is [Windows Store paid version of Clementine Player](https://www.microsoft.com/en-us/p/clementine-player/9p1wszc124tj) an authorized thing? Or did someone release it to collect money for himself? Why is this version paid? Asking because can't find any info about it on website nor on github

**Comment by hatstand** [comment]
no

**Comment by v1993** [comment]
@hatstand  What does "no" mean here? Genuinely curious what it is and does Clementine team want to do something with it.

**Comment by burtek** [comment]
@v1993 MS did nothing when I notified scam team of this... 🤷‍♂️
