### ISSUE TITLE
Spotify plugin; Invalid Signature: blob

### ISSUE THREAD

**Issue by abhijeetviswa** [clementine-player/Clementine#6709]
### Before posting

Please follow the steps below and check the boxes with [x] once you did the step.

- [x] I checked the issue tracker for similar issues
- [x] I checked the [changelog](https://github.com/clementine-player/Clementine/blob/master/Changelog) if the issue is already resolved
- [x] I tried the latest Clementine build from [here](https://builds.clementine-player.org/)

### System information

Please provide information about your system and the version of Clementine used.

- Operating System: Kubuntu 20.04
- Clementine version: 1.4.0rc1-254-gbf3d3db23

### Expected behaviour / actual behaviour

Installed the latest Debian package of Clementine and got greeted by this error. 

I've noticed a lot of similar previous issues. Is there any reason why the signature suddenly goes stale?

**Comment by jbroadus** [comment]
I just tried and it seems to be working now.
```
12:29:44.099 INFO  SpotifyBlobDownloader:96         Downloading QUrl("https://spotify.clementine-player.org/version16-64bit/blob")
12:29:44.099 INFO  SpotifyBlobDownloader:96         Downloading QUrl("https://spotify.clementine-player.org/version16-64bit/blob.sha512")
12:29:44.099 INFO  SpotifyBlobDownloader:96         Downloading QUrl("https://spotify.clementine-player.org/version16-64bit/libspotify.so.12.1.51")
12:29:44.099 INFO  SpotifyBlobDownloader:96         Downloading QUrl("https://spotify.clementine-player.org/version16-64bit/libspotify.so.12.1.51.sha512")
12:29:52.162 DEBUG SpotifyBlobDownloader:223        Verifying "blob" against "blob.sha512" true
12:29:52.168 DEBUG SpotifyBlobDownloader:223        Verifying "libspotify.so.12.1.51" against "libspotify.so.12.1.51.sha512" true
```
I also downloaded and verified the signature on the 32 bit version.

**Comment by abhijeetviswa** [comment]
Yep. It's working now. 
Is there any particular reason why it does not work at certain times?

**Comment by jbroadus** [comment]
> Yep. It's working now.
> Is there any particular reason why it does not work at certain times?
> EDIT: Closing this issue. Though, I'd still love to hear from you on the reason. Thanks :)

I'm not sure. In the past, I've seen it return a Google cloud bucket page instead of the object. It also looks like the error handling in SpotifyBlobDownloader isn't great. It downloads the files and digests in parallel, and as long as the last download succeeds, it tries to verify the signatures.

**Comment by ShapeShifter499** [comment]
I'm getting this error again today, any fixes?

**Comment by jbroadus** [comment]
Working for me. What kind of error are you seeing now?

**Comment by delightfuldude** [comment]
Same here on Manjaro :(
