### ISSUE TITLE
Feature request: Clementine v1.4 support MacOSX 10.11 or later (same as V1.3.1)

### ISSUE THREAD

**Issue by bits4fun** [clementine-player/Clementine#6711]
Hi,

Current V1.4 RC builds of Clementine only supports OSX 10.13. When run, OSX report system problem:

"Dyld Error Message:
  Symbol not found: _OBJC_CLASS_$_MTLCaptureManager
  Referenced from: /Applications/Clementine 2.app/Contents/MacOS/../Frameworks/QtGui.framework/Versions/5/QtGui (which was built for Mac OS X 10.13)
  Expected in: /System/Library/Frameworks/Metal.framework/Versions/A/Metal
 in /Applications/Clementine 2.app/Contents/MacOS/../Frameworks/QtGui.framework/Versions/5/QtGui"
 
Is is possible to use Qt5.11, which is final Qt5 supported on both Debian Buster and Mac?

Cheers,
Gunther.

**Comment by hatstand** [comment]
Apple barely supports old versions so I don't think we have the resources to.
