### ISSUE TITLE
Notarize Clementine builds for macOS

### ISSUE THREAD

**Issue by foss-** [clementine-player/Clementine#6725]
### System information

macOS 10.15.5
Clementine 1.4.0rc1-272-gedb8c3b4e

### Expected behaviour / actual behaviour

Clementine should be notarized.
See :https://developer.apple.com/documentation/xcode/notarizing_macos_software_before_distribution

### Currently

When opening clementine macOS will complain and not open the app.

![Screenshot](https://user-images.githubusercontent.com/5708172/84659440-b2f91b80-af17-11ea-9c94-c4928b9b7149.png)

**Comment by hatstand** [comment]
It costs $100 and is a lot of hassle.

**Comment by foss-** [comment]
Apple provides [free developer memberships to open source projects](https://developer.apple.com/support/membership-fee-waiver/) if I am not mistaken.

**Comment by hatstand** [comment]
> if you’re a nonprofit organization, accredited educational institution, or government entity 

Nope.
