### ISSUE TITLE
The tooltip displays raw HTML on KDE

### ISSUE THREAD

**Issue by outloudvi** [clementine-player/Clementine#6733]
### Before posting

- [x] I checked the issue tracker for similar issues
- [x] I checked the [changelog](https://github.com/clementine-player/Clementine/blob/master/Changelog) if the issue is already resolved
- [x] I tried the latest Clementine build from [here](https://builds.clementine-player.org/)

### System information

- Operating System: Arch Linux
- Clementine version: 1.4.0rc1-3, and 1.4.0rc1-279-g76a24a0a2

Other KDE/Qt related info:
```
KDE Plasma Version: 5.19.1 (package version 5.19.1-1)
KDE Frameworks Version: 5.71.0
Qt Version: 5.15.0
qt5-webengine: 5.15.0-2
```

### Expected behaviour / actual behaviour

Expected behaviour: Normal tooltip interface
Actual behaviour:
![image](https://user-images.githubusercontent.com/19144373/85150072-a7458600-b284-11ea-937f-526a295ddbc1.png)

### Steps to reproduce the problem (only for bugs)
1. Open Clementine.
2. Play a song.
3. Check the tooltip.

This problem happens recently, so it's very likely that it's caused by a recent KDE/Qt update or deprecation.

**Comment by firew4lker** [comment]
FYI:

https://invent.kde.org/frameworks/plasma-framework/-/commit/c46a0dbf00d9f30155e233daca1a6e8ac314db9c

**Comment by Pointedstick** [comment]
See https://bugs.kde.org/show_bug.cgi?id=422616

**Comment by outloudvi** [comment]
Exactly! From KDE bug 422616, it seems that there is currently no way to display HTML for the latest KDE framework. The solution would be:
1. Use the Windows way in all systems: https://github.com/clementine-player/Clementine/blob/04c85c2bb76e788bcf9dbbc607541c400e88ef8d/src/ui/qtsystemtrayicon.cpp#L234-L238
2. Wait for a upstream fix.

**Comment by nicolasfella** [comment]
As I have statet in https://bugs.kde.org/show_bug.cgi?id=423852 the [SNI specification](https://freedesktop.org/wiki/Specifications/StatusNotifierItem/StatusNotifierItem/) explicitely mentiones HTML markup in the tooltip subtitle, but not in the title. I read this as HTML is not allowed in the title and thus Clementine should not use it.

**Comment by loimu** [comment]
@nicolasfella 

The fact is `QSystemTrayIcon::setToolTip()` knows nothing about titles/subtitles, and you HAVE TO deal with it FFS

**Comment by nicolasfella** [comment]
There's always the possibility of
1. Patching QSystemTrayIcon to support tooltip subtitles
2. Not using QSystemTrayIcon

**Comment by loimu** [comment]
@nicolasfella 

So your solution is throwing a crossplatform framework out of the window and implementing everything individually for each platform just because some moronic developer has a problem with it? Cool story bro

>Patching QSystemTrayIcon to support tooltip subtitles

Thanks but no thanks. I'd rather part my ways with KDE Plasma and advertise everyone to not use it under whatever circumstances
