### ISSUE TITLE
Unable to disable notifications in settings

### ISSUE THREAD

**Issue by brndd** [clementine-player/Clementine#6741]
### Before posting

Please follow the steps below and check the boxes with [x] once you did the step.

- [x] I checked the issue tracker for similar issues
- [x] I checked the [changelog](https://github.com/clementine-player/Clementine/blob/master/Changelog) if the issue is already resolved
- [x] I tried the latest Clementine build from [here](https://builds.clementine-player.org/)

### System information

Please provide information about your system and the version of Clementine used.

- Operating System: Fedora 32
- Clementine version: 1.4 1.rc1.20200617gitedb8c3b.fc32

### Expected behaviour / actual behaviour

Setting notifications to 'Disabled' in Tools -> Preferences -> Notifications should disable desktop notifications in KDE and others.

However, changing this setting doesn't work. Setting it to 'Disabled' and then clicking on 'Apply' or 'OK' does nothing, and the setting is reset back to the default ('Show a native desktop notification') when the menu is reopened. In fact, none of the settings on this page work.

**Comment by jbroadus** [comment]
This was my fault. Also affected search settings.
