### ISSUE TITLE
WMA tracks kills Clementine

### ISSUE THREAD

**Issue by liftarn** [clementine-player/Clementine#6746]
- [x] I checked the issue tracker for similar issues

### System information

Please provide information about your system and the version of Clementine used.

- Operating System: Windows 10 Pro
- Clementine version: 1.3.1

### Expected behaviour / actual behaviour
That the track plays.

### Steps to reproduce the problem (only for bugs)
Start playing the track.
Crash

The track that crashed for me was the third track from Bats & Machines Vol I that can be downloaded from http://www.batbeat.com.co/descargas.html I tagged it using MusicBrainz Picard before playing it.

**Comment by hatstand** [comment]
> - [ ] I tried the latest Clementine build from [here](https://builds.clementine-player.org/)

Try the latest build.
