### ISSUE TITLE
[1.4.0rc1] BUG dependency error on Linux Mint 20

### ISSUE THREAD

**Issue by mohicanb** [clementine-player/Clementine#6751]
### Before posting
- [X] I checked the issue tracker for similar issues
- [X] I checked the [changelog](https://github.com/clementine-player/Clementine/blob/master/Changelog) if the issue is already resolved

### System information
- Operating System: Linux Mint Xfce 20.0
- Clementine version: version 1.4.0-rc1 from official Mint depository.

I have been using Clementine 1.3.1 on Linux Mint 19.
Today I upgraded my install to Linux Mint 20.
During the process I saw a warning that a library was going to be deleted but that Clementine depended on it.
After the upgrade (Clementine was updated to version 1.4.0-rc1), when I tried to launched Clementine I had a very brief error empty dialog and Clementine did not launch.

I uninstalled and reinstalled Clementine. I did not change this behavior.
Then I uninstalled Clementine and I installed the Flatpak version.
The Flatpak version runs fine.

## Steps to reproduce the problem (only for bugs)
Install Linux Mint 20.
Install the regular Clementine version.
Launch it.

**Comment by jbroadus** [comment]
I think Mint is using the Ubuntu packaged clementine, not the one built here. You can try this one instead:
https://github.com/clementine-player/Clementine/releases/download/1.4.0rc1-293-g1f7607b1d/clementine_1.4.0rc1-293-g1f7607b1d.focal_amd64.deb

**Comment by mohicanb** [comment]
The bug does not occur on a fresh Install of Ubuntu 20 or Mint 20 (with the version 1.4.0-rc1 from the official Ubuntu depository).
It is therefore related to the upgrade process from Mint 19.3 to Mint 20.
I'm closing it. Thank you.
