### ISSUE TITLE
[WINDOWS] Clementine crashes when trying to edit a track directly in the Playlist

### ISSUE THREAD

**Issue by kadai** [clementine-player/Clementine#6754]
### Before posting

Please follow the steps below and check the boxes with [x] once you did the step.

- [x] I checked the issue tracker for similar issues
- [x] I checked the [changelog](https://github.com/clementine-player/Clementine/blob/master/Changelog) if the issue is already resolved
- [x] I tried the latest Clementine build from [here](https://builds.clementine-player.org/)

### System information

Please provide information about your system and the version of Clementine used.

- Operating System: Windows 10 (64-bits)
- Clementine version: 1.4.0rc1-292-gdd9ed2334

### Expected behaviour / actual behaviour
Expected to be able to edit an individual track directly from the Playlist. Instead, the application crashed.

### Steps to reproduce the problem (only for bugs)
In my case, I had this:

Start Clementine with some FLAC files loaded in a playlist.
Select one and try to edit it directly (not using CTRL+E window)
Clementine will crash before it allows you too type/copy content

This crash only happens when trying to edit the tracks directly in a playlist. If I use CTRL+E to have the edit window appear, Clementine does not crash at all.

Thanks in advance.

**Comment by jbroadus** [comment]
Should be fixed when this is merged:
https://github.com/clementine-player/Clementine/pull/6753

**Comment by kadai** [comment]
> 
> 
> Should be fixed when this is merged:
> #6753

Oh thanks! Will stay tuned for the merge and builds.

**Comment by jbroadus** [comment]
Looks better in today's build.

**Comment by kadai** [comment]
Yeah, the last available version fixed this issue. Thank you.

Closing this issue then.
