### ISSUE TITLE
Clementine tray icon shows html text when I hover cursor on it

### ISSUE THREAD

**Issue by Echocs7** [clementine-player/Clementine#6768]
### Before posting

Please follow the steps below and check the boxes with [x] once you did the step.

- [x] I checked the issue tracker for similar issues
- [x] I checked the [changelog](https://github.com/clementine-player/Clementine/blob/master/Changelog) if the issue is already resolved
- [ ] I tried the latest Clementine build from [here](https://builds.clementine-player.org/)

### System information

Please provide information about your system and the version of Clementine used.

- Operating System: Archlinux
- Clementine version:  1.4.0rc1-3
- Desktop envirement: KDE Plasma 5.19.4

### Expected behaviour / actual behaviour
Render the played music
### Steps to reproduce the problem (only for bugs)
Hover the cursor on the clementine's tray icon
![clementine_weird_bug](https://user-images.githubusercontent.com/68904873/89230327-fba98880-d5da-11ea-9410-d59b6c2aab19.png)

Request: if it is a bug from kde's side can you add an option to just show the song name without html rendering?

**Comment by Echocs7** [comment]
It seems like KDE has disabled HTML rendering for tray icons. https://bugs.kde.org/show_bug.cgi?id=422616

I think normal text rendering became a necessity.

**Comment by paperbagcorner** [comment]
This is a duplicate of #6733.

**Comment by Echocs7** [comment]
Glad too see that it was already fixed! I'll wait for it to be released.
