### ISSUE TITLE
Can't get 1.3.1 to start any longer- Mac OS

### ISSUE THREAD

**Issue by MoonBlake** [clementine-player/Clementine#6797]
### Before posting

Please follow the steps below and check the boxes with [x] once you did the step.

- [ ] I checked the issue tracker for similar issues
- [ ] I checked the [changelog](https://github.com/clementine-player/Clementine/blob/master/Changelog) if the issue is already resolved
- [ ] I tried the latest Clementine build from [here](https://builds.clementine-player.org/)

### System information

Please provide information about your system and the version of Clementine used.

- Operating System: Mac OS 10.15.6
- Clementine version: 1.3.1

### Expected behaviour / actual behaviour 
After several crahses it now appears that the software asks if I wnat to reopen the former windows or not. Independant of what I choose to klick on Clementine crashes. No use of the software possible any longer.

**Comment by jadkik** [comment]
The latest build from CI works. If you click on the little green check mark and check the artifacts of `Build Mac DMG`: https://github.com/clementine-player/Clementine/runs/1204361208

You can download the artifacts for `release_mac`. It's an unsigned build so you have to whitelist it when you download and unzip, but it works.

I guess that means we only need a new official release.

**Comment by hatstand** [comment]
https://github.com/clementine-player/Clementine/releases
