### ISSUE TITLE
Transition Clementine Snap

### ISSUE THREAD

**Issue by kz6fittycent** [clementine-player/Clementine#6801]
I've been maintaining (with the much welcomed assistance of others) the Clementine snap for some time now. It's been received quite well (almost 11k downloads worldwide). 

It's easy enough to make the transition and I'd love to discuss with the Clementine project. Here's a link to my [repo](https://github.com/kz6fittycent/clementine/blob/master/snapcraft.yaml).  

Here's a link to the snap in the [Snap-store.](https://snapcraft.io/clementine) 

Let me know if you'd like to proceed.

**Comment by hatstand** [comment]
A PR including a Github action for publishing it automatically would be the first step towards this.

**Comment by kz6fittycent** [comment]
> A PR including a Github action for publishing it automatically would be the first step towards this.

You mean like this one: https://github.com/clementine-player/Clementine/pull/5870

I'd be happy to open another but I want to get some input on the level of interest before I do it again.

**Comment by hatstand** [comment]
Yes, but we really need to have automated testing and deployment for it otherwise it will inevitably break in the future.

**Comment by kz6fittycent** [comment]
The [snapcraf.yaml](https://github.com/clementine-player/Clementine/tree/master/snap) is already in your repo as @jonaski assisted in updating it some time ago. This is meant to transition the snap to your team so that you can control it.

**Comment by hatstand** [comment]
Owning it, for us, requires automating it. I don't have the time or knowledge to do that right now, sorry.

**Comment by kz6fittycent** [comment]
Okay - I'll find another route. Thanks anyway.

**Comment by Nightmayr** [comment]
I've created a PR to add a Github action to build and publish the snap, let me know if you have any questions.
