### ISSUE TITLE
Import of OPML causes application crash

### ISSUE THREAD

**Issue by cgku** [clementine-player/Clementine#6802]
### Before posting

Please follow the steps below and check the boxes with [x] once you did the step.

- [x] I checked the issue tracker for similar issues
- [x] I checked the [changelog](https://github.com/clementine-player/Clementine/blob/master/Changelog) if the issue is already resolved
- [x] I tried the latest Clementine build from [here](https://builds.clementine-player.org/)

### System information

Please provide information about your system and the version of Clementine used.

- Operating System:
- Kubuntu 20.04
- KDE Plasma Version: 5.18.5
- KDE Frameworks Version: 5.68.0
- Qt Version: 5.12.8
- Kernel Version: 5.4.0-48-generic
- OS Type: 64-bit
- Processors: 4 × Intel® Core™ i5-3570K CPU @ 3.40GHz
- Memory: 31.3 GiB of RAM 

- Clementine version: 1.4 rc1

### Expected behavior / actual behavior
Expect to add a podcast by opening an OPML file.
Selecting the OPML file in the Add Podcast screen causes the application to crash.
I am able to add podcast by URL.

### Steps to reproduce the problem (only for bugs)
1. From menu:  Music > Add Podcast
2. Click "Open OPML file..."
3. Select the file to open (either double clicking or single click then clicking Open) -- Clementine crashes

**Comment by jbroadus** [comment]
I'm not able to repro. Is there a repro opml file that you'd be willing to share?

**Comment by cgku** [comment]
Attached is the OPML file (as a .txt).  I am not the original creator of this export; a friend gave it to me as a suggested list.  It appears to be a rather old export, so maybe the opml version is too old?

Thanks for looking into this.
[export.opml.txt](https://github.com/clementine-player/Clementine/files/5388821/export.opml.txt)

**Comment by jbroadus** [comment]
I can repro with that file. The bug is in the handling of the outer outline block. If you don't want to wait for a fix, this should work:
[fixed.opml.txt](https://github.com/clementine-player/Clementine/files/5395002/fixed.opml.txt)

**Comment by cgku** [comment]
That worked!  Thanks for your help on this.
