### ISSUE TITLE
last.fm doesn't scrobble tracks 

### ISSUE THREAD

**Issue by pandenis** [clementine-player/Clementine#6807]
### Before posting

Please follow the steps below and check the boxes with [x] once you did the step.

- [X ] I checked the issue tracker for similar issues
- [ X] I checked the [changelog](https://github.com/clementine-player/Clementine/blob/master/Changelog) if the issue is already resolved
- [ X] I tried the latest Clementine build from [here](https://builds.clementine-player.org/)

### System information

Please provide information about your system and the version of Clementine used.

- Operating System: Ubuntu 20.10 Betta
- Clementine version: 1.4 rc2

### Expected behaviour
Scrobbling songs info to last.fm site
### Actual behaviour
In last.fm site displaying "Scrrobling now" with the name of the track, but actual after the track played the song doesn't scrobble in the latest tracks 

### Steps to reproduce the problem (only for bugs)
Play any track using logged last.fm user

### Note
Scrobbling from Spotify works as well

**Comment by TheUbuntuGuy** [comment]
Duplicate of https://github.com/clementine-player/Clementine/issues/6522
