### ISSUE TITLE
how to really install clementine on raspberry pi

### ISSUE THREAD

**Issue by nguxx** [clementine-player/Clementine#6816]
```
uname -a
Linux raspberrypi 5.4.51-v7+ #1333 SMP Mon Aug 10 16:45:19 BST 2020 armv7l GNU/Linux
```
I've tried so many thing to try to get clementine on my Raspian i don't even remember all 

Still i get 
```
sudo dpkg -i clementine_1.3.1.jessie_armhf.deb 
(Reading database ... 173746 files and directories currently installed.)
Preparing to unpack clementine_1.3.1.jessie_armhf.deb ...
Unpacking clementine (1.3.1~jessie) over (1.3.1~jessie) ...
dpkg: dependency problems prevent configuration of clementine:
 clementine depends on libcdio13 (>= 0.83); however:
  Package libcdio13 is not installed.
 clementine depends on libchromaprint0 (>= 0.2); however:
  Package libchromaprint0 is not installed.
 clementine depends on libcrypto++9; however:
  Package libcrypto++9 is not installed.
 clementine depends on libechonest2.1 (>= 2.1.0); however:
  Package libechonest2.1 is not installed.
 clementine depends on libglew1.10 (>= 1.10.0); however:
  Package libglew1.10 is not installed.
 clementine depends on libimobiledevice4 (>= 0.9.7); however:
  Package libimobiledevice4 is not installed.
 clementine depends on libprotobuf9; however:
  Package libprotobuf9 is not installed.
 clementine depends on libqt4-xmlpatterns (>= 4:4.5.3); however:
  Package libqt4-xmlpatterns is not installed.
 clementine depends on libqtwebkit4 (>= 2.1.0~2011week13); however:
  Package libqtwebkit4 is not installed.
 clementine depends on libtag1c2a (>= 1.9.1); however:
  Package libtag1c2a is not installed.
 clementine depends on gconf2 (>= 2.28.1-2); however:
  Package gconf2 is not installed.
 clementine depends on libprojectm-data | projectm-data; however:
  Package libprojectm-data is not installed.
  Package projectm-data is not installed.

dpkg: error processing package clementine (--install):
 dependency problems - leaving unconfigured
Processing triggers for gnome-menus (3.31.4-3) ...
Processing triggers for desktop-file-utils (0.23-4) ...
Processing triggers for mime-support (3.62) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Errors were encountered while processing:
 clementine
```

and if i try 
```
apt search libcdio13
Sorting... Done
Full Text Search... Done
```
Is there a place where to find all the up-to-date dependencies needed to install clementine today ?
thanks

**Comment by jbroadus** [comment]
You probably need to add jessie repositories to your apt sources list or download+install individual dependency packages.

If you have a Pi 3 or 4, it looks like you can install a 64 bit Ubuntu Focal and get a newer version of Clementine. 
https://ubuntu.com/download/raspberry-pi
https://packages.ubuntu.com/focal/clementine

**Comment by nguxx** [comment]
> If you have a Pi 3 or 4, it looks like you can install a 64 bit Ubuntu Focal and get a newer version of Clementine

As far I know Ubuntu Focal comes only with the server version eg without GUi. Don't think Clementine can be run just in CLI.
Adding Jessie repo... It is an option but I'm afraid that it could mess up my pi. 
Adding extension manually is a very time consuming because you need to find the old one... for exemple `libcdio` is 18 now not 13... 
Hum... Not easy

**Comment by jbroadus** [comment]
You can install a desktop on the Focal image:
https://ubuntu.com/tutorials/how-to-install-ubuntu-on-your-raspberry-pi#5-install-a-desktop

**Comment by AllKind** [comment]
> apt search libcdio13
`apt search libcdio` should get you further

**Comment by nguxx** [comment]
> apt search libcdio should get you further
You get only the 19th today...

**Comment by nguxx** [comment]
> You can install a desktop on the Focal image:
https://ubuntu.com/tutorials/how-to-install-ubuntu-on-your-raspberry-pi#5-install-a-desktop

Good news, I'din't known. I would have preferred Raspbian but it will be easier this way.
Thanks
