### ISSUE TITLE
Forced UPPER CASE extension in organise files

### ISSUE THREAD

**Issue by CrustyCurmudgeon** [clementine-player/Clementine#6838]
When using the "Organise files" function on files in the database, Clementine forces the extension tag (%extension) to be upper case as in .MP3 for all file writes. Can this be changed?

**Comment by jbroadus** [comment]
I took a look at the organise code and it's taking the extension from the source file. Are you trying to move files from a case-insensitive filesystem?

**Comment by CrustyCurmudgeon** [comment]
My apologies. I had a closer look at the files and the organize and now see that I DO have a few files with an all caps extension. Just my luck those were the ones I was organizing.
