### ISSUE TITLE
problem with lyrics, with new qt-5.15.2

### ISSUE THREAD

**Issue by Toutatis2** [clementine-player/Clementine#6844]
My system: Linux with slackware64-current
The lyrics do not appear at all, when I use clementine compiled with the new qt-5.15.2 (but qt-5.15.1 is ok).
Some problems have been reported in slackware changelog, where were needed  "a few patches where the API
for QPrinter/QPageLayout has changed"

**Comment by jbroadus** [comment]
I'm using 5.15.2 now, but I'm not seeing the issue. Which lyric source are you using?

**Comment by Toutatis2** [comment]
The problem seems to disappear with a new compilation of qt-5.15.2.
