### ISSUE TITLE
Very slow, High processor and memory usage when scanning wav files

### ISSUE THREAD

**Issue by Clementine-Issue-Importer** [clementine-player/Clementine#687]
_From [jordo.ex](https://code.google.com/u/106157946000204043720/) on September 03, 2010 23:31:36_

What steps will reproduce the problem? 1. Add some wav files to your library.
2. Scan
3. Look at the progress indicator What is the expected output? What do you see instead? It should be faster What version of the product are you using? On what operating system? 0.4 r1905 Windows 7 64-bit Please provide any additional information below. In process explorer, file handles for /Device/Afd are constantly created. (that's how I figured out it was wav files)

_Original issue: http://code.google.com/p/clementine-player/issues/detail?id=687_

**Comment by Chocobozzz** [comment]
Closing this old issue. Feel free to reopen.
