### ISSUE TITLE
Cant rip as flac best quality

### ISSUE THREAD

**Issue by linusrg1** [clementine-player/Clementine#6876]
Please provide information about your system and the version of Clementine used.

- Operating System: Linux Mint 20.1
- Clementine version:  1.4.0rc1-398-g0393d865c

### Expected behaviour / actual behaviour
To be able to rip FLACS
### Steps to reproduce the problem (only for bugs)
Rip cd choose flac
in options move quality up to best 
flacs will rip as 0 byte files. 
I am unsure if flacs work in other qualities

**Comment by jbroadus** [comment]
```Could not initialize supporting library.```

Looks like it's related to this:
https://gitlab.freedesktop.org/gstreamer/gst-plugins-good/-/issues/335
