### ISSUE TITLE
Latest Fedora release hangs

### ISSUE THREAD

**Issue by davidgfnet** [clementine-player/Clementine#6882]
### Before posting

Please follow the steps below and check the boxes with [x] once you did the step.

- [x] I checked the issue tracker for similar issues
- [x] I checked the [changelog](https://github.com/clementine-player/Clementine/blob/master/Changelog) if the issue is already resolved
- I did not try it from head tho :( The release is pretty recent tho.

### System information

This is using: clementine-1.4.0-5.rc1.20201216gitccba649.fc32.1.x86_64
Which I assume uses commit cba649, ~17 days ago.

Clicking on Subsonic or Dropbox (for example) causes the UI to look like this: https://imgur.com/hauofZJ
CPU goes 100%. Got a bt with gdb: https://pastebin.com/f0Un9u0S

Didnt look a lot into it but seems perhaps a Qt signal loop or something like that. Every time I interrupt it is doing some UI related stuff, which is silly, since I deleted .config/Clementine and .cache/Clementine so the preferences are "fresh".

Let me know if I can help debugging this. I might try to build it from head tomorrow and see whether it has the same issue.
Thanks!

**Comment by davidgfnet** [comment]
Wait, debugging in: 

239	void InternetModel::RowsAboutToBeRemoved(const QModelIndex& parent, int first,
240	                                         int last) {
241	  for (int i = first; i <= last; i++) {

My gdb (perhaps is total bullshit since this is not a debug build) tells me last=2147483646 :D So perhaps there's some signed/unsigned conversion over there or some UB related to an int overflow.
Again perhaps this is fixed already but seems like Fedora picked a pretty bad commit to cut a release from

**Comment by davidgfnet** [comment]
Ah nevermind, im totally blind. Was fixed a few days later at https://github.com/clementine-player/Clementine/commit/c999fc70e26b8e383d997a264f9f2237b908d08e

**Comment by jbroadus** [comment]
cc @eclipseo 
I thought Fedora had picked up this fix.

**Comment by jbroadus** [comment]
Fedora has the fixed version in updates now.

**Comment by davidgfnet** [comment]
Closing then!
