### ISSUE TITLE
Use of pb namespace incompatible with protobuf 3.15.0

### ISSUE THREAD

**Issue by ahesford** [clementine-player/Clementine#6926]
The new protobuf 3.15.0 seems to add a new `pb` namespace alias that breaks compilation of clementine. Replacing the `pb` namespace with `cpb` allows clementine to compile. A sample patch is available at https://github.com/ahesford/void-packages/blob/protobuf/srcpkgs/clementine/patches/pb_namespace.patch

The patch applies cleanly to 1.4.0rc1 but I am not sure about the head of `master`.

**Comment by jbroadus** [comment]
For reference:
https://github.com/haberman/protobuf/blob/5c028d6cf42e426d47f5baa6ea3f0f5c86b97beb/src/google/protobuf/port.h#L44

Have you spotted 3.15 in the wild yet?

**Comment by ahesford** [comment]
I bumped the Void Linux package to 3.15.0 this morning, so it's making its way to the wild now.
