### ISSUE TITLE
Track informations/tags not editable since build 340

### ISSUE THREAD

**Issue by liofeu** [clementine-player/Clementine#6950]
### Before posting

Please follow the steps below and check the boxes with [x] once you did the step.

- [ x] I checked the issue tracker for similar issues
- [x ] I checked the [changelog](https://github.com/clementine-player/Clementine/blob/master/Changelog) if the issue is already resolved
- [ x] I tried the latest Clementine build from [here](https://builds.clementine-player.org/)

### System information

Please provide information about your system and the version of Clementine used.

- Operating System: Mac OSX 10.15.7 (Catalina)
- Clementine version: 1.4.0rc1-498-g681e7bea5

### Expected behaviour / actual behaviour

Since build 340, any track information/tag not editable. It remains stuck on "loading tracks..." when opening the track information window.

On build 332 and before, no problem at all.

So the issue should come from somewhere there https://github.com/clementine-player/Clementine/compare/1.4.0rc1-332-g62d2f0de9...1.4.0rc1-340-g2172732b1 

### Steps to reproduce the problem (only for bugs)

Right click on a track > Edit track Information

It remains stuck on "loading tracks..."

**Comment by jbroadus** [comment]
I don't see this issue on Fedora, so maybe limited to mac. Out of that range, this is really the only commit that touches code: https://github.com/clementine-player/Clementine/commit/341dc7326f075a2ae454dfe4548686ae0a7d01d4
And in that change, I think reordered includes is a likely culprit.

**Comment by jbroadus** [comment]
Okay, I _may_ have found something.

Here, `#include "player.h"` is moved after #include `"tagreaderclient.h"`:
https://github.com/clementine-player/Clementine/compare/1.4.0rc1-332-g62d2f0de9...1.4.0rc1-340-g2172732b1#diff-f7910d8ace8a3c68b0c35617510d98030a8526fd8f075109572680e2ab19ec91L21

player.h includes config.h. tagreaderclient.h does not. tagreaderclient.h includes core/workerpool.h which has this mac-specific macro with input that should be provided by config.h:
```
#if defined(Q_OS_MAC) && defined(USE_BUNDLE)
  search_path << qApp->applicationDirPath() + "/" + USE_BUNDLE_DIR;
#endif
```

**Comment by liofeu** [comment]
Many thanks @jbroadus, let me know if I can test anything.

**Comment by liofeu** [comment]
Yes, it does!
Many thanks
