### ISSUE TITLE
Visualization window scaling problem with scaled displays

### ISSUE THREAD

**Issue by mr-gittes** [clementine-player/Clementine#6957]
Bug? (app version 1.4 rc1, Qt 5.11.3, Linux)

The visualizations inside the visualization window don' fit to the window size when playing, i.e. on a 4k monitor with scaled display of 1.2 there is a (20%) black border on top and right of the visualization effects... no matter how large the window is (also in full screen).

If there is no display scaling (100%) in the system/monitor settings it will fit (but this workaround sucks of course...)

Any other (config) workarounds?

Thx!

**Comment by jbroadus** [comment]
Also reported here: #6651
