### ISSUE TITLE
Smart playlist feature 'file name starts with' not working on Ubuntu 20.10

### ISSUE THREAD

**Issue by dingeling** [clementine-player/Clementine#6958]
### Before posting

Please follow the steps below and check the boxes with [x] once you did the step.

- [x ] I checked the issue tracker for similar issues
- [ x] I checked the [changelog](https://github.com/clementine-player/Clementine/blob/master/Changelog) if the issue is already resolved
- [ x] I tried the latest Clementine build from [here](https://builds.clementine-player.org/)

### System information

Please provide information about your system and the version of Clementine used.

- Operating System: Ubuntu 20.10
- Clementine version: 1.4 rc2 from Ubuntu repository and latest git 1.4.0rc1-516-g8b566b2a7

### Expected behaviour / actual behaviour
using smart playlist feature with term "file name starts with" found files should be visible in list. files are located at "/mnt/Music". the executed query as seen in debug output is:

"SELECT ROWID,title, album, artist, albumartist, composer, track, disc, bpm, year, genre, comment, compilation, bitrate, samplerate, directory, filename, mtime, ctime, filesize, sampler, art_automatic, art_manual, filetype, playcount, lastplayed, rating, forced_compilation_on, forced_compilation_off, effective_compilation, skipcount, score, beginning, length, cue_path, unavailable, effective_albumartist, etag, performer, grouping, lyrics, originalyear, effective_originalyear FROM songs WHERE (filename LIKE 'file:///mnt/Music%') AND unavailable = 0 ORDER BY random()"

no results are shown. using SQLiteStudio with the same query i found 3269 entries.

i debugged clementine and found out "while (query->next()) { ... }" at src/library/librarybackend.cpp line 1106  isn't triggered

on windows the same step is working as expected.

### Steps to reproduce the problem (only for bugs)
use smart playlist feature with term "file name starts with"

![SQLiteStudio](https://user-images.githubusercontent.com/5067143/111993611-1d7a6000-8b17-11eb-96b1-5a05c01380ea.png)

**Comment by jbroadus** [comment]
This works on my fedora machine, but I can repro the issue on an ubuntu vm. It also fails on queries with the sqlite command line.

**Comment by jbroadus** [comment]
Okay, the filename is stored as a blob. On the newer sqlite version, the `like` function must be handling the conversion to text. Using the expression `CAST(filename as TEXT)` in the like clause works on the older Ubuntu version.

**Comment by dingeling** [comment]
I changed  src/smartplaylists/searchterm.cpp:328 from "filename" to "CAST(filename AS TEXT)" and can confirm it's working. But it may needs some more work depending on the sqlite version, i think.

![Clementine smart playlist](https://user-images.githubusercontent.com/5067143/112124838-1577fa00-8bc3-11eb-9ce0-35c68fdcfae1.png)
.

**Comment by jbroadus** [comment]
The cast still works on my newer version of sqlite, but there's another issue here. We encode the filename which produces `%` escaping, which is interpreted a wildcard. For these cases, we should use the ESCAPE clause to specify a character that gets encoded. Maybe `#`?

**Comment by jbroadus** [comment]
Ubuntu does have a version where this is fixed, but they disable it: 
https://git.launchpad.net/ubuntu/+source/sqlite3/tree/debian/rules?h=ubuntu/focal-updates#n48
Maybe SQLiteStudio uses its own sqlite build.
