### ISSUE TITLE
5.5 Star Rating

### ISSUE THREAD

**Issue by xrayspx** [clementine-player/Clementine#6969]
- Operating System: Kubuntu 20.10
- Clementine version: 1.4 rc2

I've found that it's possible to rate songs at higher than 5 stars using the Rating column to slide the rating to 5.5.  This will cause issues when creating playlists with a rule of "Rating equals 5 stars" for example.

### Steps to reproduce the problem (only for bugs)

In the playlist window, expand the Rating column so it's wider than it needs to be to display the 5 stars.  While rating a song, move the mouse beyond the 5 star rating to the right and click in the blank space of the expanded column.  This should rate the track 5.5 stars fairly consistently. 

To test, I've created a smart playlist with the rule Rating is Greater Than 5-Stars which currently contains 10% of songs I intended to rate a 5.

**Comment by jbroadus** [comment]
Fixed in the latest build.
https://github.com/clementine-player/Clementine/releases/tag/1.4.0rc1-533-gf4e70face

**Comment by xrayspx** [comment]
Brilliant, I've installed the new build and it's working as expected thanks!
