### ISSUE TITLE
Crashing on opening when on my laptop

### ISSUE THREAD

**Issue by tvgold42** [clementine-player/Clementine#6980]
### Before posting

Please follow the steps below and check the boxes with [x] once you did the step.

- [X] I checked the issue tracker for similar issues
- [X] I checked the [changelog](https://github.com/clementine-player/Clementine/blob/master/Changelog) if the issue is already resolved
- [X] I tried the latest Clementine build from [here](https://builds.clementine-player.org/)

### System information

Please provide information about your system and the version of Clementine used.

- Operating System: macOS Big Sur (M1 MacBook Pro, 8GB Ram)
- Clementine version: 1.3.1

### Expected behaviour / actual behaviour

The application to open as normal, however the application crashes on opening immediately.

### Steps to reproduce the problem (only for bugs)

Opening the application in any way

**Comment by hatstand** [comment]
>  I tried the latest Clementine build from here

Did you though?

**Comment by tvgold42** [comment]
> > I tried the latest Clementine build from here
> 
> Did you though?

Didn't realise there was a pre-release version, now fully updated and its working, my bad.

**Comment by hatstand** [comment]
No worries :-)
