### ISSUE TITLE
Usb not recognized as device

### ISSUE THREAD

**Issue by Garthhh** [clementine-player/Clementine#7003]
Manjaro
1.4.rc2

usb not detected as device, neither a new one or a reformatted one
sansdisk 16g cruzer glide

I added it as a folder in my music library, which let me put files on the usb , after organizing it
Which generated duplicates in the library
After unmounting the usb, clementine the duplicates remain Playlist>Remove duplicates from the playlist  removes the dups from the playlist, but not the library
I removed the folder from the music library
I can navigate to the usb & see all the files, functionality is limited
 
Sd cards are recognized, 

### Before posting

Please follow the steps below and check the boxes with [x] once you did the step.

- [ ] I checked the issue tracker for similar issues
- [ ] I checked the [changelog](https://github.com/clementine-player/Clementine/blob/master/Changelog) if the issue is already resolved
- [ ] I tried the latest Clementine build from [here](https://builds.clementine-player.org/)

### System information

Please provide information about your system and the version of Clementine used.

- Operating System:
- Clementine version:

**Comment by jbroadus** [comment]
Check to see if you have gvfs-mtp installed. I just installed Manjaro/XFCE and it's included, but I don't know about the KDE spin.

Also note that the latest version of Clementine on Arch is 1.4.0rc1+495+g10bf5dc17-2: https://archlinux.org/packages/community/x86_64/clementine/
Since somebody named a package rc2 at some point, you probably won't pick that up with an upgrade.

**Comment by Garthhh** [comment]
Thanks for the reply
I'm on a normal kde install , nothing off aur
I'm on the normal community version, 1.4.0rc1+495+g10bf5dc17-2  [notice the rc]
1.4.rc2 is the way Clementine lists it on the about page
gvfs-mtp 1.48 is installed

**Comment by jbroadus** [comment]
With the KDE spin, I was also able to see and open the device, though the behavior is a little odd. The device showed up with one name and when I double clicked to mount it, it shows a second device. It should have been able to recognize the two as the same device.

```
20:20:38.664 INFO  DeviceManager:358                Device added: "Gio/unmounted/139728439692240"
20:20:50.081 DEBUG Udisks2Lister:214                Adding pending job | DBus Path =  "/org/freedesktop/UDisks2/jobs/6"  | IsMountJob =  true  | First partition =  "/org/freedesktop/UDisks2/block_devices/sdb1"
20:20:50.136 DEBUG Udisks2Lister:278                Pending Job Completed | Path =  "/org/freedesktop/UDisks2/jobs/6"  | Mount? =  true  | Success =  true
20:20:50.150 DEBUG GioLister:302                    Skipping "16 GB Volume"
20:20:50.357 DEBUG Udisks2Lister:295                UDisks2 mount job finished: Drive =  "/org/freedesktop/UDisks2/drives/SanDisk_Ultra_20042400531130C39228"  | Partition =  "/org/freedesktop/UDisks2/block_devices/sdb1"
20:20:50.357 INFO  DeviceManager:358                Device added: "Udisks2/20042400531130C39228/SanDisk/Ultra/16008609792/7c5dc48c-0575-4a65-a0dc-0ff6deb9cb4c"
```

**Comment by Garthhh** [comment]
I tried some other u-disk usbs
The behavior is just the sansdisk 16g cruzer glide, I reformated one thinking the utilities/spyware/spam it came with could be the issue
Dolphin has no problem finding & mounting either
I can navigate to the one I side loaded with files through the clem files tab, even though devices, not so much
I copied the files to an sd, which clem thinks is a device & works with as expected
I've always struggled with the organize part as a playlist number is added, but there is no way to specify how that happens
Get the combination of file name & shuffled playlist right
an sd or usb plugged into a cheap mp3 player outputs the shuffled list of a couple of thousand files
The random on these kind of players seem to get stuck on a small group of files

In the end some changes in the way copy to device works, coupled with a problem with specific sansdisk hardware made me freak out & come over here searching for answers
The cherry on top was borking a couple of thousand files accidentally, which made me try to decide if my backup was current enough to revert to that, but that would not include the tags I added to describe the playlist
I opted to add the missing songs back from a copy of the playlist, deleting the empty folders as I went for book marking

As always working from the original bites me in the ass

Thanks for the replies
The bug is limited enough not to be worth the time to fix
