### ISSUE TITLE
MusicBrainzClient receiving status OK but malformed replies during musicbrainz outage

### ISSUE THREAD

**Issue by lumip** [clementine-player/Clementine#7027]
### Before posting

Please follow the steps below and check the boxes with [x] once you did the step.

- [x] I checked the issue tracker for similar issues
- [x] I checked the [changelog](https://github.com/clementine-player/Clementine/blob/master/Changelog) if the issue is already resolved
- [x] I tried the latest Clementine build from [here](https://builds.clementine-player.org/)

### System information

Please provide information about your system and the version of Clementine used.

- Operating System: Kubuntu 20.04 "Focal Fossa"
- Clementine version: current repository head

### Expected behaviour / actual behaviour
musicbrainz.org is currently experiencing issues / down for maintenance. Accordingly, making a discid request (e.g., `https://musicbrainz.org/ws/2/discid/fON9Bt2CFEdXrVQeKWR2YXH3WE0-?inc=artists+recordings`) returns a 502 error page in Firefox (and inspection of the received header also shows the 502 error code).
Weirdly, Clementine's `MusicBrainzClient` seems to be getting something different. Most importantly, it receives a 200 OK status code and thus does not perform any error logging. The body of the response appears to contain the same HTML error page displayed in Firefox, but followed by the usual expected XML metadata response. Because of the preprended HTML, parsing this reply fails, though, and e.g. CD ripper fails to fetch the song titles. I have redirected the entire body of the reply as received by `MusicBrainzClient` into a file that is attached below.

I'm very confused why clementine gets more information than other requests (it's not because of the User-Agent header field, see below). Is there potentially some caching of old requests going on? (I really don't belief so, though, as that would have to persist over several restarts of the program by now..) Some other crucial header fields? Is this just a fluke on the side of musicbrainz? I'm not even sure how to test this properly...

#### Manual poking musicbrainz.org using netcat
GET request for / gives 503:
```
$ nc musicbrainz.org 80 <<EOF
$ > GET / HTTP/1.1
$ > Host: musicbrainz.org
$ > 
$ > EOF
HTTP/1.1 503 Service Temporarily Unavailable
Server: openresty
Date: Mon, 17 May 2021 19:06:32 GMT
Content-Type: text/html
Content-Length: 580
Connection: keep-alive
Keep-Alive: timeout=15
ETag: "58025bc0-244"

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en-GB" lang="en-GB">
  <head>
    <title>503 Service Unavailable</title>
    <link rel="stylesheet" href="/.proxy/httperror.css" type="text/css" />
  </head>
  <body>
    <div id="bg">
      <img src="/.proxy/MusicBrainzLogo-Z.png" />
    </div>
    <h1>Server Maintenance</h1>
    <p>This site is down for maintenance.&nbsp; Please try again later.</p>
    <p id="http">503 Service Unavailable</p>
  </body>
</html>
```

GET request for discid gives 502:
```
$ nc musicbrainz.org 80 <<EOF
$ > GET https://musicbrainz.org/ws/2/discid/fON9Bt2CFEdXrVQeKWR2YXH3WE0-?inc=artists+recordings HTTP/1.1
$ > Host: musicbrainz.org
$ > User-Agent: Clementine 1.4.0rc1-600-g3f614464e
$ > 
$ > EOF
HTTP/1.1 502 Bad Gateway
Server: openresty
Date: Mon, 17 May 2021 18:55:46 GMT
Content-Type: text/html
Content-Length: 577
Connection: keep-alive
Keep-Alive: timeout=15
X-RateLimit-Limit: 1200
X-RateLimit-Remaining: 1146
X-RateLimit-Reset: 1621277748
ETag: "58025bc0-241"

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en-GB" lang="en-GB">
  <head>
    <title>502 Bad Gateway</title>
    <link rel="stylesheet" href="/.proxy/httperror.css" type="text/css" />
  </head>
  <body>
    <div id="bg">
      <img src="/.proxy/MusicBrainzLogo-Q.png" />
    </div>
    <h1>Server being naughty</h1>
    <p>One of our servers appears to be misbehaving.&nbsp; Please try again later.</p>
    <p id="http">502 Bad Gateway</p>
  </body>
</html>
```
#### Reply body received by `MusicBrainzClient` (status code was 200):
[httpReply.txt](https://github.com/clementine-player/Clementine/files/6496319/httpReply.txt)

code for creating the above file:
```
  QFile file("./httpReply.txt");
  file.open(QIODevice::OpenModeFlag::WriteOnly);
  file.write(reply->readAll());
  file.close();
```
inserted in `MusicBrainzClient::DiscIdRequestFinished`

**Comment by jbroadus** [comment]
One difference is that you're hitting port 80 with ncat. Maybe 443 hit a caching server before the error?

**Comment by lumip** [comment]
Good point, that might have been the case. I guess we can close this here. Clementine wasn't doing anything bad because of this and now we have some logging if this happens again. I'm not sure there's anymore that really can or even needs to be done about unexpected behavior in upstream services like this.
