### ISSUE TITLE
transcoder settings: Unknown encoder element: avenc_aac

### ISSUE THREAD

**Issue by Monospace-V** [clementine-player/Clementine#7049]
### Before posting

Please follow the steps below and check the boxes with [x] once you did the step.

- [x] I checked the issue tracker for similar issues
- [x] I checked the [changelog](https://github.com/clementine-player/Clementine/blob/master/Changelog) if the issue is already resolved
- [x] I tried the latest Clementine build from [here](https://builds.clementine-player.org/)

### System information

- Operating System: Windows 10
- Clementine version: Latest

### Expected behaviour / actual behaviour
Expected behaviour: AAC transcoding settings to show up
Actual:
![image](https://user-images.githubusercontent.com/76674645/123365197-71239c00-d593-11eb-8cd1-c175143cf762.png)

### Steps to reproduce the problem (only for bugs)
Open Clementine > Tools > Preferences > Transcoding > AAC

**Comment by jbroadus** [comment]
Thanks. I'll put together a settings widget for this one.
For reference: https://gstreamer.freedesktop.org/documentation/libav/avenc_aac.html

**Comment by jbroadus** [comment]
The latest build adds an options page for this element. I only added dials for bitrate and encoding algorithm, but the element exposes a lot of other properties. If there's a specific setting that you're looking for, feel free to request it.
https://github.com/clementine-player/Clementine/releases/tag/1.4.0rc1-663-gf9854e564
