### ISSUE TITLE
Segfault when closing clementine after converting files to MP3

### ISSUE THREAD

**Issue by lumip** [clementine-player/Clementine#7075]
### Before posting

Please follow the steps below and check the boxes with [x] once you did the step.

- [x] I checked the issue tracker for similar issues
- [x] I checked the [changelog](https://github.com/clementine-player/Clementine/blob/master/Changelog) if the issue is already resolved
- [x] I tried the latest Clementine build from [here](https://builds.clementine-player.org/)

### System information

Please provide information about your system and the version of Clementine used.

- Operating System: Kubuntu 20.04 (focal)
- Clementine version: current master

### Expected behaviour / actual behaviour
Clementine should always exit gracefully.

If Clementine is shut down after, at any time, converting a file to MP3 format, a segmentation fault will occur (in `TagLib::RefCounter::deref`).

### Steps to reproduce the problem (only for bugs)
- Use the file convesion dialog to convert any file to MP3 OR Rip a track from audio CD into MP3 format
- Close clementine

I'm not sure if this is just a bug in TagLib or if TagLib is used improperly within Clementine to cause this. Arguably this is not a pressing bug, because it is mostly invisible to users, but I was noticing it during debugging so I wanted to record it here.

**Comment by jonaski** [comment]
It's a cuased by a collision between the static taglib used in Clementine and the taglib used by gstreamer because they have the same namespace.
Compile with `-DUSE_SYSTEM_TAGLIB=ON` should solve it.

**Comment by lumip** [comment]
That was it. Thanks.
