### ISSUE TITLE
Overwrite transcoded files in source folder 

### ISSUE THREAD

**Issue by cmutts** [clementine-player/Clementine#7110]
Hello Team, I have a huge library with about 10,000 files in source folder. I want to mass transcode all the files from sample rate 48000 hertz to  44100 hertz. I don't want the files renamed or given a new extension. I just want them replaced or overwritten with the new transcoded files. I can't see this option at all. Is it possible?

**Comment by lumip** [comment]
This is currently not possible. I might add an option for this in the near future, though, this seems a nice feature to have.

**Comment by lumip** [comment]
Hi @cmutts.  Happy to announce that the newest pre-release builds [link](https://github.com/clementine-player/Clementine/releases/tag/1.4.0rc1-787-g1aaf74788) now have the functionality you requested.
