### ISSUE TITLE
GStreamer-CRITICAL: Trying to dispose element source, but it is in PAUSED instead of the NULL state.

### ISSUE THREAD

**Issue by AllKind** [clementine-player/Clementine#7115]
### Before posting

Please follow the steps below and check the boxes with [x] once you did the step.

- [x ] I checked the issue tracker for similar issues
- [ ] I checked the [changelog](https://github.com/clementine-player/Clementine/blob/master/Changelog) if the issue is already resolved
- [x ] I tried the latest Clementine build from [here](https://builds.clementine-player.org/)

### System information

Please provide information about your system and the version of Clementine used.

- Operating System: Linux Mint 19.3
- Clementine version: 1.4.0rc1-756-ga25887be5

### Expected behaviour / actual behaviour
Clementine should not freeze just playing local files.

### Steps to reproduce the problem (only for bugs)
Not sure how to reproduce, happend to me three times today. It just freezes, while you can hear the currently playing song until it finishes.
I think just by playing local files sequentially.

This is shown in the console:

> 17:20:32.912 DEBUG MainWindow:1596                  position: 310 , scrobble point: 315 , lastfm status: 0 , play count point: 315 , is local library item: true , playlist have incremented playcount:  false
> 17:20:36.982 DEBUG TagReader:1030                   Saving song rating tags to "/storage/pub/music/beets/albums/Salsa/Afro-Cuban_All_Stars/A_Toda_Cuba_le_Gusta/05-Afro-Cuban_All_Stars-Fiesta_de_la_Rumba.flac"
> 17:20:36.987 DEBUG MessageReply<MessageType>:89     Releasing ID 96 (finished)
> 17:20:36.987 DEBUG LibraryWatcher:707               Subdir "/storage/pub/music/beets/albums/Salsa/Afro-Cuban_All_Stars/A_Toda_Cuba_le_Gusta" changed under directory "/storage/pub/music" id 1
> 17:20:42.912 DEBUG MainWindow:1596                  position: 320 , scrobble point: 315 , lastfm status: 0 , play count point: 315 , is local library item: true , playlist have incremented playcount:  true
> 17:20:43.409 DEBUG LibraryWatcher:397               "/storage/pub/music/beets/albums/Salsa/Afro-Cuban_All_Stars/A_Toda_Cuba_le_Gusta/05-Afro-Cuban_All_Stars-Fiesta_de_la_Rumba.flac" changed
> 17:20:43.409 DEBUG _MessageReplyBase:24             Waiting on ID 97
> 17:20:43.409 DEBUG TagReader:167                    Reading tags from "/storage/pub/music/beets/albums/Salsa/Afro-Cuban_All_Stars/A_Toda_Cuba_le_Gusta/05-Afro-Cuban_All_Stars-Fiesta_de_la_Rumba.flac" . Got tags: size= 36062943 ; mtime= 1635870036 ; birthtime= 1635870036
> 17:20:43.410 DEBUG MessageReply<MessageType>:89     Releasing ID 97 (finished)
> 17:20:43.410 DEBUG _MessageReplyBase:26             Acquired ID 97
> 17:20:52.912 DEBUG MainWindow:1596                  position: 330 , scrobble point: 315 , lastfm status: 0 , play count point: 315 , is local library item: true , playlist have incremented playcount:  true
> 17:20:56.642 DEBUG TagReader:814                    Saving tags to "/storage/pub/music/beets/albums/Salsa/Afro-Cuban_All_Stars/A_Toda_Cuba_le_Gusta/05-Afro-Cuban_All_Stars-Fiesta_de_la_Rumba.flac"
> 17:20:56.644 DEBUG MessageReply<MessageType>:89     Releasing ID 98 (finished)
> 17:20:56.644 DEBUG LibraryWatcher:707               Subdir "/storage/pub/music/beets/albums/Salsa/Afro-Cuban_All_Stars/A_Toda_Cuba_le_Gusta" changed under directory "/storage/pub/music" id 1
> 17:20:56.687 DEBUG _MessageReplyBase:24             Waiting on ID 99
> 17:20:56.688 DEBUG TagReader:167                    Reading tags from "/storage/pub/music/beets/albums/Salsa/Afro-Cuban_All_Stars/A_Toda_Cuba_le_Gusta/05-Afro-Cuban_All_Stars-Fiesta_de_la_Rumba.flac" . Got tags: size= 36062943 ; mtime= 1635870056 ; birthtime= 1635870056
> 17:20:56.688 DEBUG MessageReply<MessageType>:89     Releasing ID 99 (finished)
> 17:20:56.688 DEBUG _MessageReplyBase:26             Acquired ID 99
> 17:21:02.912 DEBUG MainWindow:1596                  position: 340 , scrobble point: 315 , lastfm status: 0 , play count point: 315 , is local library item: true , playlist have incremented playcount:  true
> 17:21:03.066 DEBUG LibraryWatcher:397               "/storage/pub/music/beets/albums/Salsa/Afro-Cuban_All_Stars/A_Toda_Cuba_le_Gusta/05-Afro-Cuban_All_Stars-Fiesta_de_la_Rumba.flac" changed
> 17:21:03.066 DEBUG _MessageReplyBase:24             Waiting on ID 100
> 17:21:03.066 DEBUG TagReader:167                    Reading tags from "/storage/pub/music/beets/albums/Salsa/Afro-Cuban_All_Stars/A_Toda_Cuba_le_Gusta/05-Afro-Cuban_All_Stars-Fiesta_de_la_Rumba.flac" . Got tags: size= 36062943 ; mtime= 1635870056 ; birthtime= 1635870056
> 17:21:03.067 DEBUG MessageReply<MessageType>:89     Releasing ID 100 (finished)
> 17:21:03.067 DEBUG _MessageReplyBase:26             Acquired ID 100
> 17:21:03.067 DEBUG LibraryWatcher:600               "/storage/pub/music/beets/albums/Salsa/Afro-Cuban_All_Stars/A_Toda_Cuba_le_Gusta/05-Afro-Cuban_All_Stars-Fiesta_de_la_Rumba.flac" metadata changed
> 17:21:06.486 DEBUG TagReader:814                    Saving tags to "/storage/pub/music/beets/albums/Salsa/Afro-Cuban_All_Stars/A_Toda_Cuba_le_Gusta/03-Afro-Cuban_All_Stars-Habana_del_Este.flac"
> 17:21:06.493 DEBUG MessageReply<MessageType>:89     Releasing ID 101 (finished)
> 17:21:06.493 DEBUG LibraryWatcher:707               Subdir "/storage/pub/music/beets/albums/Salsa/Afro-Cuban_All_Stars/A_Toda_Cuba_le_Gusta" changed under directory "/storage/pub/music" id 1
> 17:21:06.532 DEBUG _MessageReplyBase:24             Waiting on ID 102
> 17:21:06.532 DEBUG TagReader:167                    Reading tags from "/storage/pub/music/beets/albums/Salsa/Afro-Cuban_All_Stars/A_Toda_Cuba_le_Gusta/03-Afro-Cuban_All_Stars-Habana_del_Este.flac" . Got tags: size= 43416887 ; mtime= 1635870066 ; birthtime= 1635870066
> 17:21:06.533 DEBUG MessageReply<MessageType>:89     Releasing ID 102 (finished)
> 17:21:06.533 DEBUG _MessageReplyBase:26             Acquired ID 102
> 
> (clementine:84708): GStreamer-CRITICAL **: 17:21:11.263: 
> Trying to dispose element source, but it is in PAUSED instead of the NULL state.
> You need to explicitly set elements to the NULL state before
> dropping the final reference, to allow them to clean up.
> This problem may also be caused by a refcounting bug in the
> application or some element.
> 
> 
> (clementine:84708): GStreamer-CRITICAL **: 17:21:11.263: 
> Trying to dispose element uridecodebin-16, but it is in PLAYING instead of the NULL state.
> You need to explicitly set elements to the NULL state before
> dropping the final reference, to allow them to clean up.
> This problem may also be caused by a refcounting bug in the
> application or some element.
> 
> 17:21:11.273 DEBUG GstEnginePipeline:877            Decoder bin pad added: src_0
> 17:21:11.273 DEBUG GstEnginePipeline:890            Initial decoder caps: audio/x-raw, format=(string)S16LE, layout=(string)interleaved, rate=(int)44100, channels=(int)2, channel-mask=(bitmask)0x0000000000000003
> 17:21:11.273 DEBUG GstEnginePipeline:896            Ignoring native format since pipeline is already running.
> 17:21:12.919 DEBUG LibraryWatcher:397               "/storage/pub/music/beets/albums/Salsa/Afro-Cuban_All_Stars/A_Toda_Cuba_le_Gusta/03-Afro-Cuban_All_Stars-Habana_del_Este.flac" changed
> 17:21:12.919 DEBUG _MessageReplyBase:24             Waiting on ID 103
> 17:21:12.919 DEBUG TagReader:167                    Reading tags from "/storage/pub/music/beets/albums/Salsa/Afro-Cuban_All_Stars/A_Toda_Cuba_le_Gusta/03-Afro-Cuban_All_Stars-Habana_del_Este.flac" . Got tags: size= 43416887 ; mtime= 1635870066 ; birthtime= 1635870066
> 17:21:12.920 DEBUG MessageReply<MessageType>:89     Releasing ID 103 (finished)
> 17:21:12.920 DEBUG _MessageReplyBase:26             Acquired ID 103
> 17:21:12.920 DEBUG LibraryWatcher:600               "/storage/pub/music/beets/albums/Salsa/Afro-Cuban_All_Stars/A_Toda_Cuba_le_Gusta/03-Afro-Cuban_All_Stars-Habana_del_Este.flac" metadata changed
> 17:21:16.593 DEBUG GstEnginePipeline:657            New segment started, EOS will signal on next buffer discontinuity
> 17:21:16.593 DEBUG GstEnginePipeline:1039           Buffer discontinuity - emitting EOS

**Comment by AllKind** [comment]
I believe this was introduced with:
https://github.com/clementine-player/Clementine/tree/1.4.0rc1-753-g7b8b477d0
As I just updated to newest version today and never encountered that problem before.

**Comment by trougnouf** [comment]
I confirm this bug is present on Arch Linux with clementine 1.4.0rc1+755+g568ff1f9d-1.

Clementine crashes consistently as soon as a song is over. The end of my terminal output is
```
g_mutex_clear() called on uninitialised or locked mutex
Aborted (core dumped)
```

**Comment by mohamedation** [comment]
same issue on Arch with Version 1.4 rc2

```
(clementine:65469): GStreamer-CRITICAL **: 12:33:14.749: 
Trying to dispose element uridecodebin-0, but it is in PLAYING instead of the NULL state.
You need to explicitly set elements to the NULL state before
dropping the final reference, to allow them to clean up.
This problem may also be caused by a refcounting bug in the
application or some element.

(clementine:65469): GStreamer-CRITICAL **: 12:33:14.749: 
Trying to dispose element source, but it is in PAUSED instead of the NULL state.
You need to explicitly set elements to the NULL state before
dropping the final reference, to allow them to clean up.
This problem may also be caused by a refcounting bug in the
application or some element.

g_mutex_clear() called on uninitialised or locked mutex
[1]    65469 abort (core dumped)  clementine
```

**Comment by weearc** [comment]
same issue on `1.4.0rc1+755`, but version 752 cannot be found on archive.archlinux.org and have to build `1.4.0rc1-753-g7b8b477d0` which works perfectly.

**Comment by d10sfan** [comment]
Same issue, after playing a song, the player would freeze and I'd have to kill it.

**Comment by heldbrendel** [comment]
Can confirm, the bug is present in version `1.4.0rc1+755+g568ff1f9d`. Had to revert back to `1.4.0rc1+495+g10bf5dc17` for it to be working again.

**Comment by ivovegter** [comment]
I also have this problem, and had to downgrade to version 1.4.0rc1+495+g10bf5dc17-4. Confirmed on Arch Linux under both X+XFCE and Wayland+Sway, if that makes any difference (it probably doesn't).

**Comment by shaygover** [comment]
+1 for Arch. Used 495 from Arch.

**Comment by eris-price** [comment]
Also having this issue on arch using X+cinnamon, had to downgrade to 495

**Comment by weearc** [comment]
If someone need these downgradge version, I packed it using clementine-git from aur and uploaded these here. Use at your own risk.
[clementine-git.zip](https://github.com/clementine-player/Clementine/files/7487388/clementine-git.zip)
[clementine-git-pkgbuild.zip](https://github.com/clementine-player/Clementine/files/7487392/clementine-git-pkgbuild.zip)

**Comment by AllKind** [comment]
The revert seems to fix it -> closing.
