### ISSUE TITLE
Apache2 Ubuntu Default Page appears when I try to connect to OneDrive

### ISSUE THREAD

**Issue by Temoshee** [clementine-player/Clementine#7122]
### Before posting

Please follow the steps below and check the boxes with [x] once you did the step.

- [X] I checked the issue tracker for similar issues
- [X] I checked the [changelog](https://github.com/clementine-player/Clementine/blob/master/Changelog) if the issue is already resolved
- [X] I tried the latest Clementine build from [here](https://builds.clementine-player.org/)

### System information

Please provide information about your system and the version of Clementine used.

- Operating System: ZorinOS 16 
- Clementine version: 1.4 rc1

### Expected behaviour / actual behaviour
Expected: When configuring OneDrive access it should allow me to connect
Actual: I get a message that Clementine connected but it goes to a default Apache2 Ubuntu Default page and inside the app I cannot access OneDrive

### Steps to reproduce the problem (only for bugs)
Click on Tools --> Preferences --> Internet Providers --> OneDrive --> Login
Login in to your OneDrive account and grant access to Clementine
Go back to the Clementine desktop app and see the lack of a connection to OneDrive

**Comment by jbroadus** [comment]
The OneDrive code was reworked a few months ago, but I don't think Debian and descendants have updated recently. Try grabbing the lastest focal version here: https://github.com/clementine-player/Clementine/releases/tag/1.4.0rc1-761-gb747423b5

**Comment by Temoshee** [comment]
Thanks! The Focal .deb file works fine.
