### ISSUE TITLE
Silent or stuttering playback after seeking within playing track

### ISSUE THREAD

**Issue by adatum** [clementine-player/Clementine#7128]
### Before posting

Please follow the steps below and check the boxes with [x] once you did the step.

- [ x ] I checked the issue tracker for similar issues
- [ x ] I checked the [changelog](https://github.com/clementine-player/Clementine/blob/master/Changelog) if the issue is already resolved
- [ x ] I tried the latest Clementine build from [here](https://builds.clementine-player.org/)

### System information

Please provide information about your system and the version of Clementine used.

- Operating System: Fedora 35 MATE
- Clementine version: clementine-1.4.0-7.rc1.20210104git479f1d4.fc35.3.x86_64 from Fedora's repository and also clementine-1.4.0rc1-2.762.g590ab22f8.fc35.x86_64.rpm downloaded from Clementine's GitHub releases: https://github.com/clementine-player/Clementine/releases/tag/1.4.0rc1-762-g590ab22f8

### Expected behaviour / actual behaviour
Seeking through a track, whether with the mouse or keyboard shortcuts, sometimes  causes the playback to go silent or stutter. Other times it plays as normal. It seems unpredictable, but the problem occurs frequently.

### Steps to reproduce the problem (only for bugs)
1. Play a track
2. Seek forward or backwards within the track, with mouse or keyboard shortcuts
3. Repeat step 2 if problem is not observed immediately

Bugzilla report: https://bugzilla.redhat.com/show_bug.cgi?id=2027016

Seeking was tried on different audio files and it is not isolated to a specific file or type. 
Also, seeking was tried with other media players such as VLC and SMPlayer which do not exhibit the problem to rule out a system-wide audio issue.

**Comment by oMoMa** [comment]
Same problem using latest build on Archlinux

**Comment by deswatson** [comment]
This may well not be a clementine bug. This behaviour started with the introduction of wireplumber in Fedora 35. It was briefly mended with a wireplumber update, but the latest update has broken it again. For more details see [this.](https://ask.fedoraproject.org/t/erratic-audio-in-fedora-35/18474/3)

**Comment by adatum** [comment]
> This may well not be a clementine bug. This behaviour started with the introduction of wireplumber in Fedora 35. It was briefly mended with a wireplumber update, but the latest update has broken it again. For more details see this.

Is there a bug report for this against wireplumber?

**Comment by pranaypratyush** [comment]
I was using `wireplumber` but moved to `pipewire-media-session` but the issue still persists.

**Comment by deswatson** [comment]
There are some weirdnesses here. My Fedora 35 system has now started behaving again, playing without stuttering after repeated seeking - and I haven't made any updates or indeed rebooted it. Haven't had time to investigate further, but it's on the list, despite the fact that I have little idea for a sensible next step in the investigation...!

**Comment by pranaypratyush** [comment]
Very weird that when this bug does its thing and I open up the volume control on KDE I can hear the music but its stuttering. 
When I close it it's back to silent.

**Comment by pranaypratyush** [comment]
Another weird thing is that  I  moved to `pipewire-media-session` and restarted the services and clementine and the big was gone but I restarted things again without changing anything and it's back. Doesn't make any sense at so many levels.

**Comment by pranaypratyush** [comment]
I fixed this issue by adding `/etc/pipewire/media-session.d/alsa-monitor.conf` :
```
rules = [
  {
    matches = [
      {
        device.name = "alsa_card.usb-FiiO_DigiHug_USB_Audio-01"
      }
    ]
    actions = {
      update-props = {
        device.nick = "Fiio"
        audio.format = "S24_3LE"
        audio.rate = 48000
        # Following value should be doubled until audio doesn't cut out or other issues stop occurring
        api.alsa.period-size = 4096
      }
    }
  }
]
```
Could be device-specific but other players don't face this issue even without this file.

**Comment by adatum** [comment]
I can confirm this issue with Rhythmbox too, so this is not specific to Clementine.

Is there a bug report for the broader issue?

**Comment by mozai** [comment]
Seeing (or not-hearing) this in version 1.4rc2 on Manjaro Linux, pipewire 0.3.63 .  Output device "choose automatically"
No problems with VLC, mocp, mpv nor mplayer.

**Comment by adatum** [comment]
This issue was fixed a long time ago. It was due to a dependency, and not specific to clementine.

**Comment by ValdikSS** [comment]
Anyone has this bug again, on Fedora 37 (wireplumber 0.4.14, pipewire 0.3.70)?
Changing to ALSA backend fixes the issue.

https://github.com/clementine-player/Clementine/assets/3054729/30797bfb-9bd3-44bc-8be8-b5914909a958

**Comment by adatum** [comment]
@ValdikSS No issues here with Fedora 37, wireplumber 0.4.14, pipewire 0.3.70, and clementine version 1.4.0 release 2.rc1.20220107git0be3143.fc36. I didn't realize I haven't upgraded clementine in so long. Maybe check your clementine version. In any case, the root cause of this issue originally seemed to be due to Gstreamer.

**Comment by adatum** [comment]
Actually, I have started encountering this issue again (Fedora 37, wireplumber 0.4.14, pipewire 0.3.71, gstreamer1 1.20.5) though less frequently than before. Not sure where the source of the issue is, though last time it wasn't with clementine.

**Comment by hxorasani** [comment]
I stilll have this prob on 1.4rc2 on ubuntu 23.04, switched to audacious.
