### ISSUE TITLE
Google Drive Files Not Playing: missing plugin error on Ubuntu 20.04.3

### ISSUE THREAD

**Issue by mikemp7** [clementine-player/Clementine#7132]
### Before posting

Please follow the steps below and check the boxes with [x] once you did the step.

- [x] I checked the issue tracker for similar issues
- [x] I checked the [changelog](https://github.com/clementine-player/Clementine/blob/master/Changelog) if the issue is already resolved
- [x] I tried the latest Clementine build from [here](https://builds.clementine-player.org/)

### System information

Please provide information about your system and the version of Clementine used.

- Operating System: Ubuntu 20.04.3 LTS 64bit 
- Clementine version: Clementine Version 1.4 rc1

### Expected behaviour / actual behaviour
I added a Google Drive folder with my music files. The files are added to my library and all metadata is downloaded properly, indicating that the auth is working correctly. 

Expected behaviour: the file will play. 
Observed behaviour: the file does not play and the app quickly skips ahead to the next track in the queue. 

I have these errors in terminal:
```
__logging_message__11:13:24.807 WARN  unknown                          libpng warning: iCCP: known incorrect sRGB profile
11:13:31.368 ERROR google_drive::Client:167         Failed to fetch file with ID "/1i3bay489tQa-KpfMprouceVJw58UnDul"
11:13:31.373 ERROR GstEnginePipeline:687            1 "gsturidecodebin.c(1383): gen_source_element (): /GstPipeline:pipeline/GstURIDecodeBin:uridecodebin-0"
11:13:31.373 ERROR logging:57                       Source ID 23 was not found when attempting to remove it
__logging_message__11:13:31.376 WARN  unknown                          QTimeLine::start: already running
11:13:33.965 ERROR google_drive::Client:167         Failed to fetch file with ID "/1i3bay489tQa-KpfMprouceVJw58UnDul"
11:13:33.968 ERROR GstEnginePipeline:687            2 "gsturidecodebin.c(1383): gen_source_element (): /GstPipeline:pipeline/GstURIDecodeBin:uridecodebin-15"
11:13:33.968 ERROR logging:57                       Source ID 24 was not found when attempting to remove it
__logging_message__11:13:33.970 WARN  unknown                          QTimeLine::start: already running
11:13:35.037 ERROR google_drive::Client:167         Failed to fetch file with ID "/1i3bay489tQa-KpfMprouceVJw58UnDul"
11:13:35.040 ERROR GstEnginePipeline:687            3 "gsturidecodebin.c(1383): gen_source_element (): /GstPipeline:pipeline/GstURIDecodeBin:uridecodebin-30"
11:13:35.040 ERROR logging:57                       Source ID 25 was not found when attempting to remove it
__logging_message__11:13:35.042 WARN  unknown                          QTimeLine::start: already running
11:13:37.792 ERROR StreamDiscoverer:54              Discovery failed: "Missing plugins" 

11:13:43.234 ERROR google_drive::Client:167         Failed to fetch file with ID "/1i3bay489tQa-KpfMprouceVJw58UnDul"
11:13:43.237 ERROR GstEnginePipeline:687            4 "gsturidecodebin.c(1383): gen_source_element (): /GstPipeline:pipeline/GstURIDecodeBin:uridecodebin-45"
11:13:43.237 ERROR logging:57                       Source ID 28 was not found when attempting to remove it
__logging_message__11:13:43.239 WARN  unknown                          QTimeLine::start: already running
__logging_message__11:13:43.240 WARN  unknown                          QTimeLine::start: already running
11:13:43.280 ERROR google_drive::Client:167         Failed to fetch file with ID "/1i3bay489tQa-KpfMprouceVJw58UnDul"
11:13:43.283 ERROR GstEnginePipeline:687            5 "gsturidecodebin.c(1383): gen_source_element (): /GstPipeline:pipeline/GstURIDecodeBin:uridecodebin-60"
11:13:43.283 ERROR logging:57                       Source ID 29 was not found when attempting to remove it
__logging_message__11:13:43.285 WARN  unknown                          QTimeLine::start: already running

```

When I right click on a file and click "View Stream Details" I see this error: 
`Error discovering googledrive:/1i3bay489tQa-KpfMprouceVJw58UnDul: Missing plugins
`
What I've tried: 
- Installed gstreamer plugins (no changes) 
- Tried different versions of Clementine (no changes)
- Tried the same steps on Clementine on my Debian computer (it works there!) 
- Re-authed the drive connection and re-synced library (no changes) 

Video: https://photos.app.goo.gl/4Hy6kFqTUaq6iX7j9

### Steps to reproduce the problem (only for bugs)
1. Install Clementine Version 1.4 rc1 on Ubuntu 20.04.3
2. Add Google Drive folder with music files 
3. Attempt to play the files  

Do you have any ideas to fix and/or to understand which specific plugin is having issues? Thank you!

**Comment by hatstand** [comment]
> I tried the latest Clementine build from here

Did you?

**Comment by mikemp7** [comment]
I did previously and it didn't work. I just built from source and it worked. Version 1.4.0rc1-768-gb1e750c52. Sorry. Thanks for the help and the work, love Clementine!
