### ISSUE TITLE
Can't log in to Spotify with Clementine

### ISSUE THREAD

**Issue by DoctorHamster** [clementine-player/Clementine#7167]
Hello,
I just downloaded Clementine and tried to log in with Spotify but it says Bad username and/or password. Anybody knows why it's saying that? And, aye, I'm using the correct username and password.

Thanks

**Comment by Eris-JBG** [comment]
I'm experiencing the same issue on clementine 1.4 rc2 on Arch linux, installed from the main arch repos. I have a spotify premium acct, and I've tried both my sign in email, and the username string as the username, and neither work, it just spins forever. I saw an old post about symlinking libprotobuf into the spotify blob folder in ~/.config/Clementine, and this also did not solve the issue. Any help would be greatly appreciated.

**Comment by eris-price** [comment]
I'm experiencing the same issue on clementine 1.4 rc2 on Arch linux, installed from the main arch repos. I have a spotify premium acct, and I've tried both my sign in email, and the username string as the username, and neither work, it just spins forever. I saw an old post about symlinking libprotobuf into the spotify blob folder in ~/.config/Clementine, and this also did not solve the issue. Any help would be greatly appreciated.

**Comment by RichLuna** [comment]
Same issue here in Debian 11, Clementine 1.4 rc2.

While running in verbose mode I get:

/home/user/.config/Clementine/spotifyblob/version16-64bit/blob: error while loading shared libraries: libQtCore.so.4: cannot open shared object file: No such file or directory

**Comment by eris-price** [comment]
> I'm experiencing the same issue on clementine 1.4 rc2 on Arch linux, installed from the main arch repos. I have a spotify premium acct, and I've tried both my sign in email, and the username string as the username, and neither work, it just spins forever. I saw an old post about symlinking libprotobuf into the spotify blob folder in ~/.config/Clementine, and this also did not solve the issue. Any help would be greatly appreciated.

I was able to solve my issue by installing qt4, which for whatever reason seems to be a requirement for clementine's spotify integration despite it being a qt5 application

**Comment by RichLuna** [comment]
The issue seems to be also present in the flatpak version, so I guess this is unintended.

In Debian 11 all QT4 libraries have been removed so they would need to be compiled. A little excessive for a simple workaround.

**Comment by kblaschke** [comment]
Spotify actually sunset libspotify on May 16th 2022, effectively making it useless:

https://developer.spotify.com/community/news/2022/04/12/libspotify-sunset/

There's no alternative available, just the (limited) web playback SDK. Unless Spotify implements a real replacement, or some developers reverse-engineer the newer P2P and server protocols, there won't be any alternative.
