### ISSUE TITLE
Build fails on m1 macbook at last step after running `make -j8`

### ISSUE THREAD

**Issue by parz3val** [clementine-player/Clementine#7194]
### Before posting

Please follow the steps below and check the boxes with [x] once you did the step.

- [ x] I checked the issue tracker for similar issues
- [ x] I checked the [changelog](https://github.com/clementine-player/Clementine/blob/master/Changelog) if the issue is already resolved
- [ x] I tried the latest Clementine build from [here](https://builds.clementine-player.org/)

### System information

Please provide information about your system and the version of Clementine used.

- Operating System: Macos Monterey, M1 Air
- Clementine version: 1.3+

### Expected behaviour / actual behaviour
Succcessful build on macos. 

### Steps to reproduce the problem (only for bugs)

Follow the build guide for the macos
```xcode-select --install
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
brew install glib pkgconfig cmake boost protobuf protobuf-c qt cryptopp gettext gstreamer gst-plugins-base gst-plugins-good gst-plugins-bad gst-plugins-ugly gst-plugins-libav
brew tap tomahawk-player/homebrew-tomahawkqt5
brew install tomahawk-player/homebrew-tomahawkqt5/liblastfm
sudo ln -s /usr/local/include/lastfm /usr/local/include/lastfm5
export Qt5_DIR=/usr/local/opt/qt5/lib/cmake
export Qt5LinguistTools_DIR=/usr/local/Cellar/qt/5.11.2/lib/cmake/Qt5LinguistTools
export GST_SCANNER_PATH=/usr/local/Cellar/gstreamer/1.14.4/libexec/gstreamer-1.0/gst-plugin-scanner
export GST_PLUGIN_PATH=/usr/local/lib/gstreamer-1.0
export PATH="/usr/local/opt/gettext/bin:$PATH"

git clone https://github.com/clementine-player/Clementine
cd Clementine
cd bin
cmake ..
make -j8
```
I followed the steps there and I used this
```https://github.com/clementine-player/Clementine/blob/master/.github/workflows/all.yml#L883``` for reference as well. I had to correct few paths but I was able to get it working to the point of running cmake which successfully completes.  

But, when I run `make -j8` I get the error 

```
1 warning generated.
[100%] Linking CXX executable ../clementine.app/Contents/MacOS/clementine
ld: library not found for -lcdio
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [clementine.app/Contents/MacOS/clementine] Error 1
make[1]: *** [src/CMakeFiles/clementine.dir/all] Error 2
make: *** [all] Error 2
```

I've been able to figure this out. Any help would be appreciated.

**Comment by gamedevsam** [comment]
Can we get some visibility on this? I'm on an M1 as well and want to contribute to the development of my favorite music player :)

**Comment by trg818** [comment]
I think you need to do
`brew install libcdio`
as well; at least I did. My compilation attempt fails because xgettext is not found (although I did install gettext), though.

**Comment by parz3val** [comment]
yes. it still fails

**Comment by ClintEsteMadera** [comment]
This issue is almost 5 months old. The only stable build for Mac does not work for me on a MBP with a M1 pro chip. Could you please create a build that works with this architecture? This is only the beginning... more and more people are buying the latest Macs and this issue will be a blocker for more and more people....

**Comment by trg818** [comment]
Frankly, I have given up on this since my last attempt and have since then used Strawberry, which has so far worked fairly well, except from occasional hang-ups. Its basic functionality is similar enough to that of Clementine, of which it is a derivate.

**Comment by Kingcow** [comment]
I think you add the following line (depending on your version of libcdio) to [CMakeLists.txt](https://github.com/clementine-player/Clementine/blob/9ef681b0e9e945c662905c1ffc5e179dd8e04d3c/CMakeLists.txt).
`link_directories("/opt/homebrew/Cellar/libcdio/2.1.0/lib")`
