### ISSUE TITLE
Getting a wierd error message on arch linux

### ISSUE THREAD

**Issue by CloudyWhale** [clementine-player/Clementine#7199]
### Before posting

Please follow the steps below and check the boxes with [x] once you did the step.

- [x] I checked the issue tracker for similar issues
- [x] I checked the [changelog](https://github.com/clementine-player/Clementine/blob/master/Changelog) if the issue is already resolved
- [x] I tried the latest Clementine build from [here](https://builds.clementine-player.org/)

### System information

Please provide information about your system and the version of Clementine used.

- Operating System: Arch Linux
- Clementine version: 1.4.0rc2-2

### Expected behavior / actual behavior
Expected:
Program opens
Actual behavior:
I get this error: clementine: symbol lookup error: clementine: undefined symbol: _ZN6google8protobuf8internal16InternalMetadataD1Ev

### Steps to reproduce the problem (only for bugs)
run "sudo pacman -S clementine" to install
then run "clementine"

**Comment by CloudyWhale** [comment]
I think it's an Issue with something called protobuf

**Comment by CloudyWhale** [comment]
Clementine looks ugly I don;t care anymore

**Comment by fitojb** [comment]
Okay, I guess…
