### ISSUE TITLE
OGG files not indexed in library

### ISSUE THREAD

**Issue by sir-farfan** [clementine-player/Clementine#7213]
### Before posting

Please follow the steps below and check the boxes with [x] once you did the step.

- [ x ] I checked the issue tracker for similar issues
- [ x ] I checked the [changelog](https://github.com/clementine-player/Clementine/blob/master/Changelog) if the issue is already resolved
- [  ] I tried the latest Clementine build from [here](https://builds.clementine-player.org/)

### System information

- Operating System: Debian Testing
- Clementine version:  clementine/testing,now 1.4.0~rc1+git347-gfc4cb6fc7+dfsg-2.1 amd64

### Expected behaviour / actual behaviour
OGG files indexed in the library

### Steps to reproduce the problem (only for bugs)
Add ID3v2.3 tag information to OGG files using EasyTAG 
Refresh the library

### more info
I re encoded some files as OGG (because what could go wrong?)
Clementine can play the files if I put them directly in the playlist, however, info is guessed from the file name instead of the tag.
The songs won't show in the library neither with the tag nor with the file name info, or at least I haven't been able to find the songs with that.
mpv plays and shows the tag file info correctly with the cover and everything.

Someone reported a similar issue 5 years ago (#5685) but didn't receive any replays.

Any ideas?
Do I need to install some extra libraries maybe?

**Comment by fabi321** [comment]
See https://github.com/clementine-player/Clementine/issues/5685#issuecomment-1320964523 for a workaround
