### ISSUE TITLE
Unable to authenticate with Spotify.

### ISSUE THREAD

**Issue by rokejulianlockhart** [clementine-player/Clementine#7235]
### Before posting

- [x] I checked the issue tracker for similar issues
- [ ] I checked the [changelog](https://github.com/clementine-player/Clementine/blob/master/Changelog) if the issue is already resolved
- [ ] I tried the latest Clementine build from [here](https://builds.clementine-player.org/)

### System information

- Operating System: `posix.uname_result(sysname='Linux', nodename='beedell.rokejulianlockhart.1669806072', release='6.0.10-200.fc36.x86_64', version='#1 SMP PREEMPT_DYNAMIC Sat Nov 26 16:53:11 UTC 2022', machine='x86_64')`
- Clementine version: 1.4 rc2

### Expected behaviour / actual behaviour
Clementine should be able to authenticate with Spotify because my account is subscribed to Premium, yet it is unable to.

### Steps to reproduce the problem (only for bugs)
Provide account-relevant information—specifically, the username and password—and invoke Login.

**Comment by adem4ik** [comment]
Afaik Spotify support is dropped:
https://github.com/clementine-player/Clementine/issues/7200
https://github.com/clementine-player/Clementine/commit/a551c40c4eaa4c0b603bd4436f762ef33db968ad
