### ISSUE TITLE
Playing files from MTP devices doesn't work

### ISSUE THREAD

**Issue by Clementine-Issue-Importer** [clementine-player/Clementine#724]
_From [gillet.gui](https://code.google.com/u/110188699169664183429/) on September 11, 2010 18:00:15_

What steps will reproduce the problem? 1.Plug a Creative Zen MP3 player
2.Try to launch a song

The song is added to the playlist but we get an error like :
Invalid URI "Music/Queens&#37;20Of&#37;20The&#37;20Stone&#37;20Age/(2007)&#37;20Era&#37;20Vulgaris/01&#37;20-&#37;20Turnin'&#37;20on&#37;20the&#37;20Screw.mp3". What version of the product are you using? On what operating system? Clementine v0.5 RC1 for Windows on Windows Vista (Yeah, sorry about that) Please provide any additional information below. Also, when I try to transfer a song to this device the "OK" Button is diactivated.

_Original issue: http://code.google.com/p/clementine-player/issues/detail?id=724_

**Comment by Chocobozzz** [comment]
.
