### ISSUE TITLE
Global hotkeys are not working when caps-lock is pressed

### ISSUE THREAD

**Issue by Clementine-Issue-Importer** [clementine-player/Clementine#741]
_From [lifeissecret](https://code.google.com/u/116827120866829281287/) on September 13, 2010 17:04:45_

What steps will reproduce the problem? 1. Set global hotkey (e,g, Ctrl+T) for Play/Pause
2. Minimize Clementine to tray
3. Press Caps (I use caps to change keyboard layout, so I pressed Shift+Caps instead)
4. Press Ctrl+T What is the expected output? What do you see instead? Hot key doesn't work when caps is activated What version of the product are you using? On what operating system? Clementine 0.4.2, Qt 4.7.0-rc1, Gentoo Please provide any additional information below. Media keys are not working either when caps is on

_Original issue: http://code.google.com/p/clementine-player/issues/detail?id=741_

**Comment by Chocobozzz** [comment]
Closing this old issue. Feel free to re open.
