### ISSUE TITLE
add insets to play list cells

### ISSUE THREAD

**Issue by Clementine-Issue-Importer** [clementine-player/Clementine#754]
_From [andrew.gaydenko](https://code.google.com/u/andrew.gaydenko/) on September 15, 2010 12:45:45_

In accordance with this group conversation: http://groups.google.com/group/clementine-player/browse_thread/thread/00a8c13ed293dcaf#

_Original issue: http://code.google.com/p/clementine-player/issues/detail?id=754_

**Comment by Chocobozzz** [comment]
Obsolete.
