### ISSUE TITLE
Delete from disk fails when files do not exist

### ISSUE THREAD

**Issue by Clementine-Issue-Importer** [clementine-player/Clementine#787]
_From [gms8994](https://code.google.com/u/112543938082916096616/) on September 21, 2010 22:16:06_

What steps will reproduce the problem? 1. Right click on files in Library pane that do not exist, but are still in the library
2. Click 'Delete from disk'
3. Watch as clementine says that the files couldn't be found, but nothing else happens

I would expect that the songs would be removed from the library.

_Original issue: http://code.google.com/p/clementine-player/issues/detail?id=787_

**Comment by Chocobozzz** [comment]
Closing this old one. Feel free to reopen.
