### ISSUE TITLE
gstreamer backend broken with 0.10.30

### ISSUE THREAD

**Issue by Clementine-Issue-Importer** [clementine-player/Clementine#791]
_From [elan.ruusamae](https://code.google.com/u/113116052157326853629/) on September 22, 2010 17:42:04_

worked when i had gstreamer 0.10.29, so i suspect clementine is using something private from gstreamer api, which it shouldn't. or just doing it wrong.

i tried with 0.5 and with 0.5.1, but it's still broken

UI error when playing .mp3 says:

GStreamer could not create the element: volume. Please make sure that you have installed all necessary GStreamer plugins (e.g. OGG and MP3)

on console it says:
(<unknown>:25885): GStreamer-CRITICAL **: 
Trying to dispose object "audiobin", but it still has a parent "pipeline".
You need to let the parent manage the object instead of unreffing the object directly.

gst itself works ok from commandline:
$ gst-launch filesrc location="test.mp3" ! mad ! pulsesink
Setting pipeline to PAUSED ...
Pipeline is PREROLLING ...
Pipeline is PREROLLED ...
Setting pipeline to PLAYING ...
New clock: GstPulseSinkClock
^CCaught interrupt -- handling interrupt.
Interrupt: Stopping pipeline ...
Execution ended after 6988121852 ns.
Setting pipeline to PAUSED ...
Setting pipeline to READY ...
Setting pipeline to NULL ...
Freeing pipeline ...

if you need more info, i'd be happy to provide it (assuming i'm able to)

_Original issue: http://code.google.com/p/clementine-player/issues/detail?id=791_

**Comment by mk288** [comment]
I met the same issue:
GStreamer could not create the element: volume. Please make sure that you have installed all necessary GStreamer plugins (e.g. OGG and MP3)
in  clementine_1.2.3.jessie_i386, can open and failed to play audio with the above error message.
Thanks!
