### ISSUE TITLE
First Track always the same in shuffle

### ISSUE THREAD

**Issue by Clementine-Issue-Importer** [clementine-player/Clementine#793]
_From [slistopad](https://code.google.com/u/116548919945165469696/) on September 22, 2010 20:48:44_

What steps will reproduce the problem? 1. Change to Shuffle All
2. Quit Clementine
3. Start Clementine and start playback What is the expected output? What do you see instead? I expect it to start the playlist at a random location, instead it always starts at the first track,  if you skip to the next song it is a random song What version of the product are you using? On what operating system? .5 on Windows XP Please provide any additional information below. I love clementines shuffle algorithm,  much better than most on windows.  However I think it would be smoother if the first track of the shuffled playlist was indeed a random track.

_Original issue: http://code.google.com/p/clementine-player/issues/detail?id=793_

**Comment by MavropaliasG** [comment]
@Clementine-Issue-Importer or @amuttsch  Please fix this, it is so simple yet important !!!
