### ISSUE TITLE
Error copy the killers disc

### ISSUE THREAD

**Issue by Clementine-Issue-Importer** [clementine-player/Clementine#933]
_From [monru90](https://code.google.com/u/110947253092997052692/) on November 01, 2010 12:44:33_

What steps will reproduce the problem? 1. Select de Hot Fuss: limited edition the killers (is the only one with happens)
2. Try to copy to your n85 devide, or maybe try to organice
3.See that error: http://bayimg.com/iaapAaADd What is the expected output? What do you see instead? Copy normal What version of the product are you using? On what operating system? Clementine 0.5.3 in windows 7 x64 proffesional Please provide any additional information below. Convert to mp4 also don't work fine.

_Original issue: http://code.google.com/p/clementine-player/issues/detail?id=933_

**Comment by Chocobozzz** [comment]
Closing this old issue. Feel free to reopen.
