### ISSUE TITLE
Group tracks by disk number

### ISSUE THREAD

**Issue by Clementine-Issue-Importer** [clementine-player/Clementine#974]
_From [trovich](https://code.google.com/u/103257557707529107891/) on November 19, 2010 00:19:57_

To reproduce:
1. Take some album with multiple-disk edition. Album + bonus CD, for example.
2. Put the same album name for all tracks of album.
3. Put the applicable disk numbers into "Disk Number" ID3v2 attribute.

Amarok 1.4 displayed each disk nicely as small sub-tree branches in the context, I suppose this may be already done in upcoming 0.6, but I'm using 0.5 for now.

It would be very nice to have the same option in a collection view. This can be made optional by adding 4-th level of "Group By" control, by adding Disc Number option in the list. 

Additional level needed because I'm already using existing for artist/year/album grouping, suppose this is pretty popular mode.

Note: of course, I can put each disk number into the Album, but this is not really correct.

_Original issue: http://code.google.com/p/clementine-player/issues/detail?id=974_

**Comment by paperbagcorner** [comment]
This was added in #4596.
